### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bradleypatton** [dotnet/command-line-api#1001]
I was trying to figure out how to use an alias with the DragonFruit option model and found the link to Aliases broken:

https://github.com/dotnet/command-line-api/blob/master/docs/Syntax-Concepts-And-Parser.md#Aliases

This link further down the page also appears to be out of date:

https://github.com/dotnet/command-line-api/blob/master/docs/Your-first-app-with-System.CommandLine.DragonFruit.md

**Comment by jonsequitur** [comment]
Can you provide a link to where you found the broken links?

**Comment by bradleypatton** [comment]
Sorry thought I had added that. Here is the page:
https://github.com/dotnet/command-line-api/blob/master/docs/How-To.md#Add-an-alias-to-an-option-or-command

Has at least 3 broken links including
https://github.com/dotnet/command-line-api/blob/master/docs/Features-overview

**Comment by jonsequitur** [comment]
Thanks, @bradleypatton. I fixed the ones I found.
