### ISSUE TITLE
Quotation marks round option values don't work as expected

### ISSUE THREAD

**Issue by RobClenshaw** [dotnet/command-line-api#1007]
It seems that quotation marks around option values do not treat the values as string literals. I've been looking at passing in a jdbc url to a command - here's a simplified version of the code for bug reproduction purposes.

```
var rootCommand = new RootCommand { Name = "jdbc" };
rootCommand.AddOption(new Option<string>("url", "pass in a jdbc url"));
rootCommand.Invoke("jdbc url \"jdbc:sqlserver://10.0.0.2;databaseName=master\"");
```

The output I get is 

```
Required argument missing for option: url
Unrecognized command or argument 'jdbc'
Unrecognized command or argument 'sqlserver://10.0.0.2;databaseName=master'

Usage:
  jdbc [options]

Options:
  url <url>         pass in a jdbc url
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

It seems that because the jdbc url starts with **jdbc:** and the colon is a valid delimiter, this confuses the code into thinking that a value is about to follow it.

**Comment by jonsequitur** [comment]
Nice bug! I'm taking a look. It appears that this is happens only when the potential subtoken matches a command name, in this case `"jdbc"`.

![image](https://user-images.githubusercontent.com/547415/89429477-72857500-d6f2-11ea-9142-e9196fd4ee26.png)
