### ISSUE TITLE
[Question] how to validate an option based on value of another option

### ISSUE THREAD

**Issue by AndrewSav** [dotnet/command-line-api#1022]
I have read through the validation tests [here](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.Tests/ParsingValidationTests.cs).

Let's say I have an option `--dns-record-type` which is `FromAmong` "a","cname".

I have an option: `--ip-address` which is required if `--dns-record-type` is "a". I have an option `--cname` which is required if `--dns-record-type` is "cname".

How do I write validators to enforce these rules?

I tried adding a validator to the `--ip-address` option, it does not seem to be fired if the option is not specified.

I also tried to add validator to the command, but it seems there is no way to access option values from this validator.

How do I solve this?

**Comment by jonsequitur** [comment]
The validation API is pretty limited. Try the `Option` constructor overload that takes a `ParseResult<T>`. I took a swing at it to make sure it would work for your scenario and here's what I came up with:

![image](https://user-images.githubusercontent.com/547415/90464221-aa60c500-e0c1-11ea-8cdd-80db9b00dff5.png)

**Comment by AndrewSav** [comment]
Thank you. In the meanwhile I came up with something like this:

```
            recordTypeOption.AddValidator(commandResult =>
            {
                var value = commandResult.GetValueOrDefault<string>();
                if (string.Equals(value, "a", StringComparison.OrdinalIgnoreCase))
                {
                    if (!commandResult.Parent.Children.Contains("ip-address"))
                    {
                        return "When '--record-type' is 'a', '--ip-address' is required.";
                    }
                }
                if (string.Equals(value, "cname", StringComparison.OrdinalIgnoreCase))
                {
                    if (!commandResult.Parent.Children.Contains("cname"))
                    {
                        return "When '--record-type' is 'cname', '--cname' is required.";
                    }
                }
                return null;
            });
```
