### ISSUE TITLE
Trailing spaces break parsing in a response file

### ISSUE THREAD

**Issue by AndrewSav** [dotnet/command-line-api#1027]
If you have a partial command line like `--option1 value1 --option2 value2 --options3 value3` and you copy and paste it to a response file, and then break it up to a line per token so that the response file works, if you are not careful enough you can leave trailing spaces behind like this:

```
--option1<space>
value1<space>
--option2<space>
value2<space>
--options3<space>
value3
```

This is not get parsed as expected with `program @responseFile` and gives validation errors instead, similar to this:

```
Unrecognized command or argument '--option1 '
Unrecognized command or argument 'value1 '
```

etc.

**Comment by jonsequitur** [comment]
Thanks for the fix, @hackf5!
