### ISSUE TITLE
Tab completion with dotnet-suggest is not working

### ISSUE THREAD

**Issue by Dimension4** [dotnet/command-line-api#1028]
I can't get dotnet suggest working for my application. I have a .netcore 3.1 app with a few commands but I get no tab completion whatsoever. Neither in Windows Terminal, nor in Cmder.

dotnet-suggest version: 1.1.137102+f2556cacb35c0b68201d73eaf1c0df8c5e57e43e
System.CommandLine version: 2.0.0-beta1.20371.2

The shim script is also in place, `$env:DOTNET_SUGGEST_SCRIPT_VERSION` prints `1.0.0`.

`my_app [suggest]` also prints

> --help
> --version
> -?
> -h
> /?
> /h
> c
> clear
> g
> get
> o
> open

`dotnet-suggest list` prints

> dotnet-suggest
> dotnet suggest

I did the following steps:

1. Reference System.CommandLine in my project.
1. Install dotnet-suggest via `dotnet tool install --global dotnet-suggest --version 1.1.137102`.
1. Paste the shim script from [here](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.Suggest/dotnet-suggest-shim.ps1) into my $PROFILE.

Do I have to do something else to get this working?

**Comment by jonsequitur** [comment]
Do partial completions work, e.g. 

```console
> myapp cl⇥
```

**Comment by Dimension4** [comment]
Nope doesn't work. Maybe I should mention that I'm using F#, not C#. But since everything else works, I don't think this is a problem. 

If it helps here is the source code (with some slight adjustments):

```F#

open System
open System.IO
open System.CommandLine
open System.CommandLine.Invocation

let private myAppTemp = Path.Combine(Path.GetTempPath(), "MyApp")

type private LogSource =
    | Latest = 0
    | App1 = 1
    | App2 = 2
    | App3 = 3
    | App4 = 4

let private logDirs = Map [
    LogSource.App1, Path.Combine(myAppTemp, "Logs/App1")
    LogSource.App2, Path.Combine(myAppTemp, "Logs/App2")
    LogSource.App3, Path.Combine(myAppTemp, "Logs/App3")
    LogSource.App4, Path.Combine(myAppTemp, "Logs/App4")
]

type private CacheSource =
    | All = 0
    | Cache1 = 1
    | Cache2 = 2

let private cacheDirs = Map [
    CacheSource.Cache1, Path.Combine(myAppTemp, "Cache1")
    CacheSource.Cache2, Path.Combine(myAppTemp, "Cache2")
]

type private MyAppLocations =
    | Temp = 0
    | InstallDir = 1

let private myAppDirs = Map [
    MyAppLocations.Temp, myAppTemp
    MyAppLocations.InstallDir, Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Programs/MyApp")
]


let private getLogFile logSource =
    let logFiles =
        logDirs
        |> Map.map (fun _ path ->
            match Directory.Exists(path) with
            | true ->
                Directory.GetFiles(path, "*.log")
                |> Seq.map FileInfo
                |> Seq.sortByDescending (fun file -> file.LastWriteTime)
                |> Seq.tryHead
            | false -> None)

    match logSource with
    | LogSource.Latest ->
        logFiles
        |> Seq.choose (fun entry -> entry.Value)
        |> Seq.sortByDescending (fun file -> file.LastWriteTime)
        |> Seq.tryHead
    | src -> logFiles.[src]


let logCommand folderAction fileAction =
    let cmd = Command("log", "Retrieves log files and folders.")
    cmd.AddAlias "l"
    Option<bool>([|"--folder"; "-f"|], (fun _ -> false), "Open the log folder instead of the log file.") |> cmd.Add
    Argument<LogSource>("source", (fun _ -> LogSource.Latest)).AddSuggestions(Enum.GetNames(typeof<LogSource>)) |> cmd.Add

    cmd.Handler <- CommandHandler.Create(
        fun (source: LogSource) (folder: bool) ->
            let log = getLogFile source
            match log with
            | Some file ->
                match folder with
                | true -> folderAction file.Directory.FullName
                | false -> fileAction file.FullName
            | None ->
                printfn "No logs for %A present." source)
    cmd


let openCommand =
    let cmd = Command("open", "Opens the given shortcut.")
    cmd.AddAlias "o"
    let openSystemDefault path = System.Diagnostics.Process.Start("explorer", (sprintf "\"%s\"" path)) |> ignore
    logCommand openSystemDefault openSystemDefault |> cmd.Add
    Argument<MyAppLocations>("source").AddSuggestions(Enum.GetNames(typeof<MyAppLocations>)) |> cmd.Add

    cmd.Handler <- CommandHandler.Create(
        fun (source: MyAppLocations) ->
            let path = myAppDirs.[source]
            printfn "%s" path
            match Directory.Exists path with
            | true -> openSystemDefault path
            | false -> printfn "Cannot open '%s'. Folder does not exist." path)
    cmd


let getCommand =
    let cmd = Command("get", "Prints information about the given sub-command.")
    cmd.AddAlias "g"
    let printAction = printfn "%s"
    logCommand printAction printAction |> cmd.Add
    cmd


let private clearCache source =
    let target = cacheDirs.[source]
    if Directory.Exists target then
        Directory.Delete(target, true)
        printfn "Cache \"%A\" has been cleared." source
    else
        printfn "Cache \"%A\" does not exist." source


let clearCommand =
    let cmd = Command("clear", "Clears the given cache.")
    cmd.AddAlias "c"
    Argument<CacheSource>("source").AddSuggestions(Enum.GetNames(typeof<CacheSource>)) |> cmd.Add
    cmd.Handler <- CommandHandler.Create(
        fun (source: CacheSource) ->
            match source with
            | CacheSource.All ->
                clearCache CacheSource.Cache1
                clearCache CacheSource.Cache2
            | other -> clearCache other)
    cmd


let rootCommand =
    let root = RootCommand()
    seq {
        openCommand
        getCommand
        clearCommand
    } |> Seq.iter root.Add

    root


[<EntryPoint>]
let main argv =
    let root = rootCommand
    root.Invoke argv

```

**Comment by KathleenDollard** [comment]
Just a thing to check... some shells may require you restart the shell.

**Comment by Dimension4** [comment]
There have been several reboots in between and a lot of shell restarts. Didn't help unfortunately.

**Comment by Dimension4** [comment]
Any new insights on the matter? This is kind of a blocker for me atm.

**Comment by jonsequitur** [comment]
Thanks for the code sample. I tried it out and it's working for me. I'm using a newer version of `System.CommandLine`, so you might want to try update that. I'm using the same version of `dotnet suggest` as you are, with PowerShell in Windows Terminal. 

It didn't work for me until I opened a separate terminal though.

**Comment by jonsequitur** [comment]
If that doesn't work, there are debugging steps outlined here: https://github.com/dotnet/command-line-api/issues/794#issuecomment-600601807. I'm definitely curious to know what's going on.

**Comment by jonsequitur** [comment]
The log entry seems to indicate that everything is working until the shim script returns values back to the shell. If you add this to your `$profile` and start a new terminal, does it return shell completions?

```powershell

$scriptblock = {
    param($wordToComplete, $commandAst, $cursorPosition)
        "world", "from", "PowerShell" | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
Register-ArgumentCompleter -Native -CommandName hello -ScriptBlock $scriptblock
```

Another question it occurred to me to ask: does `dotnet-suggest ⇥` return completions in your shell? (Note that `dotnet suggest ⇥` (without the hyphen) won't work because of #343).

**Comment by Dimension4** [comment]
Note my sentence after the log output:

> but if I try my application, e.g. my_app --ver I get no log entries at all.

`dotnet-suggest ⇥` yields correct suggestions with the normal shim script (with and without your additional script). The suggestions for my application are still absent. I get no log entries either, except one line when I install my app as a global tool:

> dotnet-suggest received: |register|--command-path|C:\Users\bla\.dotnet\tools\et.exe|--suggestion-command|et

**Comment by jonsequitur** [comment]
Sorry, I missed that. The code sample you provides works fine for me and it looks like `dotnet-suggest` works fine for you, so it seems like something specific to 1) your program + 2) your machine. 

A way to debug this is to add a `[debug]` directive to the command line that `dotnet-suggest` uses to launch your app:

https://github.com/dotnet/command-line-api/blob/d50118a09bef72d912b9fb85116996b687ec0928/src/System.CommandLine.Suggest/SuggestionDispatcher.cs#L182-L185

Change it to something like this:

```csharp
            string suggestions = _suggestionStore.GetSuggestions(
                targetExePath,
                "[debug] " + targetArgs,
                Timeout).Trim();
```

Rebuild and install `dotnet-suggest`, and then when you trigger suggestions, it should hang while your app waits for you to attach the debugger. It will resume automatically once the debugger is attached. Set it to break on all exceptions and see what there is to see.

**Comment by Dimension4** [comment]
Hmm it looks like dotnet-suggest is not even started when I try to tab complete my_app (no log entries at all). I can attach the debugger if I do `dotnet-suggest reg⇥`. But that doesn't help much because `dotnet-suggest reg⇥` is working just fine. What is the powershell version that you got it working with? Did it work without installing my_app?

**Comment by Dimension4** [comment]
Hmm I'm not sure why but it's working now. I think my_app didn't register properly the first time I've tested it. It showed up in `dotnet-suggest list` but it didn't work. I've just reinstalled both tools and it looks like everything is working fine now. 

I'm glad we figured it out in the end. Thank you for your time and help.
