### ISSUE TITLE
ArgumentNullException when used with .NET5.0 SingleFilePublish

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/command-line-api#1031]
I'm seeing an exception when trying to use the dragonfruit API with the new NET5.0 style single file publish.

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.CommandLine.DragonFruit.CommandLine.GetDefaultXmlDocsFileLocation(Assembly assembly)
   at System.CommandLine.DragonFruit.CommandLine.ConfigureHelpFromXmlComments(CommandLineBuilder builder, MethodInfo method, String xmlDocsFilePath)
   at System.CommandLine.DragonFruit.CommandLine.BuildParser(MethodInfo method, String xmlDocsFilePath, Object target)
   at System.CommandLine.DragonFruit.CommandLine.InvokeMethodAsync(String[] args, MethodInfo method, String xmlDocsFilePath, Object target, IConsole console)
   at System.CommandLine.DragonFruit.CommandLine.ExecuteAssemblyAsync(Assembly entryAssembly, String[] args, String entryPointFullTypeName, String xmlDocsFilePath, IConsole console)
   at AutoGeneratedProgram.Main(String[] args)
   at AutoGeneratedProgram.<Main>(String[] args)
```

A little bit of source reading shows that `Assembly.Location` is being [read here](https://github.com/dotnet/command-line-api/blob/a5217048b1a1e93082cbcbcf48479ee8b565ab2a/src/System.CommandLine.DragonFruit/CommandLine.cs#L315).

This is probably running afoul of [this part of the design](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md#assemblylocation)

I know dragonfruit is an experiment, but is there any plan to support this scenario?

**Comment by jonsequitur** [comment]
I think we'll want to fix this (and would certainly accept a PR).

**Comment by bradleypatton** [comment]
Running into this as well. Looks like the code in GetDefaultXmlDocsFileLocation assumes assembly.Location is non-null and has the path to the xml docs. 

        private static string GetDefaultXmlDocsFileLocation(Assembly assembly)
        {
            return Path.Combine(
                Path.GetDirectoryName(assembly.Location),
                Path.GetFileNameWithoutExtension(assembly.Location) + ".xml");
        }

Reading this [blog post ](https://www.hanselman.com/blog/how-do-i-find-which-directory-my-net-core-console-application-was-started-in-or-is-running-from) from Scott Hanselman it seems like `AppContext.BaseDirectory` might be better to use but I'm not sure.

**Comment by jpiquot** [comment]
I have the same issue when running from SingleFilePublish. No errors when running from VS.

**Comment by little512** [comment]
I also have the same issue when publishing with .NET CLI. I only get this runtime error followed by a segfault after publishing and running.

**Comment by Trapulo** [comment]
same issue

**Comment by vatsan-madhavan** [comment]
I started playing around with making a fix for this, and `AppContext.BaseDirectory` looked promising until I came across the `<DocumentationFile>` msbuild property. 

Suppose the location of the XML doc is redirected to another path like this: 

```xml
<PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>D:\temp\doc.xml</DocumentationFile>
</PropertyGroup>
```

A few things happen: 

- `doc.xml` is generated under `D:\temp\` (`$(DocumentationFile)` is directly passed to `Csc` task)
- `doc.xml` is **also generated** under `AppContext.BaseDirectory` [1]
- When `$(DocumentationFile)` is specified/defined, then `$(AssemblyName).xml` is no longer produced (anywhere). [2]


[1] `Microsoft.Common.CurrentVersion.Targets` [always generates](https://github.com/dotnet/msbuild/blob/c70d520b5b8df990f651f0d00cd186a68cb277c6/src/Tasks/Microsoft.Common.CurrentVersion.targets#L385-L389) doc-file under `$(Outdir)

```xml
  <ItemGroup>
    <IntermediateAssembly Include="$(IntermediateOutputPath)$(TargetName)$(TargetExt)"/>
    <FinalDocFile Include="@(DocFileItem->'$(OutDir)%(Filename)%(Extension)')"/>
    <CopyUpToDateMarker Include="$([MSBuild]::NormalizePath('$(MSBuildProjectDirectory)', '$(IntermediateOutputPath)', '$(MSBuildProjectFile).CopyComplete'))" />
  </ItemGroup>
```

[2] `Microsoft.NET.Sdk.BeforeCommon.targets` [controls ](https://github.com/dotnet/sdk/blob/89a363b6726e8e0eabf85f3717e2ba1e4a79ca13/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L274-L277)this:

```xml
  <PropertyGroup Condition="'$(GenerateDocumentationFile)' == 'true' and '$(DocumentationFile)' == ''">
    <DocumentationFile Condition="'$(MSBuildProjectExtension)' == '.vbproj'">$(AssemblyName).xml</DocumentationFile>
    <DocumentationFile Condition="'$(MSBuildProjectExtension)' != '.vbproj'">$(IntermediateOutputPath)$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
```

Also, there doesn't seem to be a way to detect when an assembly is a bundled-assembly - at least none I could find from a cursory search of docs. It's clear that `Assembly.Location` will return `string.Empty` for bundled-assemblies, but I'm not sure that that converse is true (i.e., when `Assembly.Location` returns `string.Empty`, the assembly in question isn't always bundled, is it?). 

So when `Assembly.Location` returns `string.Empty`, we could make an educated guess that what we are dealing with is a bundled-assembly, and probe `AppContext.BaseDirectory` for an xml file matching the name `$(AssemblyName).xml` (only when `assembly.Name` in `GetDefaultXmlDocsFileLocation` happens to also match `$(AssemblyName)`) . Here, `$(AssemblyName)` is the name of the main assembly. If such an xml is found, that could be loaded as a fallback. 

For e.g., if the main assembly were named `TestApplication`, then we'd have to find `TestApplication.xml` at `Appcontext.BaseDirectory`, and `assembly.Name` in `GetDefaultXmlDocsFileLocation` would have to also match `TestApplication` for that probe to be made. I want to protect against the possibility of `GetDefaultXmlDocsFileLocation` being used to look for documentation for `SomeOtherAssembly`.... 

I'm hoping for feedback and suggestions

Something like this seems to work well with self-contained exes: 

```C#
        private static string GetDefaultXmlDocsFileLocation(Assembly assembly)
        {
            if (!string.IsNullOrEmpty(assembly.Location))
            {
                return Path.Combine(
                    Path.GetDirectoryName(assembly.Location),
                    Path.GetFileNameWithoutExtension(assembly.Location) + ".xml");
            }

            if (assembly == Assembly.GetEntryAssembly())
            {
                return Path.Combine(
                    AppContext.BaseDirectory,
                    assembly.GetName().Name + ".xml");
            }

            return string.Empty;
        }
```

When the `<DocumentationFile>` property is specified (i.e., the generated xml is named something other than `$(AssemblyName)`), `--help` is based on reflection and terse; whereas when `<DocumentationFile>` is absent and the generated xml is named the same as `$(AssemblyName)` then `--help` works nicely and prints out content based on documentation.

**Comment by VictorioBerra** [comment]
Was this released? I am still experiencing this issue.

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Version>1.0.1</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PublishSingleFile>true</PublishSingleFile>

    <SelfContained>true</SelfContained>

    <PublishTrimmed>true</PublishTrimmed>

    <PublishReadyToRun>true</PublishReadyToRun>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine.DragonFruit" Version="0.3.0-alpha.20574.7" />
  </ItemGroup>

</Project>
```

Error:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.CommandLine.DragonFruit.CommandLine.GetDefaultXmlDocsFileLocation(Assembly assembly)
   at System.CommandLine.DragonFruit.CommandLine.ConfigureHelpFromXmlComments(CommandLineBuilder builder, MethodInfo method, String xmlDocsFilePath)
   at System.CommandLine.DragonFruit.CommandLine.BuildParser(MethodInfo method, String xmlDocsFilePath, Object target)
   at System.CommandLine.DragonFruit.CommandLine.InvokeMethodAsync(String[] args, MethodInfo method, String xmlDocsFilePath, Object target, IConsole console)
   at System.CommandLine.DragonFruit.CommandLine.ExecuteAssemblyAsync(Assembly entryAssembly, String[] args, String entryPointFullTypeName, String xmlDocsFilePath, IConsole console)
   at AutoGeneratedProgram.Main(String[] args)
   at AutoGeneratedProgram.<Main>(String[] args)
```

**Comment by jonsequitur** [comment]
This is available on our daily feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json

There are breaking changes in the latest System.CommandLine and a few more in progress which shouldn't affect DragonFruit but we don't want to churn the public nuget.org version too much until these changes are done.

**Comment by FramnkRulez** [comment]
Has this been made available on the public pre-release NuGet yet?  The latest pre-release version of dragonfruit (0.4.0-alpha.21617.1) doesn't seem to have the fix.

**Comment by jonsequitur** [comment]
Everything that has been merged to main is available on the prerelease feed after the official build finishes, typically about 30 minutes after merge.
