### ISSUE TITLE
null passed to handler function if argument type throws a TypeInitializerException

### ISSUE THREAD

**Issue by bratkartoff** [dotnet/command-line-api#1034]
If one the arguments of the handler function cannot be initialized because it throws a TypeInitializerException, System.CommandLine passes null to the handler.
I think it would be more useful to rethrow the TypeInitializerException to make bugs in the user code easier to find.

```csharp
class Program
{
    static void Main(string[] args)
    {
        var rootCommand = new RootCommand();
        rootCommand.Handler = CommandHandler.Create((ThisClassHasABug o) => {
            if (o == null)
                Console.WriteLine("object is null");
        });
        rootCommand.Invoke("");
    }
}

class ThisClassHasABug
{
    static ThisClassHasABug()
    {
        throw new Exception("Something failed here");
    }
}
```

Output: `object is null`

Version: `2.0.0-beta1.20427.1`

**Comment by jonsequitur** [comment]
The reason this exception is swallowed is because of the default exception handler, which is included when you use `Command.Invoke`. You can opt out of it.

There's more discussion of this in #796.

**Comment by bratkartoff** [comment]
Closing this because it's already possible to pass the exceptions through, it's just not the default behaviour, and the discussion whether this should be the default behaviour is in #796
