### ISSUE TITLE
releases are not being tagged consistently

### ISSUE THREAD

**Issue by adamralph** [dotnet/command-line-api#1036]
As per https://github.com/dotnet/command-line-api/issues/827#issuecomment-614174924, tagging started with `2.0.0-beta1.20213.1`.

The next release, `2.0.0-beta1.20214.1` was also tagged, but then `2.0.0-beta1.20253.1` and `2.0.0-beta1.20303.1` were not. `2.0.0-beta1.20371.2` was then tagged, but the latest release, `2.0.0-beta1.20427.1` was not.

<img src="https://user-images.githubusercontent.com/677704/92560466-c3990380-f272-11ea-9b12-7dcdd8499522.png" width="356px" /><img src="https://user-images.githubusercontent.com/677704/92561011-a7499680-f273-11ea-8903-17607322d844.png" width="177px" />

Please tag releases consistently.

**Comment by jonsequitur** [comment]
I'll hide the interim releases. They were put out because our internal package pipeline was disripted.
