### ISSUE TITLE
Global options on sub command not parsed by root

### ISSUE THREAD

**Issue by rsking-mondo** [dotnet/command-line-api#1041]
When putting a global option on a sub command, it is not initially parsed by the root command, i.e.

``` csharp
var root = new Command("parent");
var firstChild = new Command("first");
root.AddCommand(firstChild);
var option = new Option<int>("--global");
firstChild.AddGlobalOption(option);
var secondChild = new Command("second");
firstChild.AddCommand(secondChild);
var rootValue = root.Parse("first second --global 123").ValueForOption(option);
var firstChildValue = firstChild.Parse("second --global 123").ValueForOption(option);
var secondChildValue = secondChild.Parse("--global 123").ValueForOption(option);
```

Expected Result:

`rootValue == firstChildValue == secondChildValue == 123`

Actual Result

`rootValue == 0`
`firstChildValue == secondChildValue == 123`

Interestingly, if you have one of the child commands parsed first, then it does work

``` csharp
var firstChildValue = firstChild.Parse("second --global 123").ValueForOption(option);
var rootValue = root.Parse("first second --global 123").ValueForOption(option);
var secondChildValue = secondChild.Parse("--global 123").ValueForOption(option);
```

Expected Result:

`firstChildValue == rootValue == secondChildValue == 123`

Actual Result:

as expected.

**Comment by rsking-mondo** [comment]
I think that this has something to do with https://github.com/dotnet/command-line-api/blob/e09c1f31adace14b16826ed03ff33266595ed14d/src/System.CommandLine/CommandLineConfiguration.cs#L95 not going to sub commands. In the working case above, that would be called on `firstChild`, which would apply then to `secondChild`, where as in the non-working case, on the global options on `root` would be applied to `firstChild`.

**Comment by rsking-mondo** [comment]
``` csharp
private void AddGlobalOptionsToChildren(Command parentCommand)
{
    foreach (var child in parentCommand.Children.FlattenBreadthFirst(c => c.Children))
    {
        if (child is Command childCommand)
        {
            foreach (var globalOption in parentCommand.GlobalOptions)
            {
                if (!childCommand.Children.IsAnyAliasInUse(globalOption, out _))
                {
                    childCommand.AddOption(globalOption);
                }
            }

            AddGlobalOptionsToChildren(childCommand);
        }
    }
}
```

should recursively add global options to sub commands.

**Comment by jonsequitur** [comment]
Nice find! Thanks for reporting this.
