### ISSUE TITLE
No error when omitting arguments in child commands  

### ISSUE THREAD

**Issue by DArdouin** [dotnet/command-line-api#1046]
No error saying argument is required is prompted when we forget root's argument, while invoking a child command (verb) whereas it's used in its handler

```c#
    class Program
    {
        static async Task Main(string[] args)
        {

            var rootCommand = new RootCommand();
            rootCommand.AddArgument(new Argument<string>("msg"));
            rootCommand.Handler = CommandHandler.Create<string>(Console.WriteLine);

            var verb = new Command("verb");
            verb.Handler = CommandHandler.Create<string>(msg=> Console.WriteLine($"{msg} from verb"));

            rootCommand.AddCommand(verb);

            await rootCommand.InvokeAsync(args);
        }
    }
```
![image](https://user-images.githubusercontent.com/9949583/94300773-7934a980-ff37-11ea-86a2-8a3dfa5f09a2.png)

**Comment by jonsequitur** [comment]
This is by design. When a child command is specified, the parent commands' options and arguments aren't required (though they're allowed to be present and can be bound to your command handler.)

To require the argument to be specified you can add it as well to the child command, like this:

```csharp

    class Program
    {
        static async Task Main(string[] args)
        {
            var rootCommand = new RootCommand();
            var msgArg = new Argument<string>("msg");

// add msgArg here...
            rootCommand.AddArgument(msgArg);                  
            rootCommand.Handler = CommandHandler.Create<string>(Console.WriteLine);

            var verb = new Command("verb");
// ...and add msgArg again here:
            verb.AddArgument(msgArg);                         
            verb.Handler = CommandHandler.Create<string>(msg=> Console.WriteLine($"{msg} from verb"));

            rootCommand.AddCommand(verb);

            await rootCommand.InvokeAsync(args);
        }
    }

```



This has the additional effect of allowing `msgArg` to be specified in either position, so both of the following are valid:

```console
> Sanbox hello verb
> Sanbox verb hello
```

**Comment by DArdouin** [comment]
Yup that's what i dit, the help feels a bit clunky when doing this though. 

Thank for your answer !

**Comment by jonsequitur** [comment]
Do you mean the usage section specifically? Yeah, it gets a bit cluttered when options are valid in multiple positions like this. Any suggestions to make it easier to understand?
