### ISSUE TITLE
Support "Or" Argument 

### ISSUE THREAD

**Issue by tdashworth** [dotnet/command-line-api#1051]
Would it be possible to support two (or more?) optional arguments that together must be required. For example:

`dotnet clean <PROJECT>|<SOLUTION>`

where you must pass either a project or a solution. It this case they would be the same type `FileInfo` but I'm looking for a `FileInfo` and `string`. 

Otherwise is it possible to setup two commands? One `clitool subcommand1 <string-arg>` and another `clitool subcommand1 <file-arg>`?

**Comment by jonsequitur** [comment]
You can do this with a `ParseArgument<T>` delegate, for example:

```csharp

public class FileInfoOrString
{
    public FileInfoOrString(FileInfo fileInfo) => FileInfoArg = fileInfo;
    public FileInfoOrString(String s) => StringArg = s;
    public FileInfo FileInfoArg {  get; }
    public String StringArg {  get; }
}

var root = new RootCommand
{
    new Argument<FileInfoOrString>("FileInfo|String", parse: argResult => {
        var arg = argResult.Tokens.Single().Value;
        if (File.Exists(arg))
        {
            return new FileInfoOrString(new FileInfo(arg));
        } 

        return new FileInfoOrString(arg);
    })
};


```

**Comment by tdashworth** [comment]
Thanks! Exactly what I need 😀

**Comment by tdashworth** [comment]
I was struggling to use the argument name "FileInfo|String" and for it to bind to the command handler. I have made a PR for a small change to replace the "|" with "or" so that it allows a friendlier parameter name to the handler.
