### ISSUE TITLE
DateTime parsing

### ISSUE THREAD

**Issue by kalatchev** [dotnet/command-line-api#1052]
Whatever I've tried, I am unable to pass DateTime parameter. Is it possible at all? If yes - what format should I use and how I can control it?

**Comment by jonsequitur** [comment]
Here's a working example. A couple of potential gotchas are making sure the `Option` or `Argument` name matches a handler parameter (`"-d"` -> `d`) in this example, and that if there are spaces in an argument, you put quotes around it so it'll be treated as a single token.

![image](https://user-images.githubusercontent.com/547415/94996647-c4b00e80-055a-11eb-9c15-2adb0b0bb581.png)

**Comment by SamZhangQingChuan** [comment]
Hi @jonsequitur . Could you please try to invoke the command from terminal? I cannot make it work. Thanks a lot!
