### ISSUE TITLE
Usage for REPL?

### ISSUE THREAD

**Issue by drock07** [dotnet/command-line-api#1070]
It seems like this would be possible, but I can't quite seem to figure out how.

I'd like to use this library within a REPL started by my command line utility. Meaning, you run the initial command line program, which starts a REPL. Ideally, it would be nice to package my different commands in this REPL as CommandLine.Commands, however, it seems like all the commands need to be "subcommands" of a root command. In this context, that doesn't work as well since the commands being entered into the REPL don't have an initial "root" command. 

Is there anyway to utilize the parsing capability of this library, but have it choose between multiple commands rather than one command with multiple subcommands?

**Comment by jonsequitur** [comment]
You can parse input without specifying a root command, so given a command like this to handle REPL input:

```csharp
var replInputParser = new Command("repl")
{
    new Command("one"),
    new Command("two")
}; 
```

you can parse input like this:

```csharp
var result = replInputParser.Parse("one");
```

Would this work for what you're trying to do?

**Comment by drock07** [comment]
Yeah, I think that's exactly right. Thank you!

What would be the easiest way to then invoke the ParseResult? The InvocationPipeline class in internal. I'm guessing there's an Extension method somewhere that wraps it.

**Comment by jonsequitur** [comment]
There's an extension method: `System.CommandLine.Parsing.ParseResultExtensions.Invoke`. Maybe this needs to be a in a different namespace to make it easier to find?

**Comment by drock07** [comment]
Perfect. Thank you so much for your help!
