### ISSUE TITLE
docs: add example of AddArgument

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#1142]
The documentation doesn't include an example of `AddArgument`.

I'm actually looking how I can collect a bunch of arguments that are after `--`.
For example: `./my-command --option1 value1 -- any additional arguments`.
How can I get a `string[]` that contains: "any", "additional", "arguments"?

cc @Keboo @jonsequitur

**Comment by Keboo** [comment]
@tmat I believe what you are looking for is the unparsed tokens on the `ParseResult`. Something like this:
```C#
[Fact]
    public void Can_retrieve_unparsed_tokens()
    {
        var rootCommand = new RootCommand("my-command")
        {
            new Option<string>("--option1"),
        };
        rootCommand.TreatUnmatchedTokensAsErrors = false;
        var result = rootCommand.Parse("my-command --option1 value1 -- any additional arguments");
        result.UnparsedTokens.Should().BeEquivalentTo("any", "additional", "arguments");
    }
```

**Comment by jonsequitur** [comment]
One additional point: `TreatUnmatchedTokensAsErrors` isn't necessary here. The behavior of `--` is always enabled.

**Comment by nzain** [comment]
The documentation should really explain the use of the `Argument<T>` class and how to use it - at the time of writing only `Option<T>` is used and explained in great depth. Actually it is very simple, but not obvious. For anyone looking for final integration, it could look like this:

```
MyDemo --chip 0 18
```
where 18 is some mandatory `Argument<int>` that is always required and not an `Option<int>` (like `--chip 0`). As I write this, the naming is intuitive. The `Argument.Name` is matched with the appropriate method argument:

```cs
        internal static Task<int> Main(string[] args)
        {
            // Create a root command with some options
            RootCommand rootCommand = new("GPIO demo (libgpiod + System.Devices")
            {
                new Option<int>("--chip"),
                new Argument<int>("pin", "The pin to use")
            };
            // Note that the parameters of the handler method are matched according to the names of the options
            rootCommand.Handler = CommandHandler.Create<int, int>(ExecuteAsync);
            // Parse the incoming args and invoke the handler
            return rootCommand.InvokeAsync(args);
        }

        private static async Task ExecuteAsync(int chip, int pin)
        {
            Console.WriteLine($"gpio chip {chip}, pin {pin} ({(logicalNumbering?"logical":"board")} numbering scheme)");
        }
```

**Comment by jonsequitur** [comment]
Related: #1238.

**Comment by jonsequitur** [comment]
More detailed docs have now been published: https://docs.microsoft.com/en-us/dotnet/standard/commandline/define-commands

Please let us know what you think.
