### ISSUE TITLE
Question: Is possible to get a list of integers as Option<List<int>>?

### ISSUE THREAD

**Issue by BizarreNULL** [dotnet/command-line-api#1144]
For example, in a program that I need to receive a list of ports:

```csharp
new Option<List<int>>(new[] {"--ports", "-p"})
{
    Description = "Set of ports to check (default is 80, 443, 8080 and 8433)"
}
```

What is the correct syntax to use `List<T>` type as the value of an `Option<T>`?

**Comment by jonsequitur** [comment]
That will work just as you've written it. `List<T>`, `IEnumerable<T>`, and `T[]` are all valid.

![image](https://user-images.githubusercontent.com/547415/102723991-fb2b3900-42c0-11eb-81ef-1ac3dd244983.png)

**Comment by BizarreNULL** [comment]
Can I receive all these values in a single `List<T>`, for example: `-p 1,2,3,4`?

**Comment by jonsequitur** [comment]
You can do either of these without any special configuration:

```console
> -p 1 -p 2 -p 3 -p 4
> -p 1 2 3 4
```

If you want to use commas, you need to provide a custom `ParseArgument<T>` delegate:

![image](https://user-images.githubusercontent.com/547415/102914652-79105100-4435-11eb-889a-f50988621266.png)

**Comment by BizarreNULL** [comment]
Amazing! Thankyou for your insights and samples.
