### ISSUE TITLE
Question: How to access an Option from RootCommand inside a Command?

### ISSUE THREAD

**Issue by BizarreNULL** [dotnet/command-line-api#1149]
There is a `RootCommand` that has a debug `Option`. Inside this `RootCommand` exists several other Command:

```csharp
var rootCommand = new RootCommand
{
    someCommand1,
    someCommand2,
    // ...

    new Option<bool>(new[] {"--debug", "-d"})
    {
        Description = "Print debugging information"
    }
};
```

How `someCommand1` can access the value of `Option` "--debug" in `rootCommand `?

**Comment by jonsequitur** [comment]
You can add the option to `subcommand1` as well. Or, if you want it available everywhere, you can do `rootCommand.AddGlobalOption(debugOption)`.

**Comment by BizarreNULL** [comment]
Thank you by the example with `AddGlobalOption`.
