### ISSUE TITLE
Set pattern for Option value

### ISSUE THREAD

**Issue by AmRo045** [dotnet/command-line-api#1163]
Hi,
Does this library support something like this:
```C#
new Option<string>(
    "--protocol",
    @"\b(http|https|ftp|socks)\b",  // Pattern for option value
)
```

**Comment by jonsequitur** [comment]
We're not generally providing this kind of "stringly-typed" API for a few reasons:

* Parsing the input means some set of rules for interpreting this string has to be devised and documented. Using properties and parameters is clearer and works in more obvious and discoverable ways with existing tools (IntelliSense, compiler, etc.)
* The parsing is a (very small) performance concern.

That said, it would be straightforward to implement something like this on top of the System.CommandLine APIs using an extension method, e.g. `new Option<string>("--protocol").WithAllowedValues( ... )`
