### ISSUE TITLE
Program.Main(int, bool, FileInfo)' has the wrong signature to be an entry point

### ISSUE THREAD

**Issue by ve3** [dotnet/command-line-api#1165]
From both document pages.
* https://github.com/dotnet/command-line-api/blob/main/docs/DragonFruit-overview.md
* https://github.com/dotnet/command-line-api/blob/main/docs/Your-first-app-with-System-CommandLine-DragonFruit.md

When I build, I got this failed.

> Program.Main(int, bool, FileInfo)' has the wrong signature to be an entry point

My code:
```
using System;
using System.Collections.Generic;
using System.CommandLine;
using System.CommandLine.Invocation;
using System.IO;

namespace experiment
{
    class Program
    {
        /// <param name="intOption">An option whose argument is parsed as an int</param>
        /// <param name="boolOption">An option whose argument is parsed as a bool</param>
        /// <param name="fileOption">An option whose argument is parsed as a FileInfo</param>
        static void Main(int intOption = 42, bool boolOption = false, FileInfo fileOption = null)
        {
            Console.WriteLine($"The value for --int-option is: {intOption}");
            Console.WriteLine($"The value for --bool-option is: {boolOption}");
            Console.WriteLine($"The value for --file-option is: {fileOption?.FullName ?? "null"}");
        }
    }
}
```

Maybe incorrect document.

**Comment by jonsequitur** [comment]
Did you have package reference to `System.CommandLine.DragonFruit`? If so, which version, and can you tell us more about the project? Which framework version does it target?

**Comment by ve3** [comment]
No, I didn't reference it. Sorry, that is my fault.
