### ISSUE TITLE
Error CS2017 when adding to library project

### ISSUE THREAD

**Issue by erikmourits** [dotnet/command-line-api#1167]
I get the following error when adding system.commandline.dragonfruit (0.3.0-alpha.20574.7) to an empty class library project (netstandard2.1):
Error	CS2017	Cannot specify /main if building a module or library	ClassLibrary1	ClassLibrary1\CSC	1	Active

Which is weird because I haven't specified a main. It seems that adding dragonfruit maken Visual Studio add '/main' to the csc commandline. I'm not sure if this is a Visual Studio bug or a dragonfruit bug.

**Comment by jonsequitur** [comment]
This is because DragonFruit adds a `Main` method via a build target. It's not intended to work with a class library.

Most of its functionality is directly related to interpreting the alternative `Main` signature. Is there specific functionality in DragonFruit that you wanted to use in a class library?

**Comment by soudevrielink** [comment]
On behalf of Erik:
I developed an abstraction layer which will be used by "plugins" (Console Applications).
This abstraction layer creates predefined subcommands and enforces the use of specific/limited arguments.
It's some sort of contract between the main application and plugins.

**Comment by jonsequitur** [comment]
Is there a reason to use `System.CommandLine.DragonFruit` rather than `System.CommandLine` for this?

**Comment by soudevrielink** [comment]
Mea culpa, I had a misconception about DragonFruit. System.CommandLine works perfect! Thank you

**Comment by erikmourits** [comment]
Thanks for the feedback. I'll close the issue.
