### ISSUE TITLE
Q: How can i explicitly map an option to a property of a complex type in a simple way?

### ISSUE THREAD

**Issue by elgonzo** [dotnet/command-line-api#1186]
In a project i am trying to migrate from another CLI libary to System.CommandLine, i am attempting use model binding with complex types.

Is there a relatively simple way to explicitly specify the mapping of an option to a property of a complex type, in case the name of the property from the complex type does not match the option name?

Assume i do not want to add another alias to the option to match the property name. I also do not want to change the property name to match the option alias or have its first letter match the single-letter alias. Nor do i want to create sub classes of or wrapper classes for my settings classes (the "complex types") with additional proxy properties. I am aware of these possibilities, but i would prefer defining simply an explicit option-to-property mapping over either refactoring code, introducing new classes or changing the CLI surface.

Lets say i have this code with the SomeSettings class being part of an already existing project that uses a different CLI library so far (grossly simplified example):

```
public class SomeSettings
{
	public bool NoConfirmationRequired {get; set; }
}


var rootCmd = new RootCommand
{
	//
	// this option should map to SomeSettings.NoConfirmationRequired
	//
	new Option<bool>("-Y")
};

command.Handler = CommandHandler.Create(
	(SomeSettings settings) => RunStuff(settings)
);
```

How would i associate the -Y option with the `SomeSettings.NoConfirmationRequired` property without either introducing additional aliases, without changing the property name and without sub-classing or wrapping the SomeSettings class?

Ideally, i would like the definition of this mapping either close to the property declaration in the SomeSettings class (like, for instance, an attribute on the property), or close to or as part of the Option definition.

**Comment by jonsequitur** [comment]
There are two approaches that can work right now. One is to add a constructor that maps to that property, like so:

```csharp
public class SomeSettings
{
    public SomeSettings(bool y)
    {
         NoConfirmationRequired = y;
    }
	public bool NoConfirmationRequired {get; set; }
}
```

The other (a bit more code) is to customize the model binder for `SomeSettings`. Here's an example: https://github.com/dotnet/command-line-api/blob/2dafa1fda234499597a231cdf0bbfbfc74f79a4a/src/System.CommandLine.Tests/Binding/ModelBinderTests.cs#L480-L498

**Comment by elgonzo** [comment]
The second approach of directly setting up the ModelBinder looks like it meets my needs perfectly. My settings classes for multiple verbs/commands have already custom attributes annotating the properties to associate them with CLI arguments, and with the attribute information it should be quite easy to programmatically set up the commands, options and model binders programmatically.

Thanks so much for the quick help!
