### ISSUE TITLE
AddValidator should be in Symbol 

### ISSUE THREAD

**Issue by JohniMichels** [dotnet/command-line-api#1192]
Currently `AddValidator` is in all derived classes of `Symbol` and all of them use a specialized class (OptionResult, CommandResult, ArgumentResult) that inherits from SymbolResult.
It would be great if Symbol would declare this method using `void AddValidator(Func<SymbolResult, string?> v)` as argument, then it would be possible to create validations that works for symbol in a non specialized way, and override on derived classes, working on both Options and Arguments.
So I could create a method like
```
public static string? ValidateFileContent(SymbolResult symbolResult)
{
    var fileName = symbolResult.Tokens.First().Value;
    // FILE CONTENT VALIDATION
    return null;
}
public static T ValidateFileContentForSymbol<T>(this T symbol)
{
    symbol.AddValidator(ValidateFileContent)
}
```
This would also be valid for functions like FindResultFor.
Currently we can do something equivalent using a switch statement and casting.

**Comment by jonsequitur** [comment]
We're looking at reworking the validator API so that it operates on parsed values rather than tokens, with the goal that you can validate, for example, and `int` rather than a `SymbolResult`. This kind of heads in a different direction which is that a validator would be reusable for a given type `T` but not across non-generic `Symbol`/`SymbolResult` types.

Thoughts on the relative usefulness of these approaches?

**Comment by JohniMichels** [comment]
Actually, if the validator runs on a parsed argument it will be a better solution. I'm currently using on validations for Id's that are strictly positive numbers, but there are commands where I use them as arguments, and times that I use them as options.

**Comment by jonsequitur** [comment]
Have you also looked at the `Option<T>` and `Argument<T>` constructor overloads that take a `ParseArgument<T>` delegate?

**Comment by JohniMichels** [comment]
That will work if, as the example I gave, can be constrained on a specific type (I'm assuming you're suggesting uint as the argument). Any validation that is not directly tied to a type, like a specific range or a Json content would not work.

**Comment by jonsequitur** [comment]
`ParseArgument<T>` lets you do custom validation by setting the `ArgumentResult.ErrorMessage` property:

![image](https://user-images.githubusercontent.com/547415/107254966-a9637d00-69ec-11eb-8789-f3e9426a4893.png)

**Comment by JohniMichels** [comment]
I see where we can go. This method always use ArgumentResult. But isn't it strange to use a validation in parser?

**Comment by jonsequitur** [comment]
> This method always use ArgumentResult. 

Correct. The `ArgumentResult` will be parented to an `Option` or `Command` depending on how you configured it. We might consider a more specific parameter here, if it's useful.

> But isn't it strange to use a validation in parser?

Maybe? I think of System.CommandLine as more of a parser generator than a parser. In that sense, your code configures a custom grammar. `ParseArgument<T>` gives you the ability to write the rules of that grammar, albeit in a very constrained way. 

Of course the real point is to make the API both flexible and understandable. Does this approach seem reasonable? What would you do differently?

**Comment by JohniMichels** [comment]
I think it's a really nice solution in the sense that it already provides everything to be DRY, and will be greater when `ParseArgument` receives an already parsed value, since it'll have those 3 first lines already resolved.
