### ISSUE TITLE
Subcommands are not shown in help

### ISSUE THREAD

**Issue by muni-mavenblue** [dotnet/command-line-api#1193]
My exe is deploy.exe.
The deploy.exe -h doesn't show it's subccomands. This is what is shown:
```
.\deploy.exe -h
Usage:
  deploy [options] [<args>...]

Arguments:
  <args>

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

But there are several subccomands. The subcommands work as expected. And if I make a mistake with a subcommand then help is much better, e.g.: 
```
.\deploy.exe -c c buil
'buil' was not matched. Did you mean 'build'?
Unrecognized command or argument 'buil'

Usage:
  deploy [options] [command]

Options:
  -c, --component <component>
  --version                      Show version information
  -?, -h, --help                 Show help and usage information

Commands:
  git
  build
  version <versionString>
  run <AVM|AVM2|BSM|EPM|MUP> <Acc|Local|Prod|ST|Test> <versionString>
  ftp <AVM|AVM2|BSM|EPM|MUP> <Acc|Local|Prod|ST|Test> <versionString>
```

So this help output is great, it shows all available sub commands. Why doesn't it show this commands list when I do the command deploy.exe -h?

Can I improve the deploy.exe -h output myself?

**Comment by jonsequitur** [comment]
That's a very good question. 

Which version of System.CommandLine are you using? Can you provide a code example that reproduces the issue?

**Comment by muni-mavenblue** [comment]
The version is v2.0.0-beta1.20574.7, the latest from nuget at the moment of writing.

After some testing I found the problem. I also had installed the System.CommandLine.DragonFruit (v0.3.0-alpha.20574.7) from nuget. After removing the dragonfruit package it now works as expected!

**Comment by jonsequitur** [comment]
Ah, very interesting. DragonFruit doesn't support subcommands, so that makes sense. 

Thanks!
