### ISSUE TITLE
Handling suggestion sort order?

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/command-line-api#12]
If the provider calls `Define.Arguments().FromAmong("high","medium").FromAmong("low")` should we sort the suggestion list alphabetically or in the order that configured?

**Comment by kimsey0** [comment]
Currently, the default implementation of `GetSuggestions` in `Symbol` [orders child symbol aliases alphabetically](https://github.com/dotnet/command-line-api/blob/afd010ba8cb3cbd714c734465d1a5de1ee133e2d/src/System.CommandLine/Symbol.cs#L149). Could it make sense to change that to order first by position at which the text to match was matched, then alphabetically? I.e., changing:

``` cs
.OrderBy(symbol => symbol, StringComparer.OrdinalIgnoreCase)
.Containing(textToMatch);
```

to

``` cs
.Containing(textToMatch)
.OrderBy(symbol => symbol.IndexOfCaseInsensitive(textToMatch))
.ThenBy(symbol => symbol, StringComparer.OrdinalIgnoreCase);
```

For a concrete tool I'm working on, this would change the suggestions order when typing `my-tool me<tab>` from
> fix-docker-desktop-ti**me**
> [meta](https://github.com/mateodelnorte/meta)-pull

to the, to me, more natural:

> **me**ta-pull
> fix-docker-desktop-time
