### ISSUE TITLE
IStandardIn doesn't provide a way to read input

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/command-line-api#1201]
I'm trying to abstract some console related things with the IConsole and found that `IStandardIn` only says whether things are redirected. Could we add the following API:

```csharp
    public interface IStandardIn
    {
        bool IsInputRedirected { get; }

        TextReader In { get; }
    }
```

**Comment by jonsequitur** [comment]
We're working on completing this interface (#275). I'll close this as a duplicate.
