### ISSUE TITLE
SecureString is not boud as ArgumentType

### ISSUE THREAD

**Issue by lennybacon** [dotnet/command-line-api#1210]
It would be great to have the ability to use SecureString as argument type.

```csharp
      var argument = new Argument("password") {
        Description = "The user name for basic authentication.",
        ArgumentType = typeof(SecureString),
        Arity = ArgumentArity.ZeroOrOne
      };
```

**Comment by jonsequitur** [comment]
`SecureString` should be avoided: https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-5.0#remarks

It's on the path to obsoletion (https://github.com/dotnet/designs/pull/147), so we shouldn't add support for it here.

**Comment by lennybacon** [comment]
Thanks
