### ISSUE TITLE
Process class

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#1213]
The `System.CommandLine.Invocation.Process` seems out of scope for this library?

And because of its namespace you end up with it easily, leading to conflicts with `System.Diagnostics.Process`.

**Comment by tmds** [comment]
cc @jonsequitur

**Comment by jonsequitur** [comment]
Agreed. It should be internal. It's used for `dotnet-suggest` integration but shouldn't be part of the public API.

**Comment by elgonzo** [comment]
@jonsequitur
@Keboo

unless i am confused, pull https://github.com/dotnet/command-line-api/pull/1255 does not resolve the issue reported here, as `System.CommandLine.Invocation.Process` is still public.

**Comment by jonsequitur** [comment]
Oops. :)

**Comment by jonsequitur** [comment]
Second time's the charm.
