### ISSUE TITLE
Suggestion: Add LegalFileNamesOnly to ArgumentExtensions

### ISSUE THREAD

**Issue by AronParker** [dotnet/command-line-api#1224]
There is an overload for legal file paths: https://github.com/dotnet/command-line-api/blob/4b43131a66cb675d681f23254a08a7e3d34a7e6f/src/System.CommandLine/ArgumentExtensions.cs#L112 

Which is convenient to implement because the .NET framework provides `Path.GetInvalidPathChars()`. However there is also `Path.GetInvalidFileNameChars()` so adding LegalFileNamesOnly to ArgumentExtensions would be quite useful but costs very little effort to implement. I have needed this recently but was disappointed to learn it wasn't found.

I have a pull request ready (no tests yet though) but the Contributing guide tells me to make an issue first so that's what I'm doing here.

**Comment by jonsequitur** [comment]
That sounds useful. We'd definitely appreciate a PR.
