### ISSUE TITLE
Arity ZeroOrMore not working with default exposed package

### ISSUE THREAD

**Issue by FelicePollano** [dotnet/command-line-api#1232]
Have this code:
 ```
var rootCommand = new RootCommand()
            {
               new Option<string>(new []{"--path","-p"},getDefaultValue:()=>Directory.GetCurrentDirectory(),"path where to search")
                ,new Option<string[]>(new []{"-f","--files"},getDefaultValue:()=>new []{"*.*"})
                ,new Argument<string>("search","string to search for")
            };
```

Option "files" will be forwared as null to the handler if we use the package   2.0.0-beta1.20574.7. In order to make it works I had to use a version compiled by the trunk. Is this intended or can we open an issue?

**Comment by jonsequitur** [comment]
Can you give an example of the handler code?

**Comment by FelicePollano** [comment]
Branched out my project to reproduce: https://github.com/FelicePollano/FFF/tree/caseforIssue%231232, 
my code was more or less like this:
```
 rootCommand.Handler= CommandHandler.Create<string,string,string[]>(async (search,path,files)=> {
            
                await  Task.CompletedTask;
                if(null==files)
                    throw new Exception("files is null");
                    /* original code below */
              
            });
```
and ... at the time I'm writing is working...
Will try to revert the trunk in using the package, if it works I will close the issue myself...

**Comment by FelicePollano** [comment]
even the main branch of my tool now is working by using the package:
https://github.com/FelicePollano/FFF/tree/main
No idea how didn't work some days ago, and no way to prove, so issue is closed, thank you for your interest in it.
