### ISSUE TITLE
Arguments after double dash are not parsed as arguments

### ISSUE THREAD

**Issue by heaths** [dotnet/command-line-api#1238]
I'm upgrading a project that was using a 0.1 version of System.CommandLine to a 2.0 version, but found in 2.0 arguments after a double dash are not parsed as arguments. You even have tests for it that treat them as unparsed text, despite having [commented on a past issue](https://github.com/dotnet/command-line-api/issues/959#issuecomment-653192286):

> From https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean
>> More precisely, a double dash (--) is used in most bash built-in commands and many other commands to signify the end of command options, after which only positional parameters are accepted.

Whether someone actually uses this or not we can't know, but it does create a possible compatibility issue. If a goal is unix-like behavior, the passing positional arguments after a double dash should at least be an option.

**Comment by jonsequitur** [comment]
Thanks, @heaths. This is a tricky one.

The behavior in System.CommandLine 2.x is based on the `dotnet` CLI's behavior going back several years. Reading through the linked comments and other sources, I agree that the current behavior is incorrect. I'm surprised it hasn't been raised before, but it's well-enough entrenched that changing it now would be a significant breaking change. 

But what we should probably do is introduce a configuration point allowing people to opt into the current behavior in order to maintain it as a legacy implementation, while defaulting to the more POSIX-ly correct behavior.

**Comment by heaths** [comment]
I appreciate the compatibility concern and agree that some configuration for opting into it might be good. In my case, there's really no supported scenario for passing `--` followed by extra arguments like there is for `dotnet run -- <args to target>`.

I was able to [work around](https://github.com/heaths/Nerdbank.GitVersioning/blob/2d697b3e81b86dcf6f1e3a1137a222d322cfc914/src/nbgv/Program.cs#L201-L217) with middleware, but admit it's not a hack I feel particularly great about. The target tool has been around for a long time, though, and documented `--` in usage so I didn't want to break existing callers.

BTW: I hope I did that as intended - docs say the arguments can be modified but I found 1) that wasn't true (can find no way to do it), and 2) it still happened too late, hence the enum cast hack. If you have a better suggestion I'm all ears.

**Comment by jonsequitur** [comment]
> docs say the arguments can be modified but I found 1) that wasn't true (can find no way to do it)

Can you elaborate?

**Comment by heaths** [comment]
There's [this line](https://github.com/dotnet/command-line-api/blob/main/docs/How-To.md#user-content-middleware-pipeline:~:text=altering%20the%20input%20before%20invoking%20your%20application%20logic):

> altering the input before invoking your application logic

Though, to be fair, I see it [also says](https://github.com/dotnet/command-line-api/blob/main/docs/How-To.md#user-content-middleware-pipeline:~:text=The%20ParseResult%20can%20even%20be%20replaced%20during%20this%20phase):

> The ParseResult can even be replaced during this phase

Would be nice if middleware - at least if executed early enough - could simply update values as desired - perhaps access to a context that provides read-write access to arguments instead of read-only access as other code outside middleware does (or would).

**Comment by jonsequitur** [comment]
Got it. I think "altering the input" was meant to convey replacing the `InvocationContext.ParseResult` and not to imply something more granular. I suspect a lot of edge cases will start to crop up if we allow the `ParseResult` to become mutable.

**Comment by ryuujo1573** [comment]
Thanks for your work! 
..and I was wondering if you could please have a look of this individual case? Excuse me for my poor English..

I was trying to parse some pattern like this:
> run python
> print("hello world!")

Yes as you can see, the args to be parse contain multiple lines, and, in this case: 
```C#
var runComplex = new Command("run")
{
    new Argument<string>("lang"), // python
    new Argument<string>("code"), // the trailing string (after the first \n)
}
```
```C#
builder.UseMiddleware(async (context, next) =>
{
    var parseResult = context.ParseResult;
    // parseResult.ValueForArgument<string>("code");
    if(parseResult.UnmatchedTokens.Count > 0)
    {
        var str = parseResult.UnmatchedTokens
            .Aggregate((a, b) => $"{a} {b}")
            .Replace("`n", "\n");
        var code = str[(str.IndexOf('\n') + 1)..];
        var lang = parseResult.ValueForArgument<string>("lang");
        RunCode(lang, code);
    }
    else
        await next(context);
});
```

I was stuck for how to aggregate all the following text into one argument *`code`*, rather than turning into `ParseResult.UnmatchedTokens`, what could I do?
Thank you!

**Comment by jonsequitur** [comment]
@ryuujo1573 If you want the `code` argument to be able to handle multiple tokens, you can do this:

```csharp
var runComplex = new Command("run")
{
    new Argument<string>("lang")
    new Argument<string[]>("code") 
}
```

**Comment by ryuujo1573** [comment]
> @ryuujo1573 If you want the `code` argument to be able to handle multiple tokens, you can do this:
> 
> ```cs
> var runComplex = new Command("run")
> {
>     new Argument<string>("lang")
>     new Argument<string[]>("code") 
> }
> ```

Thanks! I'll try this!! <3
