### ISSUE TITLE
Unspecified options of nullable string type should default to null instead of an empty string

### ISSUE THREAD

**Issue by database64128** [dotnet/command-line-api#1244]
Similar to #1233:

``` cs
using System;
using System.CommandLine;
using System.CommandLine.Invocation;
using System.Text;

var rootCommand = new RootCommand("Unspecified options of nullable string type should default to null instead of an empty string.")
{
    new Option<string?>("--name"),
};
rootCommand.Handler = CommandHandler.Create<string?>(NullCheck);

Console.OutputEncoding = Encoding.UTF8;
await rootCommand.InvokeAsync(args);

static void NullCheck(string? name)
{
    if (name is null)
        Console.WriteLine("Name: Null!");
    else
        Console.WriteLine("Name: Not null!");
}
```

Without passing `--name`, `name` should be `null` instead of an empty string.

**Comment by database64128** [comment]
I took a look at the code. It seems there's currently no way for `typeof(T)` to tell the difference between `string` and `string?` types. I'm not sure if it's possible to fix this issue with the current implementation of nullable reference types in C#.

But we can at least enable nullable ref types in tests to ensure things work in nullable contexts.

**Comment by Corey-M** [comment]
@database64128 While Nullable Reference Types are a compile-time concept they do leave [some clues][1].

Sadly, like all good murder mysteries, those clues are seldom simple to find. You'll need to search several places to get an idea of whether or not any particular parmeter is `string?`, `string!` or `string`. Doable, but not entirely simple. Also won't always work on `internal`, `private` and `protected` methods depending on compile options.

NRT turned out to be a lot more complex than anyone on the language team ever dreamed it would be. This is one of the outcomes.

[1]: https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md

**Comment by database64128** [comment]
``` cs
var nameOption = new Option<string?>("--name", () => null);
```

When `--name` is not specified, `name` is still an empty string. Is this expected?

**Comment by database64128** [comment]
``` cs
var nameOption = new Option<string?>("--name", ParseIntoNullableString, true);

static string? ParseIntoNullableString(ArgumentResult argumentResult)
    => argumentResult.Tokens.Any() ? argumentResult.Tokens.Single().Value : null;
```

Even with this, the option still returns an empty string when not specified.

cc @jonsequitur @Keboo

**Comment by jamesthurley** [comment]
I've also encountered the same issue as @database64128, after upgrading from 0.3 to 2.0 I can't seem to differentiate between the user not providing an argument vs providing an argument value as an empty string, as `getDefaultValue: () => null` seems to be ignored for stings.

**Comment by js6pak** [comment]
Seems like this issue has been fixed. I can't pinpoint by what exactly but in `2.0.0-beta2.21617.1` it works correctly so the default value for string options is the actual default value (`null` or `getDefaultValue`) not an empty string :tada:

**Comment by database64128** [comment]
> Seems like this issue has been fixed. I can't pinpoint by what exactly but in `2.0.0-beta2.21617.1` it works correctly so the default value for string options is the actual default value (`null` or `getDefaultValue`) not an empty string 🎉

8a0f746b0d9f2afba278349482cd7c2137de473d. Definitely better than before, but not exactly a fix though. Now an unspecified `Option<string>` gives you `null`, which is not null safe. I had to either replace `Option<string>` with `Option<string?>` and add null checks, or stick with `Option<string>` and set `Option.IsRequired` to `true`. Kind of clumsy, but that's all we can do given the current state of nullable reference types.
