### ISSUE TITLE
Registration with dotnet-suggest requires UseShellExecute to be False on NetFx472

### ISSUE THREAD

**Issue by smaine** [dotnet/command-line-api#1254]
Does dotnet-suggest support suggestions from applications built against the desktop framework?

I was spelunking why `dotnet-suggest list` wasn't showing my application as being registered, which lead me to the sentinel file in [IO.Path]::GetTempPath()\system-commandline-sentinel-files, where this exception was logged:

```
Exception during registration:
System.InvalidOperationException: The Process object must have the UseShellExecute property set to false in order to redirect IO streams.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.CommandLine.Invocation.Process.StartProcess(String command, String args, String workingDir, Action`1 stdOut, Action`1 stdErr, ValueTuple`2[] environmentVariables)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_1>d.MoveNext()
```
This feels like it's probably framework/OS dependent, which is why I'm hesitant to just submit a patch to https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs

**Comment by elgonzo** [comment]
No need to submit a patch, as the respective code change (UseShellExecute = false) has been made in January: https://github.com/dotnet/command-line-api/pull/1145/commits/ad22b69ac8944fe29fd3433c4072828f3398d5af
:-)

**Comment by smaine** [comment]
Awesome. Is that after the https://www.nuget.org/packages/System.CommandLine/2.0.0-beta1.20574.7, which is the most recently published version available on NuGet.org?

**Comment by jonsequitur** [comment]
It is. The fix is available on the "daily" build feed and a new version will be published on nuget.org in the next day or two.

**Comment by smaine** [comment]
Updated to 21216.1 and it works as expected. Thanks for pushing the updated package!
