### ISSUE TITLE
dotnet-format broken from removal of Option.Argument setter

### ISSUE THREAD

**Issue by kzu** [dotnet/command-line-api#1265]
I just noticed that the [FormatCommand](https://github.com/dotnet/format/blob/main/src/FormatCommand.cs#L48-L84) customizes options by setting the argument directly.

What's the migration path for scenarios like those?

[edit]

At least these two seem to be (mostly) equivalent:

```csharp
new Option(new[] { "--fix-style", "-s" })
{
    Argument = new Argument<string?>("severity") { Arity = ArgumentArity.ZeroOrOne }.FromAmong(SeverityLevels)
},
```

and

```csharp
new Option<string?>(new[] { "--fix-style", "-s" }) { Name = "severity" }.FromAmong(SeverityLevels),
```

The only issue is that the second option (compatible with latest package) actually adds "severity" as an alias to the option, which the former doesn't.

**Comment by jonsequitur** [comment]
What's your goal in setting `Name = "severity"`? Are you doing this in order to customize help or for model binding or value lookup from the parse result?

**Comment by kzu** [comment]
This is not my CLI app, it's dotnet/format. No idea what or why they are setting that :). But asking on their side of the issue might help answer that: https://github.com/dotnet/format/issues/1111

**Comment by JoeRobich** [comment]
> What's your goal in setting `Name = "severity"`?

@jonsequitur It is to customize the help message.

**Comment by jonsequitur** [comment]
Got it. For that, you can now do this:

```cs
new Option<string?>(new[] { "--fix-style", "-s" }) { ArgumentHelpName = "severity" }.FromAmong(SeverityLevels)
```
