### ISSUE TITLE
help UX: usage show [options] in a bad way

### ISSUE THREAD

**Issue by daniaremon** [dotnet/command-line-api#1268]
Simple issue:
when i need help (with "-h" "--help" or other) in a command or subcommand, which has options, this happens:

![image](https://user-images.githubusercontent.com/32546402/117197595-9d9a1380-adad-11eb-9c1b-65866f09f9f6.png)

The help say I can use -n option after the main command. But it must be used after the xmodule subcommand.

-------------------------------------
Suggestion:

maincommand [options] generate xmodule [options A]

options:
-?, -h ....

options A:
-n, --name ....

**Comment by elgonzo** [comment]
I cannot reproduce. Are you perhaps using an old-ish version of System.CommandLine?

(I would have checked older System.CommandLine versions myself over on dotnetfiddle.net, but unfortunately the package selector currently seems to be frozen and non-functional, so you have to tolerate me blind-guessing :) )
<br>

Using version **2.0.0-beta1.21109.1** with the following code:

```csharp
var rootCmd = new RootCommand()
{
    new Command("generate")
    {
        new Command("xmodule")
        {
            new Option<string>(new [] {"-n", "--name" })
        }
    }
};

rootCmd.Invoke("generate xmodule --help");
```
i get the following output: 

    Usage:
      HelpTestApp generate xmodule [options]

    Options:
      -n, --name <name>
      -?, -h, --help       Show help and usage information

If you still see the issue with 2.0.0-beta1.21109.1, please post a brief code example that reproduces the issue you see.

**Comment by daniaremon** [comment]
Thanks. It was the version:

I was working with version (2.0.0-beta1.21216.1):

![image](https://user-images.githubusercontent.com/32546402/117384350-5d6b8b80-aea8-11eb-9513-f3c7e0c62373.png)

I tried the same code with a newer version (2.0.0-beta1.20071.2) and it works!!! :

![image](https://user-images.githubusercontent.com/32546402/117384798-6577fb00-aea9-11eb-89c1-8f6ee7bef45d.png)

SDG
