### ISSUE TITLE
Add "Description" to help 

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/command-line-api#1276]
6.0.100-preview.4.21209.4 

We've added the description to help (yeah!!!). However, it currently appears under the subcommand name. To better mirror the other headers like "Usage", I suggest we use "Description:" instead. 

![image](https://user-images.githubusercontent.com/5844318/114265948-774ca800-99a8-11eb-9fed-0f761d7dfe5d.png)

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/command-line-api/blob/d4d31f7291da5e06b573bf5f3096542b02fe5553/src/System.CommandLine/Help/HelpBuilder.cs#L63
