### ISSUE TITLE
Support for options with optional arguments

### ISSUE THREAD

**Issue by magol** [dotnet/command-line-api#1294]
I wonder if it is possible to have flag options that may or may not define a value, like it is described in https://github.com/dotnet/corefxlab/issues/520

**Comment by jonsequitur** [comment]
This is supported today by setting arity to `ZerOrOne`.

**Comment by magol** [comment]
@jonsequitur 
Ahhh, thank you. 

I have now tested to add ```ArgumentArity.ZeroOrOne``` to my ```Option``` declaration, wish make it possible to ignore the option value. But how do I know if the option is given or not? I get the same value regardless whether I specify the option or not.

```C#
            RootCommand root = new RootCommand
            {
                new Option<int>("--server", "Some description", ArgumentArity.ZeroOrOne)
                {
                    IsRequired = false,
                    ArgumentHelpName = "PortNumber"
                }
            };
            root.Handler = CommandHandler.Create(delegate(int server)
            {
                Console.WriteLine($"--server = {server}");
            });
```

**Result**
```
> MyApp.exe
--server = 0
> MyApp.exe --server
--server = 0
> MyApp.exe ---server 1234
--server = 1234
```

And I want it to be visible in the help that the value is optional with [ and ], like this
```
Options:
  --server [PortNumber]  Some description
```

**Comment by jonsequitur** [comment]
For this you can use `int?`:

```cs

RootCommand root = new RootCommand
{
    new Option<int?>("--server", "Some description", ArgumentArity.ZeroOrOne)
    {
        IsRequired = false,
        ArgumentHelpName = "PortNumber"
    }
};
root.Handler = CommandHandler.Create(delegate(int? server)
{
    Console.WriteLine($"--server = {server}");
});

root.Invoke("");
root.Invoke("--server");
root.Invoke("--server 123");
```

![image](https://user-images.githubusercontent.com/547415/120074138-4ad01680-c050-11eb-8492-02b462080a7d.png)

**Comment by magol** [comment]
The problem is that I don't can see if the ```--server``` option is given or not. The first two alternatives in your example  give the same result.

**Comment by jonsequitur** [comment]
Ah, I see. For that you'll need to pass a custom `ParseArgument<T>` to the `Option<T>` constructor, and you can check the `ArgumentResult.Tokens` to see exactly what was passed.

**Comment by magol** [comment]
But, if I sett ```ParseArgument<T>```, I cannot set ```ArgumentArity```. So, if I not specify any value, ```OnParse``` will not be called and it become an error output.

```C#
            var root = new RootCommand
            {
                new Option<int?>("--server", OnParse,true,"Some description")
                {
                    IsRequired = false,
                    ArgumentHelpName = "PortNumber"
                }
            };
```

**Comment by SiliconFiend** [comment]
I would also find this useful. I am currently working around it like this:
`var myOption = new Option<string>(new string[] { "--my-option", "-A" }, description: "Enable my option. Optionally specify an argument.") { Arity = ArgumentArity.ZeroOrOne };`
`var rootCommand = new RootCommand
{
myOption
};`
`rootCommand.Handler = CommandHandler.Create<...> ...`
`bool bMyOptionActive = rootCommand.Parse(args).CommandResult.FindResultFor(myOption) is { };`
`rootCommand.InvokeAsync(args);`
Note that setting Arity in the initializer requires C# 9.0 or higher. I didn't find a templated constructor that took the arity as an argument. But if you don't set it, the command line parser will complain if you leave off the argument. The "is { }" construct also requires C# 8.0 or greater but there are workarounds for that.

**Comment by jonsequitur** [comment]
@magol You can now set the `Arity`:

![image](https://user-images.githubusercontent.com/547415/124958469-0b8dd180-dfcf-11eb-9fbd-6a46656f9336.png)

**Comment by lavedon** [comment]
@jonsequitur ,

I seem be having a problem implementing your technique. I am not able to create an option that can be in 3 states (no option entered, option flag without arguments, and option with arguments).

I can not pass any argument to the option, no matter what argument is passed it is overwritten with the default value.
However, If the user does not enter the option the flag returns null per expected behavior.

```csharp
var ageOption =  new Option<int?>("--age", _ => 0, true, "Enter your age")
{
	IsRequired = false,
	ArgumentHelpName = "Enter your age.",
	Arity = ArgumentArity.ZeroOrOne
};
```
No option
age is null
--age 
age == 0
--age 37
age == 0 << Whoops 

I tested this with Option<string?>
and always have the same problem

Here is my complete code:

```csharp
#nullable enable
#nullable disable warnings
using System;
using System.CommandLine;
using System.CommandLine.Invocation;
using System.Reflection;

namespace flag_args
{
    class Program
    {
        static void Main(string[] args)
        {
            var rootCommand = new RootCommand("root command").WithHandler(nameof(HandleArgs));
            var ageOption =  new Option<int?>("--age", _ => 0, true, "Enter your age")
            {
                IsRequired = false,
                ArgumentHelpName = "Enter your age.",
                Arity = ArgumentArity.ZeroOrOne
            };

            rootCommand.AddOption(ageOption);
            rootCommand.Invoke(args);

            bool running = true;
            while (running){
                Console.WriteLine();
                Console.Write(">");
                var input = Console.ReadLine();
                if (input == "q")
                {
                    running = false;
                    return;
                }
                string[] newArgs = input.Split(' ');
                rootCommand.Invoke(newArgs);
            }
        }

        static void HandleArgs(int? age)
        {
            if (age is null)
            {
                Console.WriteLine("You do not want to tell me your age.");
            } else if (age == 0) {
                Console.WriteLine($"You used the age flag.  But did not enter an age.  I will guess.");
            } else {
                Console.WriteLine($"You entered your age as {age}");
            }
        }

    }

    public static class ProgramExtensions
    {
        public static Command WithHandler(this Command command, string name)
        {
            var flags = BindingFlags.NonPublic | BindingFlags.Static;
            var method = typeof(Program).GetMethod(name, flags);

            var handler = CommandHandler.Create(method!);
            command.Handler = handler;
            return command;
        }
    }
}
```

Thank you kindly for any assistance.  And thank you for all your hard work on this indispensable library.

**Comment by BobSilent** [comment]
the result is always `0` because your parsing is always returning `0`: `_ => 0`
you need to take care for whole parsing, so e.g.

```csharp
            var rootCommand2 = new RootCommand
            {
                new Option<int?>(name: "--age",
                    parseArgument: result => int.TryParse(result.Tokens.FirstOrDefault()?.Value, out var value) ? value: 0,
                    isDefault: true,
                    description: "Enter your age")
                {
                    IsRequired = false,
                    ArgumentHelpName = "your age",
                    Arity = ArgumentArity.ZeroOrOne
                }
            };
```

but calling it like that
```csharp
            rootCommand2.Handler = CommandHandler.Create(delegate (int? age)
            {
                System.Console.WriteLine($"age='{(age == null ? "null" : age)}'");
            });
            rootCommand2.Invoke("");
            rootCommand2.Invoke("--age");
            rootCommand2.Invoke("--age 123");
```
I would expect as output:
```
age='null'
age='0'
age='123'
```

but i get:
```
age='0'
age='null'
age='123'
```

as for `rootCommand2.Invoke(@"--age");` the `ParseArgument<T>` is not invoked.

@jonsequitur is this expected? 
I would expect that `ParseArgument<T>` gets invoked for 
```csharp
rootCommand2.Invoke("--age");
rootCommand2.Invoke("--age 123");
```
and not for `rootCommand2.Invoke("");`

**Comment by jonsequitur** [comment]
The constructors that take a `ParseArgument<T>` also have a `bool  isDefault` which, when set to true, indicate that the `ParseArgument<T>` should get called even if there are no matching tokens for the option. In this way it can be used to generate a default value. For this reason,  `rootCommand2.Invoke("")` does call the custom parse delegate.

Thee appears to be a bug though in that `rootCommand2.Invoke("--age")` is not calling it.

**Comment by BobSilent** [comment]
Maybe to be complete here from documentation perspective: 
Set `isDefault: false` in `Option` constructor to get this result:
```
age='null'   //rootCommand2.Invoke("")
age='0'      //rootCommand2.Invoke("--age")
age='123'    //rootCommand2.Invoke("--age 123")
```
and being able to differentiate between the three calls.

Unfortunately when parsing I do not know if the parser was called to set a `defaultValue` because the Option `--age` was set but no argument was specified or as the option was omitted (`--age` not set on command line): 
I cannot differentiate between a `rootCommand2.Invoke("")` and a `rootCommand2.Invoke("--age")` call.
@jonsequitur  is it possible to provide this information during parsing? 

First I thought there is an `internal IsImplicit` property on `ArgumentResult` but this is internal and it only checks if `Argument.HasDefaultValue && Tokens.Count == 0` 
which is `true` in both cases.

**Comment by jonsequitur** [comment]
The solution is not exactly obvious but this test shows how you can distinguish these cases. Short version: it's the option, not just the argument, that's implicit when e.g. `""` is parsed.

https://github.com/dotnet/command-line-api/blob/be7ff040e53022fa6730dc30ea511f7bdd97f3f9/src/System.CommandLine.Tests/ArgumentTests.cs#L503-L537

**Comment by jonsequitur** [comment]
And to be clear, suggestions for an easier API are very welcome.

**Comment by wasabii** [comment]
I believe @jonsequitur's solution fails for arrays. Even returning null from the parseArgument results in an empty array. Looks like it tries to do a GetvalueOrDefault somewhere, and generates a new array.
