### ISSUE TITLE
Dictionary<string, string> option parsed but not passt to handler

### ISSUE THREAD

**Issue by rgn** [dotnet/command-line-api#1297]
Hi,

I have the requirement to pass kev/value pairs as an option. So I've tried to implement the idea from [#840](https://github.com/dotnet/command-line-api/issues/840).

The parsing works as expected, but the returned instance is not passed to my handler.

````
var attributesOption = new Option<Dictionary<string, string>>("--attributes", parseArgument: argumentResult => {
	var dict = argumentResult.Tokens
              .Select(t => t.Value.Split('='))
              .ToDictionary(p => p[0], p => p[1]);

	Console.WriteLine($"Parsed {dict.Keys.Count} keys.");

	return dict;			
});

var rootCmd = new RootCommand()
{
	attributesOption
};

rootCmd.Handler = CommandHandler.Create<Dictionary<string, string>>(
	(attrs) =>
	{
		Console.WriteLine($"Received {attrs.Keys.Count} keys.");
	}
);

rootCmd.Invoke("--attributes foo=bar blah=blub fizz=buzz");

Output:

Parsed 3 keys.
Received 0 keys.
````

I've prepared a [dotnetfiddle](https://dotnetfiddle.net/KcGg4f) that shows this behavior with version 2.0.0-beta1.21216.1.

Any ideas? Did I make a mistake here?

**Comment by jonsequitur** [comment]
The name of your handler parameter (`attrs`) needs to match one of the aliases of your option, case insensitive and disregarding characters such as `"-"` that aren't valid in a parameter name. If you rename the parameter to `attributes` it should work.

**Comment by rgn** [comment]
You're right, thanks for the input. Somehow I overseen that.
