### ISSUE TITLE
Enhancement idea: Provide a CommandLineBuilder extension to display a startup banner and copyright message

### ISSUE THREAD

**Issue by BobSilent** [dotnet/command-line-api#1300]
It would be a good idea to have a `CommandLineBuilder ` Extension for enabling the display of a startup banner and copyright message.

something like 
```csharp
new CommandLineBuilder(...)
            .UseDefaults()
            .UseShowLogo() // <-------
            .Build()
            .InvokeAsync(args);
```

which displays this information
```
<ToolName> Version <FileVersion> (<assmeblyInfo.InformationVersion>)
<assmeblyInfo.Copyright>

```

and maybe provides an additional global option `--noLogo`, to not display the startup banner and copyright message.

it could maybe look like this
```csharp
        public static CommandLineBuilder UseShowLogo(
            this CommandLineBuilder builder,
            string titleOverride = default)
        {
            if (builder.Command.Children.GetByAlias("--noLogo") != null)
            {
                return builder;
            }

            var noLogoOption = new Option("--noLogo", "Do not display the startup banner and copyright message.");

            builder.AddOption(noLogoOption);

            builder.UseMiddleware(async (context, next) =>
                                  {
                                      if (!context.ParseResult.HasOption(noLogoOption))
                                      {
                                          var console = context.Console.Out;
                                          var assemblyInfo = // (string ProductName, string Copyright, string FileVersion, string InformationVersion)
                                          var toolName = titleOverride ?? assemblyInfo.ProductName;

                                          console.WriteLine($"{toolName} Version {assemblyInfo.FileVersion} {(string.IsNullOrWhiteSpace(assemblyInfo.InformationVersion) ? string.Empty : $"({assemblyInfo.InformationVersion})")}");

                                          if (!string.IsNullOrWhiteSpace(assemblyInfo.Copyright))
                                          {
                                              console.WriteLine($"{assemblyInfo.Copyright}");
                                          }

                                          console.WriteLine();
                                      }

                                      await next(context).ConfigureAwait(false);
                                  },
                                  // show also when usage help is displayed
                                  MiddlewareOrder.ExceptionHandler);

            return builder;
        }
```

**Comment by jonsequitur** [comment]
Preferences in this area vary so widely that I think it's best to let people create these kinds of extensions themselves. This makes it easier to use libraries like Spectre.Console. 

We're still in the process of making help customization more flexible for this same reason.

**Comment by terrajobst** [comment]
Personally, I massively dislike logos. I understand that people are trying to emulate what they see in our command line tools, but when it comes to the CLI my suggestion is to emulate syntax conventions and general look & feel of Unix based tools.

**Comment by BobSilent** [comment]
I totally agree with you, and personally I also like much more the unix look&feel (in the meanwhile).

But i also have users which are not so familiar with the commandline and can make mistakes even by running a commandline tool... so it is easier to show such a banner/logo for them to directly display the version information. Otherwise they are not able to tell me which tool version was used for issue investigation.

But anyhow your (wise) words 😊 let me directly close this issue..  
Thanks for reminding me to stay with basics and not to overengineer here 😉
