### ISSUE TITLE
HelpBuilder can throw ArgumentOutOfRangeException when console has no width

### ISSUE THREAD

**Issue by adamralph** [dotnet/command-line-api#1306]
In some environments, e.g. [CircleCI](https://circleci.com/), `System.Console.WindowWidth` [returns a negative integer](https://github.com/dotnet/runtime/blob/a822d3909b90139b642b143e889505ab7157b10c/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L38).

This value of `System.Console.WindowWidth` is [used by `System.CommandLine.CommandLineConfiguration`](https://github.com/dotnet/command-line-api/blob/a0a2bf5ccfe828b9a2ad32f8e3dd3ba8d39e7ed7/src/System.CommandLine/CommandLineConfiguration.cs#L94) as an argument to `HelpBuilder`, which [throws an exception](https://github.com/dotnet/command-line-api/blob/a0a2bf5ccfe828b9a2ad32f8e3dd3ba8d39e7ed7/src/System.CommandLine/Help/HelpBuilder.cs#L25) if the value is less than zero.

```text
Unhandled exception. System.ArgumentOutOfRangeException: Max width must be positive (Parameter 'maxWidth')
   at System.CommandLine.Help.HelpBuilder..ctor(IConsole console, Int32 maxWidth)
   at System.CommandLine.CommandLineConfiguration.<>c.<.ctor>b__1_0(BindingContext context)
   at System.CommandLine.Invocation.ServiceProvider.<>c__DisplayClass1_0.<.ctor>b__3(IServiceProvider _)
   at System.CommandLine.Invocation.ServiceProvider.GetService(Type serviceType)
   at System.CommandLine.Binding.BindingContext.get_HelpBuilder()
   at System.CommandLine.Invocation.HelpResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
```

The end result is that a program using `System.CommandLine` cannot be invoked in those environments.

**Comment by jonsequitur** [comment]
Ouch.

**Comment by adamralph** [comment]
@jonsequitur could the be fix be as simple as https://github.com/dotnet/command-line-api/pull/1307 ?

**Comment by jonsequitur** [comment]
I don't think we want to disable help. `HelpBuilder` defaults to `int.MaxWidth` in order to output non-wrapping text when there's no terminal. So maybe instead of throwing we should just set the width to the default.

**Comment by adamralph** [comment]
@jonsequitur like so? https://github.com/dotnet/command-line-api/pull/1308/files

**Comment by adamralph** [comment]
Has this bug fixed been released?

**Comment by jonsequitur** [comment]
It's available on the daily feed. https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json

**Comment by adamralph** [comment]
Thanks @jonsequitur. I don't really want to go delving into alternate feeds, so I guess I'll just wait until it's on NuGet.
