### ISSUE TITLE
Please add '-V' as alias/optional alias for '--version'

### ISSUE THREAD

**Issue by cerebrate** [dotnet/command-line-api#1309]
This is very commonly used, especially on the Linux platform, and I would like to provide it.

**Comment by jonsequitur** [comment]
Initially, we should enable this via #1332 and let people add the alias themselves if they want to. 

Before making it a default for everyone, I'd want to collect more opinions about it.

**Comment by cerebrate** [comment]
#1332 would satisfy my requirements perfectly, so that in itself works for me.

**Comment by jonsequitur** [comment]
If so, feel free to close this. I'll add #1332 to the [2.0 milestone](https://github.com/dotnet/command-line-api/milestone/1).

**Comment by cerebrate** [comment]
Will do.
