### ISSUE TITLE
'Parser' does not contain a definition for 'InvokeAsync'

### ISSUE THREAD

**Issue by a-game** [dotnet/command-line-api#1313]
I'm trying to add a middleware to my command line tool as described [here](https://github.com/dotnet/command-line-api/blob/main/docs/How-To.md#middleware-pipeline)

But I'm getting an error saying that the `Parser` does not have an `InvokeAsync`. I looked around and found a related question and answer https://github.com/dotnet/command-line-api/issues/627#issuecomment-528160677. Where it was advised to use the a parser extension method.

Is that still valid? I can't seem to find the mentioned `InvocationExtensions` or any `ParserExtensions`.

Here is my code:

```csharp
            var root = new RootCommand("cmd") {
                new Command("child") {
                    new Command("grandchild") {
                        new Option<string>(
                            new []{"--name", "-n"},
                            getDefaultValue: () => "Game",
                        ),
                    }.WithHandler(typeof(Program), nameof(DoStuff)), // This is just an extension metod
                 }
            };

            var cmdBuilder = new CommandLineBuilder(root);
            cmdBuilder.UseMiddleware(async (context, next) =>
            {
                context.Console.Out.WriteLine("Hello!");
                await next(context);
            });

            cmdBuilder.UseDefaults();
            var parser = cmdBuilder.Build();
            return await parser.InvokeAsync(args); // Error: 'Parser' does not contain a definition for 'InvokeAsync'
```

**Comment by elgonzo** [comment]
You have to include the `System.CommandLine.Parsing` namespace. The parser-related extension methods are here: https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Parsing/ParserExtensions.cs

**Comment by a-game** [comment]
Thank you so much!
