### ISSUE TITLE
RootCommand with optional arguments

### ISSUE THREAD

**Issue by bradykelly** [dotnet/command-line-api#1325]
Is it at all possible to have an optional positional argument for a root command? If so, how can I achieve this?

**Comment by elgonzo** [comment]
Set the `Arity` property for your positional argument to `ZeroOrOne`:
```C#
var rootCmd = new RootCommand()
{
    new Argument<string>("MyArgument") { Arity = ArgumentArity.ZeroOrOne }
};
```
