### ISSUE TITLE
Is there a way to specify option groups for a command?

### ISSUE THREAD

**Issue by norbusonam** [dotnet/command-line-api#1330]
As an example, I have one command ("run") and 3 options (--file <file>, --support-file <file>, and --dir <directory>)

Is there a way I can enforce this to be the only allowed usage: 

_Calls file function_
run --file <some_file>
run --file <some_file> --support-file <some_file>
_Calls directory function_
run --dir <some_directory>

And in all other cases show an error and the help output?

In other words, the command can take either a file or a directory. If it takes a file, it can also take a support directory. Additionally, whether it takes a file or a directory, different handlers would be called.

Is the better way to do this to make a file subcommand and a dir subcommand for run?

**Comment by jonsequitur** [comment]
We don't have direct API support for this but you can do it using a custom `ParseArgument<T>` delegate passed to one or several of these `Option`  constructors.

**Comment by norbusonam** [comment]
@jonsequitur Will this result in --help being inaccurate since its a custom parser? And improper usage wouldn't print the --help output?

**Comment by jonsequitur** [comment]
Help won't reflect the custom parse rules. You could include that in the various `Option.Description` properties, or custom help using `HelpBuilder`.

Improper usage will still print the help output.

**Comment by norbusonam** [comment]
@jonsequitur Got it, thanks!
