### ISSUE TITLE
Single dash alias gets picked up in another option's IEnumerable argument

### ISSUE THREAD

**Issue by icedoor** [dotnet/command-line-api#1353]
I have a command, `testing`, that has a couple of options.
One option has two aliases, `-s` and `--silent`, and expects a `boolean` argument.
Another option has one alias, `--somestuff`, and expects an `IEnumerable<string>` argument.

Running:
`testing --somestuff this is -some stuff`

I expect the `--somestuff` option to get the argument `{ "this", "is", "-some", "stuff" }`
What actually happens is that it reads a part of `-some` as `-s` and then it cannot continue parsing the remaining  `ome stuff`.

Running:
`testing --somestuff this is --silentsome stuff`

It does what I expect and the `--somestuff` option gets the argument `{ "this", "is", "--silentsome", "stuff" }`

So the alias with double-dash, `--silent`, does not get picked up in the IEnumerable arguments but the single-dash alias, `-s`, does.

**Comment by elgonzo** [comment]
What you observe is the behavior resulting from POSIX (un)bundling (https://github.com/dotnet/command-line-api/blob/main/docs/Syntax-Concepts-and-Parser.md#bundling), which is the default behavior of System.CommandLine.

However, System.CommandLine can be configured to disable this POSIX bundling feature, for example by utilizing the CommandLineBuilder:
```c#
using System.CommandLine;
using System.CommandLine.Invocation;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

...

var parser = new CommandLineBuilder(yourRootCommand) { EnablePosixBundling = false }
	.UseDefaults()
	.Build();
	
parser.Invoke("--somestuff this is -some stuff");
```
dotnetfiddle demonstrating this: https://dotnetfiddle.net/kHHNxo

**Comment by icedoor** [comment]
@elgonzo I did not know about that, thank you for your response! Disabling posix bundling worked perfectly for my use case.
I cannot find any documentation on the EnablePosixBundling flag, that could be helpful.
