### ISSUE TITLE
ValueForOption<string>(Option) returns empty string when option is not present

### ISSUE THREAD

**Issue by mhutch** [dotnet/command-line-api#1360]
`ValueForOption(Option<string> option)` returns an empty string when the option is not present. This feels unintuitive and inconsistent. AFAICT this method returns `default` for other types when the option is not present, and it's odd for `string` to be different without a really good reason.

It's also annotated with `[MaybeNull]`. If I have nullable reference types enabled and do this:

```csharp
var myOptionValue = result.GetOptionValue(myStringOption);
Console.WriteLine(myOptionValue.Length);
```

I get a `CS8602` warning about dereferencing a possibly null value. _I have to check for null anyways but don't get any value from that check_.

Returning null would be useful. It's much easier to special case `null` than to special case an empty string, especially with non-nullable reference types:

```csharp
if (result.GetOptionValue(myOption) is string myOptionValue)
{
    // do stuff I only do when this option is passed
}
```

Or have very clear and readable handling of defaults:

```csharp
string myOptionValue = result.GetOptionValue(myOption) ?? "myDefaultValue";
```

**Comment by jonsequitur** [comment]
It originally did pass `null` for `string` as well as for `IEnumerable` types. We changed it based on some users' feedback, after which we've also heard feedback in favor of the original behavior.

One proposal that's been made a few times is to enable both behaviors by honoring nullability annotations, allowing the parser to treat e.g. `Option<string>`  differently from `Option<string?>`.

**Comment by qmfrederik** [comment]
Ouch, this is super counter-intuitive! So for most options, like `FileInfo`, you can do `if(value != null)` but somehow, for strings, you need `string.IsNullOrEmpty(value)`?

My vote goes to the original behavior ;-)

**Comment by JeroenBos** [comment]
Especially if `null` is _explicitly_ set as default value, like below, then I'm very surprised when the empty string is passed to the handler if the argument was not provided.

```csharp
new Option<string?>(alias: "mystring", getDefaultValue: () => null)
```
