### ISSUE TITLE
Exception details not shown for async commands

### ISSUE THREAD

**Issue by gabrielmaldi** [dotnet/command-line-api#1366]
When using `CommandHandler.Create(MethodInfo)` with an async method, if an exception is thrown, the details are not printed to the console.
```csharp
class Program
{
    public void TestCommand()
    {
        throw new InvalidOperationException();
    }

    public async void TestCommandAsync()
    {
        throw new InvalidOperationException();
    }

    static int Main(string[] args)
    {
        return new CommandLineBuilder(new RootCommand()
        {
            new Command("test")
            {
                Handler = CommandHandler.Create(typeof(Program).GetMethod("TestCommand"))
            },
            new Command("test-async")
            {
                Handler = CommandHandler.Create(typeof(Program).GetMethod("TestCommandAsync"))
            }
        })
            .UseDefaults()
            .Build()
            .Invoke(args);
    }
}
```

This is the output generated by running both commands:

<img width="1037" alt="Screen Shot 2021-07-31 at 20 13 12" src="https://user-images.githubusercontent.com/3728897/127754554-ff55914c-b9b6-46c1-9b90-76cd24831f0b.png">

For the async method, only `Unhandled exception` is printed.

The behavior is the same if we use:
```csharp
static async Task<int> Main(string[] args)
{
    return await new CommandLineBuilder(new RootCommand()
    ...
        .InvokeAsync(args);
```

Is there a way to get the full exception details printed to the console when using async commands?

Thanks!

**Comment by elgonzo** [comment]
That's a problem with your code, not a problem with System.CommandLine.

Your async method definition is using `async` in conjunction with `void` return type, hence no exception being caught. As per `async` documentation (https://docs.microsoft.com/en-us/dotnet/csharp/async#important-info-and-advice):


> async void should only be used for event handlers.
> 
> async void is the only way to allow asynchronous event handlers to work because events do not have return types (thus cannot  make use of Task and Task<T>). Any other use of async void does not follow the TAP model and can be challenging to use, such as:
>   
>  - _**Exceptions thrown in an async void method can't be caught outside of that method.**_
>  - async void methods are difficult to test.
>  - async void methods can cause bad side effects if the caller isn't expecting them to be async.

(Emphasis mine)

**Comment by gabrielmaldi** [comment]
@elgonzo, you're completely right. Thanks!
