### ISSUE TITLE
Value is populated incorrectly in same prefix scenario

### ISSUE THREAD

**Issue by fhnaseer** [dotnet/command-line-api#1369]
If options have same prefix, then value is not populated correctly if one value is provided.

Sample Code:
// Make a command,
var command = new Command("convert");
command.AddArgument(new Argument<string>("command") { Arity = ArgumentArity.ExactlyOne });

// Make options with same prefix,
var outputOption = new Option<string>(new[] { "--output", "-o" }, Resources.OutputFileOptionDescription);
var outputFormatOption = new Option<string>(new[] { "--output-format", "-f" }, Resources.OutputFormatOptionDescription);

// Create handler to parse,
            command.Handler = CommandHandler.Create<string, string, string>((command, output, outputFormat) =>
            {
...
            });

Run program with following arguments => convert -f xml

Expected Behavior: (in CommnadHandler.Create line) 
output = "xml", outputFormat = "xml"

Actual Behavior:
output = "", outputFormat = "xml"

It seems that during name matching, outputFormat is applied to both output and outputFormat instead of only output.

**Comment by elgonzo** [comment]
Seems to be the same issue as https://github.com/dotnet/command-line-api/issues/1365

**Comment by fhnaseer** [comment]
> Seems to be the same issue as #1365

Agree. Closing this one.
