### ISSUE TITLE
Could we expose the RawInput of ParseResult?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/command-line-api#1379]
I'd like to get the raw command line input via `ParseResult`, is the `RawInput` what I'm looking for, and could we expose it?
Are there some concerns?

**Comment by jonsequitur** [comment]
The `RawInput` property is internal because it's very much an implementation detail used by the suggestions system and is not always available. 

Can you say more about your use case?

Have you tried `Environment.GetCommandLineArgs`?
