### ISSUE TITLE
Question: can not get the option value

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/command-line-api#1383]
When I use the code sample below to parse the command line input, it seemed I could not get the option value correctly, is there something wrong with my code?

The code I used for the test:

``` c#
using System.CommandLine;

var command = new RootCommand("h");
command.AddOption(new Option(new[] { "-v", "--verbose" }, "Verbose"));
command.AddOption(new Option("--schema", "schema"));

var parseResult = command.Parse(args);

Console.WriteLine("----- Tokens ------");
foreach (var token in parseResult.Tokens)
{
    Console.WriteLine($"{token.Type}: {token.Value}");
}
Console.WriteLine("------------------");

Console.WriteLine($"Schema value: {parseResult.ValueForOption("--schema")}");
```

code repository: <https://github.com/WeihanLi/SamplesInPractice/blob/master/CommandLineAppSamples/GetStarted/Program.cs>

The command line input/output:

![image](https://user-images.githubusercontent.com/7604648/130328744-00930849-0ad9-4825-a91b-4f3bf7d06eda.png)

The option value should be `https`?

**Comment by elgonzo** [comment]
You haven't provided an argument type for your schema option, hence why `ValueForOption` returns _null_.

Define your option with a matching argument type, like:

```C#
command.AddOption(new Option<string>("--schema", "schema"));
```
or 
```C#
command.AddOption(new Option("--schema", "schema", argumentType: typeof(string)));
```
and it should work.

**Comment by WeihanLi** [comment]
Great thanks for your reply @elgonzo , worked as you mentioned above
