### ISSUE TITLE
CommandLineStringSplitter bug parsing commandline

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/command-line-api#1385]
I use the code below to parse my commandLine input
```c#
var commandLine = "POST --raw='{""Id"":1,""Name"":""Alice""}'";
CommandLineStringSplitter.Instance.Split(commandLine).ToArray();
```

The result I got is :

![image](https://user-images.githubusercontent.com/7604648/130472087-a80b788c-ce1d-4325-b4a7-f5fc8a7421d7.png)

Expected result:

![image](https://user-images.githubusercontent.com/7604648/130472301-0501c809-52a3-41e6-aa59-7f91fd4c230f.png)

**Comment by jonsequitur** [comment]
There's a bug here but the expected output is a little different from what you have. 

This method's behavior is intended to reproduce the command line splitting observed in a console app's `Main` method. To verify, I wrote this simple console app.

![image](https://user-images.githubusercontent.com/547415/130494920-96f46ef6-5f50-4c7f-9f0b-941b7c33ec2e.png)

So I think the expected output for your example input should be:

```console
POST
--raw={Id:1,Name:Alice}
```

Of course this isn't valid JSON. To get the values passed to your app that you want, you would also need to appropriately escape your command line, which will vary from one shell to another, e.g.:

![image](https://user-images.githubusercontent.com/547415/130498340-3011f46b-6daf-4983-bc8a-d8eda481ba98.png)

**Comment by WeihanLi** [comment]
Yeah , thanks @jonsequitur , it had to escape quotes on Windows, but no need for Linux.

The expected result should be the result you provide.
