### ISSUE TITLE
Argument with ZeroOrOne throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by whc2001** [dotnet/command-line-api#1395]
I tried to make one of the arguments optional so I tried this. It works when I fill both arguments, but only filling the first argument will cause an exception to be thrown out:

```C#
var rootCommand = new RootCommand
{
    new Argument("test")
    {
        ArgumentType = typeof(string),
        Description = "test",
        Arity = ArgumentArity.ExactlyOne
    },
    new Argument("test2")
    {
        ArgumentType = typeof(string),
        Description = "test2",
        Arity = ArgumentArity.ZeroOrOne
    },
};

rootCommand.Handler = CommandHandler.Create<string, string>((test, test2) =>
{
    Console.WriteLine($"test = {test}, test2 = {test2}");
});

rootCommand.Invoke("aaaaa bbbbb");    // Prints the output correctly

rootCommand.Invoke("aaaaa");    // System.ArgumentOutOfRangeException: "Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name"
```

I wonder if I am not using `ArgumentArity.ZeroOrOne` correctly. According to #1325 this is the way to do it.

**Comment by elgonzo** [comment]
I can confirm.

This seems to be a regression. In 2.0.0-beta1.20574.7 it still worked, however in or around 2.0.0-beta1.21079.2 the issue starts to occur.

**Comment by whc2001** [comment]
Can confirm, downgraded to 20574.7 and it worked. Seems like it's a bug.

**Comment by elgonzo** [comment]
@jonsequitur 

the issue is still present in 2.0.0-beta2.21617.1 and 2.0.0-beta2.21623.1 (i haven't tested against other versions).
