### ISSUE TITLE
Consider removing ICommand, IOption, and IArgument

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#1402]
These interfaces were originally introduced when the parser components were made mutable. They were intended provide a "read-only" API for parse results that would discourage modifying an already-configured `Parser`, because tracking state changes is additional overhead and complexity. But additional implementations of these interfaces aren't intended to be supported and might not work as expected. Removing them could simplify some code. 

We would want to address issues that might come up from e.g. adding `Option` aliases after the construction of a `Parser`.

**Comment by adamsitnik** [comment]
Can this issue be closed now since #1538 got merged?
