### ISSUE TITLE
Question: Can we supress the default --version option?

### ISSUE THREAD

**Issue by wokket** [dotnet/command-line-api#1409]
I'm working on a codebase that is looking to use `--version` as a normal option for application behaviour (for back-compat reasons).

I've had a hunt through the open issues and can't find anything obvious, is there any way to prevent the default `--version` option from being added so we can use it ourselves?

**Comment by jonsequitur** [comment]
If you're calling `Command.Invoke` what happens underneath is it calls `CommandLineBuilder.UseDefaults()` which adds the version option but if you use `CommandLineBuilder` you can configure your parser not to include it.

**Comment by wokket** [comment]
It took  a bit of hunting but I found [a sample](https://github.com/dotnet/command-line-api/blob/main/docs/How-To.md#middleware-pipeline) that demonstrates the `CommandLineBuilder` and got it working.  Thanks for the prompt response 👍

**Comment by jonsequitur** [comment]
You're welcome!
