### ISSUE TITLE
[Question] When will be the stable Release?

### ISSUE THREAD

**Issue by 2ji3150** [dotnet/command-line-api#1414]
I think this project is great and would like to use it.
But seems the newest release version is in Beta for quite a long time and look like doesn't have a roadmap.
May I ask when will it be a stable release ?

**Comment by jonsequitur** [comment]
This milestone is tracking progress toward a stable release: https://github.com/dotnet/command-line-api/milestone/1

We're hoping to remove the beta tag this year.

**Comment by 2ji3150** [comment]
Oh I see. Thanks!
