### ISSUE TITLE
Empty arguments result in unexpected parameter value passed to validation function

### ISSUE THREAD

**Issue by cwellsx** [dotnet/command-line-api#1420]
I previously posted a minimal example for testing here: https://github.com/dotnet/command-line-api/issues/1413#issuecomment-922420022

Now I add validation to that sample, like this:

            var filter = new Argument<string[]>("filter", Array.Empty<string>);
            filter.AddValidator(argumentResult => ValidateFilter(argumentResult.Tokens.Select(token=>token.Value)));

... and ...

        private static string ValidateFilter(IEnumerable<string> tokenValues)
        {
            Console.WriteLine($"Validating: {string.Join(", ", tokenValues)}");
            return null;
        }

When I run `foo a b` or `bar a b` then I get a console output like this which is expected:

    Validating: a, b
    bar arguments: a, b

But when I run it without argument then I get a result like this, both for `foo` and for `bar`:

    Validating: System.String[]
    bar arguments:

The result is good, but the parameter passed to the validation function isn't -- instead of being given an empty enumerable, I'm given an enumerable which contains one string, and the string value is `"System.String[]"` which is unexpected.

**Comment by elgonzo** [comment]
I cannot confirm with the latest nuget package 2.0.0-beta1.21471.2. As expected, when using the commands `foo` or `bar` with no further arguments, _argumentResult.Tokens_ is an empty collection, with the _ValidateFilter_ method only outputting `Validating: `.

Also 2.0.0-beta1.21308.1 does not exhibit the problem you describe. dotnetfiddle proof using 2.0.0-beta1.21308.1: https://dotnetfiddle.net/MEvIBR (i added some more diagnostics outputs to your code to better track what is happening...)

I therefore suggest you update to 2.0.0-beta1.21471.2. If the problem then still occurs, i strongly suspect some other thing in your _real_ code causing/triggering the observed behavior.

**Comment by cwellsx** [comment]
Thanks, you're right.
I reproduced the problem using beta1.20071.2
It no longer exists in beta1.21308.1
