### ISSUE TITLE
Parameters with the same prefix are both set

### ISSUE THREAD

**Issue by Buildstarted** [dotnet/command-line-api#1434]
When one parameter has a prefix of a parameter with the same name both are set when I expect only one to be set.

```
static async Task Main(string foo, string bar, string fooBar)
{
	Console.WriteLine($"foo    : {foo}");
	Console.WriteLine($"bar    : {bar}");
	Console.WriteLine($"fooBar : {fooBar}");
}
```

Example call: `Program.exe --foo-bar "testing"`

When setting `--foo-bar` both `foo` and `fooBar` are set when I expect only `fooBar` to be set.

**Comment by jonsequitur** [comment]
What version are you using?

**Comment by Buildstarted** [comment]
Ah I knew I forgot something.

As far as I know it's the latest: `0.3.0-alpha.21216.1`

**Comment by Buildstarted** [comment]
Confirmed fixed in the preview feed.
