### ISSUE TITLE
StackOverflowException in ArgumentResult.GetValueOrDefault<>() call

### ISSUE THREAD

**Issue by BobSilent** [dotnet/command-line-api#1464]
Comming from #1294 

I get a `StackOverflowException` for `ArgumentResult.GetValueOrDefault<>()` call:
```csharp
var rootCommand = new RootCommand
{
    new Option<int?>(name: "--age",
        parseArgument: result =>
        {
            return result.GetValueOrDefault<int?>() ?? 0;
            //return int.TryParse(result.Tokens.FirstOrDefault()?.Value, out var value) ? value: 0;
        },
        isDefault: false,
        description: "Enter your age")
    {
        IsRequired = false,
        ArgumentHelpName = "your age",
        Arity = ArgumentArity.ZeroOrOne
    }
};

rootCommand.Invoke(@"--age");
```

**Workaround:** 
Switching from 
`result.GetValueOrDefault<int?>()` 
to 
`int.TryParse(result.Tokens.FirstOrDefault()?.Value, out var value)` 
throws no exception.

**Comment by elgonzo** [comment]
Not really a bug in the library (although, a lack of documentation about the _parseArgument_ parameter in the Option/Option&lt;T&gt;> constructors could be considered an issue wrt to your problem).

Note the documentation comment for the `ArgumentResult.GetValueOrDefault<T>` method:

https://github.com/dotnet/command-line-api/blob/be7ff040e53022fa6730dc30ea511f7bdd97f3f9/src/System.CommandLine/Parsing/ArgumentResult.cs#L41-L46

This method gets the _**parsed**_ value. However, to get the parsed value the argument of the option obviously has to be parsed. To get the parsed value of your --age option argument, the provided _parseArgument_ delegate has to be executed (as this is what you have provided to actually parse the argument). I guess you see now where this is going...

**Comment by BobSilent** [comment]
this was just an example, and it was my fault tried to call myself to get the parsed value in the parser... 🤔
