### ISSUE TITLE
How-to documentation for sub-commands confusing or wrong

### ISSUE THREAD

**Issue by elgonzo** [dotnet/command-line-api#1478]
The how-to for sub commands at https://github.com/dotnet/command-line-api/blob/main/docs/How-To.md#add-a-subcommand-or-verb looks wrong to me. It shows an example using a RootCommand with the description string "Parent", and then proceeds to explain and illustrate as if "Parent" were a named command/verb.

I guess it still refers to an older library version. If not, in what situations and how would one use the description string of the RootCommand like a verb/command name?

**Comment by jonsequitur** [comment]
@elgonzo, should this be closed now?

**Comment by elgonzo** [comment]
Yes, should be closed. (My apologies, i was expecting the issue to be closed with the merge.)
