### ISSUE TITLE
Make column rendering APIs public 

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#1492]
Per @vlada-shubina's recommendation (https://github.com/dotnet/command-line-api/pull/1484#discussion_r758068130), we should make `RenderAsColumns` and associated methods public in a way that doesn't limit usage to classes inheriting `HelpBuilder`.

**Comment by vlada-shubina** [comment]
May I suggest the following:

1) make the following logic extension/utility for the `IIdentifierSymbol` https://github.com/dotnet/command-line-api/blob/fc76f3dfb638f99de3ca8294f91fc80bf0f8008b/src/System.CommandLine/Help/HelpBuilder.cs#L489-L514

2) `GetSecondColumnText` should use customization logic first (as the first column) and only then default logic. Customization should replace the whole text, not only one of the parts.

3) customization maybe set up when building parser, but it is not handy, especially for options.
It would be better to use delegate for custom help when creating the symbol (option). Imo opinion even for command it might work better - this would avoid iterating this code when building the parser:

```

...
        builder = builder.UseHelp(CustomHelpLayout());
...
        private static IEnumerable<HelpDelegate> CustomHelpLayout()
        {
            yield return context =>
            {
                if (context.ParseResult.CommandResult.Command is ICustomHelp custom)
                {
                    custom.WriteHelp(context);
                }
                else
                {
                    context.HelpBuilder.Write(context);
                }
            };
        }

```

and similar code for all symbols to be customized.

This syntax imo is better:
```
var option = new Option<string>();
option.HelpFirstColumn = ctx => { custom thing goes here }
option.HelpSecondColumn = ctx => { custom thing goes here }

var command = new Command(...)
command.HelpFirstColumn = ctx => { custom thing goes here }
command.HelpSecondColumn = ctx => { custom thing goes here }
command.HelpWriter = ctx => { custom thing goes here }

```

if any of above is not set - fallbacks to default.

**Comment by jonsequitur** [comment]
I'm hesitant to do this until we've spent more time experimenting with other output rendering approaches, e.g. VT (Spectre.Console) or HTML (notebooks). Do we think these more granular properties would be applicable to all help layouts?

> this would avoid iterating this code when building the parser:

We don't iterate the layout when building the parser, only if help is requested. Though if someone doesn't use `yield` there might be more up-front allocation.
