### ISSUE TITLE
Consider expanding the structure returned from GetSuggestions

### ISSUE THREAD

**Issue by baronfel** [dotnet/command-line-api#1499]
Right now GetSuggestions returns the strings representing valid tokens from the given position.  It might be a good feature to return a structure of the suggested token + a description of the token.  This would allow for easier inclusion in tab-completion displays like:

* Powershell's [CompletionResult.Tooltip](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.completionresult.tooltip?view=powershellsdk-7.0.0#System_Management_Automation_CompletionResult_ToolTip)
* ZSH's [Completion Item Descriptions](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Completion-Functions) (search for `explanation` in this document)
* Bash doesn't have a directly analogous structure
* Fish shell's [completion item descriptions](https://fishshell.com/docs/current/completions.html)

These allow for self-directed experiences like so, where the user gets some context about what each flag does:
![LbraMXm - Imgur](https://user-images.githubusercontent.com/573979/144310503-4cb35285-6ae0-40e8-a007-ed6a91f34254.png)

Having this ability seems like a great way to address discoverability, especially since adding this documentation is already highly-encouraged by the library design already!

**Comment by jonsequitur** [comment]
This is a great suggestion.

This is something we've considered doing as well for non-CLI use cases such as magic commands in .NET Interactive notebooks. Our data structure there is based on LSP and is a subset of this: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem

We'll likely have use cases for more of these properties in a notebook than in any CLI, but I'd appreciate thoughts on which of these might be useful in the richest shells.
