### ISSUE TITLE
Allow `LocalizationResources` in `HelpContext`

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/command-line-api#1500]
When implementing custom help for dotnet new, I need access to `LocalizationResources` to reuse the headings.

**Comment by jonsequitur** [comment]
`HelpBuilder` provides access to a `LocalizationResources` instance. Maybe we should make this public? 

`InvocationContext` also has it.

**Comment by vlada-shubina** [comment]
Making `LocalizationResources` available via `HelpBuilder` is good enough. `InvocationContext` is not accessible via `HelpContext`.
