### ISSUE TITLE
Lambda expression on Create no longer valid for System.CommandLine.Invocation.CommandHandler.Create?

### ISSUE THREAD

**Issue by EricZimmerman** [dotnet/command-line-api#1517]
so i am on the latest version, 2.0.0beta2 216123.3 and have a cli with 23 (!) options. i have many other programs working without any issues, but they have less command line args.

i tried some of the sample code to try to get things working since NamingConventionBinder.CommandHandler.Create is complaining, probably because it only supports up to 16 variables.

![image](https://user-images.githubusercontent.com/4265254/145748554-f5974c9e-9962-4414-86b2-abbf6997ee03.png)

here is all the code i have tried, to no avail. 

```
rootCommand.Handler = System.CommandLine.NamingConventionBinder.CommandHandler.Create<string,string,string,string,string,string,string,string,string,bool,string,string,string,bool,string,string,bool,bool,bool,bool,bool,bool,bool>(DoWork);

rootCommand.Handler =System.CommandLine.Invocation.CommandHandler.Create(
                (string f, string m, string json, string jsonf, string csv, string csvf, string body, string bodyf, string bdl, bool blf, string dd, string @do, string de, bool fls, string ds, string dt, bool sn, bool fl , bool at, bool vss, bool dedupe, bool debug, bool trace) =>
            {

            });
            
rootCommand.Handler = System.CommandLine.Invocation.CommandHandler.Create(
                (string aString, int anInt) =>
                {
                    Console.WriteLine(aString);
                    Console.WriteLine(anInt);
                });
```

are the docs out of date? is there a way, ideally with NamingConventionBinder, so i can keep things consistent, to get this working? if not, what method is suggested?

**Comment by EricZimmerman** [comment]
also, i had to figure out to even use NamingConventionBinder.CommandHandler.Create after code that worked yesterday broke today! =( i saw it was stripped out to a new nuget package and once i made those adjustments, things worked fine. is there a running list of breaking changes between versions, or do we just need to wait until that stuff is summarized and shows up under the releases?

**Comment by jonsequitur** [comment]
You can see a list of breaking changes here: https://github.com/dotnet/command-line-api/issues?q=label%3A%22Breaking+Change%22+milestone%3A%222.0+GA%22+

To continue using the name-based binding, you should be able to reference System.CommandLine.NamingConventionBinder and change a `using` from `System.CommandLine.Invocation` to  `System.CommandLine.NamingConventionBinder` and your existing code should continue to work.

The overloads of `System.CommandLine.Invocation.CommandHandler.Create` mostly require you to pass the `Option` or `Argument` instances you want to bind to.

**Comment by EricZimmerman** [comment]
Yes I figured that out myself with name convention builder, 
so I have that working for my other apps.

what to do with the 23 arg setup tho? And why doesn't the smaller lambda example work anymore? I'll try rolling back to an older version to see if the project sample code works 

It doesn't seem to like that many options, or am I doing something wrong?

**Comment by jonsequitur** [comment]
> what to do with the 23 arg setup tho? 

The new source generator package should work for these cases, but I noticed it's not building correctly. Or you can continue to use [complex model binding](https://github.com/dotnet/command-line-api/blob/main/docs/model-binding.md#more-complex-types) which is now found in the System.CommandLine.NamingConventionBinder package.

> And why doesn't the smaller lambda example work anymore? 

Do you mean they don't compile or they don't work at runtime?

The `Create` methods having this signauture moved to the new package. This compiles for me:

```cs
rootCommand.Handler = System.CommandLine.NamingConventionBinder.CommandHandler.Create(
                (string aString, int anInt) =>
                {
                    Console.WriteLine(aString);
                    Console.WriteLine(anInt);
                });
```

**Comment by EricZimmerman** [comment]
sounds good and thank you for the directions! i will give the new method a try

i will give the complex model a try too. that looks like a clean way to deal with a lot of options.

i have been swapping out all my commandline parsing from flcp to this project and its been pretty seamless so far, once i got the first one working. i like it!

**Comment by EricZimmerman** [comment]
for anyone else, this is what i ended up working with:

 _rootCommand.Handler = System.CommandLine.NamingConventionBinder.CommandHandler.Create(DoWork);

where DoWork looked something like this:

private static void DoWork(string f, string m, string json)

and so on

**Comment by jonsequitur** [comment]
There's more improvement coming here. Thanks for jumping on the early adopter wagon, but please be aware we're likely to break this again. 😳
