### ISSUE TITLE
Allow help as a verb

### ISSUE THREAD

**Issue by adam8797** [dotnet/command-line-api#1525]
I'm looking for a way to use the auto generated help screens, but as a verb instead of (or even in addition to) the `--help` flag, and I'm not finding much of a solution. Do you all have any guidance on this? Or if this isn't implemented, I think this could be a good addition.

An example of this in the wild would be the Docker CLI where:

These two are equivalent:
```
docker help
docker --help
```

as well as:
```
docker help pull
docker pull --help
```

**Comment by jonsequitur** [comment]
Help is implemented as an option but options don't need to have prefixes in System.CommandLine. `--help` is already supported.

You can specify your own help aliases using `CommandLineBuilder.UseHelp`:

https://github.com/dotnet/command-line-api/blob/685f1542094354d3729feb06fdd50057760debda/src/System.CommandLine.Tests/UseHelpTests.cs#L227-L258

I think these can address most of your examples.

To implement it as a verb that describes the command that's specified afterward on the command line (e.g. `docker help pull`), this is probably something you could do with the latest help APIs, but it's not supported out of the box.

**Comment by adam8797** [comment]
Thanks! Ok I'll look into that all.
