### ISSUE TITLE
Your first app not working after breaking changes

### ISSUE THREAD

**Issue by martiener1** [dotnet/command-line-api#1542]
Hello, I wanted to start using this package, but the [Your first app](https://github.com/dotnet/command-line-api/blob/main/docs/Your-first-app-with-System-CommandLine.md) example has errors on the following line:
```csharp
rootCommand.Handler = CommandHandler.Create<int, bool, FileInfo>(
```

This is caused by the breaking changes as explained in [Beta 2 announcement](https://github.com/dotnet/command-line-api/issues/1537)

**Comment by elgonzo** [comment]
I guess this is covered by "_[...] we've started work on official online documentation and samples [...]_" in the Beta 2 announcement.
(The page you are referring to is part of the old documentation. As of time of writing, there have been no updates yet in command-line-api/docs related to the Beta 2.

**Comment by JoshuaDouce** [comment]
I had the same issue thankyou @martiener1 for pointing to the Beta 2 announcement 👍
