### ISSUE TITLE
Custom Type Converter / Binding for Options

### ISSUE THREAD

**Issue by brporter** [dotnet/command-line-api#1544]
How can I define an instance of ```Option<T>``` where ```T``` is ```System.Net.IPAddress```? 

The following fails with an InvalidOperationException. I am assuming there is an extensibility point for parsed argument type conversion and model binding, but I cannot seem to find an example in the tests or documentation.

```c#
var option = new Option<IPAddress>(new[] { "--ip" });
var pResult = option.Parse("--ip 127.0.0.1");
var value = pResult.GetValueForOption(option); // Fails with System.InvalidOperationException
```

**Comment by baronfel** [comment]
You should use the overload that takes a `parseArgument` delegate:

```fsharp
#r "nuget: System.CommandLine, 2.0.0-beta2.21617.1"

open System.Net
open System.CommandLine
open System.CommandLine.Parsing

// make the option
let o = Option<IPAddress>("--ip", fun (r: ArgumentResult) -> IPAddress.Parse r.Tokens[0].Value)
// parse and extract a value
let ip = o.Parse("--ip 127.0.0.1").GetValueForOption(o)
// assert that the parsed value is a known good value
ip = IPAddress.Parse("127.0.0.1")
```

This script outputs `true` for me, you can verify by running it in `dotnet fsi`.  Of course you'd want to handle any errors during parsing with better user output.
