### ISSUE TITLE
Cannot parse lists in complex types with NamingConventionBinder

### ISSUE THREAD

**Issue by kinelski** [dotnet/command-line-api#1552]
### Code to reproduce the issue

```cs
using System.CommandLine;
using System.CommandLine.NamingConventionBinder;

public class Program
{
    public static void Main(string[] args)
    {
        var command = new RootCommand()
        {
            new Option<List<int>>("--list-option")
        };

        command.Handler = CommandHandler.Create((CommandArgs args) =>
            Console.WriteLine($"Args: {args.ListOption.Count}"
        ));

        command.Invoke(args);
    }

    private class CommandArgs
    {
        public List<int> ListOption { get; set; } = new();
    }
}
```

### Input arguments
```
--list-option 10 20
```

### Expected output
```
Args: 2
```

### Actual output
```
'20' was not matched. Did you mean one of the following?
-h
Unrecognized command or argument '20'.
```

### Notes
- The same behavior happens when using an `int[]` option instead of a `List<int>`.
- The program works as expected when only one integer is passed (e.g. "--list-option 10").
- I'm using `System.CommandLine` version `2.0.0-beta2.21617.1` and `System.CommandLine.NamingConventionBinder` version `2.0.0-beta2.21617.1`.
- The program works as intended when using `System.CommandLine` version `2.0.0-beta1.21308.1` without the `NamingConventionBinder`.

**Comment by jonsequitur** [comment]
After looking at this more closely, I realized that this is due to an intentional change in the default behavior. See #1199.

If you change your command creation code as follows, it will work as it did before:

```cs
var option = new Option<List<int>>("--list-option");
option.AllowMultipleArgumentsPerToken = true;

var command = new RootCommand
{
     option
};

```

Also, these input arguments will work in either case:

```console
--list-option 10 --list-option 20
```

This syntax is much more common which is why we're making the other opt-in.

**Comment by kinelski** [comment]
Thank you for the clarification!
