### ISSUE TITLE
CommandHandler cannot be found with nuget package 2.0.0-beta2.21617.1

### ISSUE THREAD

**Issue by atiq-cs** [dotnet/command-line-api#1554]
Builds ok with previous versions i.e., `2.0.0-beta1.21308.1`

However build fails with latest release, `2.0.0-beta2.21617.1`

    [atiq@Matrix GitUtility]$ dotnet build
    D:\GitUtility\Main.cs(32,27): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(48,30): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(59,27): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(73,25): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(82,25): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(91,27): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(104,27): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]
    D:\GitUtility\Main.cs(114,26): error CS0234: The type or namespace name 'CommandHandler' does not exist in the namespace 'System.CommandLine.Invocation' (are you missing an assembly reference?) [D:\GitUtility\GitUtility.csproj]

    The build failed. Fix the build errors and run again.

I am using .Net 6

**Comment by glennawatson** [comment]
I solved this one personally including the `System.CommandLine.NamingConventionBinder` nuget package.

Hunted in the code base for the assembly.

**Comment by atonalfreerider** [comment]
Was this class removed on purpose? Is there an updated way to create the command handler? If so, the documentation is out-of-date. It is still recommending `CommandHandler.Create`

https://github.com/dotnet/command-line-api/blob/main/docs/Your-first-app-with-System-CommandLine.md

**Comment by jonsequitur** [comment]
It was moved to a separate package. You can see the details here: https://github.com/dotnet/command-line-api/issues/1537

**Comment by atiq-cs** [comment]
Example fix (`Invocation.CommandHandler` to `NamingConventionBinder.CommandHandler`) is here, for reference: https://github.com/atiq-cs/GitUtility/commit/7a9392bfb74928b93398d210b1430c9451a0f225
