### ISSUE TITLE
Option without values

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/command-line-api#1576]
How can we declare options without associated values?

If I specify an option without a type:
```c#
new Option("--test", "test")
{
    Arity = ArgumentArity.ZeroOrOne,
}
```

I can do both `--test` *and* `--test foo`. Unfortunately this breaks scenarios where positional arguments and options are involved. Let's say we also have an argument:
```c#
new Argument<string>("someargument")
{
    Arity = ArgumentArity.ExactlyOne,
},
new Option("--test", "test")
{
    Arity = ArgumentArity.ZeroOrOne,
},
```

then I can do `someargumentvalue --test` but not `--test someargumentvalue`, because the argument's value will be eaten by the option. This is unexpected for me, as the option without an associated value should not consume a value. Am I missing something obvious? How can I create "flaggy" options?

**Comment by elgonzo** [comment]
If you want an option that doesn't accept any value, why are you then using an arity of `ArgumentArity.ZeroOrOne`? "ZeroOrOne" specifically means the option accepting zero or **one** value.

If you want an option that accepts exactly zero (i.e., no) values, you should use `ArgumentArity.Zero` for that option.

**Comment by Trolldemorted** [comment]
Thanks for the quick response! I had the erroneous assumption that the arity expresses how often I can specify an option, and thus I set it to 0 or 1 to prevent users from passing `--test` multiple times. Stupid me, case closed :)

**Comment by elgonzo** [comment]
> I had the erroneous assumption that the arity expresses how often I can specify an option
 It's not entirely wrong, but it's all coming down to how many values are/can be provided for that option.

For example, an option accepting multiple value could be used like `-o 1 2 3` to provide three values, but it could also be used equivalently `-o 1 -o 2 -o 3` to the same effect. :-)

**Comment by jonsequitur** [comment]
Thanks @elgonzo for a very clear explanation.
