### ISSUE TITLE
Transforming argument/option into a complex type?

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/command-line-api#1579]
Given the breaking changes Beta 2, I wonder how to deal with the following:

```csharp
new Argument<SomeComplexType>(...)
```

I would like get the opportunity to get the string value and perform my logic to create `SomeComplexType` so it will be passed to any given command handler. 

Primitive types aren't enough for me :)
Thanks for your help.

**Comment by baronfel** [comment]
Hi @SuperJMN, have you tried one of the constructors that takes a `ParseArgument<T>` delegate, like [this one](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Argument%7BT%7D.cs#L71-L75)? You can use the `ArgumentResult` passed to that delegate to get the Token(s) for the Argument and parse them in any way you need, or report any errors that you need to the user via the `.ErrorMessage` property on the ArgumentResult.

**Comment by jonsequitur** [comment]
Another approach that can work if you need to combine values from multiple options or arguments into a single instance of a complex type is to implement `BinderBase<SomeComplexType>` and pass that to `SetHandler` for the appropriate parameter.

**Comment by SuperJMN** [comment]
Neat, I was using the getDefaultValue factory instead and that's why I got confused!

**Comment by jonsequitur** [comment]
You're welcome! Thanks for giving trying out the beta.
