### ISSUE TITLE
Calling Command.Parse changes the outcome of following Invoke

### ISSUE THREAD

**Issue by ghord** [dotnet/command-line-api#1589]
I'm trying to get some global options before invoking the command using following code:
```c#
RootCommand root = ...
//Parse options first and check some global options
//Issue: With this line uncommented, InvokeAsync line does not print help message in case of missing arguments
//Issue: Commenting out this line restores InvokeAsync functionality
var options = root.Parse(args);

if (options.GetValueForOption(debuggerWait))
{
    Logger.Information("Waiting for debugger attach...");
    while (!Debugger.IsAttached)
    {
        await Task.Delay(100);
    }
    Debugger.Break();
}
//Execute command normally, should print help messages if wrong args are specified
return await root.InvokeAsync(args);
```

What's very strange to me is that introducing the line with root.Parse(args) changes the outcome of root.InvokeAsync() when no args are provided (It no longer displays help for the command). Shoud Parse Extension method change the state of the Command object in this way?

I'm on version 2.0.0-beta2.21617.1.

**Comment by elgonzo** [comment]
> Shoud Parse Extension method change the state of the Command object in this way?
_(I am not associated with the project)_ It's quite likely a bug. I don't see any scenario where a _Parse_ invocation altering the behavior of subsequent method calls on the command would be both expected and meaningful. On the contrary, i would argue that the observed behavior would be quite unexpected and cumbersome to deal with for the vast majority of developers using System.CommandLine.

By the way old build 2.0.0-beta1.21308 does _not_ exhibit this issue: https://dotnetfiddle.net/WqzNZi , further indicating that the behavior observed in 2.0.0-beta2.21617.1 is actually a bug.
