### ISSUE TITLE
Option AddValidator() does not throw error if validation fails when SymbolResult.ErrorMessage is set.

### ISSUE THREAD

**Issue by ashscodes** [dotnet/command-line-api#1594]
I have an extension method that adds validation for the length of a string.

```csharp
internal static Option<string> MaxLength(this Option<string> option, int max)
{
    option.AddValidator(or =>
    {
        string value = or.GetValueOrDefault<string>();
        if (value.Length > max)
        {
            or.ErrorMessage = string.Format(
                "Option {0} cannot contain more than {1} characters. {2} were passed.",
                or.Token.Value,
                max,
                value.Length);
        }

        return null;
    });

    return option;
}
```

And I set my option as so in the constructor for the Command.

```csharp
Option msgOption = new Option<string>(
        aliases: new string[] { "-m", "--message" },
        description: "A message. Limited to 80 characters.")
    .MaxLength(80);
```

But despite the remarks of `SymbolResult.ErrorMessage` -  `"Setting this value to a non-null during parsing will cause the parser to indicate an error for the user and prevent invocation of the command line."`, it does not stop the command from processing. I can see the debugger sets the value, but it continues as normal. If the string is just returned instead of ErrorMessage being set, then the command fails the validation as expected.

```csharp
if (value.Length > max)
{
    return string.Format(
        "Option {0} cannot contain more than {1} characters. {2} were passed.",
        or.Token.Value,
        max,
        value.Length);
}
```

**Comment by jonsequitur** [comment]
This is fixed in the latest version (which is still only on the preview feed [here](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json)). We changed the validator delegate to be `void`-returning and removed this ambiguity.
