### ISSUE TITLE
Model binding of properties is no longer working

### ISSUE THREAD

**Issue by philipproplesch** [dotnet/command-line-api#1611]
Currently in the process of upgrading to the latest and greatest and ran into an issue with the model binding.

Our arguments and options are generally nested within a separate class (see `TestParameters` in the shortened repro below) and added as a property to the respective command handlers.

The binding has been working fine until version 2.0.0-beta1.21216.1, however starting with 2.0.0-beta1.21308.1 (and up to the current version) this no longer seems to work and said property is always null.

I believe I tracked it down to the changes made to the `ModelBinder` in #1277, that moved the `if (valueDescriptor.ValueType != parentType) { ... }` inside `if (includeMissingValues) { ... }`.

As it turns out `includeMissingValues` is explicitly set to `false` via `UpdateInstanceInternalNotifyIfNonDefaultsUsed` though and therefore the property is never bound.

Example:

```csharp
// Program.cs

using System.CommandLine;
using System.CommandLine.Invocation;
using System.CommandLine.NamingConventionBinder;

var command = new Command("test");
command.AddOption(new Option<string>("--name"));
command.Handler =
    CommandHandler.Create(
        typeof(TestCommandHandler).GetMethod(
            nameof(ICommandHandler.InvokeAsync),
            new[] { typeof(InvocationContext) }));

await command.InvokeAsync("test --name foo");

public class TestCommandHandler : ICommandHandler
{
    public TestParameters Parameters { get; set; }
    
    public Task<int> InvokeAsync(InvocationContext context)
    {
        // `Parameters` property is null with >= 2.0.0-beta1.21308.1

        Console.WriteLine(Parameters.Name);
        return Task.FromResult(0);
    }
}

public class TestParameters
{
    public string Name { get; set; }
} 
```

```xml
<!-- *.csproj -->

<ItemGroup>
    <!-- does not work -->
    <PackageReference Include="System.CommandLine.NamingConventionBinder" Version="2.0.0-beta2.21617.1" />
    <!-- works -->
    <!-- <PackageReference Include="System.CommandLine" Version="2.0.0-beta1.21216.1" /> -->    
</ItemGroup>
```

**Comment by jonsequitur** [comment]
I don't think the old behavior of creating an instance was the correct one. There's nothing in the example model that will match the property name `Parameters` or have reason to associate the `--name` option's value to it without doing some recursive searching and picking a best match, which could easily become ambiguous once multiple model types are involved. 

The new `Command.SetHandler` API and a `BinderBase<TestParameters>` was designed to make this kind of behavior easier to understand. Is that an option for your codebase?

**Comment by philipproplesch** [comment]
Appreciate the quick response and explanation!

Absolutely understandable and going forward it definitely seems to make sense to transition to the `BinderBase<>` class. 

Thank you!
