### ISSUE TITLE
RootCommand handler invoked before sub commands

### ISSUE THREAD

**Issue by no1melman** [dotnet/command-line-api#1614]
```
./mytool --no-cache get data
```

Here I need to have `--no-cache` executed before the sub commands `get data`. 

But from playing around it appears that if you have sub commands, and do the above, only the final sub command handler gets executed....

**Comment by jonsequitur** [comment]
Correct. Only one subcommand's handler gets called. 

Assuming `get` and `data` are both subcommands, then your example command line is only valid if `data` has a handler. If `get` has a handler, it won't be called in your example because `data` was specified.

In any case, assuming `--no-cache` is an option, you can access its value from any subcommand.

**Comment by no1melman** [comment]
Okay, so I guess as well the normal pattern to handle an option used at multiple points is to just abstract the handling of it

**Comment by jonsequitur** [comment]
Here's an example of how you can use the same option in multiple places:

```cs
using System.CommandLine;

var option = new Option<int>("-x");

var subCommand = new Command("child")
{
    option
};
subCommand.SetHandler((int x) => Console.WriteLine($"Option -x value from subcommand: {x}"), option);

var rootCommand = new RootCommand{
    option,
    subCommand
};
rootCommand.SetHandler((int x) => Console.WriteLine($"Option -x value from root command: {x}"), option);

rootCommand.Invoke("-x 123");
rootCommand.Invoke("child -x 456");
```

Outputs:
```console
Option -x value from root command: 123
Option -x value from subcommand: 456
```

You can effectively do the same thing using `Command.AddGlobalOption` which adds it to the target command and all of its subcommands.

**Comment by no1melman** [comment]
Thanks for that, quality answer
