### ISSUE TITLE
DateTime parsing broken in Beta 3

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#1615]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/547415/152693454-430b291d-ce8c-4639-9744-5abcf2987498.png">

**Comment by ohine** [comment]
@jonsequitur Thanks for looking into this and getting it fixed!

**Comment by jonsequitur** [comment]
We pulled out support for type converters in beta 3 in order to support trimming, and you found a test gap. 

Thanks for trying the beta!
