### ISSUE TITLE
Need basic example for using `System.CommandLine.Rendering` standalone

### ISSUE THREAD

**Issue by jasonswearingen** [dotnet/command-line-api#1616]
I am trying to color my console output.

It seems like  `System.CommandLine.Rendering`  should be able to do it, but there are no examples showing this.

I looked through the Tests and Samples but they are all deeply nested and depend on me somehow constructing an `IConsole` which I can not figure out how to construct/obtain.

Please consider "Developer First Time Experience" and provide basic end-to-end examples accordingly.

**Comment by jonsequitur** [comment]
System.CommandLine.Rendering is being deprecated.

For colored console output, I'd definitely recommend taking a look at Spectre.Console.

**Comment by jasonswearingen** [comment]
Thank you, I will look at Spectre!
