### ISSUE TITLE
dotnet-suggest: ZSH shim 

### ISSUE THREAD

**Issue by JohnnyWombwell** [dotnet/command-line-api#1618]
Hi, is there an example of a `dotnet-suggest` z-shell shim script somewhere?

I would have expected to find an example _somewhere_  but my google skills are failing me :|

**Comment by baronfel** [comment]
There's an example [here](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#zsh) on the Microsoft docs, but it is fairly basic completion.

With the move towards supporting more rich completions in beta2, we'd like to look into more zsh integrations that show descriptions for tab-completions. Does this sound like something that's useful for you? Do you have any particular CLI tools that have good completions in zsh that you'd prefer?

**Comment by JohnnyWombwell** [comment]
Sorry, I was referring to a shim for the `dotnet-suggest` global tool. So the equivalent of this bash shim https://github.com/dotnet/cli/blob/master/scripts/register-completions.bash

**Comment by JohnnyWombwell** [comment]
@baronfel, to answer your questions, yes, more descriptive autocompletions would be something we'd use. Anything that helps our users discover the features they need (or didn't know they needed 😄) is welcome.

In terms of other applications that have useful completion functionality, just the obvious ones really, `git` and `docker` do a very nice job in this regard (and our users, devs, are familiar with this model).

**Comment by JohnnyWombwell** [comment]
So, I'm no authority on zsh completions but this seems to do the job:
```sh
_dotnet_suggest_complete()
{
    local fullpath=`which ${words[1]}`
    local position line
    read -nl position
    position=$(($position-1))
    read -l line
    line=$(echo "${line}" | sed s/\"/'\\\"'/g)
    local completions=`dotnet-suggest get --executable "$fullpath" --position ${position} -- "${line}"`
    reply=( "${(ps:\n:)completions}" )
}

compctl -K _dotnet_suggest_complete + -f `dotnet-suggest list`
```

**Comment by jonsequitur** [comment]
Would you be interested in submitting a PR, @JohnnyWombwell?

**Comment by JohnnyWombwell** [comment]
Yeah sure, I'd be happy to.

I'm away on vacation until the end of the month so will get back to it in March.
