### ISSUE TITLE
SetHandler does not work with non generic option flag

### ISSUE THREAD

**Issue by trockefeller-pathway** [dotnet/command-line-api#1626]
I'm trying to upgrade to the new pattern of using `SetHandler` based on this update post https://github.com/dotnet/command-line-api/issues/1537 and I have a .net fiddle that is showing the failure here https://dotnetfiddle.net/qUFjJW and the code for the fiddle is copied below. 

It is failing on the option `var someOption = new Option("--myOption","some option flag");`

When I pass in "--myOption" it is saying that I am missing an argument or an option for that parameter even though I am passing in `someOption`

If I change the definition of someOption to be `var someOption = new Option<bool>("--myOption","some option flag");` then it works, but I have to pass in the option like `--myOption True`, and I don't want to have to add the `True` part, I just want to use it as a boolean flag option of present or not present.

Is this unexpected behavior that will be corrected at some point, or am I calling my option flag incorrectly?

```csharp
using System;
using System.CommandLine;
					
public class Program
{
	public static void Main()
	{
		var stringArgument = new Argument<string>("myString", "Some string argument");
		var someOption = new Option("--myOption","some option flag");
		var rootCommand = new RootCommand
		{
			stringArgument,
			someOption
		};
		
		rootCommand.Description = "My test commandline program to break SetHandler";
		rootCommand.SetHandler<string, bool>((someString, someOptionFlag) => doStuff(someString, someOptionFlag), stringArgument, someOption);
		var args = new string[]{"Hello World!", "--myOption"};
		rootCommand.Invoke(args);
	}
	
	public static void doStuff(string someString, bool someOptionFlag)
	{
		Console.WriteLine(someString);
		Console.WriteLine($"Some option flag is set: {someOptionFlag}");
	}
}
```

**Comment by jonsequitur** [comment]
> If I change the definition of someOption to be var someOption = new Option<bool>("--myOption","some option flag"); then it works, but I have to pass in the option like --myOption True, and I don't want to have to add the True part, I just want to use it as a boolean flag option of present or not present.

You aren't required to pass `true` or `false` to an `Option<bool>` (but you are allowed to). `Option.Arity` defaults to `ArgumentArity.ZeroOrOne` when the `Option.ValueType` is `bool`, whether you set it explictly or it's the generic argument for an `Option<T>`.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/547415/153095691-3b3480b6-b3e4-4e66-95a1-442ace378844.png">

**Comment by trockefeller-pathway** [comment]
I thought for sure I had tested this before, and I thought you had to pass the option `True` or `False`, but sure enough, just making it an `Option<bool>` resolves things for me. Just calling it wrong. Thanks.
