### ISSUE TITLE
Question: Can I setup conditional options?

### ISSUE THREAD

**Issue by fvelaayl** [dotnet/command-line-api#1627]
Hello!

Can I setup conditional options? 

For example in my command line application I want an options for all and another option to select one item:

myapp show --all
myapp show --project myproject

thanks and best regards,

**Comment by jonsequitur** [comment]
Am I correct that you want these two options to be mutually exclusive?

We don't support this directly but you can do this by adding a validator:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/547415/153618889-a9301aa8-6742-41bc-b087-77dc717e3ad0.png">

**Comment by fvelaayl** [comment]
thanks @jonsequitur
