### ISSUE TITLE
Non-generic GetValueForOption does not work with boolean flag

### ISSUE THREAD

**Issue by einarmo** [dotnet/command-line-api#1647]
Reproduction:

```c#
var opt = new Option<bool>(new[] { "-b" }, "Some description");

var cmd = new RootCommand
{
    opt
};

var res = cmd.Parse("-b");
Assert.True((bool)res.GetValueForOption((Option)opt));
```

It works if you pass "true", e.g. `-b true`, or if you use the generic method directly.

I ended up adding this code to work around the issue:

```c#
// Here I only know that opt is some Option<>

if (opt.GetType() == typeof(Option<>).MakeGenericType(typeof(bool)))
{
    res = bindingContext.ParseResult.GetValueForOption((Option<bool>)opt);
}
```

**Comment by shaggygi** [comment]
@jonsequitur Had a related question on GetValueForOption...

I have UseExceptionHandler setup to try and catch random errors.

What is need to search for a particular global option and get its value when an exception hits?  I've tried a few things, but keeps returning nulls.

```csharp
Parser parser = new CommandLineBuilder(new MyRootCommand())
    .UseDefaults()
    .UseExceptionHandler((exception, context) => {

    // Need to check and get a value for an optional global value here.
}
```

Any help is appreciated.

**Comment by jonsequitur** [comment]
You should be able to use `context.ParseResult.GetValueForOption(theOption)`.

**Comment by shaggygi** [comment]
@jonsequitur Okay.  I see what I was doing wrong.  As usual, I truly appreciate your help (and this API  😄).  Thx
