### ISSUE TITLE
remove the legacy double dash behavior and `ParseResult.UnparsedTokens`

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#1653]
This functionality exists primarily to support the pre-existing behavior of the `dotnet` CLI, but that can likely be reimplemented using `Argument<string[]>`.

**Comment by baronfel** [comment]
As a case study for users of this library, [here](https://github.com/dotnet/sdk/pull/23889/commits/3250361d1d3e39b5b3354dc20b21bdb8078186fb) is a commit where explicit -- behavior was superseded with an `Argument<string[]>`.

**Comment by Tunduk** [comment]
@jonsequitur Hi!
`dotnet/sdk` team merged [PR](https://github.com/dotnet/sdk/pull/26761) with removing legacy double dash behavior.
If you don't mind I want to try to fix this issue.

**Comment by jonsequitur** [comment]
Closed by #1806.
