### ISSUE TITLE
Argument conversion is missing TimeSpan.TryParse

### ISSUE THREAD

**Issue by GabeDeBacker** [dotnet/command-line-api#1717]
Attempting to use an option of type Option<TimeSpan> fails because there is no implementation that calls TimeSpan.TryParse in:

https://github.com/dotnet/command-line-api/blob/dd44dd05a20bf6af02615d8363948a630e821d00/src/System.CommandLine/Binding/ArgumentConverter.StringConverters.cs

**Comment by jonsequitur** [comment]
Fixed by #1718.
