### ISSUE TITLE
Parent command required options are not checked for presence

### ISSUE THREAD

**Issue by kriswuollett** [dotnet/command-line-api#1721]
As I was trying to find my version of implementing #1659, the `checkOnlyGlobalOptions` handling seems to be blocking check for required options in parent commands as seen in the debugger: https://github.com/dotnet/command-line-api/blob/3e0db9e5830f2722645b9a576f80e3650b50f23a/src/System.CommandLine/Parsing/ParseResultVisitor.cs#L353-L382

Is this a bug, or what am I missing to make sure all the options I specify are required are checked as expected? I'm using version `2.0.0-beta3.22114.1`, but have not tried using the latest code from git.

Example app invocation which references the existing instance of the option as suggested in the linked issue above:

```shell
dotnet MyApp database migrate --tag foo
```

Expected to see error about `database` `--port` or `--host` option missing with the following code (please forgive the verbosity, don't much about C# yet to know the tricks to make it more compact). As far as usability goes, I'd also expect arguments to be checked from root command to leaf, not leaf to root, so I'd think it would be more reasonable to expect to see `host` missing first:

```csharp
using System;
using System.CommandLine;
using System.CommandLine.Binding;
using System.Threading.Tasks;

namespace MyApp
{
    public static class GlobalParameters
    {
        public static readonly Option<bool> Verbose = new("--verbose");
    }

    public record GlobalOptions(bool Verbose)
    {
        public static GlobalOptions Build(BindingContext bindingContext) => new(
            bindingContext.ParseResult.GetValueForOption(GlobalParameters.Verbose)
        );
    }

    public class GlobalOptionsBinder : BinderBase<GlobalOptions>
    {
        protected override GlobalOptions GetBoundValue(BindingContext bindingContext) =>
            GlobalOptions.Build(bindingContext);
    }

    public class RootCommandGroup : RootCommand
    {
        public RootCommandGroup()
        {
            AddOption(GlobalParameters.Verbose);
            AddCommand(new DatabaseCommandGroup());
        }
    }

    public static class DatabaseParameters
    {
        public static readonly Option<string> Host = new("--host") {IsRequired = true};
        public static readonly Option<int> Port = new("--port") {IsRequired = true};
    }

    public record DatabaseOptions(GlobalOptions GlobalOptions, string Host, int Port)
    {
        public static DatabaseOptions Build(BindingContext bindingContext) => new(
            GlobalOptions.Build(bindingContext),
            bindingContext.ParseResult.GetValueForOption(DatabaseParameters.Host),
            bindingContext.ParseResult.GetValueForOption(DatabaseParameters.Port)
        );
    }

    public class DatabaseOptionsBinder : BinderBase<DatabaseOptions>
    {
        private readonly GlobalOptionsBinder _globalOptionsBinder = new();

        protected override DatabaseOptions GetBoundValue(BindingContext bindingContext) =>
            DatabaseOptions.Build(bindingContext);
    }

    public class DatabaseCommandGroup : Command
    {
        public DatabaseCommandGroup() : base("database")
        {
            AddOption(DatabaseParameters.Host);
            AddOption(DatabaseParameters.Port);
            AddCommand(new MigrateCommand());
        }
    }

    public static class MigrationParameters
    {
        public static readonly Option<string> Tag = new("--tag") {IsRequired = true};
    }

    public record MigrationOptions(DatabaseOptions DatabaseOptions, string Tag)
    {
        public static MigrationOptions Build(BindingContext bindingContext) => new(
            DatabaseOptions.Build(bindingContext),
            bindingContext.ParseResult.GetValueForOption(MigrationParameters.Tag)
        );
    }

    public class MigrationsOptionsBinder : BinderBase<MigrationOptions>
    {
        protected override MigrationOptions GetBoundValue(BindingContext bindingContext) =>
            MigrationOptions.Build(bindingContext);
    }

    public class MigrateCommand : Command
    {
        private static Task<int> Handle(MigrationOptions migrationOptions)
        {
            Console.WriteLine(migrationOptions);
            return Task.FromResult(42);
        }

        public MigrateCommand() : base("migrate")
        {
            AddOption(MigrationParameters.Tag);
            this.SetHandler((MigrationOptions options) => Handle(options), new MigrationsOptionsBinder());
        }
    }

    public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            var rootCommand = new RootCommandGroup();
            return await rootCommand.InvokeAsync(args);
        }
    }
}

```

Actual results:
```
MigrationOptions { DatabaseOptions = DatabaseOptions { GlobalOptions = GlobalOptions { Verbose = False }, Host = , Port = 0 }, Tag = foo }

Process finished with exit code 42.

```

**Comment by kriswuollett** [comment]
Seems like I need to have code like the following and put all options and args at the end like `database migrate --verbose --host localhost --port 5432 --tag foo`:

```csharp
        public MigrateCommand() : base("migrate")
        {
            AddOption(GlobalParameters.Verbose);
            AddOption(DatabaseParameters.Host);
            AddOption(DatabaseParameters.Port);
            AddOption(MigrationParameters.Tag);
            this.SetHandler((MigrationOptions options) => Handle(options), new MigrationsOptionsBinder());
        }
```

Is there any way to reduce the boilerplate, and also be able to invoke the app like `--verbose database --host localhost --port 5432 migrate  --tag foo`?

**Comment by elgonzo** [comment]
Try making your required database-related options "global" with respect to the DataBaseCommand. In other words, if an option should also be in effect on sub-commands of a command, use the [`AddGlobalOption`](https://github.com/dotnet/command-line-api/blob/372d408431a3c0001cbe9e8e247a8e1561dc2e89/src/System.CommandLine/Command.cs#L108-L114) method instead of `AddOption`. (The name _AddGlobalOption_ doesn't really mean that the option is applied globally, but rather that the option is applied to the command and all descendant sub-commands.)

```C#
    public class DatabaseCommandGroup : Command
    {
        public DatabaseCommandGroup() : base("database")
        {
            AddGlobalOption(DatabaseParameters.Host);
            AddGlobalOption(DatabaseParameters.Port);
            AddCommand(new MigrateCommand());
        }
    }
```

Dotnetfiddle: https://dotnetfiddle.net/7OiHEb

**Comment by jonsequitur** [comment]
If you use `AddGlobalOption(GlobalParameters.Verbose)` at your root command, you won't have to repeat adding it for subcommands and it will be valid on all subcommands. If it's marked `IsRequired = true` then it can be satisfied anywhere it appears, so e.g. it will be required but any of the following would work:

```console
> --verbose database migrate
> database --verbose migrate
> database migrate --verbose
```

The same is true for any subtree of your command hierarchy. When you add an option to a command, it's only valid (in terms of the grammar of your CLI) directly under that command, but you can add it to as many commands as you like, and `AddGlobalOption` will add it to the current command and all of its descendants.

I'm not sure I've addressed the question. Please let me know whether that was helpful.

**Comment by kriswuollett** [comment]
Thanks, yes, this was helpful! I'll have to put some more thought and work into my example like automatically checking for environment variable first, and making options reusable, e.g., group of options for database connection for "src" and "dst". That probably requires making the options members of the commands, and passing the command to the binder at invocation time.
