### ISSUE TITLE
Localization How-To

### ISSUE THREAD

**Issue by GiulioPierucci** [dotnet/command-line-api#1723]
I'd like to localize usage and error in my language (italian), but I don't find an how-to or a guide about this argument. I already read the documents in doc folder and the overview on Microsoft website.

May you help me to point in the right direction?
Thanks in advance

Giulio

**Comment by jonsequitur** [comment]
I don't believe we've covered this in the documentation yet but it's pretty straightforward. You can see an example in the tests here: 

https://github.com/dotnet/command-line-api/blob/6c71bd788d9c8f8628787792d865b9eb683f851f/src/System.CommandLine.Tests/ResourceLocalizationTests.cs#L33-L51

**Comment by GiulioPierucci** [comment]
Thanks a lot, mate. I totally missed it.

**Comment by GiulioPierucci** [comment]
Sorry again, 
i have another stupid question: how I can localize "Option '--my-option' is required."? I inherited LocalizationResources class, but i can't find the method.

what i'm doing wrong? 

Thanks again

**Comment by jonsequitur** [comment]
It looks like that message needs to be made localizable. 

I've opened #1724 to track this.
