### ISSUE TITLE
How can I have a global option with nested commands?

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/command-line-api#1743]
I have a nested command setup as follows:

```csharp
var rootCommand = new RootCommand()
{
    new Command("verb")
    {
        new Command("childverb")
    }
};
```

I need a `--verbose` flag that can be used on all of them, but it does the exact same thing so I don't want to have to add a variable to every single command.

is there some way to have a global `--verbose` flag?

Would middleware work?

**Comment by jonsequitur** [comment]
It sounds like `rootCommand.AddGlobalOption` will do what you need.
