### ISSUE TITLE
Adding 2 values to one option 

### ISSUE THREAD

**Issue by matinmn87** [dotnet/command-line-api#1744]
Hi. Is there a way to assign 2 values to one option?
For example, if the call is in this way:
`tkp.exe keep --name test --content this -t work`
make it this & also the -t works (Just looks for 2 values, not more):
`tkp.exe keep test this -t work`
Thanks for your help

**Comment by jonsequitur** [comment]
Are you looking for something like this? 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/547415/170740248-719f25ac-c666-4528-aeac-e7243f402991.png">

**Comment by matinmn87** [comment]
Something like this. but I don't want to insert 2 -t for that: `-t option1 option2`

**Comment by matinmn87** [comment]
Hello again. If it's not possible, please tell me. Thanks for your answers

**Comment by matinmn87** [comment]
Thanks
