### ISSUE TITLE
Prevent invocation of subcommands unless they are the first argument

### ISSUE THREAD

**Issue by harenbrs** [dotnet/command-line-api#1747]
Is there a way to ensure that only the first (non-option) argument is parsed as a potential subcommand? In my application I need to be able to invoke the root command with arguments that can be the same as a subcommand token.

A reproducible example:

```csharp
using System.CommandLine;
using System.CommandLine.NamingConventionBinder;

namespace CLITest
{
    internal class Program
    {
        static int Main(string[] args)
        {
            var rootCommand = new RootCommand()
            {
                new Command("sub")
                {
                    Handler = CommandHandler.Create(() => Console.WriteLine("sub"))
                },
                new Argument<string[]>("args")
            };

            rootCommand.Handler = CommandHandler.Create((string[] args) =>
            {
                Console.WriteLine($"root: {string.Join(" ", args)}");
            });

            return rootCommand.Invoke(args);
        }
    }
}
```

The subcommand `sub` should only be invoked when running `CLITest.exe sub [...]`, but *not* when running `CLITest.exe other args sub foo`. In this case, the root command handler should be invoked with all the arguments stored in `args`: `"other", "args", "sub", "foo"`.

Is there some way to enforce this without manually examining `args` in `Main` and bypassing the invocation altogether?

**Comment by harenbrs** [comment]
Unfortunately that's not an option for me, as the invocation must match a previous implementation exactly.

**Comment by harenbrs** [comment]
> One way is to use a `--` in your invocation, which instructs the parser (and any other posix-compliant parser) to parse the tokens after the `--` as arguments rather than as options or commands: `CliTest.exe -- other args sub foo`

Based on this, my new workaround is to programmatically insert a `"--"` at a specific position into the `args` array depending on what arguments are given. (*Maybe that was what you meant?*) This keeps tab-completion working, but it is fairly hacky and inefficient as in my case I need to load some data to check whether or not to insert it. A purely grammatical pattern-matching solution at the framework level would be ideal.

I feel there should be an option to stop subcommands from being picked up from the middle of the command line, I don't think that is at all an unconventional grammar.

**Comment by harenbrs** [comment]
Sorry for commenting a lot, but I've found an acceptable solution using a short-circuiting middleware (as described [here](https://github.com/dotnet/command-line-api/blob/main/docs/How-To.md#middleware-pipeline)):

```csharp
var parser = new CommandLineBuilder(rootCommand)
    .AddMiddleware(async (context, next) =>
    {
        var command = rootCommand.Where(command => context.ParseResult.FindResultFor(command) != null).FirstOrDefault();
        
        if (args.Where(arg => !arg.StartsWith("-")).FirstOrDefault() != command?.Name)
        {
            // Short-circuit to root command
            Execute(args);
            return;
        }
        
        await next(context);
    })
    .UseDefaults()
    .Build();
```

This checks if the command that the framework wants to invoke corresponds to the first non-option token and if not, executes something else instead (my root command handler in this case).

Feedback welcome if I'm missing something that could go wrong with this.

**Comment by baronfel** [comment]
That seems like a fine workaround, good thinking to use a middleware to prevent your command handlers from being tainted with this handling 👍

**Comment by harenbrs** [comment]
@elgonzo That's a very good point, thanks for making me aware of it. In my case I only ever expect a simple boolean flag as the first argument, so that should be fine.
