### ISSUE TITLE
Crash when using DateOnly

### ISSUE THREAD

**Issue by sebasijan** [dotnet/command-line-api#1749]
.NET 6.0

This is how I created my root command:

        private static Command GetCommand(IMediator mediator, CancellationToken cancellationToken)
        {
            var rootCommand = new RootCommand("Seed Users.");
            var createdDate = new Option<DateOnly>(
                name: "--created",
                description: "The date to set EntityChanges.OccurredAt.",
                isDefault: true,
                parseArgument: result => DateOnly.Parse(result.Tokens[0].Value));

            var seedUsersCommand = new Command("user", "Seed users.")
            {
                createdDate
            };
            seedUsersCommand.SetHandler(
                async (string userCreatedDate) =>
                {
                    if (DateOnly.TryParse(userCreatedDate, out var date))
                    {
                        await mediator.Send(
                            new SeedBaselines<User, UserDTO>(date),
                            cancellationToken);
                    }
                },
                createdDate);

            rootCommand.AddCommand(seedUsersCommand);

            return rootCommand;
        }

But its crashing with this error 

 > Unhandled exception: System.ArgumentException: The SetHandler call for command 'user' is missing an Argument or Option for the parameter at position 0. Did you mean to pass one of these?                                                                                                                                                                                 at System.CommandLine.Handler.GetValueForHandlerParameter[T](IValueDescriptor[] symbols, Int32& index, InvocationContext context)                                                                                                               at System.CommandLine.Handler.<>c__DisplayClass19_0`1.<SetHandler>b__0(InvocationContext context)                       at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)                         at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()    --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()                                                                                                                  --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()         --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()--- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()                                                                                                                      --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()            --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()                                                                                                                       --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()       --- End of stack trace from previous location ---                                                                          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()                                                                                                                              

**Debug Params:**

    user --created 2022/10/10

It works fine if I receive it as a string and then do the mapping inside the handler, but surely that's not right.   

What am I doing wrong?

**Comment by baronfel** [comment]
Hi @sebasijan  - I think this is because in your handler you have the option typed as `string`, when you've already parsed it as a `DateOnly`. If you change the type of `userCreatedDate` to `DateOnly` (and update your handler as well), then things should just work.
