### ISSUE TITLE
Is it possible to make console apps like this with System.CommandLine.Rendering?

### ISSUE THREAD

**Issue by matinmn87** [dotnet/command-line-api#1753]
Hi. Do your Rendering solution can produce something like this?https://raw.githubusercontent.com/spectreconsole/spectre.console/main/docs/input/assets/images/example.png
If yes, why there's no doc for it?

**Comment by elgonzo** [comment]
My apologies for not directly addressing your concern, but i feel this part of the "[_Beta 2 announcment and the road to GA_](https://github.com/dotnet/command-line-api/issues/1537)" is relevant here to be aware of:

> Deprecating System.CommandLine.Rendering
>
> The System.CommandLine.Rendering project grew out of the realization that no help API could cover all of the ways in which someone might want to customize help. We started exploring approaches to rendering output that would look good in both older Windows command prompts that lack VT support as well as Linux and Mac terminals and the new Windows Terminal. This led to discussions about first-class support for VT codes and the lack of a separation of a terminal concept in System.Console. That discussion is ongoing and has implications well beyond the scope of this library. In the meantime, many of the objectives of System.CommandLine.Rendering were realized beautifully by the [Spectre.Console](https://spectreconsole.net/) project.

**Comment by matinmn87** [comment]
Ok, so I'll use spectre. thanks
