### ISSUE TITLE
Error handling in System.CommandLine.CompletionSuggestions

### ISSUE THREAD

**Issue by wli3** [dotnet/command-line-api#178]
1. bubble up we could crash user's shell start. Maybe it is too much.
2. Don't throw, the user will never know if there is a real config is wrong. And if it is file locking, that might be fine.
3. Print warning but that could also be annoying for people to see it should up on shell start.

**Comment by jonsequitur** [comment]
Since the problem is typically something that needs to be shown to the developer, not the end user, we've added a feature to enable debug logging via an environment variable in `dotnet-suggest`.
