### ISSUE TITLE
How to propagate custom CancellationToken?

### ISSUE THREAD

**Issue by sakno** [dotnet/command-line-api#1783]
I'm using CommandLine library in embedded scenario where input and output are fully controlled by the host (and not associated with stdin and stdout). In this case, `CancelOnProcessTermination` makes no sense. Instead, I want to propagate cancellation token from the host. At the moment, it is not possible. `InvocationContext.GetCancellationToken` returning token associated with internal CTS. As a result, there is no way to cancel the operation by the host.

To address this issue, I would like to propose some changes in public API:
```csharp
public static class ParserExtensions
{
    // added token as the last parameter
    public static int Invoke(this Parser parser, string commandLine, IConsole? console = null, CancellationToken token = default);
    public static int Invoke(this Parser parser, string[] args, IConsole? console = null, CancellationToken token = default);
    public static Task<int> InvokeAsync(this Parser parser, string commandLine, IConsole? console = null, CancellationToken token = default);
    public static Task<int> InvokeAsync(this Parser parser, string[] args, IConsole? console = null, CancellationToken token = default);
}

public static class CommandExtensions
{
    // added token as the last parameter
    public static int Invoke(this Command command, string[] args, IConsole? console = null, CancellationToken token = default);
    public static int Invoke(this Command command, string commandLine, IConsole? console = null, CancellationToken token = default);
    public static Task<int> InvokeAsync(this Command command, string[] args, IConsole? console = null, CancellationToken token = default);
    public static Task<int> InvokeAsync(this Command command, string commandLine, IConsole? console = null, CancellationToken token = default);
}
```

If the changes will be approved, I'm ready to make a PR.

**Comment by jonsequitur** [comment]
You raise a valid use case. This looks related to #1469 and #1502. Have you looked at those and do you think it would address this issue?

**Comment by sakno** [comment]
Yeah, I didn't try hard enough to find a similar issues :( I see that PR is still open. Can I help somehow with that? Or PR is on the final stage of review?

**Comment by sakno** [comment]
@jonsequitur , review from my side is done. Also, I proposed a few changes to the original PR.
