### ISSUE TITLE
System.CommandLine defaults have large dependency closure

### ISSUE THREAD

**Issue by jkotas** [dotnet/command-line-api#1794]
## Repro

`dotnet publish -c Release -r win-x64 /p:PublishTrimmed=true`

```csharp
using System.CommandLine;

internal class Program
{
    private static int Main(string[] args)
    {
        var fileOption = new Option<FileInfo?>(
            name: "--file",
            description: "The file to read and display on the console.");

        var rootCommand = new RootCommand("Sample app for System.CommandLine");
        rootCommand.AddOption(fileOption);

        rootCommand.SetHandler(
            (FileInfo file) => ReadFile(file),
            fileOption);
        return rootCommand.Invoke(args);
    }

    private static void ReadFile(FileInfo file)
        => File.ReadLines(file.FullName).ToList()
            .ForEach(line => Console.WriteLine(line));
}
```

## Actual result:

The trimmed application has referenced to many types and binaries that should not be needed:
```
System.Private.Uri.dll
System.Net.Primitives.dll
System.ObjectModel.dll
System.ComponentModel.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Collections.NonGeneric.dll
System.Runtime.Serialization.Formatters.dll
System.Diagnostics.Process.dll
...
```

## Expected result:

The trimmed application should only reference types and binaries that are actually needed.

**Comment by jkotas** [comment]
Context: https://github.com/dotnet/runtime/pull/72082#issuecomment-1185706575

**Comment by adamsitnik** [comment]
We have made some progress recently, but we are definitely not done yet:

```diff
System.Private.Uri.dll
System.Net.Primitives.dll
- System.ObjectModel.dll
- System.ComponentModel.dll
- System.ComponentModel.Primitives.dll
- System.ComponentModel.TypeConverter.dll
- System.Collections.NonGeneric.dll
System.Runtime.Serialization.Formatters.dll
- System.Diagnostics.Process.dll
```

**Comment by adamsitnik** [comment]
My guess is that all of the redundant references come from here:

https://github.com/dotnet/command-line-api/blob/c63e231c1e5102c51bd9247a4f3feec9175d601d/src/System.CommandLine/Binding/ArgumentConverter.StringConverters.cs#L14

which is just a dictionary of parsers that in theory can be used by the app:

https://github.com/dotnet/command-line-api/blob/c63e231c1e5102c51bd9247a4f3feec9175d601d/src/System.CommandLine/Binding/ArgumentConverter.StringConverters.cs#L172-L182

Since `Argument` and `Option` are generic now, we could introduce a parse method similar to:

```cs
internal bool TryParse(string token, out T value)
{
    if (typeof(T) == typeof(IPAddress))
    {
        if (IPAddress.TryParse(token, out var ip))
        {
            value = (T)(object)ip;
            return true;
        }

        value = default;
        return false;
    }
    // else if (typeof(T)...
}
```

@jkotas Does trimmer recognize such typeof checks? If not, how can I get rid of these references?

**Comment by am11** [comment]
@adamsitnik, very nice! Should/can we update https://github.com/dotnet/runtime/blob/f561a058b13523c4b045803c9876e823b4cfe0fc/eng/Versions.props#L174 to latest revision? It's four months old and seems like we don't have a darc subscription in runtime repo for command-line-api (dotnet/format, dotnet/sdk etc. have such a subscription).

**Comment by jkotas** [comment]
> Does trimmer recognize such typeof checks? 

Trimmer does not recognize patterns like these.

> If not, how can I get rid of these references?

This is yet another deserializer. You can look at e.g. how we have solved this problem for System.Text.Json deserializer. The general shape of the solution is:

- Avoid collections of built-in deserializers or discovering deserializers using reflection.
- Expose each built-in deserializer as a public entrypoint with concrete types.
- Use source generators to generate the glue code if the entrypoints with concrete types are cumbersome to use.

**Comment by adamsitnik** [comment]
> Should/can we update

We should, but I should not do it myself, as I introduced all the breaking changes and they are reasonable and easy to fix for me.

I am about to write a doc that lists all the breaking changes, explains the reasoning behind them and how to solve the issues.

@am11 would you be interested in updating dotnet/runtime once I have the doc ready? And share some feedback about whether the changes are move in the right direction or not?
