### ISSUE TITLE
Update NuGet packages frequently and provide daily builds

### ISSUE THREAD

**Issue by rubo** [dotnet/command-line-api#1809]
Could we please have NuGet packages updated more frequently?
Also, the daily feed [link](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json) in the README doesn't contain the necessary packages. Only these two:

- `dotnet-suggest`
- `System.CommandLine.Generator`

**Comment by jonsequitur** [comment]
There seems to be an issue with the build pipeline. We're looking into it.

**Comment by jonsequitur** [comment]
Different build problem this time, but the package feed is to date again. Thanks for the heads up!
