### ISSUE TITLE
How to tell if built-in help handler was called instead of user SetHandler? 

### ISSUE THREAD

**Issue by wm2015email** [dotnet/command-line-api#1811]
I have a WPF application that I want to do some cleanup after the CommandLine invoke call, but I have no way of knowing if
--help was invoked or one of my command line arguments was invoke. 

```C#
...
var rc = rootCommand.SetHandler((context) => {
   var result = context.ParseResults;
   //do something...
}
rootCommand.Invoke(e.Args);

// OK... now I want to know... did SetHandler get called or was built in Help Handler called (myapp --help)...
if (help called) {
   close app...
}
else {
  do something else...
}
```

**Comment by wm2015email** [comment]
COuld you at least return a code that says that help was invoked?

**Comment by elgonzo** [comment]
If the cleanup is only necessary when your command handler(s) have been invoked, wouldn't it make sense to let the command handlers themselves do the cleanup as last step of whatever actions they do? Or asked differently: What would force you to do the cleanup _outside_ the command handlers?

**Comment by adamsitnik** [comment]
With #2071 :

```cs
ParseResult parseResult = rootCommand.Parse(args);
if (parseResult.Action is HelpAction)
{

}
else
{

}
```
