### ISSUE TITLE
How are validators supposed to work?

### ISSUE THREAD

**Issue by voltagex** [dotnet/command-line-api#1824]
Trimming down my code to the bare minimum
```
    static void Main(string[] args)
    {
        var commands = new RootCommand("Testing command line validators");
        //https://github.com/dotnet/command-line-api/blob/4b605851d45131db2374ba711f2443040521d702/src/System.CommandLine.Tests/ParsingValidationTests.cs#L254
        commands.AddValidator(commandResult =>
        {
            commandResult.ErrorMessage = "This is an error";
        });

        var localCommands = new Command("local", "Act on the local machine");
        var remoteCommands =
            new Command("remote", "Act on a remote machine");
        remoteCommands.AddArgument(new Argument<string>("host", "Hostname to act on"));

        //common to both local and remote mode, is there a better way?
        var pathArgument = new Argument<string>("path", "Path to scan");

        localCommands.AddArgument(pathArgument);
        remoteCommands.AddArgument(pathArgument);

        commands.AddCommand(localCommands);
        commands.AddCommand(remoteCommands);

        var pr = commands.Parse(args);
        Console.WriteLine(pr);
        Environment.Exit(0);
    }
```

If I break before Environment.Exit, I can see that `ParseResult.Errors` is empty. 

I had started at https://github.com/dotnet/command-line-api/issues/381 but I haven't been able to make much progress. What I was originally trying to do is make `myprogram.exe local remote` invalid, but `myprogram.exe local` and 'myprogram.exe remote` valid

How are validators supposed to work if I can't return out of the void function in AddValidator?

Edit: @jonsequitur's answer works and the info in https://github.com/dotnet/command-line-api/issues/1824#issuecomment-1229506145 should be added to the documentation. Thanks all.

**Comment by elgonzo** [comment]
You add the validator to your root command. But your root command has neither options nor arguments. Unless i am mistaken, a validator only validates options/arguments belonging to the command the validator has been added to. It does not validate options/arguments belonging other commands. Hence, there is nothing to validate for the root command's validator, and no errors in ParseResult.Errors.

Add validators to _localCommands_ and _remoteCommands_ to validate the respective options/arguments of these commands.

**Comment by jonsequitur** [comment]
A validator is only checked if the command is matched by the submitted command line. So for example a validator for `local` would not be called if the command line parses to match `remote`. And if a subcommand is matched, then its parent validator(s) would not be called.

**Comment by lonix1** [comment]
I found one can validate all of a command's options at once (similar to "model validation"):
````cs
myCommand.AddValidator(commandResult => ...);
````

Or a specific option (similar to "property validation"):
````cs
myOption1.AddValidator(commandResult => ...);
myOption2.AddValidator(commandResult => ...);
````

Generally I found the latter to be more useful. But the former is useful too, e.g. when comparing options to each other.

I wonder if there is a better/official way? I got the above from reading the unit tests.

**Comment by KathleenDollard** [comment]
@voltagex could you edit your initial message to indicate that @jonsequitur's answer works and close this?

@elgonzo's answer was about the same but the lack of options /args was not part of the answer. Validation is not called on parent commands.

And the original question was about ensuring just one of two command names is called. That part just happens automatically and `myprogram.exe local remote` would be a parsing error with no further work.

**Comment by jonsequitur** [comment]
> Generally I found the latter to be more useful. But the former is useful too, e.g. when comparing options to each other.

@lonix1 You can also validate one option from within another's validator. This has certain advantages because it makes no assumptions about where in the hierarchy the different options might be (for example when a global option is used that might occur under multiple possible commands.)

Here's an example:


```csharp
var optionX = new Option<int>("-x");
var optionY = new Option<int>("-y");
var errorMessage = "You can't use -x and -y together.";
optionX.AddValidator(result =>
{
    if (result.FindResultFor(optionY) is not null)
    {
        result.ErrorMessage = errorMessage;
    }
});
```
