### ISSUE TITLE
Customising help text with Spectre.Console

### ISSUE THREAD

**Issue by lonix1** [dotnet/command-line-api#1835]
It's generally easy to use this library with Spectre.Console. But has someone managed to use it for the help text specifically?

The help is [typically customised](https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help#add-or-replace-help-sections) like so:
````cs
HelpBuilder.Default.GetLayout()
  .Append(_ => _.Output
    .WriteLine("EXTRA CONTENT APPENDED TO HELP"));
````

So I tried this:
````cs
HelpBuilder.Default.GetLayout()
  .Append(_ => AnsiConsole.Create(new AnsiConsoleSettings() { Out = new AnsiConsoleOutput(_.Output) })
    .MarkupLine("[blue]EXTRA CONTENT APPENDED TO HELP[/]"));
````

That prints the text, but not in colour.

(@patriksvensson Would you know if this is currently possible?)

**Comment by patriksvensson** [comment]
@lonix1 Sorry, I cannot recreate the issue you're seeing. What terminal, operating system, etc. are you using?

<img width="469" alt="image" src="https://user-images.githubusercontent.com/357872/188074971-658d1a31-20b7-4b2b-bcbe-104a9f2468c8.png">

**Comment by jonsequitur** [comment]
In `dotnet-repl`, here's what I did. 

* Created a custom `HelpBuilder`: https://github.com/jonsequitur/dotnet-repl/blob/82d7df4aee7609b6f9d2026f5c46f8965371dd24/src/dotnet-repl/SpectreHelpBuilder.cs

* Replaced the default help builder with it: https://github.com/jonsequitur/dotnet-repl/blob/7b1af76f6842f5819e34b421c90bf34523903b4f/src/dotnet-repl/CommandLineParser.cs#L98-L101

Here's what the help output looks like: 

 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/547415/188233379-eb00fe5c-7ae2-463f-b375-5f892de1c741.png">

**Comment by lonix1** [comment]
When I run that dotnet-repl I get different colours. So problem must be me.

Thanks.
