### ISSUE TITLE
[Feature Request] Expose which command was run

### ISSUE THREAD

**Issue by lonix1** [dotnet/command-line-api#1839]
I have a global option for which I perform validation:
````cs
class FileOption: Option<FileInfo?>
{

  public FileOption() : base("file")
  {
    AddValidator(Validate);
  }

  public static void Validate(OptionResult result)
  {
    // whichCommandWasRun = ???             // <-------------------
  }

}
````

I need to know which command was run before I can decide how to validate. Example use case: a global option for a config file. When running a "setup" command, the config file should not exist. When running any other command, the config file must exist.

I can't determine which command was run, as the `OptionResult` does not expose that information.

The solution could be something like:
- `result.CommandRun is SetupCommand`
- or `result.CommandLine.Contains(" setup")`, e.g. for command line of `"myapp --file /home/me/.myapp.config setup"`
- or `result.CommandLine.Command.Any(x => x is SetupCommand)`
- etc...

The exact syntax doesn't matter, it just matters than in every part of the system one can refer to the original command line invocation. It's an important source of information for many use cases. Not exposing that info makes downstream code more complicated.

**Comment by lonix1** [comment]
@KalleOlaviNiemitalo Thank you. I looked in there but didn't find what I needed because I didn't cast to the correct subclass.

I used your advice to do this: recurse to get `RootCommandResult`, cast to `CommandResult`, get its `Command`, check its what I want.

**Comment by jonsequitur** [comment]
The simplest way to get the command indicated by `ParseResult` is `parseResult.CommandResult.Command`.

**Comment by jonsequitur** [comment]
Sorry, I missed that you're trying to figure this out from within the validator. In that case you can just check the `OptionResult.Symbol`. If you want to pattern match it to `Command` you can, but the parent symbol for an `Option` can only ever be a `Command` or `RootCommand` (which inherits `Command`). 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/547415/188943974-0d3620b4-5de6-49c0-b09a-90a6e6ed16c5.png">
