### ISSUE TITLE
IdentifierSymbol.AddAlias summary not useful in Intellisense

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/command-line-api#1845]
The XML documentation of IdentifierSymbol.AddAlias includes `<see href="/dotnet/standard/commandline/syntax#aliases">alias</see>`. The Intellisense tooltip in Visual Studio 2017 displays the `/dotnet/standard/commandline/syntax#aliases` string as is, not as a clickable hyperlink, so it is not useful there.

<https://github.com/dotnet/command-line-api/blob/209b724a3c843253d3071e8348c353b297b0b8b5/src/System.CommandLine/IdentifierSymbol.cs#L62-L69>

**Comment by adamsitnik** [comment]
fixed by #2073

https://github.com/dotnet/command-line-api/blob/22905db23895750c908bdb8948e9c5749aa34276/src/System.CommandLine/Command.cs#L87-L91

https://github.com/dotnet/command-line-api/blob/22905db23895750c908bdb8948e9c5749aa34276/src/System.CommandLine/Option.cs#L101-L105
