### ISSUE TITLE
Async handler doesn't bubble exceptions when awaited.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/command-line-api#1861]
Async handlers dont bubble exceptions to the Invoker which leads to an undesired outcome.

```cs
var rootCommand = new RootCommand();

rootCommand.SetHandler(async () =>
{
     await RunAsync();
});

return await rootCommand.InvokeAsync(args);
```

```cs
public static async Task RunAsync()
{
     throw new Exception("Test"); //<-- doesn't bubble up.
}
```

**Comment by elgonzo** [comment]
Well, it actually does: https://dotnetfiddle.net/KU4ATy

The problem you reported is not caused by the code you presented.

**Comment by KieranDevvs** [comment]
> Well, it actually does: https://dotnetfiddle.net/KU4ATy (My dotnetfiddle example uses System.CommandLine 2.0.0-beta4.22272.1)
> 
> The problem you reported is not caused by the code you presented, unless perhaps an older version of the library exhibited such a bug.

No I think this is something to do with dotnetfiddle.
https://dotnetfiddle.net/qFZEsT

As you can see, the exception should be caught and the return code should be -9.

**Comment by elgonzo** [comment]
Ah, alright. I see, the dotnetfiddle output did fool me. You are right, the exception is caught and printed out by System.CommandLine and not propagated further up the call stack.

**Comment by elgonzo** [comment]
Sorry for coming back to this about a whole month later. I just had to address a very similar situation where i didn't want the exception handling inside the handler, and remembered this report. There is a solution to that problem, and for completeness' sake, i decided to post this solution here.

By default, as noticed, System.CommandLine catches exceptions thrown by command handlers and generates some error output. This behavior can be changed, however, by utilizing CommandLineBuilder:
```C#
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

...

var parser = new CommandLineBuilder(rootCommand)
    .UseVersionOption()
    .UseHelp()
    .UseEnvironmentVariableDirective()
    .UseParseDirective()
    .UseSuggestDirective()
    .RegisterWithDotnetSuggest()
    .UseTypoCorrections()
    .UseParseErrorReporting()
//    .UseExceptionHandler()          <---- we don't want to use this
    .CancelOnProcessTermination()
    .Build();
    
try
{
    return await parser.InvokeAsync(args);		
}
catch
{
    return -9;
}    
```
(dotnetfiddle: https://dotnetfiddle.net/0pjOQT)

**Comment by KieranDevvs** [comment]
> ```cs
> var parser = new CommandLineBuilder(rootCommand)
>     .UseVersionOption()
>     .UseHelp()
>     .UseEnvironmentVariableDirective()
>     .UseParseDirective()
>     .UseSuggestDirective()
>     .RegisterWithDotnetSuggest()
>     .UseTypoCorrections()
>     .UseParseErrorReporting()
> //    .UseExceptionHandler()          <---- we don't want to use this
>     .CancelOnProcessTermination()
>     .Build();
> ```

Thanks for the work around, I've managed to get the behaviour I expect. I will say though, it would be nice to have an easier way to disable the internal exception handler without manually specifying all the other features via the builder.

Maybe expose a global options class? i.e:

```cs
CommandLineDefaultOptions.UseInternalExceptionHandler = false;

var nameOption = new Option<string?>("--name", "Name option");

var rootCommand = new RootCommand("Sample app for System.CommandLine");
rootCommand.AddOption(nameOption);

rootCommand.SetHandler(async (name) => await RunAsync(name), nameOption);

return await rootCommand.InvokeAsync(args);
```
