### ISSUE TITLE
Error, help and version output are not shown if application is started via executable

### ISSUE THREAD

**Issue by ta-stratec** [dotnet/command-line-api#1867]
If started with dotnet command, e.g. _dotnet app.dll_,
-  help is shown if requested via option ✔️ 
-  version is shown if request via option ✔️ 
-  error and help are shown if invalid command/error is passed. ✔️ 

If started via executable, e.g. _app.exe_, 
-  help is **not** shown if requested via option 🐛 
-  version is **not** shown if request via option 🐛
-  error and help are **not** shown if invalid command/option is passed. 🐛

Environment: Windows 10, .NET 6, System.Commandline 2.0.0-beta4.22272.1

**Comment by baronfel** [comment]
Do you have sample code that shows this behavior? This is not what I'd expect at all so I'm wondering if there's something easily reproducible you could show to verify the behavior.

**Comment by ikeras** [comment]
Just a guess but is app.exe a WinExe? If app doesn't have a console attached to it, then when it's run with --help I'd guess System.CommandLine doesn't know where to output the information. Since dotnet.exe has a console attached, I expect it works in that case, even if the app is ultimately going to display a window.

**Comment by ta-stratec** [comment]
> Just a guess but is app.exe a WinExe? If app doesn't have a console attached to it, then when it's run with --help I'd guess System.CommandLine doesn't know where to output the information. Since dotnet.exe has a console attached, I expect it works in that case, even if the app is ultimately going to display a window.

That's a good point. I tried to reproduce it with a simple example application for uploading as requested but failed. But it was just a console app while my real application is a WinExe. I going to test it once more configuring my app as console app (temporarily). Thx in advance!
