### ISSUE TITLE
Skip showing help when the parser fails parsing the provided args

### ISSUE THREAD

**Issue by qui8t** [dotnet/command-line-api#1873]
Currently, if you miss any of the required args, or provide invalid values for the arguments, the parser will fail to parse and shows why it failed, plus it displays the help message. I was wondering if I can avoid showing help.

**Comment by jonsequitur** [comment]
Here's how I did this recently in the context of a custom `HelpBuilder`:

https://github.com/jonsequitur/dotnet-repl/blob/743cb22edd61e0b0e6cae08c01e02db9b9f428a2/src/dotnet-repl/SpectreHelpBuilder.cs#L18-L22

We'll come up with something simpler, but is one approach that works currently.

**Comment by qui8t** [comment]
Thank @jonsequitur for the suggestion, with that I was able to build the following.

```csharp
var parser = new CommandLineBuilder(rootCommand)
    .UseExceptionHandler((e, context) =>
    {
        exceptionHandler(e, context);
    }, errorExitCode: 1)
    .UseVersionOption()
    .UseHelp(context =>
    {
        context.HelpBuilder.CustomizeLayout(
            x =>
            {
                # this will avoid showing help if the parser fails to parse arguments.
                if (x.ParseResult.Errors.Any())
                    return new List<HelpSectionDelegate>();

                return HelpBuilder.Default.GetLayout().Prepend(
                _ => AnsiConsole.Write(
                    new FigletText("MyProgram")));
            });
    })
    .Build();
```

I appreciate how holistic and expressive `command-line-api` is, but I would appreciate it more if I could have done this type of adjustments much simpler :)
