### ISSUE TITLE
String gets parsed as system path

### ISSUE THREAD

**Issue by AngelMunoz** [dotnet/command-line-api#1877]
Hello there hopefully you're having a good week!

I'm writing a sort of a package manager for web stuff, but right now I'm having a bit of an issue with a string argument that is getting parsed as a system path somehow 

```fsharp
#r "nuget: System.CommandLine, 2.0.0-beta4.22272.1"

open System
open System.CommandLine
let package = Argument<string>(name="package", description="thing to install")
let rootCmd = RootCommand("test")
rootCmd.AddArgument(package)
rootCmd.SetHandler(Action<string>((fun file -> printfn "%A" file)), package)
rootCmd.Invoke([|"@shoelace-style/shoelace"|])
```
this code produces the following output 

```
PS C:\Users\scyth\Desktop> dotnet fsi Script1.fsx
Error reading response file 'shoelace-style/shoelace': Could not find a part of the path 'C:\Users\scyth\Desktop\shoelace-style\shoelace'.
Required argument missing for command: 'fsi'.

Description:
  test

Usage:
  fsi <package> [options]

Arguments:
  <package>  thing to install

Options:
  --version       Show version information
  -?, -h, --help  Show help and usage information
```

switching the last line to 
```
rootCmd.Invoke([|"I can be parsed"|])
```
makes it work as expected

```
PS C:\Users\scyth\Desktop> dotnet fsi Script1.fsx
"I can be parsed"
PS C:\Users\scyth\Desktop>
```

I'm not sure if I'm missing something or do I need to scape these somehow, any pointers would be nice, thanks in advance and have a good day

**Comment by baronfel** [comment]
I think you're hitting the default string interpolation handler. Check out [this doc](https://github.com/dotnet/command-line-api/issues/1750#:~:text=Custom%20token%20replacement) for some details on it. You can replace that response file handling entirely, though - we do this in the .NET SDK [here](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Parser.cs#L160).

**Comment by jonsequitur** [comment]
@AngelMunoz, was @baronfel's suggestion useful here? Can we close this issue?

**Comment by AngelMunoz** [comment]
That is likely to work, I'll try to get something done this week and report back otherwise I'll close it in the meantime and open it back if anything, thanks for the pointers
