### ISSUE TITLE
Command-local arguments?

### ISSUE THREAD

**Issue by paralaxsd** [dotnet/command-line-api#1885]
Hi,

I'm writing an application with a number of sub commands.
I'd like my app to accept a single argument at the root command level so users can easily indicate an optional file path for the app to open instantly.

My problem is, that when I'm adding this argument to the root command, it will then also show up as an unwanted argument in any sub command help. There seems to be no way around this behavior as [HelpBuilder.GetCommandArgumentRows](https://github.com/dotnet/command-line-api/blob/ff9e8f74cf5945e51a70b9910afa5956b9a353f3/src/System.CommandLine/Help/HelpBuilder.cs#L157-L163) will recursively include all parent command arguments.

If I use an option instead of an argument, I'm free to decide whether it should be global or local to a given command. I'm wondering if it would be possible to have the same freedom for arguments or if I can realize my scenario in another way? Thanks!

**Comment by elgonzo** [comment]
My apologize for not directly responding with a suggestion. But i want to direct your attention to something with respect to your desired CLI. Maybe you already have thought about that, and if so, i am sorry for just adding redundant noise to your question.

What if the given file path is just a file name "foo" that is coincidentally matching a sub-command of the same name "foo"?

The distinction between / identification of what would be supposed to be an argument (for your root command) or a sub-command name is application-specific. I have to admit that i don't have an idea of how this ambiguity could be resolved on the library-level in a general way without replacing this amibiguity with another kind of ambiguity (as an attempted resolution of such ambiguities can only be fuzzy without taking the desired application logic into account) affecting other application scenarios. Considering this, i feel the option-based approach is preferable as it simply avoids this potential ambiguity.

**Comment by paralaxsd** [comment]
Thanks for you input @elgonzo. I haven't specifically looked into how that's implemented, but it doesn't seem to be an issue anyhow. If I run my app with a given sub command, the framework automatically runs the handler for the sub command and otherwise the argument is interpreted as a file path.

I'm supporting a range of file formats with known file extensions so there is no way for any accidental collision as of now.

As mentioned, I could resolve my issue by using a non-global option but I'd like to keep it simple for the user - most applications open their content directly if given a file path and I think that's sensible.

**Comment by elgonzo** [comment]
FYI: A non-global option has the behavior that you can also specify with a sub command, e.g. `myapp -global foo.txt subcmd`, without this being an error as far as the System.CommandLine library is concerned. If this is an issue for you, you would have to work-around this behavior somehow, which probably isn't making it much better/simpler than an Argument-based approach.

Following is a rough outline of how the Argument-based approach would work. It basically relies on CommandLineBuilder and analyzing the parse result for determining whether a single argument has been given or a sub-command is invoked, or whether a combination of argument value + sub-command has been given. It also takes care of not showing the root argument in the help output of sub-commands.

```C#
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

//
// Make root command file path argument optional.
//
var rootArg = new Argument<string>("filePath") { Arity = ArgumentArity.ZeroOrOne };

...

var parser = new CommandLineBuilder(rootCmd)
    .UseDefaults()
    .Build();

var parseResult = parser.Parse(args);

if (parseResult.Errors.Count > 0)
{
    //
    // Trigger standard System.CommandLine error output
    //
    parseResult.Invoke();
}
else if (
    parseResult.Tokens.Count > 1
    && (parseResult.CommandResult.Command == rootCmd || parseResult.Tokens[0].Type != TokenType.Command)
) {
    //
    // Detected that the root command file path argument has been specified together with other stuff...
    //
    ... output custom error message (e.g., cannot use file path argument together with sub-command)
    ... not sure what kind of error output you desire here; to make this look like System.CommandLine error output will require additional work
}
else
{
    //
    // When help is invoked on any sub-command, hide the root argument for the help output
    //
    if (parseResult.Tokens.Count > 0 && parseResult.Tokens[0].Type == TokenType.Command)
    {
        rootArg.IsHidden = true;
    }

    parseResult.Invoke();
}
```
I wrote this brief code example in a way that the different concerns (invalid root command argument + sub-command combination; help output) are dealt with separately, making it (hopefully) easy to follow. It assumes that the root command has not other arguments or options except the one for the file path to open. I hope this can serve as a starting point for a more fleshed out solution.

**Comment by paralaxsd** [comment]
Ah perfect, thanks for that snippet!
For various reasons my parser uses a custom middleware that's run with higher priority than the one for `--help` and comes with its own handler. Integrating parts of your approach into my `CommandLineService` class I arrive at a solution that works for my scenario:

```cs
public void AddArgument<TType>(Argument<TType> argument, Action<TType> handler, bool isGlobal = true)
{
    _rootCommand.AddArgument(argument);

    _globalMiddleWareHandler += ctxt =>
    {
        var appliesToRootCmd = ctxt.ParseResult.CommandResult.Command == _rootCommand;

        if(appliesToRootCmd || isGlobal)
        {
            var argRes = ctxt.ParseResult.FindResultFor(argument);
            if (argRes is { })
            {
                var argVal = ctxt.ParseResult.GetValueForArgument(argument);
                handler(argVal);
            }
        }
        else
        {
            argument.IsHidden = true;
        }
    };
}
```
