### ISSUE TITLE
Only return suggestions for options after prefix is specified

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/command-line-api#19]
Given command: `Dosomething.exe move --x 5 --y 42`
The input `dosomething move ` would return suggestions for `--x` and `--y`.  However, (seemingly) many tools don't provide suggestions until after the prefix is specified (see posh-git and powershell).

Questions:
[ ] What should the default behavior be?
[ ] Should we support both scenarios (if yes create issue)?

**Comment by jonsequitur** [comment]
I think this issue becomes moot after support is added for #351. @MarkMichaelis?
