### ISSUE TITLE
Consider adding a general capability, independent of current invocation concepts, to align shutdown handling with standard cancellation APIs. (For example, should `CancellationToken` support be available in `async Main`?)

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#1921]

**Comment by jonsequitur** [comment]
Apologies for the absence of a description on this issue. I think the issue might be outside the scope of System.CommandLine but the concept of adding `CancellationToken` support to `Main` might be worth a new issue in dotnet/runtime.

@adamsitnik Thoughts on this?

**Comment by tmds** [comment]
I always liked the idea of having a `CancellationToken` for `Main`. It was something that also came up when we were discussing the `PosixSignal` API. See https://github.com/dotnet/runtime/issues/50527#issuecomment-812676464 and following comments.

You can easily implement it yourself using the `PosixSignal` API.

cc @davidfowl
