### ISSUE TITLE
Allow joining the aliases

### ISSUE THREAD

**Issue by am11** [dotnet/command-line-api#1955]
In most Unix utilities, joining the alias is very common:
```sh
$ git clean -x -d -f
# is same as
$ git clean -xdf
```

similarly `tar -cz`, `rm -rf`, `docker run -it` etc. Note that in joined form, the last argument may (or may not) accept the value (e.g. `tar -czf filename.tar.gz <paths>`).

Granted that System.CommandLine does not enforce single letter alias followed by a single hyphen (`dotnet new -lang` in one of the anomaly in officially supported args), it would still be nice to support joining aliases when consumer's code doesn't have such anomaly.

Proposal: add a POSIX mode `.UsePosixMode()`, such that if enabled, the library will validate that all aliases are conforming to [guidelines](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html), and will allow joining the aliases.

Another thing which POSIX mode could enable is allowing no whitespace between alias and its value:

```sh
$ tar -xf file -C/tmp
# is same as
$ tar -xf file -C /tmp
```

similarly, `docker run -v$HOME/projects/dotnet-sdk:/sdk` etc.

**Comment by jonsequitur** [comment]
This works by default today unless explicitly disabled. One requirement is that all of the unbundled aliases must be valid on their own.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/547415/200919103-60f5e5b4-5c46-42e7-8fe9-fa4224b0ebf3.png">

**Comment by am11** [comment]
Ah thanks! Yup, v2 is working as expected. For some reason, I was testing with `0.1.0-e170320-1` (https://github.com/dotnet/jitutils/blob/27574461a859d362e499f3b2c5eaffacbe74e3aa/src/jit-include.props#L4). 😅
