### ISSUE TITLE
Options do not get processed before the next subcommand

### ISSUE THREAD

**Issue by rcdailey** [dotnet/command-line-api#1961]
Complete example is at the bottom. When I run this:

```
.\ConsoleApp1.exe --debug subcommand1
```

I get output:

```
Arg1: none
```

What I expect:

```
Debug: false
Arg1: none
```

Is this a bug or am I misunderstanding something?

```cs
// Project name is ConsoleApp1
public static class Program
{
    public static async Task<int> Main(string[] args)
    {
        var root = new RootCommand();

        // -------------------
        var opt = new Option<bool>("--debug")
        {
            Arity = ArgumentArity.Zero
        };
        root.AddOption(opt);
        root.SetHandler((bool debug) =>
        {
            Console.WriteLine($"Debug: {debug}");
        }, opt);

        // -------------------
        var subcommand1 = new Command("subcommand1");
        var opt1 = new Option<string?>("--arg1")
        {
            Arity = ArgumentArity.ExactlyOne
        };
        subcommand1.AddOption(opt1);
        subcommand1.SetHandler((string? arg1) =>
        {
            Console.WriteLine($"Arg1: {arg1 ?? "none"}");
        }, opt1);

        // -------------------
        var subcommand2 = new Command("subcommand2");
        var opt2 = new Option<string?>("--arg2")
        {
            Arity = ArgumentArity.ExactlyOne
        };
        subcommand2.AddOption(opt2);
        subcommand2.SetHandler((string? arg2) =>
        {
            Console.WriteLine($"Arg2: {arg2}");
        }, opt2);

        // -------------------
        subcommand1.AddCommand(subcommand2);
        root.AddCommand(subcommand1);
        return await root.InvokeAsync(args);
    }
}
```

**Comment by jonsequitur** [comment]
This is expected. Only one command handler is invoked. In your example command line, that's the handler for `subcommand1`. To see the parsed value for `--debug`, change this:


```c#
        subcommand1.SetHandler((string? arg1) =>
        {
            Console.WriteLine($"Arg1: {arg1 ?? "none"}");
        }, opt1);
```

to this:


```c#
        subcommand1.SetHandler((string? arg1, bool debug /* <-- add a parameter here*/) =>
        {
            Console.WriteLine($"Arg1: {arg1 ?? "none"}");
            Console.WriteLine($"Debug: {debug}");
        }, opt1, opt /* <--  pass your debug option here */);
```

**Comment by rcdailey** [comment]
> This is expected. Only one command handler is invoked. In your example command line, that's the handler for `subcommand1`. To see the parsed value for `--debug`, change this:
> 
> ```cs
>         subcommand1.SetHandler((string? arg1) =>
>         {
>             Console.WriteLine($"Arg1: {arg1 ?? "none"}");
>         }, opt1);
> ```
> 
> to this:
> 
> ```cs
>         subcommand1.SetHandler((string? arg1, bool debug /* <-- add a parameter here*/) =>
>         {
>             Console.WriteLine($"Arg1: {arg1 ?? "none"}");
>             Console.WriteLine($"Debug: {debug}");
>         }, opt1, opt /* <--  pass your debug option here */);
> ```

Isn't that effectively adding a global option? Is my UX weird? Because I remember seeing cli apps that accept options to the left of verbs. You're forcing options to the right in this solution.

Feels like I'm trying to do something unusual, but I don't know what is "standard".

**Comment by jonsequitur** [comment]
The left versus right placement of the option is something you can control. This isn't done via the handler API but in your parser setup.

You can make the option valid 

```csharp
var debugOption = new Option<bool>("--debug");

var command = new RootCommand
{
    debugOption, // <-- This makes the option valid before the subcommand, e.g. myapp --debug subcommand
    new Command("subcommand")
    {
        debugOption // <-- This makes the option valid after the subcommand, e.g. myapp subcommand --debug 
    }
};
```

The handler setup is the same. In effect, `ParseResult.GetValueForOption(debugOption)` will work regardless of which order the end user specified the option in.
