### ISSUE TITLE
Option with `ArgumentArity.ZeroOrMore` only returns first argument 

### ISSUE THREAD

**Issue by BobSilent** [dotnet/command-line-api#1967]
Trying to define an Option with a list arguments:
```csharp
        var o = new Option<List<string>>($"--Option1")
        {
            Arity = ArgumentArity.ZeroOrMore
        };

        var r1 = o.Parse($"--Option1 str1 str2 ");
        var v1 = r1.GetValueForOption(o);
```
I would expect to get a string list with 2 values for `v1`, 

unfortunately I only get a list with one value `str1` and a parsing error `Unrecognized command or argument 'str2'.`

This is working as expected:
```csharp
        var a = new Argument<List<string>>() { Arity = ArgumentArity.ZeroOrMore };

        var r2 = a.Parse($"str1 str2 ");
        var v2 = r2.GetValueForArgument(a);
```

![image](https://user-images.githubusercontent.com/13506173/201971229-a626958e-e550-49c4-8f98-0a8914d3a609.png)

**Comment by elgonzo** [comment]
By default, only one value per token (option) is allowed. To pass multiple values for an option, you would then do this:
```
myApp --Option1 str1 --Option1 str2
```
If you prefer a single option token consuming multiple values like `myApp --Option1 str1 str2`, you would need to set the option's [`AllowMultipleArgumentsPerToken`](https://learn.microsoft.com/en-us/dotnet/api/system.commandline.option.allowmultipleargumentspertoken#system-commandline-option-allowmultipleargumentspertoken) property to _true_, like:
```
 var a = new Argument<List<string>>() { Arity = ArgumentArity.ZeroOrMore,  AllowMultipleArgumentsPerToken = true};
 ```

**Comment by BobSilent** [comment]
@elgonzo  thanks for clarification, thats working (i think in a previous - maybe beta - it was different)

The only thing is, it is a bit confusing, as I set an `Arity` on an option - okay this means the how many times I can specify the option, but the enum type is named `ArgumentArity` thats where my confusion comes from.

Just one additional question, the Option Arity behaves differently (screenshot `o0`) when only setting `AllowMultipleArgumentsPerToken = true` (see screenshot `o1`) without setting `Arity`, is this intended?

![image](https://user-images.githubusercontent.com/13506173/202127783-8b05b7bb-f961-4d64-bcb5-e820f5f397fc.png)

**Comment by elgonzo** [comment]
About a little more than a year ago, the default value for _AllowMultipleArgumentsPerToken_ was changed from true to false. See here for the related discussion: https://github.com/dotnet/command-line-api/issues/1199

The results for the _o0_ and _o1_ options in your debugger screenshot make sense, as the default arity for List\<T\> value types is _OneOrMore_ (i haven't found any documentation that explains this completely, just a sentence that is giving an example regarding two value types here: https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax#argument-arity). 

But the 3rd, using _o2_, the parse result does not look right to me. As you explicitly set the arity to be _ZeroOrOne_, only str1 should be the only value token assigned to --Option1. It seems that unrelated to _AllowMultipleArgumentsPerToken_ , System.CommandLine currently has trouble with collection-type options with an arity whose ArgumentArity.MaximumNumberOfValues is being 1. I just went ahead and (re)posted this as its own issue report: https://github.com/dotnet/command-line-api/issues/1970

**Comment by BobSilent** [comment]
Thanks a lot for your explanation!

**Comment by elgonzo** [comment]
Oh, by the way, i made a little mistake when reading your code there in your screenshot. Regardless of System.CommandLine currently having an issue with collection-type options and arities with ArgumentArity.MaximumNumberOfValues being 1, the parsing of your _o2_ option should still fail anyhow (with a meaningful error, of course).

Because your commandline is `--Option1 str1 str2 --Option1 str3`. _AllowMultipleArgumentsPerToken_ would only have an effect on how the "str2" token would be interpreted. But regardless of the _AllowMultipleArgumentsPerToken_ setting, that commandline specifies at least two values for --Option1 ("str1" and "str3"), which ArgumentArity.ZeroOrOne will not allow to pass. My apologies for not correctly reading your actual command line string earlier...
