### ISSUE TITLE
dotnet-suggest not available for .net 7

### ISSUE THREAD

**Issue by petersladek** [dotnet/command-line-api#2014]
dotnet-suggest global tool is not available for .net 7 target framework.

**Comment by dim5** [comment]
@baronfel is there something blocking a .net 7 release? Can I contribute somehow?

**Comment by baronfel** [comment]
@jonsequitur got any input on that^? I'm not sure which option (or some third option?) the team thinks is best.

**Comment by jonsequitur** [comment]
This is now updated to target .NET 7.
