### ISSUE TITLE
If Argument.HelpName was set, HelpBuilder.Default calls GetCompletions but ignores the result

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/command-line-api#2038]
HelpBuilder.Default.GetArgumentUsageLabel(Argument argument) calls `argument.GetCompletions()` unless `argument.ValueType` is `bool` nor `bool?`. However, if `argument.HelpName` is a non-empty string, then GetArgumentUsageLabel ignores the result of GetCompletions. In that situation, it would be better if GetArgumentUsageLabel skipped the GetCompletions call. Doing so would improve performance if the application has slow completion sources.

<https://github.com/dotnet/command-line-api/blob/6524142f1398ed78eadfb9b802ba6492c6af63c4/src/System.CommandLine/Help/HelpBuilder.Default.cs#L66-L92>

This scenario was not optimized in <https://github.com/dotnet/command-line-api/pull/1367> when HelpBuilder was changed to display Argument.HelpName.

Fixing this might solve <https://github.com/dotnet/sdk/issues/27374>, in which .NET SDK uses a completion callback that ends up resolving MSBuild SDKs from NuGet, even though the completions won't be displayed in help. Such a slow completion callback could still be intolerable in `dotnet-suggest`, though.

**Comment by jonsequitur** [comment]
Under proposal #2071, another approach for turning off completions in help output that would be more explicit might look like this:

```csharp
switch (parseResult.Action)
{
    case HelpAction helpAction:

        helpAction.UseCompletionsAsExamples = false;
        await helpAction.RunAsync();

        break;

    //...
}
```

Thoughts?

**Comment by jonsequitur** [comment]
That's true. Does the existing implementation seem intuitive enough? Would deeper help configuration on the symbol objects themselves be more intuitive?
