### ISSUE TITLE
Introduce Directive symbol type

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/command-line-api#2056]
From #2046:

Currently the only way for the users to implement custom directives is enabling directives parsing in the config, using this property to get parsed output:

https://github.com/dotnet/command-line-api/blob/76437b04511d88543df5cde2c7910e8d40e30888/src/System.CommandLine/ParseResult.cs#L86

and provide a custom, expensive Middleware.

We need to introduce a dedicated `Directive` type that derives from `Symbol`.

Initial requirements:

- [ ] introducing new `Directive` symbol type, with a possibility to define an `Action<ParseResult, string>` which should be executed when directive is parsed (the list of arguments for the action is an open question, when implementing the feature it should became more obvious)
- [ ] introducing `Command.Directives` property to allow users for defining directives
- [ ] turning existing code into new directives https://github.com/dotnet/command-line-api/blob/76437b04511d88543df5cde2c7910e8d40e30888/src/System.CommandLine/Parsing/ParseOperation.cs#L350-L378
- [ ] extending tokenization and parsing with the concept of Directive

**Comment by adamsitnik** [comment]
> If a subcommand defines directives, then do users still place those directives at the start of the command line, or after the name of the subcommand?

They will still be supported only at the start. The problem with config is that it does not belong to symbol tree. But `RootCommand` does, so perhaps it should be allowed only for `RootCommand`?

**Comment by adamsitnik** [comment]
#2059 was supposed to close #2058, not this usse

**Comment by jonsequitur** [comment]
> But RootCommand does, so perhaps it should be allowed only for RootCommand?

I think this is important.

We explicitly decided not to support directives anywhere on the command line after the first occurrence of a non-directive token.

**Comment by adamsitnik** [comment]
> Because directives don't appear in help

I believe that we should change that, otherwise how users are going to find out about their existence and capabilities?

**Comment by jonsequitur** [comment]
I think most end users will not care about directives (e.g. `[suggest]` is intended to be called from tooling, not directly by users) and many CLI authors won't want them in their help output. Maybe this is a use case for `--help verbose` or something similar.

**Comment by jonsequitur** [comment]
> I feel that directives should not be specific to a command, not even to a RootCommand. Command-specific stuff should be options instead.

Agreed. The idea of hanging directives off of `RootCommand` is related to a discussion about whether `RootCommand` needs to exist at all, beyond just being the root object in the symbol tree. But in terms of the CLI syntax, directives are intended to be "app-level" concepts, and they can only occur before all other tokens. This is why in terms of the parser's structure, it makes sense to only allow this symbol type to be added at the root.
