### ISSUE TITLE
Update .editorconfig with for .NETCore version

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/command-line-api#208]
Currently, the .editorconfig is missing
- [ ] "Use expression body for ..." 
- [ ] Use camelCase for parameter names

We should find the "standard" .editorconfig file for .NETCore and use that.

**Comment by marcusturewicz** [comment]
Would the editorconfig from dotnet/runtime suffice?

https://github.com/dotnet/runtime/blob/master/.editorconfig
