### ISSUE TITLE
New Config proposal

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/command-line-api#2101]
One of our goals is simplyfing the configuration, making it easier to discover and use.

This can be achieved by making the configuration mutable (no need for a dedicated builder) and making it an optional argument for `Command.Parse` (this has already happened).

My current idea is following:

```cs
public class CliConfiguration
{
    public CliConfiguration(Command command)
    {
        Command = command;
        Directives = new()
        {
            new SuggestDirective()
            // I am not sure whether we should enable other Directives by default
            // new EnvironmentVariablesDirective()
            // new ParseDirective()
        };
    }

    public Command Command { get; }

    public bool EnablePosixBundling { get; set; } = true;

    public bool EnableDefaultExceptionHandler {  get; set; } = true;

    public bool EnableTypoCorrections { get; set; } = false;

    public TimeSpan? ProcessTerminationTimeout { get; set; } = TimeSpan.FromSeconds(2);

    public int ParseErrorExitCode { get; set; } = 1;

    public TryReplaceToken? ResponseFileTokenReplacer { get; set; } = StringExtensions.TryReadResponseFile;

    public List<Directive> Directives { get; }
}
```

How to disable signaling and handling of process termination via a `CancellationToken`? Set `ProcessTerminationTimeout` to `null`.

How to disable default response file token replacer? Set `ResponseFileTokenReplacer` to `null`.

How to customize exception handler? Set `EnableDefaultExceptionHandler` to `false` and catch the exceptions on your own:

```cs
CliConfiguration config = new(command) { EnableDefaultExceptionHandler = false };
ParseResult parseResult = command.Parse(args, config);

try
{
    return parseResult.Invoke();
}
catch (Exception ex)
{
    // custom exception handler
}
```

The alternative for customizing the `ParseErrorExitCode` is following:

```cs
ParseResult parseResult = command.Parse(args);

if (parseResult.Errors.Any())
{
    return $customValue;
}
```

The most tricky part is how `HelpOption` and `VersionOption` should be enabled and disabled. Currently, the config builder just adds them to the provided `Command` options list:

https://github.com/dotnet/command-line-api/blob/3b5c4beb3e3d09702ba7d05b098f3594759188fd/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L336-L351

I don't like it, as it's a side effect. But on the other hand, I don't have an ideal alternative.

Possible solutions:

## Expect the users to add them in explicit way.

```cs
command.Options.Add(new HelpOption());
command.Options.Add(new VersionOption());
```

Advantage(s): no magic, everything is crystal clear, perf.
Disadvantage(s): help would be not enabled by default.

## Create every command with Help and Version options added by default

```cs
public Command(string name, bool addDefaultOptions = true)
{
    if (addDefaultOptions)
    {
        Options.Add(new HelpOption());
        Options.Add(new VersionOption());
    }
}
```

Advantage(s): help enabled by default.
Disadvantage(s): Hard to customize help (find, cast & customize or replace) I expect that `Version` makes sense only for the root command, it would pollute subcommands.

Perhaps it would make more sense for `RootCommand`?
Maybe the argument should not be optional, so everyone who creates a Command would need to think about it?

## Expose the options as part of Config type, add them the root Command when parsing

```cs
public class CliConfiguration
{
    public HelpOption? HelpOption { get; set; } = new ();
    
    public VersionOption? VersionOption { get; set; } = new ();
}
```

Advantage(s): quite easy to discover and configure, enabled by default.
Disadvantage(s): side effect of adding them to the root command (but so far nobody complained about it beside me?)

Do we really need `VersionOption` enabled by default?

## Add a list of default Options to Config, similarly to Directives

```cs
public class CliConfiguration
{
    public List<Option> Options { get; }
}
```

Advantage(s): quite easy to discover, consistent with Directives
Disadvantage(s): hard to configure a specific option (find HelpOption, cast it and then set the builder), side effect of adding them to the root command 

@jonsequitur @KathleenDollard @Keboo @KalleOlaviNiemitalo please provide feedback

**Comment by adamsitnik** [comment]
With the regards to `IConsole`, we should IMO extend the config in following way:

```cs
public class CliConfiguration
{
    /// <summary>
    /// The standard output.
    /// </summary>
    public TextWriter Out { get; } = Console.Out;

    /// <summary>
    /// The standard error.
    /// </summary>
    public TextWriter Error { get; } = Console.Error;
}
```

this would allow us to still test the apps without introducing new abstraction to BCL and remove the last property from `InvocationContext` (to replace `InvocationContext` with `ParseResult` everywhere)

**Comment by adamsitnik** [comment]
Feedback from @KalleOlaviNiemitalo https://github.com/dotnet/command-line-api/pull/2103#discussion_r1140957348

**Comment by tmds** [comment]
Will the library provide something that combines `CliConfiguration` with a `RootCommand` in a single object, so a `Main` method could look like:

```cs
var commandLine = CreateAppCommandLine();
return await commandLine.InvokeAsync(args);
```

**Comment by jonsequitur** [comment]
> Yeah I don't like Command.Parse having side effects on Command.Options. 

Agreed. While the symbol types are mutable because it makes the API easier to use, System.CommandLine itself should not mutate them indirectly. This is why the implicit parser used by `Command.Parse` was both an internal implementation detail and a code smell.

**Comment by jonsequitur** [comment]
> Will the library provide something that combines CliConfiguration with a RootCommand in a single object, so a Main method could look like:

I think `CommandLineConfiguration` is that type (since it carries a reference to a `RootCommand`), although maybe the name makes that unclear.

**Comment by tmds** [comment]
> I think CommandLineConfiguration is that type (since it carries a reference to a RootCommand), although maybe the name makes that unclear.

Yes, the name is appropriate for something that holds configuration settings. Not for something that is invoked on.

**Comment by jonsequitur** [comment]
> Not sure what should happen if the same token strings are in both.

Overriding global options' aliases on specific subcommands has always been supported, so this should work fine.

> Command.AddStandardOptions() which applications would call explicitly if they want --help and --version.

We've tried to make sure that end users get a good CLI experience by default, so I would worry this would lead to a proliferation of command line tools without help support.

**Comment by adamsitnik** [comment]
An alternative solution that we have just discussed offline with @jonsequitur is extending `RootCommand` with all the configuration properties (things like Directives make sense only on root command level). We are going to give it a try and get back with our findings.

**Comment by adamsitnik** [comment]
I took one more look at it, here are my thoughts:

Feels natural for `RootCommand`:

```cs
public List<Directive> Directives { get; }
```

Is related to parsing, in theory could be customized per `Command` (moved even to `Command`):

```cs
public bool EnablePosixBundling { get; set; } = true;
public bool EnableParseErrorReporting { get; set; } = true;
public bool EnableTypoCorrections { get; set; } = false;
public TryReplaceToken? ResponseFileTokenReplacer { get; set; } = StringExtensions.TryReadResponseFile;
```

Is related to execution and is required to be configurable for scenarios where `RootCommand` is not used:
            
```cs
public bool EnableDefaultExceptionHandler { get; set; } = true;
public TimeSpan? ProcessTerminationTimeout { get; set; } = TimeSpan.FromSeconds(2);
public TextWriter Output { get; set; } = Console.Out;
public TextWriter Error { get; set; } = Console.Error;
```


@jonsequitur I lean towards keeping `CliConfig`, making it mutable and exposing `Help` and `Version` as two properties:

```cs
public class CliConfiguration
{
// parsing 
    public bool EnablePosixBundling { get; set; } = true;
    
    public bool EnableParseErrorReporting { get; set; } = true;

    public bool EnableTypoCorrections { get; set; } = false;
    
    public TryReplaceToken? ResponseFileTokenReplacer { get; set; } = StringExtensions.TryReadResponseFile;

// symbols
    public List<Directive> Directives { get; }

    public HelpOption? HelpOption { get; set; } = new ();
    
    public VersionOption? VersionOption { get; set; } = new ();
    
// execution
    public bool EnableDefaultExceptionHandler { get; set; } = true;
    
    public TimeSpan? ProcessTerminationTimeout { get; set; } = TimeSpan.FromSeconds(2);

    public TextWriter Output { get; set; } = Console.Out;

    public TextWriter Error { get; set; } = Console.Error;
}
```
