### ISSUE TITLE
Uncaught AggregateException when CancelOnProcessTermination

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#2112]
The `ProcessTerminationHandler` is waiting with a timeout for the handler task to complete here:

https://github.com/dotnet/command-line-api/blob/02a776b901846b96cc2a7442b2032102944cafa9/src/System.CommandLine/Invocation/ProcessTerminationHandler.cs#L85

It's currently not handling the case where the handler completed with an exception.
When that happens, the `Wait` method throws `AggregateException`.
That exception should be caught and ignored.

cc @adamsitnik

**Comment by adamsitnik** [comment]
@tmds great catch, would you like to send a PR with a fix?
