### ISSUE TITLE
Do HelpOption and VersionOption need to override Equals and GetHashCode?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/command-line-api#2118]
System.CommandLine.Help.HelpOption overrides `bool Equals(object?)` and `int GetHashCode()`:

<https://github.com/dotnet/command-line-api/blob/0403596afba9f622468d26c15a81fa17e881b1df/src/System.CommandLine/Help/HelpOption.cs#L30-L32>

Likewise System.CommandLine.Help.VersionOption:

<https://github.com/dotnet/command-line-api/blob/0403596afba9f622468d26c15a81fa17e881b1df/src/System.CommandLine/Help/VersionOption.cs#L63-L65>

Are these overrides useful? AFAICT, the library recognizes HelpOption and VersionOption by type, not by calling their `bool Equals(object?)` methods.

<https://github.com/dotnet/command-line-api/blob/0403596afba9f622468d26c15a81fa17e881b1df/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L281> <https://github.com/dotnet/command-line-api/blob/0403596afba9f622468d26c15a81fa17e881b1df/src/System.CommandLine/Parsing/ParseOperation.cs#L195> <https://github.com/dotnet/command-line-api/blob/0403596afba9f622468d26c15a81fa17e881b1df/src/System.CommandLine/Parsing/CommandResult.cs#L91>

**Comment by jonsequitur** [comment]
These are likely no longer needed.
