### ISSUE TITLE
bash completion script: suggestions should be filtered out that do not start with the word to complete

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#2143]
`dotnet-suggest` returns completions that do not start with the word to complete.

For example `p<TAB>`, can offer suggestions like:
```
pear
--project
--expose
```

For the bash completion script, in this case, we should only return suggestions that start with `p`: `pear`.

I'm not sure why `dotnet-suggest` is proposing options that do not start with `WordToComplete`? I assume it is for the UX with another shell?

If it is not desired to filter out these suggestions in `dotnet-suggest`, we can filter them out in the bash script.

**Comment by jonsequitur** [comment]
Completions use substring matching, which is intentional.

**Comment by tmds** [comment]
> which is intentional.

This is for PowerShell, I assume?

We need to filter them out for bash.

I will take a stab at improving the bash competition script next week.

**Comment by jonsequitur** [comment]
This isn't a shell-specific.

System.CommandLine uses substring matching, which has become more common than not in the IDE and editor world. Multi-word matching is also starting to become more common. These approaches help discoverability and ergonomics.

When you say they need to be filtered out for bash, do you think this falls into the category of preference or functional requirement?

**Comment by tmds** [comment]
I looked into this and there is a bigger issue.

To know what word is being completed, the script passes `COMP_POINT`. This is the index in `COMP_LINE`.

When the directive makes a suggestion for the completion, it doesn't see `COMP_LINE` but it sees the separate arguments that got parsed.

That means the index that is passed may not reflect the argument that is being completed.

For example:
```
dotnet-shift deploy --con<TAB>
```
completes using:
```
dotnet-shift --position 25 --  dotnet-shift deploy --con
```
successfully to:
```
dotnet-shift deploy --context
```

However
```
dotnet-shift              deploy --con<TAB>
```
does not.

It tries to complete using:
```
dotnet-shift --position 38 --  dotnet-shift deploy --con
```
Note the shift in position due to the additional spaces on the command.

Because the position can not be matched to the `--con` argument being completed, all options are suggested rather than completing the option name.

**Comment by tmds** [comment]
You can ignore my previous comment. It was running against a script I had modified locally.

The whole line gets passed down as a single argument. This surprises me. It means S.CL can parse full lines into their arguments with the same semantics as bash.

**Comment by jonsequitur** [comment]
> The whole line gets passed down as a single argument. 

This is because the string split that provides the `string[] args` to your .NET entry point is lossy. Without knowing how much whitespace was on the actual command line, we can't provide accurate completions that take the cursor position into account.

The method that duplicates this split behavior is available as well for you to use in unit tests: `CliParser.SplitCommandLine`.

**Comment by jonsequitur** [comment]
System.CommandLine **_can_** complete based on an array so if that's a preferable approach for bash, the shim script can be changed.

**Comment by tmds** [comment]
Oh, that is good to know. It's not needed to fix this issue, but it could be to fix others.

How does the `dotnet-suggest` invocation look like?

**Comment by tmds** [comment]
> System.CommandLine can complete based on an array so if that's a preferable approach for bash

@jonsequitur is this already exposed through the suggest directive?
