### ISSUE TITLE
Port existing dotnet org applications to latest version of System.CommandLine

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/command-line-api#2146]
- [x] dotnet/runtime: https://github.com/dotnet/runtime/pull/84229 (@am11)
- [x] dotnet/sdk: https://github.com/dotnet/sdk/pull/33157 (@adamsitnik)
- [x] dotnet/templating: https://github.com/dotnet/templating/pull/6340 (@adamsitnik)
- [x] dotnet/format: https://github.com/dotnet/format/pull/1826
- [x] roslyn: https://github.com/dotnet/roslyn/pull/68549 

@KathleenDollard @baronfel @jonsequitur have I missed any?

**Comment by am11** [comment]
I believe https://github.com/dotnet/format also uses `SystemCommandLine` and takes part in coherency updates.

**Comment by adamsitnik** [comment]
@am11 would you be interested in updating it too? I am currently working on the SDK update

**Comment by adamsitnik** [comment]
runtime, SDK, roslyn, templating and format have been updated. Closing 

@am11 again, thank you for your help!
