### ISSUE TITLE
Unable handling termination on `ctrl+c`

### ISSUE THREAD

**Issue by rubo** [dotnet/command-line-api#2151]
With the latest breaking changes, I can no longer handle the program termination gracefully. `ctrl+c` terminates immediately, making the cancellation token useless.

For instance, it doesn't enter the `catch` block on `ctrl+c`:

```csharp
rootCommand.SetAction(async (pr, ct) =>
{
    try
    {
        await Task.Delay(Timeout.InfiniteTimeSpan, ct);
    }
    catch (Exception ex)
    {
        return 1;
    }
    
    return 0;
});
```

`ProcessTerminationTimeout` is set to `Timeout.InfiniteTimeSpan`.

- Version: 2.0.0-beta4.23203.1
- OS: Windows

**Comment by jonsequitur** [comment]
What OS are you seeing this on?

**Comment by rubo** [comment]
> What OS are you seeing this on?

On Windows, as mentioned above.
