### ISSUE TITLE
Command Options which support an array are now broken in beta4

### ISSUE THREAD

**Issue by calloncampbell** [dotnet/command-line-api#2153]
I have an app which was on beta1 and has a command which takes in options for an int[] array. When I upgraded to beta4, I had to include the Arity attribute and when I ran it, I got a runtime error that it couldn't parse the second int.

Example: 
myapp.exe process-jobs --ids 1 2 3 4 5

**Comment by elgonzo** [comment]
A _lot_ has changed between beta1 and beta4, among them the default for `AllowMultipleArgumentsPerToken` being changed from _true_ to _false_ (see related discussion here: https://github.com/dotnet/command-line-api/issues/1162#issuecomment-771345612)
 
Therefore, if you want the CLI to support a syntax like `--ids 1 2 3 4 5`, you'll need to explicitly set the _AllowMultipleArgumentsPerToken_ property of the respective options (like the one for --ids) to _true_.

**Comment by calloncampbell** [comment]
Thank you, I added the missing AllowMultipleArgumentsPerToken = true and now it works.
