### ISSUE TITLE
Argument values go back to their type's default value when `PublishTrimmed` is enabled

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/command-line-api#2199]
When `PublishTrimmed` is set to `false` everything works as expected, but when it's set to `true`, the command arguments return their type's default value (e.g, an argument with type `int`  returns `0`);

```
public class MyCommand : Command
{
    public MyCommand() : base("hello", "abcd")
    {
        AddOption(new Option<string>(
            aliases: new string[] { "-n", "--name" },
            description: "Your name.",
            getDefaultValue: () => "John"
        ));
		
        Handler = CommandHandler.Create(async (string name) =>
        {
            Console.WriteLine(name ?? "empty");
        });
    }
}

myapp.exe hello -n Alex    -> prints `empty`
myapp.exe hello            -> prints `empty`
```

**Comment by dehghani-mehdi** [comment]
> I would guess that when you build your example code, there are some warnings about this.

Yes, and now I realized I have the same situation about `System.Text.Json` too.

> Give Command.SetHandler a try instead.

Using `Command.SetHandler` fixed the problem.

Could you verify that I converted my code correctly, please?

_before_
```
public class NewCommand : Command
{
    public NewCommand() : base("new", "Create new website.")
    {
        AddOption(new Option<string>(
            aliases: new string[] { "-n", "--name" },
            description: "Your website name.",
            getDefaultValue: () => "new_website"
        ));
        
        Handler = CommandHandler.Create(async (string name) => await createWebsiteAsync(name));
    }
}
```

_after_
```
public class NewCommand : Command
{
    public NewCommand() : base("new", "Create new website.")
    {
        var option = new Option<string>(
            aliases: new string[] { "-n", "--name" },
            description: "Your website name.",
            getDefaultValue: () => "new_website"
        );
        
        AddOption(option);
        
        var action = async (string name) => await createWebsiteAsync(name);        
        
        SetHandler(action, option);
    }
}
```

I'm not sure why I have to pass `option` to `SetHandler`;

**Comment by jonsequitur** [comment]
That looks correct.

> I'm not sure why I have to pass option to SetHandler. and for multiple options, I have to pass them all to SetHandler?

This is because we removed the name-based lookups. The next preview release brings back a new API for name-based lookups but it's not inferred from the parameter name as it is with `NamingConventionBinder`.
