### ISSUE TITLE
Why dont have an AddOptions method that accepts an array?

### ISSUE THREAD

**Issue by causticsudo** [dotnet/command-line-api#2200]
Suddenly, I chose to do this:

```csharp
public class Foo : Command
{
    private const string CommandName = "bar";

    public Foo() : base(CommandName)
    {     
        AddOptions(new Option[]
        {
            new Option<string>("xpto1"),
            new Option<string>("xpto2"),
            new Option<string>("xpto3"),
            new Option<string>("xpto4"),
            new Option<string>("xpto5"),
        });
    }
}
```

Instead of doing this:

```csharp
public class Foo : Command
{
    private const string CommandName = "bar";

    public Foo() : base(CommandName)
    {     
        AddOption(new Option<string>("xpto1"));
        AddOption(new Option<string>("xpto2"));
        AddOption(new Option<string>("xpto3"));
        AddOption(new Option<string>("xpto4"));
        AddOption(new Option<string>("xpto5"));
    }
}
```

I didn't understand why this wasn't possible, probably because there is another more efficient feature that I didn't identify 😄, or maybe there is a more correct way to do it that I'm not aware of.

I would really like to be able to use a feature like this:

```csharp
        private void AddOptions(Option[] options)
        {
            foreach (var option in options)
            {
                AddOption(option);
            }
        }
```

**Comment by jonsequitur** [comment]
It's not a matter of correctness. We have a general goal of keeping the API surface area as small as possible so simple convenience methods like this tend to be left out.

You can define an extension method for this pretty easily. Having it accept `Symbol[]` instead of `Option[]` will let you add in child `Command` and `Argument` objects in the same call.

**Comment by causticsudo** [comment]
Alright, it makes sense! It's also not a problem to have an extension class responsible for this behavior, in fact, that's what I did. The main purpose was to understand the motivation.
