### ISSUE TITLE
ParseErrorResult creates a new HelpAction for ShowHelp

### ISSUE THREAD

**Issue by seanadams9** [dotnet/command-line-api#2226]
If you have a created a custom help action for your commands and there is a parse error then the if creates a new HelpAction with the default HelpBuilder.

Wondering if this shouldn't be changed to look for the HelpOption on the command and call that Action instead?

**Comment by marcpopMSFT** [comment]
@jonsequitur what is the timeframe for 2.0 GA?  This is blocking the above linked command line codeflow as it breaks a test (and breaks how our help works when there are errors). We just need to know how to proceed here (unblock the test while this gets fixed or wait)

**Comment by jonsequitur** [comment]
I'm working on a fix, which is pretty straightforward. I'll PR it today.
