### ISSUE TITLE
Response file syntax is not recognized

### ISSUE THREAD

**Issue by DirkDeclercq** [dotnet/command-line-api#2235]
When I execute the following command for my cmd-line applicatin missionscript

`dotnet missionscript @myrespons1.rsp`

I received the following error :

`The splatting operator '@' cannot be used to reference variables in an expression. '@myresponse1' can be used only as an argument to a command. To reference variables in an
     | expression use '$myresponse1'.
`

Any clue what is going on ?

**Comment by elgonzo** [comment]
That looks to me like a Powershell error message, not something coming from the System.CommandLine library.

Note that `@` is a meta-character in Powershell, and you need to escape it appropriately to pass it to your missionscript. See also https://stackoverflow.com/questions/59805670/supplying-an-input-file-via-gives-an-error-the-splatting-operator-canno

**Comment by DirkDeclercq** [comment]
Thx.
Escaping like described in the Stackoverflow article solved it.
