### ISSUE TITLE
Make it easier to use cancellation tokens

### ISSUE THREAD

**Issue by KeithHenry** [dotnet/command-line-api#2271]
The various `SetHandler` overloads are great for hooking up simple actions.

However, if you need a cancellation token none of these are available and you have to use:

```c#
command.SetHandler(
    async context => 
        await MyMethod(
            context.ParseResult.GetValueForArgument(anArgument)), 
            context.ParseResult.GetValueForOption(anOption),
            context.GetCancellationToken()));
```

Which feels very clunky compared to the methods without the need for cancellation. 

Please could we add:

```c#
command.SetCancellableHandler(
    async (arg, opt, token) => 
        await MyMethod(
            arg, 
            opt,
            token), 
    anArgument, 
    anOption);

// or even
command.SetCancellableHandler(
    MyMethod, 
    anArgument, 
    anOption);

```

I realise this could be done with extension methods, but they wouldn't have access to the internal `GetValueForHandlerParameter` that the overloads of `SetHandler` do.

**Comment by KeithHenry** [comment]
@KalleOlaviNiemitalo thanks, so this is already done - #2044 back in Feb 2023 it seems.

Why is the NuGet beta package from May 2022 so far behind?

**Comment by KeithHenry** [comment]
@KalleOlaviNiemitalo thanks for the information - it does look rather stalled and dying on the vine :-(

Still, this issue isn't needed given there is already a fix in a future candidate branch. Thanks for your help.

**Comment by baronfel** [comment]
Don't worry, this library is supported. We're trying to tackle all of the issues raised by the .NET Runtime team in API review before releasing a new beta - it's unfair to ask the community to continually absorb API surface area changes so we've been holding off until the review process is complete.

If individual users would like to use the daily builds, the README has instructions on how to [use the daily builds](https://github.com/dotnet/command-line-api#daily-builds), it's a matter of adding a NuGet source to a NuGet.config file - note that this will open you up to API changes when you update packages, however. We've been doing this in the `dotnet` CLI with auto-updates, so we're accepting that churn to get the latest features and fixes ahead of a stable release.

**Comment by KeithHenry** [comment]
@baronfel That seems a good long term goal to get to a 2.0 release candidate (or 3.0 if breaking?)

It's been more than a year, and may be more than a year to finish it. In the meantime there's nothing between the custom NuGet host nightly (which is honestly a bit too beta for us) and the stale [NuGet.org](https://www.nuget.org/packages/System.CommandLine) package from 2022.

Any chance of a new (beta 5) package with the _many_ enhancements/fixes since last year, in the full knowledge that it isn't final and the project is _still_ working towards that #1891 aspirational goal in the long term?
