### ISSUE TITLE
[Question] I would like to do addoption according to the argument value.

### ISSUE THREAD

**Issue by lanopk** [dotnet/command-line-api#2280]
Hello.

I want the option to change depending on the argument value.

Each item has a folder or file attribute and a unique key value.
I would also like to have many different options depending on the folder or file.

```
//Add folder
./mycli add folder --foldername=aaa --folderdesc=bbb --folderinfo=detailfolderinfo
--> folder key generated: 1234

//Add file
./mycli add file --filename=aaa --filedesc=bbb --fileinfo=detailfileinfo
--> file key generated : 2345

//Change folder properties
./mycli change 1234 --folderinfo=newdetailinfo

//Change file properties
./mycli change 2345 --fileinfo=newdetailinfo
```

I would like to change the option items depending on the key value that is the argument in the change command.

After analyzing the key value, I want to get the type (folder/file) according to the key from the db and call AddOption according to the type.

When I call AddOption using AddValidater, the help output works fine, but when I specify the actual option, an error occurs saying that the option does not exist.

From this, it appears that parsing occurs first and validation occurs later.

Of course, I can explicitly specify the folder or file when using the change command, but since there are cases where it is specified differently from the actual key attribute, I would like to process it only with the key value.

It would be nice if there was an onPrepare function and a function to addOption when preparing.

Any little help would be appreciated.

**Comment by elgonzo** [comment]
I am just a user and not related to nor involved with the System.Commandline project.

> Of course, I can explicitly specify the folder or file when using the change command

Doing this would be much easier in my frank opinion. Easier for the user to understand how to use your CLI correctly, and easier for your program to verify correctness (or incorrectness, if you will) of the given CLI options and arguments.

> but since there are cases where it is specified differently from the actual key attribute, I would like to process it only with the key value.

I don't understand what you mean by saying that, and therefore i don't understand  how this concern would relate to not wanting or not being able to use `file`/`folder` sub commands for the `change` command. To know whether to provide `--fileinfo` or `--folderinfo` for the `change` command, the user has to know whether the key they provide represents a file or folder anyways, assuming i guessed your intent correctly.

Anyways, nothing stops you to inspect the `args` string array prior to configuring and setting up the System.CommandLine parser. Simply check whether the first item in the array is `change` and then read the second item from the `args` array and do the thing you want/need to do so you can setup the `change` command for the System.CommandLine parser accordingly...

**Comment by lanopk** [comment]
It seems clear that System.CommandLine currently has no control over these functions.

Using the IsHidden property seems like a good idea.
However, it is currently difficult to apply it to my code due to the separate classes for each Command and complex overlapping options.
I'll have to try applying this when a total reorganization is needed.

I decided to simply parse the args myself first.

Thanks for the replies.
