### ISSUE TITLE
ParseResultVisitor.ValidateAndConvertArgumentResults returns incorrect value for missing argument

### ISSUE THREAD

**Issue by lukewis** [dotnet/command-line-api#2292]
I'm trying to understand the purpose of the ParseResultVisitor.ValidateAndConvertArgumentResults method.  It seems to be the reason the test case below fails.  Could you please help me understand this behavior?

```
using System.CommandLine.Invocation;

namespace System.CommandLine.Tests
{
    [TestClass]
    public class SystemCommandlineTests
    {
        [TestMethod]
        public void WrongValueForParameter()
        {
            var root = new MyRootCommand();
            var result = root.Parse(new[] { "myapp", "dosomething", "amazing", "today" });
            Assert.AreEqual("amazing", result.GetValueForArgument(MyCommand.Arg1));
            Assert.AreEqual("today", result.GetValueForArgument(MyCommand.Arg2));
            // The following fails.  Retrieving the value for Arg3 actually returns "today" (the value of arg2)
            Assert.IsNull(result.GetValueForArgument(MyCommand.Arg3));

            // If I change my assertion to this, the test passes, but this seems quite unexpected
            // Assert.AreEqual("today", result.GetValueForArgument(MyCommand.Arg3));
        }
    }

    class MyCommand : Command
    {
        public static readonly Argument Arg1 = new Argument<string>();
        public static readonly Argument Arg2 = new Argument<string>();
        public static readonly Argument Arg3 = new Argument<string>();

        public MyCommand() : base("dosomething", "Do something amazing")
        {
            AddArgument(Arg1);
            AddArgument(Arg2);
            AddArgument(Arg3);

            this.SetHandler(Handle);
        }

        private void Handle(InvocationContext context)
        {

        }
    }

    class MyRootCommand : RootCommand
    {
        public MyRootCommand()
        {
            AddCommand(new MyCommand());
        }
    }
}

```

Below is the relevant snippet from ParseResultVisitor.ValidateAndConvertArgumentResults that seems to be causing the problem.  I would link to the code, but I can't find ParseResultVisitor anywhere in this repository.
```
if (commandArgumentResultCount == i)
{
		ArgumentResult argumentResult = new ArgumentResult(arguments[i], _innermostCommandResult);
		ArgumentResult argumentResult2 = _argumentResults[i - 1];
		int? num = _innermostCommandResult?.Tokens.Count;
		for (int j = argumentResult2.Tokens.Count; j < num; j++)
		{
			if (argumentResult.IsArgumentLimitReached)
			{
				break;
			}
			if (_innermostCommandResult != null)
			{
				argumentResult.AddToken(_innermostCommandResult!.Tokens[j]);
			}
		}
		_argumentResults.Add(argumentResult);
		if (argumentResult2.Parent is CommandResult)
		{
			AddToResult(argumentResult);
		}
		_symbolResults.TryAdd(argumentResult.Symbol, argumentResult);
}
```

**Comment by elgonzo** [comment]
Why is there a "myapp" string in your string array passed to the Parse method?

**Comment by lukewis** [comment]
Wow!  Thank you so much for taking the time to provide such a detailed answer!!  I need to absorb it a bit and try out what you suggest tomorrow morning.  For some reason I thought that Program.Main() args included the exe name.  Not sure why I thought that.  Perhaps it depends on how it's launched?  dotnet run vs direct execution with an AOT app?  Either way, thank you again for your help and I will close out this ticket as soon as I try out the things you suggest.

I'm quite excited about the Arity property (although I find that name a bit obscure), I hadn't come across that before, but it looks a lot like what I need.

Of interest, I'm using this methodology along with Spectre.Console to provide automatic prompts for missing arguments.  That's not something that's anywhere on the roadmap for this team is it?  Just making sure I'm not duplicating effort here.

**Comment by baronfel** [comment]
> Of interest, I'm using this methodology along with Spectre.Console to provide automatic prompts for missing arguments. That's not something that's anywhere on the roadmap for this team is it? Just making sure I'm not duplicating effort here.

I want this _so badly_ for the .NET CLI - we started down this path in a limited way for the template engine in `dotnet new`, and we took the approach of using a middleware to do intermediate parsing and re-parsing of arguments as the user filled them in. We likely won't continue that effort anytime soon, but if you want to take a look at some of the guts of it, the code is [here](https://github.com/dotnet/sdk/pull/30832).

**Comment by lukewis** [comment]
I absolutely wanted this for dotnet new also!  Our company has some complex
templates that could use this funtionality.  That's not my immediate use
case, but definitely on my radar!  Thank you for sharing the link!

**Comment by lukewis** [comment]
@elgonzo an update from the things I tried
1. Removing the "myapp" argument didn't seem to have any effect on the parsing (although what you said makes sense..  The third argument still contains a value of "today".  I also verified that the exe does not appear in the argument list on startup.  I have no idea why I thought that.
2. I looked for the newer version of the package that you mention (2.0.0-beta4.23407.1) but it doesn't appear to be published to nuget.org.  Is there a myget feed or some other source I should be checking?

**Comment by elgonzo** [comment]
> Removing the "myapp" argument didn't seem to have any effect on the parsing

Yes, it's unrelated to the issue you observed. It would however lead to System.CommandLine issuing an error message (to the effect of "myapp" being an unknown/unmatched argument) when you try to invoke instead of just parsing.

<br>

> but it doesn't appear to be published to nuget.org

It's available through the [daily builds nuget feed mentioned in the readme.md](https://github.com/dotnet/command-line-api#daily-builds)

**Comment by lukewis** [comment]
@elgonzo  - Thanks again for your help.  I can confirm this is resolved in the latest nightly build (apologies for missing that in the README), so I'll close this issue.  I look forward to the next "public" release!  I'm excited for "Arity", although I'm still hoping for a more "common" name.  I've been a software engineer for over 15 years and never once encountered the term Arity until now (maybe that's on me lol, but I suspect others may also be in my boat)

Brainstorming some ideas......
```
var arg = new CliArgument<string> { Multiplicity = ArgumentMultiplicity.ZeroOrOne }
var arg = new CliArgument<string> { Multiple = ArgumentMultiple.ZeroOrOne }
var arg = new CliArgument<string> { AllowMultiple = ArgumentMultiple.ZeroOrOne }
var arg = new CliArgument<string> { ExpectMultiple = ArgumentMultiple.ZeroOrOne }
var arg = new CliArgument<string> { Number = ArgumentNumber.ZeroOrOne }
var arg = new CliArgument<string> { Count = ArgumentCount.ZeroOrOne }
var arg = new CliArgument<string> { Quantity = ArgumentQuantity.ZeroOrOne }
var arg = new CliArgument<string> { Required= ArgumentRequirement.ZeroOrOne }
var arg = new CliArgument<string> { Requirement = ArgumentRequirement.ZeroOrOne }
var arg = new CliArgument<string> { HowMany = ArgumentQuantity.ZeroOrOne }
```
- Multiplicity is still more obscure than I prefer, but maybe more common than Arity?
- Number and Count have a strong association to an integer due to the collection types
- Required tends to imply it's a boolean (although it would be called IsRequired in that case)
- Requirement feels a little too "broad"
- I think Quantity might be my "least hated" from above......it still has an association to an integer, but intellisense would help

I have to admit I somewhat miss the simplicity of IsRequired.  I appreciate the power of Arity, but I wonder if IsRequired might cover 60-70% of use cases?)  Is it too confusing to have both?  The setter for one would update the other (I don't love side effects, but maybe worth it here?)

```
class CliArgument<T>
{
   bool IsRequired {get; set;} = true;
   Arity? Arity {get; set;} = Arity.ExactlyOne;
}

arg.IsRequired = false; // Would update arg.Arity to Arity.ZeroOrOne (why not ZeroOrMore you might argue?)
arg.Arity = Arity.ZeroOrOne; // Would update arg.IsRequired = false
arg.Arity = Arity.OneOrMore; // Would update arg.IsRequired = true;
```

You could also say that there is NO interaction between the two properties, but if Arity is set, it will take precedence over IsRequired?  Side note - I'm curious as to the value of Arity.Zero......I can't think of a use case

Anyways.....I'm sure you guys have already been through this thought exercise........just food for thought
