### ISSUE TITLE
Always Print Help on Root Command

### ISSUE THREAD

**Issue by mitchellmaler** [dotnet/command-line-api#2293]
Hello,

I am trying to find documentation or an example on how I can print out the help always when the root command is ran. The design idea is the root command actually won't do anything, and the user should always be using a sub command. So when the root command is invoked, the help should just print out to show the user what commands they can use.

**Comment by elgonzo** [comment]
Going with the latest 2.0.0-beta4.23407.1 build of the library (available through the [daily builds nuget feed mentioned in the readme.md](https://github.com/dotnet/command-line-api#daily-builds)), achieving this should be as simple as setting the root command's _Action_ to a `HelpAction` instance, e.g.:
```C#
var rootCmd = new CliRootCommand()
{
    Action = new System.CommandLine.Help.HelpAction()
};
```

**Comment by mitchellmaler** [comment]
@elgonzo Thanks for that. I actually was able to figure it out by just removing the root command handler. The documentation didn't say that wasn't required, but now it just expects a subcommand. 

Your example seems to be using a much different syntax/classes than what is talked about in the documentation. I will hold off on using the daily builds for now.
