### ISSUE TITLE
Feature Proposal: Source Generation for Command and Options

### ISSUE THREAD

**Issue by carstencodes** [dotnet/command-line-api#2323]
Hello, 

as I am a huge fan of Don't Repeat Yourself.

If I am using the NamingConventionBinder, I do something like this:

```csharp
var command = new CliCommand("foo", "Do the bar thing") {
   new CliOption<int>( new [] { "--number" }, getDefaultValue: () => 42 ) { Arity = ArgumentArity.ExactlyOne };
};
command.Handler = CommandHandler.Create<FooOptions>(o => { Console.WriteLine(o.Number) });
```

with

```csharp
class FooOptions 
{
   public int Number { get; private set; }
}
```

In order to minimize shattering, I would suggest doing the following:

```csharp
[HandleCommand("foo", Description="Do the bar thing")]
public partial class FooOptions
{
    [Option("--number")]
    [System.ComponentModel.DefaultValue(42)]
    [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue, MaximumIsInclusive = true)]
    public int Number { get; init; }
}
```
using

```csharp
var command = CommandFactory.Create<FooOptions>();
command.Handler = CommandHandler.Create<FooOptions>(o => {  });
```

At that point, I would like to have something like:

```csharp
interface ISupportsCommandCreation
{
     static CliCommand CreateCommand();
}
```

where a source generator will create an implementation for 

```csharp
partial class FooOptions: ISupportsCommandCreation
{
      static CliCommand ISupportsCommandCreations.CreateCommand()
      {
             // Implementation goes here
      }
}
```

What do you think? Would this be a good feature to add to this project?

If not, feel free to close this issue.

**Comment by carstencodes** [comment]
Most equivalent work is also present in `System.ComponentModel` and `System.ComponentModel.DataAnnotations`. It would be good to support it this way.

**Comment by elgonzo** [comment]
Just as an FYI, there is already a 3rd-party project that is trying to do what you seek: https://github.com/dotnet/command-line-api/discussions/2310 (based on the System.CommandLine version available on the public nuget.org and not on the newer code-System.CommandLine code base as present in the repository here, as it seems).

While i have no experience with this project, it seems it supports code generation but is lacking localization features as of now...

**Comment by carstencodes** [comment]
Awesome!
