### ISSUE TITLE
ClicCommand.Parse escapes backslash when parsing arguments

### ISSUE THREAD

**Issue by Nigusu-Allehu** [dotnet/command-line-api#2334]
I have a CliCommand that takes in a file path as an input as follows
``` C#
using System.CommandLine;
using System.CommandLine.Parsing;

class Program
{
    public static int Main(string[] args)
    {
        var rootCommand = new RootCommand
        {
            new Option<string>("--source",
            description: "my source")
        };

        ParseResult p = rootCommand.Parse(args);
        return 0;
    }
}

```

Assume a user passes `--source "C:\myfiles\"`  as an input to this command. This will result in the path being parsed to the following value `"C:\myfiles""` for the option source. 

this parsed value is completely different from what the user entered.

**Comment by elgonzo** [comment]
Not a bug in the library. Inspect the `args` array passed to your main method, and you might be surprised by what you see is in it...

**Comment by Nigusu-Allehu** [comment]
Thank you! It looks like the `args` arrya passed to the main method passes `"C:\myfiles""` instead of  `"C:\myfiles"`

**Comment by elgonzo** [comment]
By the way, the reason why this happens is the WinAPI [`CommandLineToArgv`](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) being used to split the commandline into separate strings for the `args` array (the same function that is also used to populate the `args` array in C/C++ Windows programs). To preserve the trailing backslash in the given path, use `--source "C:\myfiles\\"` (note the double backslash at the end but no double backslash after the drive letter)
