### ISSUE TITLE
Required command was not provided on `RootCommand`

### ISSUE THREAD

**Issue by cschuchardt88** [dotnet/command-line-api#2359]
I am get error `Required command was not provided.` when running `MyApp.exe --as-service` with the following code _below_. 
```csharp
internal sealed class DefaultRootCommand : RootCommand
{
    public DefaultRootCommand() : base("Description")
    {
        var exportCommand = new ExportCommand();
        AddCommand(exportCommand);

        AddOption(new Option<bool>("--as-service", "Option1"));
    }
    // ........
}
```

However if I remove the code _below_ it works fine.
```csharp
var exportCommand = new ExportCommand();
AddCommand(exportCommand);
```

# Program.cs
```csharp
static async Task<int> Main(string[] args)
{
    var rootCommand = new DefaultRootCommand();
    var parser = new CommandLineBuilder(rootCommand)
        .UseHost(_ => new HostBuilder(), builder =>
        {
            builder.ConfigureDefaults(args);
            builder.UseSystemd();
            builder.UseWindowsService();
            builder.UseCommandHandler<DefaultRootCommand, DefaultRootCommand.Handler>();
            builder.UseCommandHandler<ExportCommand, ExportCommand.Handler>();
        })
        .UseDefaults()
        .UseExceptionHandler(NullExceptionFilter.Handler)
        .Build();

    return await parser.InvokeAsync(args);
}
```

**Comment by elgonzo** [comment]
I haven't tested your code, but I believe it's the `base("Description")` invocation in your DefaultRootCommand constructor that gives you grief.

This sets the _name of the root command to "Description". However, a root command is not supposed to have a name -- or put differently: the name of the root command is supposed to be the executable itself.

I suggest to delete the invocation of the base RootCommand constructor and see whether this resolves the issue.

**Comment by cschuchardt88** [comment]
> In 2.0.0-beta4.22272.1, the "Required command was not provided" error is set by ParseResultVisitor.ValidateCommandHandler if the user-specified command does not have a handler but has subcommands. This is called during Parser.Parse. Your code above calls `builder.UseCommandHandler<DefaultRootCommand, DefaultRootCommand.Handler>()` but I think this is executed too late and the parser has already made its decision. Perhaps you could work around this by assigning a dummy handler to the command initially, just to satisfy the parser; the hosting middleware would then substitute the correct handler after parsing finishes, so the dummy handler would never be called.

The workaround I found is to change the base class to `Command` from `RootCommand`.

**Comment by cschuchardt88** [comment]
> No, I meant you'd assign a dummy handler to the root command _without_ `UseCommandHandler`, then let `UseCommandHandler` replace it with the real handler after parsing has finished.

But how would i do that if I was doing this for example:
```csharp
internal sealed partial class DefaultRootCommand : RootCommand
{
    public DefaultRootCommand() : base("wallet", "Use or manage wallet(s)")
    {
        var openWalletCommand = new OpenWalletCommand();
        var startOption = new Option<uint>("--as-service", "Option1");
        AddCommand(openWalletCommand);
    }

    public new sealed class Handler : ICommandHandler
    {
        public int Invoke(InvocationContext context)
        {
            // TODO: Add Code
        }

        public Task<int> InvokeAsync(InvocationContext context)
        {
            // TODO: Add Code
        }
    }
}
```
