### ISSUE TITLE
[Design] Is CLI syntax case sensitive?

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/command-line-api#2394]
## Update

Case sensitivity will be supported. It was always expected that CLIs could be case sensitive, but that is not how the issue is worded.

We may allow CLI authors to elect to be case insensitive at some point in the future, but not initially. Closing the issue for now.
 
## Original

Should command lines be treated as case sensitive? 

Case sensitive CLIs have different behavior for `-x` and `-X`, for example.

## Arguments for case sensitivity

Many common utilities, including `git` use case sensitivity.

Is this in the Posix standard? _Need link here if so._

There are more possibilities for identifiers if case is recognized

## Arguments for **in-*sensitivity

The PowerShell and Windows command prompt are case -insensitive.

## Questions

> Can't people just use `ToLower` if they want case-insensitivity? 

No. This would change the case of arguments, as well as CLI syntax

**Comment by Keboo** [comment]
There was a lot of discussion around this when we first started. There are a lot of conflicting things in the wild. We landed on case sensitive, as it is easier to loosen those requirements in the future vs trying to tighten them. As mentioned above, many of the examples we found where there were casing differences were often short (single letter) options. We did not find many longer named identifiers that had different behavior based only on casing.
