### ISSUE TITLE
[`Question`] Develop Console Prompt Screen

### ISSUE THREAD

**Issue by cschuchardt88** [dotnet/command-line-api#2422]
I am building a custom `console`  prompt; however I keep getting error when a command is found or not. As you will see in the _image below_.

#### How my app works:
I'm running my app as `MyApp.exe connect \\.\pipe\HelloWorld` then screen refreshes to appear as terminal on that computer. This would be my implementation of `IPC` for the program.

```csharp
        public static async Task<int> RunConsolePrompt(InvocationContext context, CancellationToken cancellationToken)
        {
            context.Console.Clear();

            var rootCommand = new DefaultRemoteCommand();
            var parser = new CommandLineBuilder(rootCommand)
                .UseParseErrorReporting()
                .Build();

            while (cancellationToken.IsCancellationRequested == false)
            {
                PrintPrompt(context.Console);

                var line = context.Console.ReadLine()?.Trim() ?? string.Empty;

                if (string.IsNullOrEmpty(line) || string.IsNullOrWhiteSpace(line))
                    continue;

                if (line.Equals("exit", StringComparison.OrdinalIgnoreCase) || line.Equals("quit", StringComparison.OrdinalIgnoreCase))
                    break;

                _ = await parser.InvokeAsync(line, context.Console);
            }

            return 0;
        }
```

```csharp
internal class ConnectCommand : Command
{
    public ConnectCommand() : base("connect", "Connect to local Neo service")
    {
        var pipeNameArgument = new Argument<string>("PIPE_NAME", "Name of the named pipe to connect to");

        AddArgument(pipeNameArgument);
    }

    public new class Handler : ICommandHandler
    {
        private static readonly string s_computerName = Environment.MachineName;
        private static readonly string s_userName = Environment.UserName;

        private NamedPipeEndPoint? _pipeEndPoint;

        public async Task<int> InvokeAsync(InvocationContext context)
        {
            var stopping = context.GetCancellationToken();

            if (EnvironmentUtility.TryGetServicePipeName(out var pipeName))
            {
                _pipeEndPoint = new NamedPipeEndPoint(pipeName);
                var pipeStream = NamedPipeTransportFactory.CreateClientStream(_pipeEndPoint);

                context.Console.SetTerminalForegroundColor(ConsoleColor.DarkMagenta);
                context.Console.WriteLine($"Connecting to {_pipeEndPoint}...");
                context.Console.ResetTerminalForegroundColor();

                try
                {
                    await pipeStream.ConnectAsync(stopping).DefaultTimeout();
                    await RunConsolePrompt(context, stopping);
                }
                catch (TimeoutException)
                {
                    context.Console.WriteLine(string.Empty);
                    context.Console.ErrorMessage($"Failed to connect! Try again Later!");

                    context.Console.SetTerminalForegroundColor(ConsoleColor.DarkCyan);
                    context.Console.WriteLine("Note: Make sure service is running.");
                    context.Console.ResetTerminalForegroundColor();
                }

                return 0;
            }

            return -1;
        }

        public int Invoke(InvocationContext context)
        {
            throw new NotImplementedException();
        }

        private static void PrintPrompt(IConsole console)
        {
            console.SetTerminalForegroundColor(ConsoleColor.DarkBlue);
            console.Write($"{s_userName}@{s_computerName}");
            console.SetTerminalForegroundColor(ConsoleColor.White);
            console.Write(":~$ ");
            console.SetTerminalForegroundColor(ConsoleColor.DarkCyan);
            console.ResetTerminalForegroundColor();
        }

        public static async Task<int> RunConsolePrompt(InvocationContext context, CancellationToken cancellationToken)
        {
            context.Console.Clear();

            var rootCommand = new DefaultRemoteCommand();
            var parser = new CommandLineBuilder(rootCommand)
                .UseParseErrorReporting()
                .Build();

            while (cancellationToken.IsCancellationRequested == false)
            {
                PrintPrompt(context.Console);

                var line = context.Console.ReadLine()?.Trim() ?? string.Empty;

                if (string.IsNullOrEmpty(line) || string.IsNullOrWhiteSpace(line))
                    continue;

                if (line.Equals("exit", StringComparison.OrdinalIgnoreCase) || line.Equals("quit", StringComparison.OrdinalIgnoreCase))
                    break;

                _ = await parser.InvokeAsync(line, context.Console);
            }

            return 0;
        }
    }
}
```

### Now this is the `prompt` _(image)_ its not my `powershell` prompt; even though it looks like it. But still in my `terminal`.
![image](https://github.com/dotnet/command-line-api/assets/8141309/ec527e45-5e43-45ee-8e54-1b50e8f9295d)

**Comment by elgonzo** [comment]
What exactly is your question?

The error message comes from System.Commandline (as you already seem to be aware of suggested by the fact that you posted your report here in the System.Commandline repository).

Specifically, it originates from your call of `parser.InvokeAsync` and is caused by you not defining a command with the name `?`...

**Comment by elgonzo** [comment]
Unfortunately, i am unable to follow your explanations :-( You say that "_Problem that I am having when I don't use RootCommand It can't not even parse `--help` or `-?`_". But System.CommandLine, doesn't need a RootCommand to successfully parse the help options (demo: https://dotnetfiddle.net/XNX628) 

> I believe the reason is because of RootCommand.ExecutableName and RootCommand.ExecutablePath is empty or if used isn't on the line that I am parsing.

While i am not 100%, i doubt `RootCommand.ExecutableName` and `RootCommand.ExecutablePath` would be related to SCL being (un)able to parse the input string "--help" or "-?". The CommandBuilder should successfully parse either input string, assuming the built-in help options have been actived via UseHelp() or UseDefaults(). But without being able to easily reproduce this on my end, i can't say for sure either way...

> What I would like to know is how to display Help info with the Command class

Your command would basically need to do something similar to what the SCL middleware for the help options does:
https://github.com/dotnet/command-line-api/blob/3e0db9e5830f2722645b9a576f80e3650b50f23a/src/System.CommandLine/Help/HelpResult.cs#L12-L23

> also only show red text in terminal image above (not the rest of the text that is displayed). 

Don't use UseParseErrorReporting() then, as it printing the help text is unfortunately hard-coded. Instead, inspect the parse result before calling Invoke/Async on it. Specifically look at its `ParseResult.Errors` list. Each of the parse errors in this list provides the error message for that error in its ``ParseError.Message` property, which you can print out.
