### ISSUE TITLE
Make available the command arguments as a handler argument

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#297]
All parameters of the DragonFruit Main are currently added as Options.
Maybe there could be a way to make a parameter, the Argument of the Command.

**Comment by jonsequitur** [comment]
Another approach that could work here would be for the binder to match properties or parameters by name using the argument name.

```csharp
var command = new Command("the-command", new Argument<bool> { Name = "x" } )
{
    new Option("-y", new Argument<string>("-y"))
};
command.Handler = CommandHandler.Create((bool x, string y) => {  /*  */ })
```

This decouples syntax from method invocation: the method doesn't have to care whether the parameter came from an option or an argument. It does require arguments to be given names, though.

@KathleenDollard @MarkMichaelis Thoughts?

**Comment by KathleenDollard** [comment]
I think this is a great direction (naming arguments and allowing access to them). 

Fro the perspective of the end user typing at the terminal - these are positional, correct?

**Comment by jonsequitur** [comment]
#310 will introduce positional parsing for arguments. 

For this issue, I believe supporting binding arguments by name during invocation will work regardless of the parser rules.

**Comment by KathleenDollard** [comment]
On @tmds original question - the AppModel/JackFruit work currently supports both attributes and a convention of ending in Args. I'd like to chat more about how this could work best after we get the reflection binder finished.

**Comment by jonsequitur** [comment]
Support for this was added by #420.
