### ISSUE TITLE
help output when Argument.Help.Name is not set

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#298]
When `Argument.Help.Name` is not set, the `--help` becomes less clear.

```
Usage:
  Test [options]

Options:
  --option    Description of option
```
vs
```
Usage:
  Test [options] <arguments>

Arguments:
  <arguments>    arguments description

Options:
  --option <OPTION>    Description of option
```
In the first case, it is not clear the command is accepting arguments, and the option command accepts a value.
Some thoughts:
- maybe the default help implementation should fill in these blanks, providing default strings `"arguments"`/`"<value>"`
- the api may encourage users to provide a `Help.Name` when creating an argument.
- setting a `Help.Name` for a boolean option may be confusing

**Comment by jonsequitur** [comment]
`Argument.Name` is no longer allowed to be `null` which effectively resolves this issue.

**Comment by jonsequitur** [comment]
`Argument.Name` is no longer allowed to be `null` which effectively resolves this issue.
