### ISSUE TITLE
help output when Argument.Description is not set

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#299]
When a `Command.Argument` doesn't set a `Help.Description` printing it out in the `Arguments:` `--help` section doesn't provide additional information.
```
Usage:
  Test [options] <arguments>

Arguments:
  <arguments>    

Options:
  --option    Description of option
```

**Comment by jonsequitur** [comment]
What additional information would be appropriate to show?

**Comment by tmds** [comment]
I don't remember what my expectation was here.
