### ISSUE TITLE
Allow a command to accept multiple distinct arguments

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#310]
Some commands take multiple distinct arguments:

```
git remote add [<options>] <name> <url>
ln <target> <link_name>
```

This is typically used for required parameters.
The user doesn't have to specify the name when providing these values.

`System.CommandLine` currently only supports a single argument.
This argument may be of arity 1+.
The above UX is not possible.

That single argument is made available as a `string[]`.
This is different from `Options`, where options are bound based on their name to handler argument parameters (related https://github.com/dotnet/System.CommandLine/issues/297). This makes it much less convenient to consume these arguments, than it is to consume `Options`.

Suggested feature:
- Support multiple arguments per command
  * Commands with have subcommands can have at most 1 arguments
  * Only the last argument can have arity > 1
  * Only the last argument can be optional
    ~ or relaxed version:  If an argument is optional, all arguments succeeding must also be optional
- Support naming arguments for handler binding (cfr Options)

**Comment by jonsequitur** [comment]
Yes, commands and options can both currently specify how many arguments are required, via argument arity, and a default value satisfies the requirement if the user doesn't specify an argument. (Help output doesn't reflect this currently.) I would expect this behavior to extend to this scenario. 

One consideration for the API design is we don't vary behavior based on the order in which child objects are added to their parents. Since the parsing of these arguments will necessarily be positional, the API will need to be explicit about their position.

**Comment by KathleenDollard** [comment]
@jnm2 

It seems to me that the difference between options and arguments is whether the argument name (`--database`) is included. I assume in the example you posted, you'd have an opinion on which is better for end users. When there are multiple arguments, they need to be positional. 

I think this would be a valuable addition. 

And when @jonsequitur is back, I think we need a separate conversation about where/how required values are supported.

**Comment by jnm2** [comment]
@KathleenDollard Yes, that is exactly how I was thinking of it. Thanks!

**Comment by jonsequitur** [comment]
@jnm2 Your API suggestion was a good one. Thoughts? https://github.com/dotnet/command-line-api/pull/542/files#diff-fb1621b467c13fb6006c42c063e47bc2.

**Comment by jonsequitur** [comment]
I've opened a separate issue to cover related help improvements: #543

**Comment by jnm2** [comment]
@jonsequitur Wow... that's a lot to get my head around, but I'm glad my suggestion was useful and I'll look forward to future versions!

**Comment by gitfool** [comment]
@jonsequitur Awesome! I’m very interested in these changes but reluctant to switch to nightly builds. Will there be another prerelease soonish? (I only ask because the last alpha was a couple of months ago.)

**Comment by jonsequitur** [comment]
There will be, and there are a few minor breaking changes which I'd like to document before publishing new packages on nuget.org.
