### ISSUE TITLE
make TestConsole available via a NuGet package

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#317]
The `TestConsole` that's used in the `System.CommandLine` tests will also be useful to people wanting to test their own apps. 

Should we:

* Make it available in a separate package, or
* Include it in the core package?

**Comment by jeredm** [comment]
I think making it part of the core package would be helpful because it is pretty light weight.

**Comment by Keboo** [comment]
No strong opinion. But I tend to agree with @jeredm in keeping it inside of the core package.

**Comment by KathleenDollard** [comment]
I agree with keeping it in core because I don't think we want to own it separately. 

If you can put it's purpose into 200 or so characters, I'll tweet or retweet so people know it is there.

**Comment by jonsequitur** [comment]
Thanks.

I'm relayering the rendering bits right now and will document this afterward (since its location is about to move).

I opened #346 to keep track of this.

**Comment by jonsequitur** [comment]
`TestConsole` is now included in `System.CommandLine` and `TestTerminal` is included in `System.CommandLine.Rendering`.
