### ISSUE TITLE
Default error exit codes

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#331]
When System.CommandLine encounters an error, the program stops with an exit code 1.

It would be nice if this would be configurable.

Perhaps it makes sense for the package to return different values for different types of errors by default (e.g. unhandled exception vs parser error). Posix shells use 'exit codes' higher than 128 for indicating process termination by signal. Picking values below that is preferable.

**Comment by fhurta** [comment]
To add to this enhancement - `CommandHandler.Create` takes now `Action` as parameter. Changing it to `Func` would allow returning custom exit code from the command handler

**Comment by Porges** [comment]
> @fhurta To add to this enhancement - `CommandHandler.Create` takes now `Action` as parameter. Changing it to `Func` would allow returning custom exit code from the command handler

For anyone finding this later: it's a hidden (undocumented?) feature but if your `Func<T, T2, T3, Task>` handler actually returns a `Task<int>` then the result will be used as an exit code.
