### ISSUE TITLE
NuGet.org

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/command-line-api#356]
Hi!

I would like to use this library for BenchmarkDotNet project. BDN is published to NuGet.org and it can reference only packages published to NuGet.org.

When can I expect `System.CommandLine` to be published to NuGet.org?

/cc @KathleenDollard

**Comment by KathleenDollard** [comment]
Cool!

Do you need it in full release or just as a preview on NuGet?

**Comment by adamsitnik** [comment]
@KathleenDollard we are gonna need a full release and signed package

I have created a new issue for BDN to make sure that we can switch as of today: https://github.com/dotnet/BenchmarkDotNet/issues/1016

As soon as we make sure that we can switch I will let you know and hopefully then you could publish the package to nuget.org

**Comment by KathleenDollard** [comment]
//cc @jonsequitur for visibility

**Comment by jmezach** [comment]
Would love to see a release of this on NuGet.org as well so we can fix augurk/Augurk.CommandLine#17.

**Comment by jonsequitur** [comment]
Packages are now available on nuget.org.
