### ISSUE TITLE
Make CommandLineBuilderExtensions.GetTerminal() public

### ISSUE THREAD

**Issue by wjk** [dotnet/command-line-api#370]
Title says it all, really. My app needs to use a custom (non-System.CommandLine-compatible) argument parser. However, I want to use the `ITerminal` functionality for outputting ANSI-based color output sequences. However, `SystemConsoleTerminal` doesn't declare compatibility with ANSI sequences. `VirtualTerminal` does, but it's an internal class.

The function mentioned in the title does exactly what I need (auto-detects ANSI support, and returns an appropriately configured `ITerminal`), but I can't access it without reflection because it's private. I could send a PR for this if desired. Thanks!

**Comment by jonsequitur** [comment]
I opened #374 which includes a change to move `GetTerminal` to `Terminal` and make it public. 

Just so you're aware, the API in `System.CommandLine.Rendering` is early and more unstable than `System.CommandLine.Experimental`. We'd appreciate your thoughts.

**Comment by wjk** [comment]
I find `System.CommandLine.Rendering` to be very stable (albeit poorly documented). I don't understand how to use some of the more complex stuff, but the ANSI output works great.

One thing I would recommend adding, however, is adding a built-in way to get the ANSI codes for `StyleSpan` and `ColorSpan`. I tried using these as a way to store color/bold data using instance properties, but I had to implement translation to the static properties on the `Ansi` class by hand. Other than that, it looks great. Keep up the good work!

**Comment by jonsequitur** [comment]
> One thing I would recommend adding, however, is adding a built-in way to get the ANSI codes for StyleSpan and ColorSpan.

Can you expand on this? Do you mean getting them from the terminal's current state?

**Comment by wjk** [comment]
No. I mean I have to do something like this in my code to translate between `ColorSpan` instances and a code I can pass to `IStandardStreamWriter.Write()`:

```cs
public void SetForeground(ForegroundColorSpan color)
{
    if (!IsRedirected && OutputMode == OutputMode.Ansi)
    {
        if (color.RgbColor != null)
        {
            RgbColor rgb = color.RgbColor;
            Writer.Write(Ansi.Color.Foreground.Rgb(rgb.Red, rgb.Green, rgb.Blue).EscapeSequence);
        }
        else if (!string.IsNullOrEmpty(color.Name))
        {
            string name = color.Name;
            AnsiControlCode code;

            if (name == nameof(Ansi.Color.Foreground.Black)) code = Ansi.Color.Foreground.Black;
            else if (name == nameof(Ansi.Color.Foreground.Blue)) code = Ansi.Color.Foreground.Blue;
            else if (name == nameof(Ansi.Color.Foreground.Cyan)) code = Ansi.Color.Foreground.Cyan;
            else if (name == nameof(Ansi.Color.Foreground.DarkGray)) code = Ansi.Color.Foreground.DarkGray;
            else if (name == nameof(Ansi.Color.Foreground.Default)) code = Ansi.Color.Foreground.Default;
            else if (name == nameof(Ansi.Color.Foreground.Green)) code = Ansi.Color.Foreground.Green;
            else if (name == nameof(Ansi.Color.Foreground.Red)) code = Ansi.Color.Foreground.Red;
            else if (name == nameof(Ansi.Color.Foreground.White)) code = Ansi.Color.Foreground.White;
            else if (name == nameof(Ansi.Color.Foreground.Yellow)) code = Ansi.Color.Foreground.Yellow;
            else if (name == nameof(Ansi.Color.Foreground.LightBlue)) code = Ansi.Color.Foreground.LightBlue;
            else if (name == nameof(Ansi.Color.Foreground.LightGray)) code = Ansi.Color.Foreground.LightGray;
            else if (name == nameof(Ansi.Color.Foreground.LightGreen)) code = Ansi.Color.Foreground.LightGreen;
            else if (name == nameof(Ansi.Color.Foreground.LightMagenta)) code = Ansi.Color.Foreground.LightMagenta;
            else if (name == nameof(Ansi.Color.Foreground.LightRed)) code = Ansi.Color.Foreground.LightRed;
            else if (name == nameof(Ansi.Color.Foreground.LightYellow)) code = Ansi.Color.Foreground.LightYellow;
            else throw new ArgumentException($"Unrecognized ForegroundColorSpan name '{name}'", nameof(color));

            Writer.Write(code.EscapeSequence);
        }
        else
        {
            throw new ArgumentException("Cannot display ForegroundColorSpan with no RgbColor or Name", nameof(color));
        }
    }
}
```

I would appreciate it if the framework would have a method that does this for me.

**Comment by jonsequitur** [comment]
We have code that does this. Given an instance of `ITerminal` you can do:

```cs
terminal.Render($"{Ansi.Color.Foreground.Blue}some text{Ansi.Color.Foreground.Default}");
```

This will render correctly whether the terminal is ANSI-enabled (by writing the escape sequences) or not (by hiding the escape sequences), and will also render correctly to redirected output, e.g. a file (by hiding the escape sequences).

**Comment by wjk** [comment]
I didn't know I could do it that way. This simplifies my code a lot. Thanks!

**Comment by jonsequitur** [comment]
As you noted, it's poorly documented. :)
