### ISSUE TITLE
Support argument assignment immediately following option name

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/command-line-api#39]
* Asignment of option values via ''
i.e. 'getuser.exe -nInigo`
Note, this is supported by POSIX

Question: 
- [ ] This would presumably be mutually exclusive when abbreviation/startswith is active?
- [ ] Does this only work for single character names or can a full name be used?

**Comment by Alxandr** [comment]
Most UNIX programs I've used where I've wanted to do this support doing things like `getuser.exe -vvnIngo` being the same as `getuser.exe -vvn Ingo` and `getuser.exe --verbose --verbose --name Ingo`.
