### ISSUE TITLE
Determine commonality between Arguments and Options

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/command-line-api#392]
Options and arguments have a fundamental and unique common characteristics in that they are used to define a thing that can be used to produce a value (which of course might be an IEnumberable).  

It's valuable in binding to be able to leverage this commonality as it reduces the number of times we need to have an overload for argument and another for option. I believe it will also provide more long term flexibility, such as considering positional arguments and allowing data to be read from a file (where the argument/option distinction may be non-existent). 

For history: at one point there was also a distinction in how names were handled for arguments and options, but that difference has been erased. This is also a question of what a Symbol (ISymbol) should be.

This is a basic decision, and worth thought now because whatever we decide we will live with. 

I postponed this in the ReflectionBinding work by temporarily creating an ISymbolBase. If we're able to resolve this soon it will be lovely, but I don't think this needs to block as I can add the overloads or stick with the temporary interface as we work this question out.

**Comment by KathleenDollard** [comment]
If we work out the logical characteristics, we can then figure out the code. Here's my current and flexible opinion:

Arguments, options and commands all have:
* a name
* a description
* a parent
* suggestions
* ability to be hidden

Arguments and options also have (I know technically this is always the argument, I think that is implementation detail because the option is what is declared, attached, bound and supplies result)
* a type
* the capacity to be bound/be the basis for producing a value
* validation

Options and commands also have:
* children (although options might just have one)

Options also have:
* aliases

**Comment by jonsequitur** [comment]
Argument names are different from option and command names. While the names for all of these are currently used in binding and in help, command and option names are actually part of the syntax of the CLI. They might also be thought of as identifiers or keywords within an CLI's syntax.

**Comment by jeredm** [comment]
I think this falls into positional arguments...

This idea is a little rough, but an application could specify columns to read from a CSV file.

`> mycsvmapperapp --columns "FirstName" "LastName" "Address"`

In this example, the 0 index in the CSV could map to a DB field named "FirstName" and the 1 index would be mapped to the "LastName" field in the DB. In this case, the argument would be positional and I don't know if we need the same for an option.

**Comment by KathleenDollard** [comment]
Can you give an example of where commands use aliases in practice (to help me think about that scenario). 

I think that options do not have a target type is an implementation detail, rather than how programmers are likely to look at options. I do not suggest changing that implementation, only softening when programmers have to know about it.

**Comment by jonsequitur** [comment]
> Can you give an example of where commands use aliases in practice (to help me think about that scenario).

Backcompat when changing a command name is one scenario I've already used.

> I think that options do not have a target type is an implementation detail, rather than how programmers are likely to look at options. I do not suggest changing that implementation, only softening when programmers have to know about it.

Both commands and options have one or more child arguments, and both typically use `Argument<T>`. The concept of an `Option<T>` would introduce an inconsistency with `Command`, which would logically also then need a `Command<T>` and, in the case of #310, generic type definitions like `Command<T1, T2>`, etc.

**Comment by jonsequitur** [comment]
> Will we require that arguments be unique in the set of arguments, options and subcommands?

Unique in what sense and why?

**Comment by tmds** [comment]
My view: arguments don't require the user to provide a name. The added value of arguments compared to options is that the user can be less verbose.

This is a boolean difference between 'arguments' and 'options', and probably there is a simpler way to handle this than the current model (Argument/Option/Symbol).

The top comment lists some other differences.

> Options and commands also have:
    children (although options might just have one)

I'm not sure what a 'child' of an Option means?

> Options also have:
    aliases

This is not a fundamental differences. You could allow an argument to be specified by name. And also to allow alternative names (aliases). I'm not saying that should be possible, just that this isn't a fundamental difference.

**Comment by tmds** [comment]
> This is a boolean difference between 'arguments' and 'options'

I've been thinking how to name the boolean. The best I came up with so far is: _positional_.

**Comment by jonsequitur** [comment]
We do have support (turned off by default) for something we called "positional options" which allow options' names to be omitted if they can be inferred by position. The feature is turned off by default because it creates some ambiguity when getting suggestions or returning errors, but if we solve those problems, I believe it could allow us to conflate "options" and "arguments". 

Under the current model, though, an option or subcommand an identifier in the syntax. An argument is a user-provided value associated with one of those identifiers. If we consider an argument to be a symbol (though it's not currently an `ISymbol`) then its parent would be the associated command or option.

**Comment by tmds** [comment]
Based on what I've been trying, I'd like not deal with Option and Argument, and write something like:
```
command.Add(new Argument<string>("--option", "description"))
command.Add(new Argument<string>("arg", "description", required: true, positional: true))

meaning:

command [options] <arg>

// `[options]` can be: `--option <value>`
```

Variations:
```
command.Add(new Argument<string>("--option", "description", required: true))

means:

command --option <value> [options] <arg>
```

```
command.Add(new Argument<string>("arg", "description", required: false, positional: true))

means:

command [options] [<arg>]
```

Some combinations of arity, required and positional don't make sense, but I don't think there is a user-friendly way to enforce that by having several types.

Maybe this API is limiting somehow, but I don't see it.

**Comment by drewburlingame** [comment]
After reading these documents... 
* http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
> utility_name[-a][-b][-c option_argument][-d|-e][-f[option_argument]][operand...]

> The utility in the example is named utility_name. It is followed by options, option-arguments, and operands. The arguments that consist of <hyphen-minus> characters and single letters or digits, such as 'a', are known as "options" (or, historically, "flags"). Certain options are followed by an "option-argument", as shown with [ -c option_argument]. The arguments following the last options and option-arguments are named "operands".

* http://www.informit.com/articles/article.aspx?p=175771
> Arguments are all the words on the command line except the command name

> Arguments can be further classified as options or operands. In the previous two examples all the arguments were operands: files for ls and raw text for echo.

I think it's helpful to break Arguments down into two groups: Options & Operands.   "Positional arguments" are operands in POSIX terminology. 

  * Argument
    * commonality of Option & Operand...
      * can be assigned a value
      * requiredness and other validations
      * help properties
      * ...
  * Option: Argument
    * Is  named
    * Is **not** positional
  * Operand: Argument
    * Is **not** named
    * Is positional


This would allow generic handling of Arguments.
