### ISSUE TITLE
Improve documentation for Installation of shim script for dotnet-suggest on Windows 

### ISSUE THREAD

**Issue by srsaggam** [dotnet/command-line-api#410]
_"For PowerShell, add dotnet-suggest-shim.ps1 to C:\Users\<USERNAME>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1."_

The documentation for installing shim script is not fully detailed.
1) The path doesnt seem to exist for all Windows users. ( echo $PsHome )

2) If the profile file doesnt exist we need to create one.

Thanks @wli3 for helping figure out this.

I know we are trying to automate this till then we may wanna update the documentation for other who wanted to test.

**Comment by jonsequitur** [comment]
I've updated the wiki: https://github.com/dotnet/command-line-api/wiki/dotnet-suggest.
