### ISSUE TITLE
`Parser.InvokeAsync` forces async methods to use the API

### ISSUE THREAD

**Issue by nattress** [dotnet/command-line-api#412]
I am adding command line parsing support for a tool and my only option to run the parse / invoke logic is to use `Parser.InvokeAsync`. Is it a deliberate decision to not have a `Parser.Invoke`?  For a simple tool I just want to run the thing synchronously and then immediately exit.

**Comment by jonsequitur** [comment]
We do plan to add a non-async version.

**Comment by couven92** [comment]
@nattress You could always do `return parser.InvokeAsync().GetAwaiter().GetResult();`

That's basically what the compiler does with a Task-returning main function as well.
