### ISSUE TITLE
<summary> parsing by DragonFruit doesn't understand <para>

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/command-line-api#415]
I'd like a line break in the help text produced from `<summary>` docs.

It seems that line breaks are ignored (understandably). Adding `<para>` elements doesn't help (in fact, it removed whitespace between paragraphs).

Perhaps a separate issue, but it'd be nice to use the `<summary>` section for the brief description, and the `<remarks>` section for more detailed information.

**Comment by jeredm** [comment]
@jonsequitur I am wondering if we want `Description` in `Symbol` to be more complex object than a `string`.  Changing to a complex object could have a large impact on unit tests. The help process assigns the XML document text to `Description`. `Description` is cleaned of new lines and whitespace and is finally split into lines to fit the screen. A more complex object would allow us to store lines of descriptions intentionally and `<remarks>`. 

Another option would be to keep the `<para>` and `<remarks>` tags in the description and parse them out when the description is printed.

**Comment by danalexandrunicoara** [comment]
Hi @drewnoakes .

Have a look over this screenshot

![image](https://user-images.githubusercontent.com/26961682/136784327-9a05bf33-fd15-4081-8772-8bc7d83134d0.png)


It seems that the **para** tag inside the **summary** tag is not ignored. Is this the intended behavior you wanted?

**Comment by AnvarKhatik** [comment]
Can I Resolve This Issue & Can U Help Me With Start It ?..

**Comment by danalexandrunicoara** [comment]
> Can I Resolve This Issue & Can U Help Me With Start It ?..

I don't have any updates on this. Feel free to work on it and see if it reproduces.

**Comment by ranma42** [comment]
IIUC according to https://github.com/dotnet/command-line-api/pull/2008#issue-1514102631 this issue can be closed.
