### ISSUE TITLE
[BUG] Using Tab-autocomplete from command-line-api (in MLNET CLI) not working properly

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/command-line-api#424]
@jonsequitur , @srsaggam

When using tab autocompletion provided by **"command-line-api"** after typing `mlnet new`, it always suggests you the same argument, in current MLNET CLI version it is always `--dataset`.

Here are the installed NuGets:
![image](https://user-images.githubusercontent.com/1712635/53467742-59ac6680-3a0c-11e9-8d99-6f104a383ad9.png)

Here's the behavior:
![mlnet-tab-complete](https://user-images.githubusercontent.com/1712635/53468007-4f3e9c80-3a0d-11e9-9e8a-883faedf86fa.gif)

That happens no matter if I previously wrote something like:

`mlnet new --label-column-na` --> Should suggest `mlnet new --label-column-name`

`mlnet new --h` --> Should suggest `mlnet new --help`

No matter what, it always suggests  `--dataset`

**Comment by jonsequitur** [comment]
Does this also repro if you type `mlnet new label-column-na⇥`?

**Comment by CESARDELATORRE** [comment]
Yes, it happens the same thing, see below:

![mlnet-tab-complete-02](https://user-images.githubusercontent.com/1712635/53468677-0b996200-3a10-11e9-8f74-df6b2d42c161.gif)

**Comment by srsaggam** [comment]
Amazing! Thank you.

**Comment by CESARDELATORRE** [comment]
Thanks a lot! 👍

**Comment by CESARDELATORRE** [comment]
Btw, when is this fix available on the public NuGet feed? Is it available now?

**Comment by srsaggam** [comment]
@CESARDELATORRE I think its available in myget. I have tried out the latest package. There may be some other bug in here. I have set up a debug session with @jonsequitur  sometime today.

**Comment by jonsequitur** [comment]
Typically a new version of the package is available in the MyGet feed a few minutes after a merge.
