### ISSUE TITLE
RenderingPlayground is broken on Windows 1809

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/command-line-api#427]
As of commit ac704e24d18feab9a0a77421f46c08bb1121cc39, running RenderingPlayground on Windows has issues to the point of being broken. This is true whether run from PowerShell, CMD, or WSL's shell. The outputs are the same, so I'm just uploading screenshots from WSL.

Moby on WSL:
![image](https://user-images.githubusercontent.com/1119883/53585278-874ff780-3b53-11e9-8073-fe595324a8a1.png)

Colors on WSL:
![image](https://user-images.githubusercontent.com/1119883/53585313-9afb5e00-3b53-11e9-82c8-ec778d88af25.png)

GridLayout on WSL:
![image](https://user-images.githubusercontent.com/1119883/53585348-ae0e2e00-3b53-11e9-9f05-3f0730200fbb.png)

**Comment by jonsequitur** [comment]
We changed a behavior here a few weeks back when introducing directives for rendering, and the RenderingPlayground no longer auto-detects. The rendering directives can be used for all programs using `System.CommandLine.Rendering`, including RenderingPlayground.

Try this:

```console
RenderingPlayground.exe [enable-vt:true] [output:ansi]
```

Related functionality is here: https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.Rendering/CommandLineBuilderExtensions.cs

**Comment by SamuelEnglard** [comment]
Is there a way to enable auto-detect in my own apps?

**Comment by jonsequitur** [comment]
Yes, you can use `System.CommandLine.Rendering.CommandLineBuilderExtensions.UseAnsiTerminalWhenAvailable`.
