### ISSUE TITLE
OperationCanceledException should not be treated as an error

### ISSUE THREAD

**Issue by jnm2** [dotnet/command-line-api#430]
If you use a command handler that is cancellable:

```cs
CommandHandler.Create<IConsole, CancellationToken>(async (console, cancellationToken) =>
{
    while (true)
    {
        await Task.Delay(1000, cancellationToken).ConfigureAwait(false);
        console.Out.WriteLine("Still alive");
    }
}
```

There's a good chance in general that it will cancel by throwing TaskCanceledException or OperationCanceledException, since the TPL is designed around throwing these. `System.Threading.Tasks.Task` goes so far as to recognize these exceptions as cancellation rather than failure.

However, System.CommandLine treats it as though it was like any other exception. That causes this unpleasantness when the user presses Ctrl+C.

> ![image](https://user-images.githubusercontent.com/8040367/53697536-1bae9a00-3da0-11e9-9d74-c37074053818.png)

This exception should never be unhandled so long as the cancellation token has actually been set, since System.CommandLine should be expecting it.

([`OperationCanceledException.CancellationToken`](https://docs.microsoft.com/dotnet/api/system.operationcanceledexception.cancellationtoken) should be ignored because there are plenty of APIs that lose the cancellation token by having to use [`TaskCompletionSource.SetCanceled`](https://docs.microsoft.com/dotnet/api/system.threading.tasks.taskcompletionsource-1.setcanceled) or [`CancellationTokenSource.CreateLinkedTokenSource`](https://docs.microsoft.com/dotnet/api/system.threading.cancellationtokensource.createlinkedtokensource) in their implementation.)

**Comment by tmds** [comment]
If the default behaviour should be different, it can be done in the default exception handler (based on the exception type):

https://github.com/dotnet/command-line-api/blob/a58aa11718049db7a9e49a65cd52db4bfb42e38f/src/System.CommandLine/Invocation/InvocationExtensions.cs#L152-L163

Alternatively, the user can add a try-catch in his handler to deal with the cancellation.
