### ISSUE TITLE
Shared top-level options?

### ISSUE THREAD

**Issue by lorenh** [dotnet/command-line-api#457]
I'm feeling dense, but was hoping a pattern of shared top-level options was supported but can't figure out how it is done.  I was looking for a way to not have to specify options that all of my subcommands might share.  So I can define a handler for the following subcommand that would receive the values for both -a and -b.

I can't figure this pattern out:
  mycli.exe -a setting1 subcommand -b setting2

But as a workaround I can do it this way, it's just a lot of repeated options
   mycli.exe subcommand -a setting1 -b setting2

**Comment by jonsequitur** [comment]
One goal of the recent model binding improvements is to enable this kind of binding. Here's an example: https://github.com/dotnet/command-line-api/blob/ed2fad8e360fd792809f76a5b608d5863590cb93/src/System.CommandLine.Tests/Binding/ModelBinderTests.cs#L289

There's still work to be done to make this API easier to reach when defining your handler.

**Comment by jonsequitur** [comment]
@lorenh This should now be much more straightforward. You can reuse options and arguments at different positions, like this:

```cs
var optionX = new Option("-x");
var command = new RootCommand
{
     optionX,
     new Command("subcommand")
     {
          optionX
     }
};
```

This allows the option instance to be reused. The option is valid in either position, like this:

```console
> myapp [-x] subcommand
> myapp subcommand [-x]
```

And the subcommand's handler will bind to arguments and options from parent commands without needing specific configuration.
