### ISSUE TITLE
Suggestion on arguments

### ISSUE THREAD

**Issue by Poltuu** [dotnet/command-line-api#481]
Is there any way to add suggestion on arguments ?

This would be useful when an pseudo-open argument actual refers to a defined collection of item.

**Comment by Keboo** [comment]
@Poltuu yes there is an [extension method](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine/Builder/ArgumentExtensions.cs#L22-L30) on Argument that you can use to provide them. You can see an example of this in the [unit tests](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.Tests/SuggestionTests.cs#L22-L37).

**Comment by Poltuu** [comment]
thanks a lot :)
