### ISSUE TITLE
Documentation of use with dependency injection 

### ISSUE THREAD

**Issue by clmcgrath** [dotnet/command-line-api#482]
Does system.commandline support dependency injection via MEDI if so 
examples should be documented on the wiki 

if not can this be implemented ? seems like an important feature

**Comment by jonsequitur** [comment]
Agreed. 

The capability to bind arbitrary values by type is roughed in via the model binding infrastructure ([example](https://github.com/dotnet/command-line-api/blob/4fe9e05bee7a9698408d151a92faabd81ef04184/src/System.CommandLine/Binding/BindingContext.cs#L46)) but the API isn't exposed well yet.

We're also investigating integration with GenericHost: #440.

**Comment by TristanApc** [comment]
I have the same request. Considering that the integration with GenericHost is closed, was there any progress on the documentation for DI?

**Comment by osoykan** [comment]
Hi, I have written a [blog post](https://oguzhansoykan.com/posts/2020/2020-04-15-netcore-cli/) about how you use Dependency Injection, which also includes Aspnet.Core. I hope it helps.
