### ISSUE TITLE
Consider capability to disable validation and binding of parent command arguments when subcommand is specified

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#483]
Currently, a parent command's arguments are still validated when a subcommand is specified on the command line. Should the parent argument instead be ignored when a subcommand is specified? Should the parent command's arguments be bindable?

```cs
var parent = new Command("parent", argument: new Argument<string>())
{
    new Command("child")
};

var result = parent.Parse("child");

result.Errors.Should().BeEmpty(); // FAILS
```

**Comment by KathleenDollard** [comment]
I'm a bit confused by this. Are you saying this would not work?

```bash
> dotnet <projectname> add package <packagename>
```

And since the project name is optional, this needs to either assume other rules on the project name or take any project name except "add". Maybe @wli3 can comment on which the CLI does today

**Comment by jonsequitur** [comment]
This currently works for the same reason that the code sample I included fails: validation and binding of parent commands is unchanged when a subcommand is invoked. Required arguments are still required, etc. This is simpler and more intuitive, I think. 

The question is whether there should also be a way to support the example I gave, effectively making the argument required only when no subcommand was specified.

**Comment by KathleenDollard** [comment]
I didn't catch that this was an "also support". What's specifying that?

**Comment by Keboo** [comment]
Isn't this technically possible with the current API (albeit somewhat complex).

```C#
[Fact]
public void Argument_is_only_required_if_subcommand_is_not_specified()
{
    var onlyRequiredIfNoChildArgument = new Argument<string> { Arity = ArgumentArity.ZeroOrOne };
    onlyRequiredIfNoChildArgument.AddValidator(x =>
    {
        if (x.Children.OfType<CommandResult>().Any())
        {
            //Not required, sub command specified
            return null;
        }

        //Required
        return "Argument is required";
    });
    var parent = new Command("parent", argument: onlyRequiredIfNoChildArgument)
    {
        new Command("child")
    };

    var result = parent.Parse("child");

    result.Errors.Should().BeEmpty();

    result = parent.Parse("");

    result.Errors.Should()
        .Contain(e => e.SymbolResult.Name == "parent" &&
                      e.Message == "Argument is required");
}
```
