### ISSUE TITLE
Any way to detect a new version of the Global Tool package and warn the user?

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/command-line-api#489]
This probably applies to any .net core global tool. 
Since a CLI tool is an independent tool, we should be able to check out that there’s a new version available (at NuGet, etc.) and at least warn the user pointing to a URL with instructions for upgrading (or do any other action in the future).

But we need a way to detect if there's a new version available. Is there any way to do this?

**Comment by loic-sharma** [comment]
> But we need a way to detect if there's a new version available. Is there any way to do this?

Yes, there's several ways to do this. I'd recommend using the registration resource (see [this documentation](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource)). For example, you can find all the versions of `dotnet-format` using the following endpoint: https://api.nuget.org/v3/registration3-gz-semver2/dotnet-format/index.json

I've written a library, [`BaGet.Protocol`](https://www.nuget.org/packages/BaGet.Protocol/0.1.75-prerelease), that can do this. I would check out [`PackageMetadataService.GetAllVersionsOrNullAsync`](https://github.com/loic-sharma/BaGet/blob/master/src/BaGet.Protocol/Services/PackageMetadataService.cs#L44).

**Comment by CESARDELATORRE** [comment]
Closing this issue here and opening it at the https://github.com/dotnet/cli repo:
https://github.com/dotnet/cli/issues/11104
