### ISSUE TITLE
help should provide available values for bool, enum types, and others

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#490]
Current:

```console
RenderingPlayground:
  Demonstrates various rendering capabilities.

Usage:
  RenderingPlayground [options]

Options:
  --sample <SAMPLE>          <colors|dir> Renders a specified sample
  --height <HEIGHT>          The height of the rendering area
  --width <WIDTH>            The width of the rendering area
  --top <TOP>                The top position of the render area
  --left <LEFT>              The left position of the render area
  --text <TEXT>              The text to render
  --overwrite <OVERWRITE>    Overwrite the specified region. (If not, scroll.)
  --version                  Display version information
```

Suggested:

```console
RenderingPlayground:
  Demonstrates various rendering capabilities.

Usage:
  RenderingPlayground [options]

Options:
  --sample <Colors|Dir|Moby|Processes|TableView|Clock|GridLayout>    Renders a specified sample
  --height <HEIGHT>                                                  The height of the rendering area
  --width <WIDTH>                                                    The width of the rendering area
  --top <TOP>                                                        The top position of the render area
  --left <LEFT>                                                      The left position of the render area
  --text <TEXT>                                                      The text to render
  --overwrite <true|false>                                           Overwrite the specified region. (If not, scroll.)
  --version                                                          Display version information
```

**Comment by KathleenDollard** [comment]
I love displaying this.  I think it pushing the help text to the right, potentially out of view is not good. 

Can we concatenate the options at the end of the help text?

**Comment by jonsequitur** [comment]
There's always a larger enum...

I think some kind of heuristic for understanding when to truncate values or wrap would probably be useful.

**Comment by jonsequitur** [comment]
A suggestion (ha!) was made by @srsaggam to use the argument's `ISuggestionSource` to populate this list, rather than using the type. This is a much better approach than the one I've taken because the extensibility point is already in place and it doesn't depend on the type. `enum` and `bool` should just work.

An open question is how many values to show and what to show if the list is too long.

**Comment by srsaggam** [comment]
@CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
@jonsequitur - Why don't you show each possible value in a different line? Like the following:

--sample 
	Colors
	Dir
	Moby
	Processes
	TableView
	Clock
	GridLayout

**Comment by jonsequitur** [comment]
That would be a particularly useful approach if we had additional information to show to the right for each value. The API can't support that today, as they're just strings, but it's an interesting idea.

Another related question is for significantly long suggestion lists (say suggestions coming from an external API), we would want some kind of a cutoff or a way to decide not to try to render them all into help. This would probably be based in some way on the available space.
