### ISSUE TITLE
--help on command not working as expected when there is a validator attached

### ISSUE THREAD

**Issue by srsaggam** [dotnet/command-line-api#496]
When we run 
>sampletool foo --help 

we get the message 
 "Option required : --option1" and then help is displayed after that. Can we skip the error message/validation checks when --help is requested?

Here is the sample to repro:
```
var command = new System.CommandLine.Command("foo", handler){ option1() } ;

 command .Argument.AddValidator((sym) =>
            {
               if(!sym.Children.Contains("--option1"))
               {
                   return "Option required : --option1";
               }
               return null; 
            }

 Option option1() =>
                new Option(new List<string>() { "--option1" }, "sample description",
                new Argument<FileInfo>().ExistingOnly());

**Comment by srsaggam** [comment]
@CESARDELATORRE @jonsequitur

**Comment by Keboo** [comment]
@srsaggam what you are probably looking for is the [invocation middleware](https://github.com/dotnet/command-line-api/blob/6d244f5de41c39724a80793633416587dbb51cd4/src/System.CommandLine/Builder/CommandLineBuilder.cs#L48-L58) that can short-circuit the processing before the validation of arguments is done.
There is a built-in method for doing help output using it as well. You can see examples of using it [int he unit tests](https://github.com/dotnet/command-line-api/blob/732c0e685349a0e917e19fbe62bba4e26e430a3a/src/System.CommandLine.Tests/UseHelpTests.cs). The implementation of `.UseHelp()` is [here](https://github.com/dotnet/command-line-api/blob/4fe9e05bee7a9698408d151a92faabd81ef04184/src/System.CommandLine/Invocation/InvocationExtensions.cs#L271-L304).

**Comment by srsaggam** [comment]
@Keboo I'm using "UseDefaults" which seems to have UseHelp() encapsulated. 

```
public static CommandLineBuilder UseDefaults(this CommandLineBuilder builder)

        {

            return builder

                   .UseVersionOption()

                   .UseHelp()

                   .UseParseDirective()

                   .UseDebugDirective()

                   .UseSuggestDirective()

                   .RegisterWithDotnetSuggest()

                   .UseTypoCorrections()

                   .UseParseErrorReporting()

                   .UseExceptionHandler()

                   .CancelOnProcessTermination();

        }

**Comment by srsaggam** [comment]
To be more specific:
Here is the code which builds the parser:
https://github.com/dotnet/machinelearning/blob/c832e27457becbe29e07623efc7969e40b280313/src/mlnet/Program.cs#L64

Here is the command definition:
https://github.com/dotnet/machinelearning/blob/features/automl/src/mlnet/Commands/CommandDefinitions.cs

**Comment by srsaggam** [comment]
[TESTAPP.zip](https://github.com/dotnet/command-line-api/files/3109630/TESTAPP.zip)
Here is the repro of the issue, if anyone is interested.

**Comment by srsaggam** [comment]
Looks like we have figured out the issue. I have used -h alias for one of the option which looks like is reserved for help internally in framework. Changing the alias to something else solved the problem. Hence closing this issue. @jonsequitur
