### ISSUE TITLE
Experimental part of System.CommandLine.Experimental name.

### ISSUE THREAD

**Issue by DualBrain** [dotnet/command-line-api#504]
I was having a conversation a while back with @KathleenDollard regarding the Experimental part of the name.  Seems to me if the intent is to continue forward with something that is (and might be for some time) an out-of-band, community oriented, OSS project that is not part of core; why not use a name that reflects this.  Using the term Experimental, to me, just doesn't seem like the right term.  To me it encouraging little more than passing curiosity... my guess is that many will be hesitant to actually leverage.  I get that eventually everyone would like to see this as part of the core; but until that happens, is Experimental the right word?  What happens when it does become part of core?  Wouldn't it be possible that continued work could be done above-and-beyond what is adopted in the official core?  I'm a firm believer in not pointing something out without offering some solutions/alternatives... so please consider terms such as Community, GitHub, OSS, **Unofficial**, etc. instead?  If I'm alone in this regard, feel free to close without further ado... just adding this as a bit of food-for-thought to start a possible conversation.

Thanks.

**Comment by hummigbird1** [comment]
I'd say I have to agree!
"Experimental" was why I ignored this library for some time, thinking it was immature yet ...
Doesn't look so immature to me now that I have played with it.

**Comment by SamuelEnglard** [comment]
While I agree that I don't think experimental should be in the name, I think that comes more from the packages being alpha status. That alone should show that it is immature. And with the API having breaking changes every time I update, the alpha is warranted.

**Comment by jonsequitur** [comment]
We've published new versions System.CommandLine and associated packages without `Experimental` in the name. 

https://www.nuget.org/packages/System.CommandLine

The version number is still 0.3.0-alpha* for the moment. There are some breaking changes coming and we'll move to a higher version number once those are mostly out of the way. Please follow #700 for details.
