### ISSUE TITLE
what am I doing wrong (null option in receiver lambda)?

### ISSUE THREAD

**Issue by phi1ipp** [dotnet/command-line-api#526]
Hey guys,

Can anyone please tell me what I'm doing wrong with the following fragment
```
var aCommand = new Command("findCreator", handler: CommandHandler.Create<string>(async (string file) =>
{
    Console.WriteLine(file);
}));
aCommand.AddOption(new Option("--input", "input file name", new Argument<string>()));
root.AddCommand(aCommand);

root.InvokeAsync(args).Wait();
```

I run the app with `app findCreator --input filename` and getting `file` as `null` in my lambda.

Can anybody provide a hint please?

**Comment by jonsequitur** [comment]
It's not you, it's us. This is our most common gotcha. The binding is done by matching handler arguments to option or arguments by name. Rename `string file` to `string input`.

Also, you can use `FileInfo` instead of `string` if you like.

**Comment by phi1ipp** [comment]
Cool, thank you for the super prompt reply @jonsequitur!

It works now :) Yeah, I initially put it as FileInfo, but as I ran into issues I decided to make it bullet proof with a simple string. Turned out I ran into gotcha ;)

Cool, you can close it, or put it in a wiki.

Thank you for the cool library, keep going!

**Comment by jonsequitur** [comment]
Potential solution: #1012. Please comment.
