### ISSUE TITLE
Adding -f alias throws error NETSDK1013

### ISSUE THREAD

**Issue by hmobius** [dotnet/command-line-api#528]
I've been trying to break the simple demo you gave us. I believe I have found an issue when adding an alias of "-f" to an option. See this code

```
public static int Main(string[] args)
{
 Option sourceFileOption = new Option("--sourceFile", "Source file to analyse", new Argument<FileInfo>());
  sourceFileOption.AddAlias("-f");

  var rawXmlCommand = new Command("crx", "new subcommand");
  rawXmlCommand.AddOption(sourceFileOption);
  rawXmlCommand.Handler = CommandHandler.Create<FileInfo>((sourceFile) =>
  {
    Console.WriteLine($"Filename given: {sourceFile?.FullName ?? "empty string"}");
  });

  var rootCommand = new RootCommand("dpsutils");
  rootCommand.Add(rawXmlCommand);
  return rootCommand.InvokeAsync(args).Result;
}
```
Instead of the argument being parsed correctly, I get the following error message

```
C:\Program Files\dotnet\sdk\2.2.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value 'c:\temp\test.xml' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\Users\danma\Documents\Code\LanguageLab\src\LanguageLab.Apps\src\LanguageLab\Apps\General\LanguageLab.Apps.General.csproj]

The build failed. Please fix the build errors and run again.
```

If I change the alias to -s for instance, the alias works as expected.

**Comment by jonsequitur** [comment]
It appears that you've accidentally made a breaking edit in `LanguageLab.Apps.General.csproj`. Try setting `TargetFramework` to `netcoreapp2.2`.

**Comment by hmobius** [comment]
All projects in my solution had `TargetFramework` set to `netcoreapp2.2` way before I added `System.CommandLine.Experimental`. This particular csproj file looks like this. 

````
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.CommandLine.Experimental" Version="0.2.0-alpha.19174.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
````

Surely if it was something in the csproj file, changing the alias from -f to -s wouldn't matter would it?

**Comment by jonsequitur** [comment]
Changing the alias shouldn't produce a build error. 

I couldn't reproduce this. Can you share a more complete repro?

Thanks.

**Comment by hmobius** [comment]
@jonsequitur Sorry for delay in response. Was on holiday. Will try to reproduce this with minimal code and share.

**Comment by hmobius** [comment]
[Test.zip](https://github.com/dotnet/command-line-api/files/3263672/Test.zip)

@jonsequitur Here is a reduced codebase that still exhibits the problem. Full error message etc in program.cs. Let me know if you need more from me.

**Comment by jonsequitur** [comment]
Ah, I see what's happening now. 

This fails:

```console
temp> dotnet run crx -f c:\temp\test.xml
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(93,5): error NETSDK1013: The TargetFramework value 'c:\temp\test.xml' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [c:\temp\LanguageLab.Apps.General.csproj]
```

This works.

```console
The build failed. Please fix the build errors and run again.
temp> dotnet run -- crx -f c:\temp\test.xml
Element: e = 2
Element: hw = 2
Element: ph = 1
Element: pr = 1
```

If you include `--` after `dotnet run` then it tells `dotnet` that everything following the `--` is intended to be passed along to your program. Without that, `dotnet` grabs everything that matches one of its own options. `-f` is telling `dotnet` to use the next argument as the target framework, which it's not a valid value for, hence the build error.

**Comment by hmobius** [comment]
OK that makes sense, but why then if I change the alias to -s from - f does the call work without including the - -? If dotnet has no - s switch, doesn't that mean there is a bug to work on?

**Comment by jonsequitur** [comment]
`dotnet` has no `-s` option so it passes it along to your program. I think the inconsistency could be considered a `dotnet` bug, but changing it would be a significant breaking change.

**Comment by hmobius** [comment]
Well that's disappointing. 
Can I join the documentation effort on this project? If there are more issues like this I'd rather find and document them for others before they find them out.

**Comment by hmobius** [comment]
OK - closing this issue.
