### ISSUE TITLE
Allow arguments and options to be cloned

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/command-line-api#530]
If you have a tool with many commands and they take similar arguments or options, it would be nice to just specify the details of the argument or option once and then implicitly or explicitly clone the argument/option as it is added to more than one command.

Without this adding an argument or option to more than one command should be an error.

**Comment by AndyAyersMS** [comment]
Similar to #457

**Comment by jonsequitur** [comment]
One approach to this that has been discussed is the ability to reuse an option or argument directly without needing to clone it, e.g.:

```cs
var optionX = new Option("-x");
var command = new RootCommand
{
     optionX,
     new Command("subcommand")
     {
          optionX
     }
};
```

This would allow the option instance to be reused and signify that this option is available in both of these positions:

```console
> myapp [-x] subcommand
> myapp subcommand [-x]
```

Thoughts?
