### ISSUE TITLE
Not possible to bind option with dash in its name to method parameter

### ISSUE THREAD

**Issue by mgnslndh** [dotnet/command-line-api#538]
The documentation for syntax-first method binding states that:

>Parameters are matched using a naming convention that converts camel-cased parameters to kebab-cased options. In this example, the option --an-int matches parameter anInt on the DoSomething method.

However, it is not possible to have a command option named "--system-name" and bind it to a parameter `string systemName`

**Comment by Keboo** [comment]
Adding some sample code the reproduces the issue:
```C#
var outer = new Command("outer");
outer.AddOption(new Option("--system-name", argument: new Argument<string>()));

var inner = new Command("inner");
outer.AddCommand(inner);

inner.Handler = CommandHandler.Create((string systemName, ParseResult result) =>
{
    string sName = result.RootCommandResult.ValueForOption<string>("--system-name");
});

outer.Handler = CommandHandler.Create((string systemName, ParseResult result) =>
{

});
```
When invoked with `outer.InvokeAsync("outer --system-name foo");` the `systemName` parameter is appropriately passed. When invoking with `outer.InvokeAsync("outer --system-name foo inner");` the `systemName` is not passed, and you are forced to look it up from the `ParseResult`.

**Comment by jonsequitur** [comment]
This is now fixed.
