### ISSUE TITLE
Help should indicate whether arguments are optional or required, and indicate arity

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#543]
Help should use the common convention (`[<arg>]`) to indicate which options are required (i.e. minimum arity >= 1) versus optional. Support for multiple distinct arguments (#310) opens the way for cases like this:

```console
 > git pull [<options>] [<repository> [<refspec>...]]
```

Arguments having a maximum arity greater than 1 can be indicated by `...`

In the above example, `repository` has an arity of `ZeroOrOne` and `refspec` has an arity of `ZeroOrMore`. It could be configured like this:

```cs
var pull = new Command("pull")
{
    new Argument<string> { 
        Name = "repository",
        Arity = ArgumentArity.ZeroOrOne 
    },
    new Argument<string[]> { // string[] defaults to ZeroOrMore 
        Name = "refspec"
    },
};

```

**Comment by gitfool** [comment]
The code implies the `repository` and `refspec` arguments are optional to the `pull` command, with no relationship between them, but the help example shows `refspec` nested and so dependent on `repository`. Presumably there’s a convention here? How would one avoid nesting?

**Comment by jonsequitur** [comment]
This is because the arguments are satisfied positionally and in the order they're added to the parent command. It's not possible to specify `refspec` without first satisfying the `repository` argument up to its maximum arity (which is 1). The first token is consumed by `repository`. Subsequent tokens are consumed by `refspec`.
