### ISSUE TITLE
Change Argument constructor to accept name as the first parameter

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#544]
Currently, `Option` and `Command` accept a name parameter as the first constructor argument but for `Argument` the first argument is the default string value, resulting in an inconsistent API:

```cs
new Command("myapp")
{
    new Option("--abc"),
    new Argument<string> { Name = "xyz"  } 
}
```

The `Argument` constructor should be changed to accept the name in this position.

**Comment by adamhewitt627** [comment]
It looks like this has been resolved with b207fa37ae7255ecdbdcef31226dc7cc51e31599.
