### ISSUE TITLE
add span types for cursor control codes

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#546]
`System.CommandLine.Rendering.Span` is an abstraction that allows rendering output to be expressed without being specific to terminal capabilities. The various span visitor classes can then translate into `System.Console` calls (`NonAnsiRenderingSpanVisitor`) or VT-100 output (`AnsiRenderingSpanVisitor`) accordingly. (The `FileRenderingSpanVisitor` likely does not need changes.) We currently don't have a set of `Span` classes for cursor movements, but it would be very helpful for e.g. hiding and showing the cursor, etc. 

Examples of the kinds of operations available are here: https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.Rendering/Ansi.cs

**Comment by Keboo** [comment]
More context and details on this from the [live stream recording](https://youtu.be/kMghsCXZQ9Y?t=6126)
