### ISSUE TITLE
Integrate CancellationToken from InvocationContext into UseHost method

### ISSUE THREAD

**Issue by couven92** [dotnet/command-line-api#549]
With the newly merged `System.CommandLine.Hosting` extensions, @tmds raised the question whether the `UseHost` method should use/pass on a `CancellationToken` from the `InvocationContext`. To better separate the [discussion](https://github.com/dotnet/command-line-api/pull/533#discussion_r291921200) started in a closed [Pull Request (#533)](https://github.com/dotnet/command-line-api/pull/533), I decided to copy the thread and continue the discussion here.

## Background

In cases where you add hosted services in the generic host (e.g. by calling `AddHostedService()`) these services might take a while to start or to shutdown (depending on the nature of the service). For that reason, `IHost` supports passing a `CancellationToken` to the `StartAsync` and `StopAsync` methods which indicate whether start should be aborted immediately, or if graceful shutdown should be circumvented.

Currently we do not pass any `CancellationToken` to either `StartAsync` nor `StopAsync`, so startup and shutdown is always as graceful as can be, but during that time there is now way for the user to terminate the operation unless they forcefully kill the process (i.e. pressing CTRL+C does not immediately shut down).

## Proposal

I see two possible approaches for this problem. The second approach has two minor variations.

1. We could decide that starting and stopping the host is the responsibility of the user, meaning that they should call `StartAsync` and `StopAsync` in their own user-defined Command handler themselves.
   In this case you'd define your handler using e.g. `CommandHandler.Create<IHost, CancellationToken>(Run)`. The `CancellationToken` would be resolved from the `BindingContext` of the invocation and work together with `CommandLine` middleware like `CancelOnProcessTermination`.
2. If the `UseHost` could access the `ServiceProvider` property on the `BindingContext` class, the middleware could simply resolve the `CancellationToken` from the invocation `BindingContext` in the same way the arguments to a command handler are resolved. However, the `ServiceProvider` property of `BindingContext` is currently internal, making it inaccessible for `System.CommandLine.Hosting`.
   1. We could mark the internals of `System.CommandLine` visible to `System.CommandLine.Hosting` in order to be able to access the internal `ServiceProvider` property of `BindingContext`.
   2. We could make the `ServiceProvider` property as `public` and re-type the property to `IServiceProvider` to prevent people from adding services.

Personally, I tend to think that the 2<sup>nd</sup> approach is better. The first variant of that approach is the least impactful as it does not incur any changes in API surface. The seconds variant has more benifits as it enables developers to create their own more elaborate middleware by getting access to the services configured in the `BindingContext`.

----

@tmds https://github.com/dotnet/command-line-api/pull/533#discussion_r291921200

> @couven92 @jonsequitur it would be nice if we could use the `CancellationToken` from
> 
> https://github.com/dotnet/command-line-api/blob/a58aa11718049db7a9e49a65cd52db4bfb42e38f/src/System.CommandLine/Invocation/InvocationExtensions.cs#L19
> here.

----

@couven92 https://github.com/dotnet/command-line-api/pull/533#discussion_r291948719

> @tmds you can do that already. A handler taking both `IHost` and `CancellcationToken` as arugments would still gte the cancellation token from the `BindingContext` as you usually would already.
> 
> During the `AddMiddleware` method used in `UseHost` there is unfortunately no way to resolve services added to the `BindingContext`, since I cannot access its `ServiceProvider` property from within the `Hosting` project. And even we could, what would you have me do with the cancellation token? Use in the calls to `host.StartAsync()` and `host.StopAsync`?
> 
> I don't think it would be a great idea to add the cancellation token to the host service provider using `ConfigureServices`. If that was your intention, I'd much rather add the `CancellationTokenSource` obtained from the private field `_cts` in `InvocationContext`, but that might not be ideal either.

**Comment by tmds** [comment]
> And even we could, what would you have me do with the cancellation token? Use in the calls to host.StartAsync() and host.StopAsync?

Yes, pass the CancellationToken to these methods.
Or use your own Lifetime class that ties to the CancellationToken lifetime.

**Comment by couven92** [comment]
Yeah, I could get behind the idea of passing the CancellationToken to `StartAsync` and more importantly `StopAsync`, but we'd still need away to get the CancellationToken from the `InvocationContext` that is passed to the `UseHost` middleware, which is something that is not possible with today's API.

Alternatively, you could argue that we shouldn't call `StartAsync` and `StopAsync` at all, and let the handler (which COULD get a resolved `CancellationToken` as argument) do that.

**Comment by tmds** [comment]
> we'd still need a way to get the CancellationToken from the InvocationContext

https://github.com/dotnet/command-line-api/blob/c9450cba187e377f8c58c5a60d07767c5ebe6b9c/src/System.CommandLine/Invocation/InvocationContext.cs#L57

**Comment by couven92** [comment]
@tmds No, you'd not want to call `AddCancellationHandling()`. Because that will throw if someone already added cancellation handling, or prevent subsequent middleware from adding it. What you really want to do is get access to the `ServiceProvider` property on `BindingContext`. However, the problem here is that both your suggestion and mine are `internal` members. So, they cannot be accessed from within `System.CommandLine.Hosting`

**Comment by tmds** [comment]
> Because that will throw if someone already added cancellation handling, or prevent subsequent middleware from adding it.

The idea of this throwing is that there is one way of providing cancellation. So if you are adding a host, you should plug into the host API for cancellation.
The API can be made more liberal (if that is needed) so it doesn't throw if cancellation was already added.

**Comment by couven92** [comment]
@jonsequitur I updated the description on the top of the issue to include an actual proposal.

**Comment by couven92** [comment]
@tmds We were talking about the calls to `StartAsync` and `StopAsync`. You cannot use anything from inside the host to call these methods. The cancellation token passed into those methods are meant to come from outside of the hosting environment and simply affect startup cancellation and graceful shutdown of the host.

**Comment by tmds** [comment]
> We were talking about the calls to StartAsync and StopAsync. You cannot use anything from inside the host to call these methods.

Yes, these methods should be passed the InvocationContext CancellationToken.

What I mean is that middleware called when the host is started:

https://github.com/dotnet/command-line-api/blob/191210071f891e17a76abb686250c9c4f0d9a949/src/System.CommandLine.Hosting/HostingExtensions.cs#L45

should leverage the host APIs, like IHostedService.StopAsync/BackgroundService.StartAsync(CancellationToken)/IHostApplicationLifetime.

**Comment by couven92** [comment]
Exactly, so you don't want to add cancellation handling to the invocation pipeline (that's the job of another Middleware), you want to resolve a CancellationToken value that can be passed into StartAsync (in line 43) and StopAsync (line 47). The way to obtain the cancellation token is resolve it from the service provider of the binding context.

**Comment by tmds** [comment]
> But we cannot do that, because the service provider is internal.

It's not clear to me what this has to do with the service provider? Why not make public and call `invocation.AddCancellationHandling` to get the token?

Unrelated question: does the `UseHost` implementation imply that every command is using a host? Or can this be on a per-command basis?

**Comment by couven92** [comment]
@tmds As I said, `AddCancellationHandling` is to be called from middleware that adds the capability of cancellation (however the middleware sees fit) to the pipeline. `UseHost` does not do that. `UseHost` wants to **Use** whatever cancellation capabilities that was configured for the pipeline. Therefore, the `CancellationToken` should be resolved from the `BindingContext` service provider (NOTE: *not* the service provider of the host, they are completely separate entities).

**Comment by couven92** [comment]
@tmds As for your question regarding per-command basis. Yes, `UseHost` adds an `IHost` to the invocation pipeline. If you set up a per-command pipeline and only added the host to one of these pipelines that would work. However, in order to set up a per-command pipeline you'd have to implement some forking behaviour. I haven't done anything remotely related to that, but I guess it would be possible if you jumped through some hoops. Probably you'd do that be creating a new parser instance in a sub-branch and invoke it with the parse result obtained from the root invocation.

**Comment by couven92** [comment]
I took the liberty of opening PR #552 implementing what IMHO is the best solution for this.

**Comment by couven92** [comment]
#552 is merged
