### ISSUE TITLE
Specifying aliases and arities on options in the "Dragonfruit" model

### ISSUE THREAD

**Issue by hummigbird1** [dotnet/command-line-api#561]
Hey everyone 

just getting started with the Dragonfruit model of specifying commandline options and I like it.
What I did not find yet is the ability to specify aliases or arities (0-1, 1, 1-n, 0-n etc.) when using the declarative model (Dragonfruit)
Either it is not documented yet. I am blind for not finding it, or it doesn't exist yet (then pointers are appreciated ;))
However in the case it does not exist yet? Is it planned? 
I could imagine that this would be possible by adding attributes to the method parameter (e.g. as in ASP.NET core controller methods [FromBody], [FromQuery] etc.)

Anyway keep up the good work! So far I like what I see!

**Comment by jonsequitur** [comment]
Thanks, @hummigbird1!

In the vast majority of cases (including in DragonFruit), the correct arity of an argument will be inferred based on the type, e.g. enumerable types will have an arity of 0,* while non-enumerable types will have an arity of 1,1 (if there's no default value) or 0,1 (if there is a default value).  

There's some discussion about how to bring aliases into DragonFruit in #525.

Attribute-based approaches are being discussed as app models that sit on top of the core API, but this is a next step.

**Comment by hummigbird1** [comment]
Thank your for your response.

Unfortunately the inferring of arity does not appear to be working for a string parameter.
Considering the following method definition `static void Main( string inputPath, string filter = "*.*")`
I would expect inputPath to be a mandatory parameter with an arity of 1 but my assumption appears to be wrong.
Can you elaborate if I am really overlooking some intended logic here or did I just uncover one of thos minor cases not covered by the infer mechanism?

**Comment by jonsequitur** [comment]
Apologies. The behavior I described only applies to arguments, not options. 

Example:

```cs
static void Main(string argument) { }
```
gives you
```console
> dotnet run -- -h # string argument
Usage:
  myapp <argument>
```
and
```cs
static void Main(string argument = null) { }
```
gives you
```console
> dotnet run -- -h
Usage:
  mypapp [<argument>]
```

We don't support required options (yet: #560), and so neither does DragonFruit. I think the arity requirements should be made consistent between them once that's added.

Related, the naming convention for how an argument is identified is being expanded a bit (#555). Feel free to weight in on the proposal.

**Comment by octum-mf** [comment]
I am not quite sure if I understand the difference between argument and options.
I guess I will have to work with it some more to be better able to understand and grasp the concepts.

Since my original question does not directly apply anymore as I see it, feel free to close the issue (I don't seem to have that option)

**Comment by hummigbird1** [comment]
I am not quite sure if I understand the difference between argument and options.
I guess I will have to work with it some more to be better able to understand and grasp the concepts.
Since my original question does not directly apply anymore as I see it, I will close this issue for now.

**Comment by jonsequitur** [comment]
Is this helpful, or can you suggest how it can be improved? https://github.com/dotnet/command-line-api/wiki/Syntax-Concepts-and-Parser

**Comment by hummigbird1** [comment]
Ah yes, the difference between option and argument is getting clearer now.
A suggestion to improve the visibility of the difference would be to show option and argument in one example
like so (if I actually got it right) 
![image](https://user-images.githubusercontent.com/9641406/59716069-841d6c00-9215-11e9-8b78-a7d3a13ced19.png)
(Tried to add it as a text but couldn't figure out the way to get preformatted text here)
