### ISSUE TITLE
REPL Suggestions access

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/command-line-api#563]
I am implementing my own REPL ( Read Evaluate Print Loop) as I want to maintain state across commands.

```
while (prompt)
      {
        Console.Write("timewarp$");
        var args = Console.ReadLine().TrimEnd()?.Split(' ');

        if (args == null || (args.Length == 1 && string.IsNullOrEmpty(args[0]))) continue;

        try
        {
          _ = await Parser.InvokeAsync(args);
        }
        catch (Exception e)
        {
          Logger.LogError(e, "something broke");
        }
      }
```

I am wondering how do I get access to the `Suggestions` so I can implement tab completion?

Or is there a different way entirely to accomplish this?

**Comment by jonsequitur** [comment]
The `ParseResult.Suggestions` extenion method will provide suggestions.

**Comment by StevenTCramer** [comment]
Thanks much I got it working.
