### ISSUE TITLE
Implementing a custom directive

### ISSUE THREAD

**Issue by tmds** [dotnet/command-line-api#567]
I'm trying to build a directive. When it is invoked I don't want the default pipeline to execute, but do something alternative. The `UseMiddleware` method puts you at `MiddlewareOrder.Middle` which is too late.

I'm not sure if you want to expose `MiddlewareOrder`?
But perhaps we can add a public `UsePreprocessingMiddleware`?

**Comment by jonsequitur** [comment]
Yeah, I was hoping to avoid exposing the actual enum, but being able to provide some sort of ordering access is probably good. Which existing middlewares did you want to short-circuit?

**Comment by tmds** [comment]
> Which existing middlewares did you want to short-circuit?

I don't want to see the errors printed by `UseParseErrorReporting`.

But actually, thinking a bit more about my use-case, what I'm really trying to do is implement a command that doesn't show up in `--help`.

So I could do this as Middleware if I can set the order before printing parse errors. But then I can't take advantage of the parser.
Or I can do it as a command, but then I need to be able to indicate it shouldn't be included in help.

**Comment by tmds** [comment]
> Or I can do it as a command, but then I need to be able to indicate it shouldn't be included in help.

Closing, as I can do this using `IsHidden = true`.
