### ISSUE TITLE
Argument with custom converter and defaultValue?

### ISSUE THREAD

**Issue by mmierzwa11** [dotnet/command-line-api#581]
Is it possible to define custom converter for argument and defaultValue?

**Comment by Keboo** [comment]
@mmierzwa11 at present the Argument class has constructors for specifying delegates for either [default value](https://github.com/dotnet/command-line-api/blob/b207fa37ae7255ecdbdcef31226dc7cc51e31599/src/System.CommandLine/Argument%7BT%7D.cs#L23), or [custom converter](https://github.com/dotnet/command-line-api/blob/b207fa37ae7255ecdbdcef31226dc7cc51e31599/src/System.CommandLine/Argument%7BT%7D.cs#L28). If you wanted both you would need to handle the "default" as part of your TryConvertArgument delegate.

**Comment by mmierzwa11** [comment]
I thought so at first, but from what I see CustomConverter is only invoked if option is specified, and default value delegate is always invoked - I want both behaviors for my option.

**Comment by jonsequitur** [comment]
@mmierzwa11 Are you wanting to feed the output of the `defaultValue` delegate into a custom converter? Can you describe a little more generally what you're looking to do?

**Comment by mmierzwa11** [comment]
I don't quite remember what was the purpose exactly, but I think I wanted custom converter for byte array (written in hex notation), with default value if not specified.

**Comment by qmfrederik** [comment]
I have two use cases which I think require me to

**Comment by qmfrederik** [comment]
I have two use cases which I think would benefit from having a custom converter which is able to specify a default value:

- One case is an option where user specifies a path to a license file. The type for this option is `License`. Ideally:
  - If a user specifies a path, we resolve the path and create a `License` object for it
  - If a user does not specify a path, we look in a couple of "well known" locations (e.g. working dir, app data,...) for a license file
- A second option where the user specifies the ID of a device connected to her/his computer. The type for this option is `Device`. Ideally:
  - If the user does not specify a value, check whether one (and only one) device is connected and return that value, or error out
  - If the user does specify a value, convert that value (or error out)

As @mmierzwa11 indicates, if you specify a custom converter, that converter is not invoked when the option is not specified, so I don't think these scenarios are currently possible.

**Comment by dashesy** [comment]
I have inline `Option`  that pass to `Command`. 
Currently I have

```C#
                new Option(
                    new[] { "--output", "-o" },
                    "File path to output the results. Pass null to suppress outputs. (Default=stdout)")
                {
                    Argument = new Argument<TextWriter>(TryConvertOutputStream)
                },
```

That I would like to have 

```C#
                new Option(
                    new[] { "--output", "-o" },
                    "File path to output the results. Pass null to suppress outputs. (Default=stdout)")
                {
                    Argument = new Argument<TextWriter>(TryConvertOutputStream, "stdout")
                },
```

Then if `--output` is not specified automatically `TryConvertOutputStream` is used along with `stdout` to create the type.
