### ISSUE TITLE
Rename CommandLineBuilder.UseMiddleware extension method

### ISSUE THREAD

**Issue by darinclarkdev** [dotnet/command-line-api#588]
You can call UseMiddleware multiple times and each one will be added to the pipeline. The name implies if you called it twice only the last call would be applied. It is a fluent wrapper over the internal void CommandLineBuilder.AddMiddleware.

**Comment by jeredm** [comment]
@darinclarkdev I understand what you mean by "Add" vs. "Use"; however, it seems that "Use" is more of the .NET Core convention. Here is some documentation that has middleware examples for other systems in .NET Core: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2

**Comment by darinclarkdev** [comment]
In that documentation the generic add command is ".Use" in my opinion that is clearer. The other concrete Middleware methods like UseDefaults are single use aren't they?

**Comment by jonsequitur** [comment]
My impression is that "add" shouldn't be used for something that's idempotent, whereas "use" should indicate that the method is idempotent.
