### ISSUE TITLE
Hidden arguments are displayed by HelpBuilder for subcommands

### ISSUE THREAD

**Issue by sloscialo** [dotnet/command-line-api#589]
Build: 0.3.0-alpha.19317.1

When generating help for the parent command, hidden arguments are shown for subcommands.

> CommandLine:
>   Testing help builder.
> 
> Usage:
>   CommandLine [command]
> 
> Commands:
>   outer \<test name\>    command Test description.

"test name" is the name of a hidden argument for the "outer" subcommand. Since it's marked hidden, I don't believe it should be written out here.

I _believe_, but not certain (I only just started using this library) that the problem is in lines 333-346 of HelpBuilder.cs :

```if (ShouldShowHelp(symbol))
            {
                foreach (var argument in symbol.Arguments())
                {
                    if (!string.IsNullOrWhiteSpace(argument.Name))
                    {
                        var argumentDescriptor = ArgumentDescriptor(argument);
                        if (!string.IsNullOrWhiteSpace(argumentDescriptor))
                        {
                            option = $"{option} <{argumentDescriptor}>";
                        }
                    }
                }
            }
```

**Comment by Icontech** [comment]
I believe that you're right. The first if-clause should probably be changed to: 
`if (ShouldShowHelp(argument) && !string.IsNullOrWhiteSpace(argument.Name))`
to resolve this issue. I'm looking into modifying the `ShouldShowHelp` method in #586, but might be able to take a look at this issue when I'm done.
