### ISSUE TITLE
Unhandled Exception: System.ArgumentException: Incorrect token type

### ISSUE THREAD

**Issue by 0xNOP** [dotnet/command-line-api#590]
I wanted to use System.CommandLine dragon fruit model in my tool but I'm getting this exception.

```csharp
async Task Main(string outputFilename = "third-party-notices.txt", string argument = null)
```

I want to pass just an argument, skipping outputFilename. Like:

`dotnet MyApp "Some Argument"`

**Comment by jonsequitur** [comment]
I was unable to reproduce this error.  

One thing to note is that you don't need to call `dotnet`. Once you've run `dotnet publish` you can invoke your app like this:

```console
> MyApp "Some Argument"
```

If that doesn't solve it, more detailed repro steps and a stack trace would be helpful.

Thanks.

**Comment by 0xNOP** [comment]
@jonsequitur it looks like it works in the latest releases, could be a bug in a previous release

**Comment by jonsequitur** [comment]
Thanks!
