### ISSUE TITLE
Forcing C# version to 7.1 messes up a project on .NET Core 3/C#8

### ISSUE THREAD

**Issue by marklio** [dotnet/command-line-api#594]
The targets file in the NuGet package forces the version to 7.1 if it isn't set. This is at odds with "new" .NET SDK projects where the language version is set as a byproduct of the target framework. It should be made aware of these new kind of projects.

**Comment by Trolldemorted** [comment]
Is there a way to use DragonFruit in projects that use `<Nullable>enable</Nullable>`?

Is there a timeframe when this will be fixed? dotnet core 3.0 has been stable for a while now.
