### ISSUE TITLE
"Unrecognized command or argument" for string options

### ISSUE THREAD

**Issue by dashesy** [dotnet/command-line-api#602]
I have 

```
var configOption = new Option(new[] {"-c", "--config" }, "configuration path");
```

But cannot pass the path to the file (also used quotes)

> Unrecognized command or argument 'D:/development/cfg.txt'

**Comment by jonsequitur** [comment]
The option's argument needs to be configured. Try this:

```cs
var configOption = new Option(new[] {"-c", "--config" }, "configuration path")
{
    Argument = new Argument<FileInfo>()
};
```

**Comment by dashesy** [comment]
I saw [this](https://github.com/dotnet/command-line-api/wiki/Your-first-app-with-System.CommandLine) in the example

```C#
    Option optionThatTakesInt = new Option(
        "--int-option",
        "An option whose argument is parsed as an int",
        new Argument<int>(defaultValue: 42));
```

But `Option` constructor in the nuget did not have a third input, so I thought that must be newer than nuget.
The documentation needs some update?

**Comment by jonsequitur** [comment]
Yes, it looks like that doc is out of date. Thanks for pointing that out.
