### ISSUE TITLE
Is there a way to specify a fallback command?

### ISSUE THREAD

**Issue by alexrp** [dotnet/command-line-api#604]
I have a project where I have a number of sub-commands. I'd like to make it so that if no sub-command is given by the user, a predetermined sub-command (say, `foo`) is executed.

I'm currently doing this by adding logic to the `RootCommand`. While this works mostly fine, it does mean that any options I add to it will appear in the `myapp -h` output as if they are global options applicable to all sub-commands, which is confusing for users. I'd prefer if these options only showed up when doing `myapp foo -h`.

Is there a cleaner way to achieve what I'm trying to do here?

**Comment by jonsequitur** [comment]
Can you give more detailed examples of what you want the command line and help to look like?

**Comment by alexrp** [comment]
Something like this:

```console
$ myapp -h
Usage:
  myapp [options] [command]

Options:
  --version    Display version information

Commands:
  build        Build binaries of a project.
  clean        Clean build artifacts of a project.
  run          Run an executable project (default command).
$ myapp run -h
run:
  Run an executable project (default command).

Usage:
  myapp run

Options:
  --cwd        Set working directory
$ myapp run --cwd /home/foo
Running project in /home/foo...
$ myapp --cwd /home/bar
Running project in /home/bar...
```

So if the user doesn't explicitly specify a command, `run` (or whatever command the programmer has specified) would be the fallback command. This is already achievable by setting `RootCommand.Handler`, but the important bit is that the options for the `run` command do not show up in the global `myapp -h`, only `myapp run -h`.

**Comment by alexrp** [comment]
Would it be possible to do this with a middleware function, perhaps? I suspect all I really need to implement what I described above is to detect whether a command was matched, and if not, then redirect to a command that I choose.

**Comment by jonsequitur** [comment]
Yes, this should work. You can reparse the input and reassign the `BindingContext.ParseResult`. Here's an example: https://github.com/dotnet/command-line-api/blob/9604cdfd8e277f346df63077c712af7d99cff030/src/System.CommandLine.Tests/Invocation/InvocationPipelineTests.cs#L168

**Comment by alexrp** [comment]
Here's what I ended up with: https://github.com/flare-lang/flare/blob/master/src/cli/Program.cs

I ran into two issues with this (you can see both in the linked code):

1. Presumably I can hide the fallback command (`ScriptCommand` in this case) by setting `IsHidden` and adding it to the `RootCommand`. However, I'm not sure how to locate the `ScriptCommand` from the `InvocationContext` within the middleware function.

This is obviously not a huge deal, but adding the `ScriptCommand` instance to the `RootCommand` from within the middleware function just feels kinda hacky.

2. The `System.CommandLine.Invocation.ParseErrorResult` class is `internal`. This means that I had to [roll my own](https://github.com/flare-lang/flare/blob/master/src/cli/ParseErrorResult.cs), which has the downside that I can't easily print the help message (as the `BindingContext.HelpBuilder` property is also `internal`).

The reason I need to roll my own is that `UseParseErrorReporting()` installs its function before all user-provided middleware functions. So if I use it, I don't get a chance to intercept the parse error and redirect to `ScriptCommand`.

**Comment by jonsequitur** [comment]
This is really helpful feedback.

For the first issue, you should be able to get to your real `ScriptCommand` instance via `InvocationContext.ParseResult.Parser.Symbols`. Any thoughts about a more convenient API?

There's been some discussion about making it possible to specify middleware order. This of course makes it easier to break some of the built-in functionality, such as exception handling, but for cases like this, the added flexibility is probably worthwhile.

**Comment by alexrp** [comment]
I managed to locate the `ScriptCommand` by doing `context.ParseResult.Parser.Configuration.RootCommand.Children.OfType<ScriptCommand>()`. A fair bit of dotting there, but otherwise seems reasonable enough.

Being able to specify middleware order would be great. I don't see any getting around the potential for breaking built-in middleware functions, but I imagine if someone needs to go down that road, they understand the implications.

**Comment by jonsequitur** [comment]
I've made `ParseErrorResult` public and opened #649.
