### ISSUE TITLE
Display default values when running help command

### ISSUE THREAD

**Issue by Marcel-Lambacher** [dotnet/command-line-api#619]
I would like to see the defined default values when I request the parameter help command.
If this is not possible by default, I would be really interested to implemented it accordingly.

**Given** is the following strongly typed main definition:
```cs
static void Main(int intOption = 42, bool boolOption = false, FileInfo fileOption)
{
    Console.WriteLine($"The value of intOption is: {intOption}");
    Console.WriteLine($"The value of boolOption is: {boolOption}");
    Console.WriteLine($"The value of fileOption is: {fileOption?.FullName ?? "null"}");
}
```

**When** running the help command:
`> ./myapp -h # or: dotnet run -- -h`

**Then** the default values should be displayed in the arguments documentation:
```
> dotnet run -- -h
Usage:
  myapp [options]

Options:
  --int-option  (Default value: 42)        An option whose argument will bind to an int
  --bool-option (Default value: false)     An option whose argument will bind to a bool
  --file-option                            An option whose argument will bind to a FileInfo
```

**Comment by Marcel-Lambacher** [comment]
Okay, as the labels has been added I'll work on this task, thanks :)

**Comment by CaptainGinja** [comment]
I also would like this feature.  Are there any plans to integrate this functionality into the master branch?

**Comment by NikiforovAll** [comment]
I like this feature and I would like to deliver this feature. Unfortunately, @Marcel-Lambacher hasn't done PR for quite some time.

**Comment by jonsequitur** [comment]
I'm happy to help anyone who would like to put together a PR for this.
