### ISSUE TITLE
Code on wiki doesn't compile

### ISSUE THREAD

**Issue by darkl** [dotnet/command-line-api#624]
Hi,
The code on this [page](https://github.com/dotnet/command-line-api/wiki/Your-first-app-with-System.CommandLine) doesn't compile. I tried modifying it, but my modification results with a program that doesn't autofill the unspecified arguments with their default values.

Thanks for your help
Elad

**Comment by darkl** [comment]
Ok, I made it work. Maybe it's worth mentioning that the options aliases should be the same as the parameters passed to delegate in `CommandHandler.Create` (I though these names are not important and they are delivered in the order you add the arguments to the options to your Command).

Elad

**Comment by jonsequitur** [comment]
Thanks, @darkl. I've updated the wiki entry with code using the latest API.
