### ISSUE TITLE
CommandLineBuilder.UseMiddleware how to use

### ISSUE THREAD

**Issue by phi1ipp** [dotnet/command-line-api#627]
Hi guys,

I'm using `syntax` approach how you call it with no explicit `CommandLineBuilder`. I wonder how can I insert `UseMiddleware` into this approach?

TIA

**Comment by jonsequitur** [comment]
The `CommandLineBuilder` is just providing a way to compose arguments that ultimately get passed into the `CommandLineConfiguration` constructor. The argument you need to supply is this one:

https://github.com/dotnet/command-line-api/blob/9604cdfd8e277f346df63077c712af7d99cff030/src/System.CommandLine/CommandLineConfiguration.cs#L25

**Comment by phi1ipp** [comment]
Well, I guess I need to rephrase...

I'm doing something like the following. So was bit confused where am I supposed to deal with `CommandLineConfiguration`?

```
            var root = new RootCommand();

            var aCommand = new Command(...);
            root.AddCommand(aCommand);

            root.InvokeAsync(args).Wait();
```

**Comment by jonsequitur** [comment]
`InvokeAsync` is a convenience method but I suppose it's not as convenient for this scenario. 

Further down, `InvokeAsync` is creating a `CommandLineBuilder` which creates a `CommandLineConfiguration`. Eventually, a `CommandLineConfiguration` is needed to create a `Parser`. This is where the invocation middleware, parser options, and command definitions all come together.

**Comment by phi1ipp** [comment]
Yeah, seems like something is missing on this route... So no really other way to expose Config or Builder for my scenario?

**Comment by jonsequitur** [comment]
The above are all public APIs so you can compose them in various ways.

Do you have a more convenient API proposal in mind?

**Comment by phi1ipp** [comment]
Oh, my bad, I see what you mean now! I didn't really do my part of the deal, sorry :) 

Let me try it, but it should be fine as far as I can see.

Thank you @jonsequitur

**Comment by phi1ipp** [comment]
Well, I thought it'd be easy, but I stumbled on this fragment inside `InvokeAsync` where `InvocationPipeline` is internal class, so I can't reproduce the same logic.
```
return await new InvocationPipeline(parseResult)
                       .InvokeAsync(null);
```

Can you suggest something please?

**Comment by jonsequitur** [comment]
Once you create an instance of a `Parser` you can use one of the `InvokeAsync` extension methods on `InvocationExtensions`.

**Comment by phi1ipp** [comment]
OMG, I'm dumb :( 

Sure, thank you for the hint @jonsequitur
