### ISSUE TITLE
Parsing two FileInfo arguments doesn't work

### ISSUE THREAD

**Issue by mahardan-oup** [dotnet/command-line-api#628]
I'm testing against v0.3.0-alpha.19405.1

I have the following code. The idea is to process a file and if specified use the comparison file in the processing. However, while the sourceFile option creates a FileInfo object absolutely fine, the comparisonFile is always null regardless of whether it is a FileInfo object, a string when the call to the Reporter constructor is called.

I'm calling `dotnet run uxs --compareTo c:\temp\compareFile.txt --sourceFile "c:\temp\source.xml"`

Would greatly appreciate advice. Is this a bug? here is my Program.cs

```
    internal class Program
    {
        public static int Main(string[] args)
        {
            var cmdBuilder = new CommandLineBuilder();
            var rootCommand = cmdBuilder.GetRootDpsUtilsCommand();
            return rootCommand.InvokeAsync(args).Result;
        }
    }
```

In the CommandLineBuilder class file

```
internal RootCommand GetRootDpsUtilsCommand()
{
   var rootCommand = new RootCommand("dpsxml");
   rootCommand.Add(BuildUniqueXmlStructureCommand());
   return rootCommand;
}

private Command BuildUniqueXmlStructureCommand()
{
    var uxsCommand = new Command("uxs");
    Option sourceFileOption = new Option(new string[] { "-f", "--sourceFile" }, "Source file") { Argument = new Argument<FileInfo>(){ Arity = ArgumentArity.ExactlyOne } };
    Option comparisonFileOption = new Option(new string[] { "-c", "--compareTo" }, "Comparison") { Argument = new Argument<FileInfo>(){ Arity = ArgumentArity.ZeroOrOne } };
    uxsCommand.AddOption(comparisonFileOption);
    uxsCommand.AddOption(sourceFileOption);

    uxsCommand.Handler = CommandHandler.Create<FileInfo, FileInfo>((comparisonFile, sourceFile) =>
    {
        Reporter uxs = new Reporter(comparisonFile, sourceFile);
        uxs.Go();
    });

    return uxsCommand;
}   
```

Thank in advance

**Comment by jonsequitur** [comment]
Binding is based on the name of the parameters in your handler. If you rename the handler parameters like this it should work:

```csharp
uxsCommand.Handler = CommandHandler.Create<FileInfo, FileInfo>((compareTo, sourceFile) =>
```

**Comment by hmobius** [comment]
Ah - that did it. Looked again at wiki and can't find this advice anywhere.
How can I suggest changes to the wiki for this kind of thing? Raise another issue?

**Comment by jonsequitur** [comment]
Another issue is perfect. 

This is [documented ](https://github.com/dotnet/command-line-api/wiki/How-To#syntax-first)so the problem might be discoverability.

**Comment by mahardan-oup** [comment]
I must admit I had not seen that so thanks for pointing it out.
