### ISSUE TITLE
Extend User-Type Binding Support in CommandHandler.Create(MethodInfo method)

### ISSUE THREAD

**Issue by fitdev** [dotnet/command-line-api#632]
Right now there are 2 limitations when working with user-typed arguments and options:

1. Only constructors accepting exactly 1 argument of type `string` are being looked at for user type instantiation during binding. Could this be extended to _also_ include those constructors where the first and the only required parameter is `string`, but that also contain _optional_ parameters.

2. Even if the constructor requirement for user types is fully satisfied (i.e. it has a public constructor accepting just `string` as its only parameter), commands whose handler has been created via `CommandHandler.Create(MethodInfo method)`, or equivalently any other Func/Action-based overload thereof, do not still instantiate user types when those types are used as arguments, i.e.:

```
public static void CustomCommand(UserTypedArgument arg1, bool option1 = true) {
//UserTypedArgument is null here even if it has a public constructor accepting string
}
```

**Comment by jonsequitur** [comment]
These are both great suggestions. The first one is probably fairly straightforward. The second one gets more complex because it's recursive and the expected behavior might not be intuitive, e.g. 

```csharp
public static void CustomCommand(UserTypedArgument1 arg1, bool option1 = true) {

}

// SNIP

public class UserTypedArgument1 
{
    public UserTypedArgument1(UserTypedArgument2 arg2) { } 
}


public class UserTypedArgument2
{
    public UserTypedArgument2(string value) { } 
}
```

Would you mind opening these as separate issues?

**Comment by fitdev** [comment]
Not sure I understood what you mean in your example, since in it `UserTypedArgument1` does _not_ have a parameterless constructor - its constructor requires 1 parameter of type `UserTypedArgument2`. I meant that currently binding does not work for user types _even if they have a public parameterless constructor_ (so there is no ambiguity which constructor to use). On top of that, I verified that such constructors for user types do get called correctly - though their results (i.e. instantiated user types) are not bound to the appropriate method parameters (so those are `null`s as far as the method code is concerned).

> Would you mind opening these as separate issues?

You mean I should create 2 new issues for 1 and 2, and you will close this one? Sure, I can do that.

**Comment by jonsequitur** [comment]
Yes, please open these as separate issues.
