### ISSUE TITLE
the naming is confusing

### ISSUE THREAD

**Issue by adamralph** [dotnet/command-line-api#635]
"System.CommandLine" and "command-line-api" seem to be being used interchangeably in the repo name, README, package names, and elsewhere.

Can we choose one and use it throughout?

**Comment by jonsequitur** [comment]
The intention is that `command-line-api` is the repo name because it contains multiple projects (including the `dotnet-suggest` tool) and namespaces, and because the namespaces are subject to change.

Did you find examples inconsistent with that?

**Comment by adamralph** [comment]
![image](https://user-images.githubusercontent.com/677704/64290500-1eac6200-cf5e-11e9-8f18-9d231ed6418b.png)

![image](https://user-images.githubusercontent.com/677704/64290519-223fe900-cf5e-11e9-8a4a-d8b5be4aa1bc.png)

![image](https://user-images.githubusercontent.com/677704/64290526-25d37000-cf5e-11e9-8cb4-e1bb22b2c154.png)

**Comment by adamralph** [comment]
> command-line-api is the repo name because it contains multiple projects (including the dotnet-suggest tool)

I guess it would be good to have that front and centre, perhaps at the top of the README.

**Comment by brandonschmidt** [comment]
I also found this confusing.  I expected system-commandline-api to have the code required to wrap System.CommandLine and expose it for extension via an API, but not the code for System.CommandLine itself.

**Comment by adamralph** [comment]
This seems to be largely fixed. The only remaining thing which is a bit confusing is the repo description:

![image](https://user-images.githubusercontent.com/677704/77821368-1d08de00-70ea-11ea-883d-e0ab7678a874.png)

IMO the prefix "System.Commandline: " should be removed.

**Comment by jonsequitur** [comment]
That was added explicitly because someone said after we renamed the repo to command-line-api that the repo name didn't communicate that this is the home of the System.CommandLine library.

**Comment by adamralph** [comment]
@jonsequitur this repo is also the home of `dotnet-suggest`, so by that logic, that should also appear in the description, as should the name of any further packages that may be added in the future.

This repo produces multiple packages. It doesn't feel right to pick one of them and put its name in the description.

The first line of `README.md` says:

> This repository contains the code for the System.CommandLine libraries and the `dotnet-suggest` global tool.

That seems clear enough, and can more package names can be added to this sentence in the future if required.

**Comment by adamralph** [comment]
Based on the arguments in my previous comment, I propose we remove the  "System.Commandline: " prefix from the repo description.

**Comment by adamralph** [comment]
Any reaction to my proposal? It's a change which will only take a few seconds. Please either make the change or close this issue.

**Comment by jonsequitur** [comment]
> Please either make the change or close this issue.

How about both? :smile:
