### ISSUE TITLE
Support of unnamed arguments?

### ISSUE THREAD

**Issue by ibigbug** [dotnet/command-line-api#647]
Hi,

Can I have my program support usage like this:

```bash
$git add a.txt
```

where `a.txt` is passed to a handler without having a name like `git add --file a.txt`

If so, is there any documentation/sample for this kind of usage?

Thanks,

**Comment by jonsequitur** [comment]
You can do this with a command argument:

```cs
var addCommand = new Command("add")
{
    new Argument<FileInfo>("file") //         <-- ARGUMENT NAME...
};
addCommand.Handler = CommandHandler.Create(
    (FileInfo file)) => //                         <-- ...MATCHES HANDLER PARAMETER NAME
    {  
    });
```

The name isn't passed on the command line, so you can invoke it just like in your example. But the name *is* used when binding to your command handler, so they should match.

**Comment by ibigbug** [comment]
this worked. thanks @jonsequitur !

**Comment by tbolon** [comment]
Thanks @jonsequitur, I was currently writing a new issue when this suggestion appeared in the github editor... This example should be included in the docs.
