### ISSUE TITLE
Inferred options based on order

### ISSUE THREAD

**Issue by cmeyertons** [dotnet/command-line-api#657]
In Powershell, you can leave out the option name, like

```ps
Join-Path -Path "path1" -ChildPath "path2"
Join-Path "path1" "path2" # same as above, inferred
```

Does `system.commandline` support this?

I would think it would create some headaches for the parser to try to distinguish between a default option and a possible subverb.

**Comment by jonsequitur** [comment]
We don't currently support this. Some work was done on this approach but there were a number of parsing ambiguities that caused difficulties for completions and error messages. The idea is appealing though and it might be revisited at some point.
