### ISSUE TITLE
Make a NuGet release?

### ISSUE THREAD

**Issue by mariopasquali** [dotnet/command-line-api#667]
Hi all,

The last version in NuGet is from 3 months ago.  Would it be possible to do a fresh release?  I know there are the nightly builds but this is not a good option for my specific case. 

Thank you,
Mario

**Comment by mariopasquali** [comment]
Anyone?  Any reason to not make a NuGet release?  The current NuGet version is very old and buggy.

**Comment by jonsequitur** [comment]
Coming right up, after #687 is in.

**Comment by jonsequitur** [comment]
I just released package updates on nuget.org. Give them a try and let us know what you think.

**Comment by mariopasquali** [comment]
Thank you for your help!  I tried migrating to this version and found issue #689, please check if valid.
