### ISSUE TITLE
Commands with arguments and options

### ISSUE THREAD

**Issue by Faustvii** [dotnet/command-line-api#675]
Hello, I've stumbled upon something that is not acting as I would've expected, maybe because I've misunderstood something.
I've tested on version `0.3.0-alpha.19405.1` and `0.3.0-alpha.19528.1`
Invoking the below command with args `["test", "Faust","--bool"]` produces the following output
```
Nice to meet you 
The value for --bool-option is: False
```
I would've expected a `Nice to meet you Faust` and the `bool-option` to be true but maybe I've misunderstood something or am I doing some obvious mistake?

```c#
        static int Main(string[] args) {
            var testCommand = new Command("test", "A argument and an option");
            testCommand.AddArgument(new Argument<string>("name"));
            testCommand.AddOption(
                new Option(
                    "--bool",
                    "An option whose argument is parsed as a bool") {
                    Argument = new Argument<bool>(),
                });

            testCommand.Handler = CommandHandler.Create<string, bool>((stringOption, boolOption) => {
                Console.WriteLine($"Nice to meet you {stringOption}");
                Console.WriteLine($"The value for --bool-option is: {boolOption}");
            });

            var rootCommand = new RootCommand() {
                testCommand
            };
            return rootCommand.InvokeAsync(args).Result;
        }
```
Looking forward to hearing from you.

**Comment by jonsequitur** [comment]
This is our most common gotcha. The parameters are matched based on the names of the arguments or options. If you change your handler code to the following, it will work as expected:

```csharp
            testCommand.Handler = CommandHandler.Create<string, bool>((name, @bool) => {
                Console.WriteLine($"Nice to meet you {name}");
                Console.WriteLine($"The value for --bool-option is: {@bool}");
            });
```

**Comment by Faustvii** [comment]
Fantastic, that works. Thanks for the quick response.

**Comment by LeaFrock** [comment]
> This is our most common gotcha. **The parameters are matched based on the names of the arguments or options**. 
@jonsequitur Excuse me, I don't find any instructions in the wiki page and have wasted a long time until I see your reply. I think it should be informed in the wiki page.
