### ISSUE TITLE
Show that an option is required on help

### ISSUE THREAD

**Issue by giggio** [dotnet/command-line-api#693]
Now that required options is implemented (see #560), it is important that the required options have some type of indication on the help docs.

This is an example from `az`, which shows `[Required]` when an option is required:

````
$ az account set --help

Command
    az account set : Set a subscription to be the current active subscription.

Arguments
    --subscription -s [Required] : Name or ID of subscription.
````

That would be good enough, IMO.

**Comment by jonsequitur** [comment]
How does this look? The square brackets already signify "optional" in the synopsis so I tried parentheses:

```console
-o, --the-option <arg-name> (REQUIRED)
```
