### ISSUE TITLE
[Feature] Alias for sub-commands

### ISSUE THREAD

**Issue by dashesy** [dotnet/command-line-api#702]
It would be nice to have aliases for sub-commands, same as aliases for arguments.
I like to keep long names for commands, but have a shortcut for them when invoking on CLI.

**Comment by jonsequitur** [comment]
Commands do support aliases. Here's an example. 

![image](https://user-images.githubusercontent.com/547415/70367866-3ba44a00-1859-11ea-8d12-d7db76831881.png)

Does this accomplish what you're looking for?

**Comment by dashesy** [comment]
Yes! Feel free to close this issue.
`Option` has a constructor to get aliases, for the sake of consistency maybe `Command` should also provide it.
