### ISSUE TITLE
Rendering doesn't work

### ISSUE THREAD

**Issue by matchesman** [dotnet/command-line-api#709]
Rendering doesn't seem to modify console output as expected. here is a screenshot of the demo app RenderingPlayground. I'm using visual studio 2019. My OS is Windows 10.

![image](https://user-images.githubusercontent.com/5124206/71201510-2de2c180-2268-11ea-971c-ecca4586023c.png)

**Comment by jonsequitur** [comment]
What was the command line input that you used to run the rendering playground?

**Comment by matchesman** [comment]
--sample Colors

**Comment by matchesman** [comment]
In the example, consoleRenderer is initialized with mode set to invocationContext.BindingContext.OutputMode(). The thing is that invocationContext.BindingContext.OutputMode() returns OutputMode.PlainText. If I set mode to OutputMode.Ansi, then it works.

```c#
var consoleRenderer = new ConsoleRenderer(  
                invocationContext.Console,  
                //mode: invocationContext.BindingContext.OutputMode(),  
                mode : OutputMode.Ansi,  
                resetAfterRender: true);
```

Now, I don't know why invocationContext.BindingContext.OutputMode() returns PlainText

**Comment by jonsequitur** [comment]
The intention is to detect the mode based on the terminal type and whether output was redirected. You can also set this explicitly using a declaration:

```console
> myapp [output:ansi] --sample Colors
```

It looks like terminal detection is not working prior to the call to `invocationContext.BindingContext.OutputMode()`.

**Comment by pjmagee** [comment]
I tired in several methods, all with no color. Cmder, default powershell terminal, default cmd.exe.

**Comment by jonsequitur** [comment]
@pjmagee How are you starting the app and what version of Windows are you using?

If I do this in the `/samples/RenderingPlayground` directory, it works as expected:

```console
 dotnet run --  [output:ansi] --sample Colors
```

Windows Terminal:

![image](https://user-images.githubusercontent.com/547415/72301484-bd875000-361b-11ea-98a3-1032a96299be.png)

PowerShell:

![image](https://user-images.githubusercontent.com/547415/72301566-06d79f80-361c-11ea-9759-a37470ee2264.png)

cmd:

![image](https://user-images.githubusercontent.com/547415/72301734-95e4b780-361c-11ea-8234-d046075e7b7d.png)

**Comment by pjmagee** [comment]
I didn't realise i was missing `[output:ansi]`. Thank you!

**Comment by jonsequitur** [comment]
Glad that helped!

Terminal detection is currently not working in RenderingPlayground, which is why the `[output:ansi]` directive is needed.
