### ISSUE TITLE
How to create command handler with more than 7 parameters

### ISSUE THREAD

**Issue by claunia** [dotnet/command-line-api#713]
Hi,

It is not clear in the documentation how to create a command handler with more than 7 parameters.

**Comment by jonsequitur** [comment]
You can use fewer parameters but make them complex types: https://github.com/dotnet/command-line-api/issues/458#issuecomment-495789697

**Comment by claunia** [comment]
Not the prettiest solution but...

However I've found that if the method to invoke is static (and thankfully all of mine are except one, that only has 3 parameters) I can do:

`Handler = CommandHandler.Create(GetType().GetMethod(nameof(Invoke)));`

**Comment by tomfrenzel** [comment]
You also can use Delegate

```
private void Run(string[] args) 
{
    var newCommand = new Command("new") 
        {
            new Option("-template","Choose a Template") 
                {
                    Argument = new Argument < string > (getDefaultValue: () => "Test")
                }
        }
    newCommand.Handler = CommandHandler.Create(handler);
    newCommand.InvokeAsync(args).Wait();
};
public delegate void Del(string template);
public static void DelegateMethod(string template) {
 Console.WriteLine(template)
}
Del handler = DelegateMethod;;
```
