### ISSUE TITLE
Support for taking control of an argument's behavior totally

### ISSUE THREAD

**Issue by rynowak** [dotnet/command-line-api#723]
## Summary

I'm trying to do something that I'm not sure if there's already a recipe for. 

I'm trying to make an option that works like `dotnet run -p <path to project>`. Basically:

- Finds a project file in the current directory if option is unspecified
- Find a project file in the specified directory if the argument specified is a directory
- Uses the argument specified if the argument is a file
- Validation that we found a single project file and it exists

I'm using this option in multiple places, so it's pretty important to me that these errors are reported by the parameter binding system (not by code that I write **after** getting the option values bound).

## What I Tried

My code is here: https://github.com/rynowak/opulence/blob/master/src/dotnet-opulence/StandardOptions.cs#L50

What I tried is creating an argument bound to `FileInfo` - and then taking control of the conversion process. This doesn't meet all my requirements because it doesn't default to the current directory - conversion delegates don't run unless a value is passed in at the command line.

So I added a default value, however you don't have the chance to report validation errors when setting the default value. The validation error can occur when defaulting if there's 0, or more than one project file in the current directory.

So I added a validator. 

At this point it seems to cover all of my bases, but it's pretty complex and non-obvious. My default value has to no-op when it hits a validation error so that my validator can report it, etc.

## What I'd like

It be nice if there were a way to specify a `Func<(something), FileInfo>` for my option that can:

- Run regardless of whether a the option is specified
- Be responsible for converting the unparsed value to a `FileInfo`
- Add my own validation errors 

All of these capabilities already exist but they're part of three different extensibility points.

**Comment by jonsequitur** [comment]
Thanks for taking the time to write this up! You're spot on.

I think it makes a lot of sense to consolidate these into a single API. I've wanted to replace the custom validation API because the intent isn't clear. (Returning a `string` to indicate a validation failure while returning `null` to indicate success was a pretty poor design decision, which I'm ok with saying because I made it.) And this has been one of the pieces I've most wanted to fix before leaving preview.

I'll make an attempt at a better design and post an update soon.

**Comment by rynowak** [comment]
I'm happy to give feedback as well when you're ready for it. I see that you've already started looking at this 👍

**Comment by jonsequitur** [comment]
@rynowak Take a look at #736 and let me know what you think. Most of the commits are refactoring but the last commit adds a number of tests that outline the ways the new API can be used: https://github.com/dotnet/command-line-api/pull/736/files#diff-2d70ca1ca71633e0fdb081a2f67da024R57

**Comment by jonsequitur** [comment]
It's also worth noting that I will likely remove `TryConvertArgument` and `TryConvertArgument<T>`, and move their associated implementations to the new mechanism if we think this API is a good improvement. 

I think that the following APIs remain useful for cases when the default parsing behavior is desired: 

* `Argument.AddValidator`
* `Argument.SetDefaultValue`
* `Argument.SetDefaultValueFactory`
* `Argument.HasDefaultValue`
* `Argument.GetDefaultValue`

@keboo @KathleenDollard @jasonmalinowski

**Comment by jonsequitur** [comment]
I've noticed one problem that this approach creates, which is that calling `Argument.SetDefaultValue` or `Argument.SetDefaultValueFactory` after using the new `ParseArgument<T>` constructor will cause the `ParseArgument<T>` delegate not to be called for default value checks.

**Comment by jonsequitur** [comment]
To summarize the changes here, here are examples of the old versus new approaches:

Old API:

```csharp
var argument = new Argument<MyCustomType>(
    convert: (ArgumentResult parsed, out MyCustomType value) =>
    {
        var custom = new MyCustomType();
        foreach (var a in parsed.Tokens)
        {
            custom.Add(a.Value);
        }

        value = custom;
        return true;
    },
    getDefaultValue: () => new MyCustomType());
```

Proposed new API:

```csharp
var argument = new Argument<MyCustomType>(
    parse: (ArgumentResult parsed) =>
    {
        var custom = new MyCustomType();
        foreach (var a in parsed.Tokens)
        {
            custom.Add(a.Value);
        }

        return custom;
    },
    isDefault: true);
```

The key changes are:

1) The `out` parameter is no longer used in the delegate type. The new version uses the return value instead. It also allows a simplified lambda, since the type `ArgumentType` can be inferred. I've included it in the example for clarity.
2) The (badly-named) `isDefault` parameter replaces the `getDefaultValue` delegate. When this is set to true, the `parse` delegate is still called, but with an `ArgumentResult` containing no tokens.

These two API changes can exist independently so if we think the `out` parameter is more idiotmatic and easier to understand, we could take only the second change.

Regarding validation, something like the following can be used in both versions to surface custom errors:

```csharp
parsed.ErrorMessage = "<error>";
```

**Comment by jonsequitur** [comment]
And returning to the original example, it could look something like this:

```csharp
var argument = new Argument<FileInfo>(parsed =>
{
    var token = parsed.Tokens.SingleOrDefault()?.Value ??
                Directory.GetCurrentDirectory();

    if (File.Exists(token))
    {
        return new FileInfo(token);
    }

    if (Path.GetExtension(token).Equals(".csproj", StringComparison.OrdinalIgnoreCase))
    {
        parsed.ErrorMessage = $"File {token} does not exist.";
        return null;
    }

    if (Directory.Exists(token))
    {
        var csprojFiles = new DirectoryInfo(token).GetFiles("*.csproj");

        switch (csprojFiles.Length)
        {
            case 0:
                parsed.ErrorMessage = "No .csproj files found";
                break;
            case 1:
                return csprojFiles.Single();
            default:
                parsed.ErrorMessage = "There's more than one .csproj file in the directory. Please specify one.";
                break;
        }
    }

    return null;
}, true)
```

Now, having said that, I wonder if we might also want to be able to inform the suggestions API at this point as well:

```csharp
parsed.AddSuggestions(csprojFiles);
```

**Comment by KathleenDollard** [comment]
I am imagining that sample with the parse behavior in a method (which is stylistic, but makes the code easier to follow in my head). Getting the token(s) is the parser part and then calling a method. 

So, just looking at that part of the sample, I think this is a good approach. I toyed with the idea of wrapping `parsed`, but in the end didn't offer value. The unexpected syntax of "Tokens" (to anyone not deeply into parsers) is the only jarring part. 

If we wrapped it, maybe (and making a method so it's easier to see the parser part):

```csharp
var argument = new Argument<FileInfo>(
       validate: values=>ValidateProjectFile(values),
       true)

string ValidateProjectFile(FileInfo[] fileInfos)
{
    var token = fileInfos.Tokens.SingleOrDefault()?.Value ??
                Directory.GetCurrentDirectory();

    if (File.Exists(token))
    {
        return new FileInfo(token);
    }

    if (Path.GetExtension(token).Equals(".csproj", StringComparison.OrdinalIgnoreCase))
    {
        parsed.ErrorMessage = $"File {token} does not exist.";
        return null;
    }

    if (Directory.Exists(token))
    {
        var csprojFiles = new DirectoryInfo(token).GetFiles("*.csproj");

        switch (csprojFiles.Length)
        {
            case 0:
                parsed.ErrorMessage = "No .csproj files found";
                break;
            case 1:
                return csprojFiles.Single();
            default:
                parsed.ErrorMessage = "There's more than one .csproj file in the directory. Please specify one.";
                break;
        }
    }

    return null;
}
```

I'll let you work out if we could just pass one when that is the arity.

**Comment by rynowak** [comment]
All of these things seem like they would simplify what I'm trying to do a lot.

@KathleenDollard - I'm a little confused about your code sample:

```C#
string ValidateProjectFile(FileInfo[] fileInfos)
{
    var token = fileInfos.Tokens.SingleOrDefault()?.Value ??
                Directory.GetCurrentDirectory();
}
```

What is `fileInfos.Tokens`? I think the parameter would have to be something besides `FileInfo[]` for this to work.

**Comment by jonsequitur** [comment]
The `Tokens` property is on the `ArgumentResult` object passed to the parse delegate.

FWIW @rynowak this is currently implemented and available in the latest `System.CommandLine` beta, so feel free to try it out and let us know what you think.

**Comment by rynowak** [comment]
Cool, I'll do that RIGHT NOW.

**Comment by jonsequitur** [comment]
Excellent. And, as usual, the MyGet feed is a couple of bug fixes ahead of nuget.org's version.

**Comment by rynowak** [comment]
Seems to do everything I wanted! Code here if you're curious. https://github.com/rynowak/opulence/pull/6

**Comment by rynowak** [comment]
BTW @jonsequitur  it seems like this doesn't work if you use a positional argument. Am I missing some detail of how I need to configure this? or just a bug?

My code is getting called and reporting an error, but the error is ignored.

**Comment by jonsequitur** [comment]
Could you provide a repro?
