### ISSUE TITLE
What happens on a blank input?

### ISSUE THREAD

**Issue by pduer** [dotnet/command-line-api#732]
Can we add an option to display the help text if NOTHING is filled out?

**Comment by jonsequitur** [comment]
Can you give an example?

Currently, we show help when there's a parse error, so if your parser is configured such that some arguments or subcommands are required, you should see help displayed on a bare invocation.

**Comment by pduer** [comment]
Hey Jon, yeah I think it might be more I just haven't been able to get an example setup correctly. 

I write lots of small console apps where I usually just want a set of VERBs. Basically, do this or do that then run till done. Right now I have to write one that has one of either 2 verbs then a filepath behind it. 

What I want to have happen is that if one of our "Admins" types in JUST the .EXE for the console app, they'll get the full help screen. In all the examples that I tired, I couldn't get that behavoir.

That said, I am probably just "doing it wrong! :)"

**Comment by jonsequitur** [comment]
Got it. Here's an example: 

```csharp
using System.CommandLine;
using System.CommandLine.Invocation;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var rootCommand = new RootCommand
            {
                new Command("one", "This is the description for command one"),
                new Command("two", "This is the description for command two")
            };

            rootCommand.Invoke(args);
        }
    }
}
```

When run with no arguments, it produces this output:

```console
Required command was not provided.

Usage:
  ConsoleApp3 [options] [command]

Options:
  --version    Display version information

Commands:
  one    This is the description for command one
  two    This is the description for command two
```

Any time there's a parse error, help is shown. The reason there's a parse error in this case is because there are subcommands (`one` and `two`) but none was provided. 

Hope this helps.

**Comment by mungojam** [comment]
@jonsequitur I've copied your exact example and oddly it doesn't work for me, it just gives a blank output when I call it with no parameters.

My references are:

```
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta1.20158.1" />
    <PackageReference Include="System.CommandLine.DragonFruit" Version="0.3.0-alpha.20158.1">
      <!--A workaround to remove a multiple entry points warning in Rider-->
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
```

**Comment by mungojam** [comment]
I've now done a workaround which works:

```c#
        static Task<int> Main(string[] args)
        {
            var command = BuildCommandLineOptions();

            if (args == null || !args.Any())
            {
                var help = new HelpBuilder(new SystemConsole());
                help.Write(command);
                return Task.FromResult(0);
            } 
            
            // Parse the incoming args and invoke the handler
            return command.InvokeAsync(args);
        }
```

**Comment by jonsequitur** [comment]
I just verified that this works in System.CommandLine 2.0.0-beta1.20104.2 and is broken in 2.0.0-beta1.20158.1.

**Comment by jonsequitur** [comment]
This was fixed by #820.

**Comment by moswald** [comment]
This appears to have regressed in `2.0.0-beta1.20214.1`. Can anyone else confirm?

**Comment by jonsequitur** [comment]
Here's what I tried, which doesn't repro the bug. Can you provide your repro @moswald?

![image](https://user-images.githubusercontent.com/547415/80285539-993b1500-86da-11ea-92da-089c7ad2dd6d.png)

**Comment by moswald** [comment]
I was using the `CommandLineBuilder` class. Maybe I'm just using it incorrectly? I can probably rework it to use `RootCommand` directly, but it looks nicer with the builder pattern.

![image](https://user-images.githubusercontent.com/85051/80395799-5a8f9100-8879-11ea-826f-cd4c63c9b7f4.png)

**Comment by thoemmi** [comment]
I'm experiencing the same issue using `CommandLineBuilder`. Can this issue be re-openend, or should we create a new one?

**Comment by moswald** [comment]
Pinging @jonsequitur just in case he missed my (now our) response.

**Comment by jonsequitur** [comment]
Ah, I see the problem. Thanks for the code sample, @moswald.

There are two different approaches here. On the one hand, there's what @mungojam's workaround and my attempt to repro did, something like:

```csharp
var command = new Command(/*...*/);
command.Invoke(args);
```

On the other hand, the code that you provided did something like:

```csharp
Parser parser = new CommandLineBuilder()
    .AddCommand(cmd1)
    .UseHelp()
    .Build();

await parser.InvokeAsync(args);
```

The `CommandLineBuilder` gives you fine control over individual behaviors whereas `Command.Invoke` creates a `Parser` internally with many behaviors applied by default. Those defaults are defined here: 

https://github.com/dotnet/command-line-api/blob/7146ca4b45df26bbf85ebb38dc1e44a3c40ca7d0/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L231-L244

So if want help shown on blank input and you're using `CommandLineBuilder` directly, both `UseHelp` and `UseParseErrorReporting` have to be applied. Or you can call `UseDefaults` (which is a little simpler) or you can use the `Command.Invoke`/`Command.InvokeAsync` extension methods, which are the simplest of all.

Hope that helps.
