### ISSUE TITLE
[Feature] Detect if the application is running as administrator or not.

### ISSUE THREAD

**Issue by pjmagee** [dotnet/command-line-api#739]
Hi, I would like to provide by own validation services into the command line as part of either argument/option validation or additional validation required.

It would be cool to be able to say admin mode is needed for [reason why admin is needed to run].

I don't want to do this validation after, because i like using the Command Line API to keep the formatting nice.

Also if i could inject some of these services, like AdminCheckerService etc and access these via my main ServiceCollection that would be a really nice way to integrate with the rest of my application.

Maybe the way I am using the command line api is not the best? But here is how I am using it at the moment. I thought maybe I could add an admin checker into my root command before continuing but not sure if what im doing is good.

https://gist.github.com/pjmagee/e78bbd317d974b538620f4b9cbee398f

**Comment by jonsequitur** [comment]
I like the code structure. I've been meaning to explore using inheritance for commands and options. Any feedback from using this approach?

By adding a validator the way you're doing, you'll be validating during parsing. It might be more appropriate to do this using middleware, as your current validation check will run when getting suggestions or asking for a parse diagram, which is probably not ideal. You can verify that by running these commands:

```console
> app [parse] --path 
> app [suggest]
```

**Comment by pjmagee** [comment]
I really like the inheritance approach. Infact, I was looking through other projects using System.CommandLine and a lot of them were using inheritance. Maybe others felt it opened up more flexibility. I will take a look into using Middleware. Thank you for the feedback.

**Comment by jonsequitur** [comment]
>  I would have liked to use the built in Delegate Handler on the Command, but I wasnt sure how to orchestrate it with my own token, or to somehow wire up the rest of my application based around the Handler, so I figured I would not use that part, and simply use it for parsing.

Can you say more about this? By not assigning the handler you're also not taking advantage of exception handling, model binding, and perhaps a number of other features implemented in the middleware, but it's hard to say for sure from this code sample.

**Comment by pjmagee** [comment]
Sure.

So, most of my services depend on a cancellation token, when the CLI is executed, there's a good chance the process will take 25 minutes to infinite amount of time to complete, it's quite a heavy duty set of processes which basically automate a game client. 

This 'cancellation token' is passed to a provider to keep so that all services can get the token from the provider during their loop, and continue if no cancellation is requested. 

In my sample provided, you can see that I'm wiring everything up using the service collection. Including the Parser. My thought process is that everything should go via my DI container including the parser, and even the Service that my main root command takes, should be injected. 

So the wiring process, and setting up my token provider, happens before the `Handler` and the Handler, passes a cancellation token (if you pass it as part of the delegate/action) if a cancellation is requested (Ctrl+C). This token, has not been the one provided by the DI container setup. 

I did not know the best way to resolve this problem, because i don't think the `System.CommandLine` is a `DI friendly` library which allows you to configure it via `ServiceCollection` easily. Because of this, i felt that I needed to opt out of the `Handler` on the RootCommand. 

Hopefully that explains why I'm only using it for parsing at the moment. If you think there is a better way to do it, or maybe i'm misunderstanding how to use `System.CommandLine` beyond the samples provided.

**Comment by pjmagee** [comment]
I thought about the issue im having a bit more, and came up with this design for essentially bootstrapping the `Parser` with my own services etc. Not sure if it's a good pattern, i have a problem with how im passing configuration through some of my services, because the wiring is setup prior to the users input of those values being set. 

I made a few changes based on your suggestions regarding the Middleware. 

https://gist.github.com/pjmagee/994833753deba47c3b95c073b8377232

**Comment by jonsequitur** [comment]
We're doing some DI with System.CommandLine in `dotnet-try` and `dotnet-interactive`. You can see an example here: https://github.com/dotnet/try/blob/master/MLS.Agent/CommandLine/CommandLineParser.cs. 

Because there are multiple subcommands, we made the decision to configure DI only when a given subcommand has been invoked, as it's easy for people to accidentally introduce startup costs via DI. In a long-running app this isn't usually a big deal, but in a command-line app, especially since we spin up the process for suggestions, this is more of potential problem.

We're also very open suggestions on how to improve System.CommandLine.Hosting.

**Comment by pjmagee** [comment]
I will close my issue as i feel the title is not reflective of the issues and feel that the middleware allowed me to validate my requirements before processing the commands by the user. Thank you for the feedback.
