### ISSUE TITLE
Issues with Help When TypoCorrection is Enabled

### ISSUE THREAD

**Issue by SethX3** [dotnet/command-line-api#766]
`UseTypoCorrections` causes problems with the `--help` option in the latest version when other global arguments are present.

For example with:
```cs
commandLineBuilder.UseVersionOption().UseHelp().UseTypoCorrections().UseParseErrorReporting().CancelOnProcessTermination();
commandLineBuilder.UseMyMiddleware();
```

Where `UseMyMiddleWare` registers:
```cs
commandLineBuilder.AddOption(new Option(new[] {"--file", "-f"}, "Change where ImageCaster should find the configuration file")
{
    Argument = new Argument<FileInfo>("file", () => new FileInfo("imagecaster.yml")).ExistingOnly()
});
```

When executing `--help`, I see `'--help' was not matched. Did you mean '--file'?`.  
When executing `-h`, I see `'-h' was not matched. Did you mean '-l', or '-t', or '-L', or '-c', or '-f'?`.

When `UseTypoCorrections` is set lower, such as 2, it addresses the issue with `--help` and `--file` colliding. (Presumably because they have a distance of 3 which is the default.)

However, I need to remove it entirely to get `-h` working.

It seems the typo correction doesn't recognize `help` or it's aliases so reports problems that aren't actually there.

**Comment by jonsequitur** [comment]
This is probably because `-h` is not a "real" option, which we need to fix: #691.
