### ISSUE TITLE
Setting null as default for Bool type results in true default

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/command-line-api#768]
The code below seems like a reasonable way to set the default value. However, for Bool (at least) you need to not call SetDefaultValue, as opposed to being able to pass null as you can with other things like Arity that you are setting. If you don't do this, the resulting default is True. Not sure how that comes about. 

I'd like to be able to pass True to SetDefaultValue and have the default for the type. 

(Or at least that seems to be what is happening). 

```csharp
        private Argument GetArgument(PropertyInfo property)
        {
            var argument = new Argument(property.Name.ToUpperInvariant())
            {
                ArgumentType = property.PropertyType,
                Description = property.GetDescription(),
                Arity = GetArity(property),
            };

            argument.SetDefaultValue( GetDefault(property));
            return argument;
        }

        private object GetDefault(PropertyInfo property)
        {
            Default<object> defaultValue = property.GetDefaultValue();
            return defaultValue?.Value;
        }
```

**Comment by KathleenDollard** [comment]
Jon and I discussed this, and it's super hard to explain. Here is a repo. Sorry it's a bit long, but it shows both the working case of the sub command failure and the broken test for the base command validation. The two tests not marked to skip will pass. The test marked to skip fails: 

```
       [Fact]
        public void Error_on_rootcommand_is_reported()
        {
            var command = BaseCommand();
            var result = command.Parse("--count Joe" );
            result.Errors.Count.Should().Be(1);
        }

       [Fact]
        public void Error_on_child_command_is_reported()
        {
            var command = BaseChildCommand();
            var result = command.Parse("child-class --count2 Joe");
            result.Errors.Count.Should().Be(1);
        }


        [Fact(Skip = "Issue #768")]
        public void Error_on_parent_command_is_reported()
        {
            var command = BaseChildCommand();
            var result = command.Parse("--count Joe child-class");
            result.Errors.Count.Should().Be(1);
        }

        private Command BaseChildCommand()
        {
            var command = BaseCommand();
            command.AddCommand(ChildCommand());
            return command;
        }

        public Command BaseCommand()
        {
            var command = new Command("base-class");
            var argument = new Argument<string>("birthday-greeting")
            {
                Arity = new ArgumentArity(0, 1)
            };
            argument.SetDefaultValue("Older");
            command.AddArgument(argument);
            command.AddOption(new Option<string>("--name", () => "MyName"));
            command.AddOption(new Option<int>("--count"));

            return command;
        }

        public Command ChildCommand()
        {
            var subCommand = new Command("child-class");
            var argument = new Argument<string>("farewell");
            argument.SetDefaultValue("Yo");
            subCommand.AddArgument(argument);
            subCommand.AddOption(new Option<string>("--greeting"));
            subCommand.AddOption(new Option<int>("--count2"));
            return subCommand;
        }
```

**Comment by KathleenDollard** [comment]
The answer here is that you can't use SetDefaultValue(null) to indicate that you have no default. If you don't want to set a default value, don't call SetDefaultValue. I added a conditional before the call and have moved on. 

However, it's a bit of a trap that setting the default value for a value type has weird results. We need to decide if that is a bug.

**Comment by jonsequitur** [comment]
> I'd like to be able to pass True to SetDefaultValue and have the default for the type.

The default value for an argument is the type default unless you override it using `SetDefaultValue`.

The specific behavior with `bool` is a bug because it's nonsensical. Ideally this should throw:

```csharp
var arg = new Argument();
arg.ArgumentType = typeof(bool);
arg.SetDefaultValue(null);
```

I'd like to avoid doing validation checks on every property setter. `Argument<T>` / `Option<T>` provide better guard rails but the non-generic versions are still needed when building app models.

**Comment by KathleenDollard** [comment]
I found some code that doesn't look right that may be related to this issue. Why are we comparing to dbnull in ParameterDescriptor (52)

```
     public object GetDefaultValue() =>
            _parameterInfo.DefaultValue is DBNull
                ? Type.GetDefaultValueForType()
                : _parameterInfo.DefaultValue;
```

**Comment by jonsequitur** [comment]
It looks odd but `ParameterInfo.DefaultValue` actually does return `DBNull` for a number of types.
