### ISSUE TITLE
Add an extension for AddOptions (plural)

### ISSUE THREAD

**Issue by gitfool** [dotnet/command-line-api#775]
I've got a command with lots of options. It would be nice to have a convenience extension like [AddOption](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L58) but that took an enumerable / params of `Option` to reduce the boiler plate code required to create commands.

**Comment by jonsequitur** [comment]
`Command` supports collection initializer syntax, so you can do things this:

```csharp
var c = new Command("cmd")
{
  new Option<int>("-x"),
  new Option<string>("-y"),
  new Argument<FileInfo[]>()
};
```
