### ISSUE TITLE
Invoking help doesn't show options

### ISSUE THREAD

**Issue by Sp1rit** [dotnet/command-line-api#783]
Given the following program:
```
class Program
{
    static void Main(string[] args)
    {
        var cmd = new RootCommand();
        cmd.ConfigureFromMethod(typeof(Program).GetMethod(nameof(Test)));
        cmd.InvokeAsync(args).Wait();
    }

    /// <summary>
    /// Executes the test method.
    /// </summary>
    /// <param name="option1">The first option.</param>
    /// <param name="option2">The second option.</param>
    public static void Test(int option1, int option2)
    {
        Console.WriteLine("HelloWorld!");
    }
}
```
When executing it with **-h**, the parameters are not shown as options:
```
Usage:
  test [options] [<args>...]

Arguments:
  <args>

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information
```
But when I execute it with an invalid option, the correct help is shown:
```
'-x' was not matched. Did you mean '-h'?
Unrecognized command or argument '-x'

Usage:
  test [options]

Options:
  --option1 <option1>    option1
  --option2 <option2>    option2
  --version              Show version information
  -?, -h, --help         Show help and usage information
```

**Comment by jonsequitur** [comment]
Your `Main` method is doing part of what DragonFruit does (configuring a command based on a target method) but not all of it. Here's the full recipe. `ConfigureHelpFromXmlComments` is the missing piece. Note that this only works if you emit XML docs in your build, something that DragonFruit also turns on using a [build property](https://github.com/dotnet/command-line-api/blob/20d7700fd26625305a6d71e9197fe183e4474fed/src/System.CommandLine.DragonFruit/targets/System.CommandLine.DragonFruit.props#L8).

https://github.com/dotnet/command-line-api/blob/20d7700fd26625305a6d71e9197fe183e4474fed/src/System.CommandLine.DragonFruit/CommandLine.cs#L104-L115

Hope that helps.
