### ISSUE TITLE
Typo in Wiki (Your first app with System.CommandLine)

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/command-line-api#790]
Hi,

`defaultValue` should be `getDefaultValue` on [Your first app with System.CommandLine](https://github.com/dotnet/command-line-api/wiki/Your-first-app-with-System.CommandLine#add-some-code) page.

More specifically this line:
```cs
Argument = new Argument<int>(defaultValue: () => 42)
```

**Comment by jonsequitur** [comment]
Thanks, @dehghani-mehdi!

Fixed.
