### ISSUE TITLE
GetDefaultValue doesn't work as expected for string types

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/command-line-api#791]
Consider following code:

```cs
var rootCommand = new RootCommand
{
    new Option("new", "Help about new")
    {
        Argument = new Argument<string>(getDefaultValue: () => "default-name")
    }
};

rootCommand.Handler = CommandHandler.Create<string>((@new) =>
{
    Console.WriteLine($"The value for @new is: {@new}");
});
```

When I run `my-app.exe new blah`, printed value which is `The value for @new is: blah` is correct.

But when I run `my-app.exe new`, I got `Required argument missing for option: new` error message, but expected output is `The value for @new is: default-value`.

I also added `Required = false`, doesn't help.

**Comment by jonsequitur** [comment]
This is intentional. `myapp.exe new` is an invalid command line for this program. The arity of the `new` option's argument is `ExactlyOne` (by convention, because its type isn't a collection type). Since  `myapp.exe new` doesn't provide an argument for the `new` option, the error `Required argument missing for option: new` is shown, and your handler is not invoked. The handler will never be invoked if there are parse errors.

If you run just `myapp.exe`, without the incomplete `new` option, then your handler will be called with the default value `default-name`.

**Comment by dehghani-mehdi** [comment]
It's confusing then.

- I added an option, (new)
- I added argument to it with default value, (default-name)

So both `my-app.exe new blah` and `my-app.exe new` should work, based on my understanding of above code.

Based on your explanation, `Required = false` do nothing I think.

In my application I changed the `new` to `Sub Command`. but still I think above (the situation which I mentioned in my first post) is not the correct behavior.

**Comment by jonsequitur** [comment]
A typical option usage would be like this:

```console
> copy --source src.txt --destination destination.txt
```
`--source` and `--destination` are options, with `src.txt` and `destination.txt` as the arguments to those options.

So the reason for the error is that something like this should be invalid:

```console
> copy --source src.txt --destination 
```

Maybe you want `new` to be a subcommand? Commands can also have arguments. The following should give the behavior you're expecting:

```csharp
var rootCommand = new RootCommand
{
    new Command("new", "Help about new")
    {
        Argument = new Argument<string>(getDefaultValue: () => "default-name")
    }
};
```

If this is the case, you'll want to set a handler on the `new` command.

**Comment by dehghani-mehdi** [comment]
Yes, as I mentioned, I changed the `new` to be a sub command, as you said and it works as expected.

I will close the issue, but still I believe the `RootCommand` and mentioned situation is a bit confusing.

Thank you for your time and also thank you for `command-line-api`, it is great and helpful.
