### ISSUE TITLE
Crashing bug when trying to implement simple src/dest 'copy' style command

### ISSUE THREAD

**Issue by mjcheetham** [dotnet/command-line-api#792]
**Description**
An exception is thrown when trying to build a simple `copy <source> <destination>` style CLI interface, with two arguments.

Stepping through the code, there appears to be some mismatch within the parsing.
For an example `mycopy src.txt dest.txt`, both `src.txt` and `dest.txt` are being matched against the `<source>` argument.

`ArgumentResult::ArgumentConversionResult` eventually tries to do `ArgumentConversionResult.Success(argument, parentResult.Tokens.Select(t => t.Value).SingleOrDefault());`, but there are _two tokens_, not one.

The application also crashes trying use the `[parse]` directive.

**Repro**
System.CommandLine 2.0.0-beta1.20104.2

```csharp
public static void Main(string[] args)
{
    var root = new RootCommand
    {
        new Argument("source") {Arity = ArgumentArity.ExactlyOne},
        new Argument("destination") {Arity = ArgumentArity.ExactlyOne}
    };
    root.Handler = CommandHandler.Create<string, string>(File.Copy);
    root.Invoke(args);
}
```

```shell
$ dotnet run -- src.txt dest.txt
Unhandled exception. System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.CommandLine.Parsing.ArgumentResult.Convert(IArgument argument)
   at System.CommandLine.Parsing.ArgumentResult.get_ArgumentConversionResult()
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateArgumentResult(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.ParseResultVisitor.Stop(SyntaxNode node)
   at System.CommandLine.Parsing.SyntaxVisitor.Visit(SyntaxNode node)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.CommandExtensions.GetInvocationPipeline(Command command, String[] args)
   at System.CommandLine.CommandExtensions.Invoke(Command command, String[] args, IConsole console)
   at MyCopy.Program.Main(String[] args) in /Users/username/MyCopy/Program.cs:line 17
```

**Comment by jonsequitur** [comment]
Very nice find.

The more common approach is to use the generically-typed `Argument<T>` and the following doesn't exhibit the bug. Can you use this as a workaround while we fix this issue?

```csharp
var root = new RootCommand
{
    new Argument<string>("source")
    {
        Arity = ArgumentArity.ExactlyOne
    },
    new Argument<string>("destination")
    {
        Arity = ArgumentArity.ExactlyOne
    }
};
```

**Comment by mjcheetham** [comment]
> Can you use this as a workaround while we fix this issue?

Sure thing @jonsequitur. Thanks for the `<T>` workaround and the quick fix too!

**Comment by perlun** [comment]
Hmm, there still seems to be edge cases that can trigger this with 2.0.0-beta1.21216.1. My repro is a bit messed up, but it roughly looks like this (simplified example to try and get the point across):

```c#
            var evalOption = new Option<string>("-e", "Executes a single-line script") 
            {
                AllowMultipleArgumentsPerToken = false, ArgumentHelpName = "script" 
            };

            var options = new[] { evalOption };

            var rootCommand = new RootCommand
            {
                Handler = CommandHandler.Create((ParseResult parseResult, IConsole console) =>
                {
                    if (parseResult.HasOption(evalOption))
                    {
                        // This is the line that throws a "more than one element" exception if e.g. "-e 'ARGV.pop()" is passed as parameters.
                        string source = parseResult.ValueForOption(evalOption);
                    }
                }
            }

            var scriptNameArgument = new Argument
            {
                Name = "script-name",
                Arity = ArgumentArity.ZeroOrOne,
            };

            rootCommand.AddArgument(scriptNameArgument);

            var scriptArguments = new Argument
            {
                Name = "args",
                Arity = ArgumentArity.ZeroOrMore
            };

            rootCommand.AddArgument(scriptArguments);

            foreach (Option option in options)
            {
                rootCommand.AddOption(option);
            }
```

If I look at the data of the inner value when this is happening, here's the exact cause of this:

![image](https://user-images.githubusercontent.com/630613/117199577-05268200-adf3-11eb-8a81-e7a832f173d9.png)

As can be seen, it seems like it (`System.CommandLine`) thinks that there's _both_ the `-e` option (`script`) present as well as the `args` positional argument. Just like in the original problem here, I am using the non-generic `Argument` type here. I'll try right away with an `Argument<string>` instead to see if it helps, but it might still be worth trying to add a unit test to reproduce this on the `command-line-api` side if you like.

**Comment by perlun** [comment]
> Just like in the original problem here, I am using the non-generic `Argument` type here. I'll try right away with an `Argument<string>` instead to see if it helps, but it might still be worth trying to add a unit test to reproduce this on the `command-line-api` side if you like.

Using the generic `Argument<T>` form here didn't help here at all unfortunately. I managed to create a simple unit test which reproduces the problem though, it might help us nail this down further: https://github.com/dotnet/command-line-api/pull/1269

**Comment by jonsequitur** [comment]
This looks like a variation on the same bug and is definitely something we'll want to fix.
