### ISSUE TITLE
Is there any way to customize the output for help

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/command-line-api#797]
Hi guys

Could I customize the output format for built-in command like -h or --verison? Says, I'd like to add some extra info before help and split command in different sections.

For example
``` my-cmd -h```

output
```
welcome to my-cmd
here is the help documents
< blablabla some extra info blablabla>

Required args:
    require-arg 1
    require-arg 2

Optional args:
    optional-arg 1
    optional-arg 2

...

< some other footnote >
```

**Comment by jonsequitur** [comment]
One approach is to derive a class from `HelpBuilder` or implement `IHelpBuilder` (depending on how much you want to reimplement) and then call the `CommandLineBuilder.UseHelpBuilder` extension method to replace the default one.

We'd be happy for feedback. 

There's no equivalent hook for `--version` but you could build up your parser so as not to call `UseVersionOption` and implement your own in its place. There's very little code involved: 

https://github.com/dotnet/command-line-api/blob/dbfbcc8e45836b496b2cdb7f31dd28006c5eb76d/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L453-L478
