### ISSUE TITLE
Return explicit failure result when incorrect options are specified

### ISSUE THREAD

**Issue by ptr727** [dotnet/command-line-api#801]
How to return an exit value other than 1 when the commandline parameters are incorrect?

If I run with no input I get the usage text printed, but the return value is 1.
How can I change the return value to e.g. -1 when the commandline arguments are incorrect?

Btw, is this the correct usage in an async main()?
```csharp
        static async Task<int> Main(string[] args)
        {
            Option pathOption = new Option<string>("--path", "Path to files to import");
            pathOption.Required = true;

            Command importVr1710Data = new Command("vr1710data", "Import VR1710 data");
            importVr1710Data.AddOption(pathOption);
            importVr1710Data.Handler = CommandHandler.Create<string>(ImportVr1710Data);

            Command importVr1710EventData = new Command("vr1710eventdata", "Import VR1710 event data");
            importVr1710EventData.AddOption(pathOption);
            importVr1710EventData.Handler = CommandHandler.Create<string>(ImportVr1710EventData);

            Command importCommand = new Command("import", "Import data");
            importCommand.AddCommand(importVr1710Data);
            importCommand.AddCommand(importVr1710EventData);

            RootCommand rootCommand = new RootCommand("Import telemetry data");
            rootCommand.AddCommand(importCommand);

            return await rootCommand.InvokeAsync(args).ConfigureAwait(true);
        }
```

**Comment by jonsequitur** [comment]
The result code of 1 for parse errors is quite common (`git`, `npm`, and `dotnet` all use it) which is why we chose it. It would be pretty simple to make this customizable, though.

**Comment by jonsequitur** [comment]
Your code looks good. The `ConfigureAwait(false)` call shouldn't be necessary.

**Comment by ptr727** [comment]
Thx, a configurable option error would be great.

The `.ConfigureAwait(true);` is a fxcop error go away, see https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007?view=vs-2019
