### ISSUE TITLE
Wiki example code needs updated

### ISSUE THREAD

**Issue by shaggygi** [dotnet/command-line-api#804]
Under https://github.com/dotnet/command-line-api/wiki/Your-first-app-with-System.CommandLine#add-some-code

```csharp
// Create a root command with some options
    var rootCommand = new RootCommand
    {
        var rootCommand = new RootCommand    // Duplicate; this line needs to be removed.
```

**Comment by SebMouren** [comment]
See [correct sample code](https://github.com/SebMouren/command-line-api-wiki/blob/SebMouren-First-App-Sample-Doesnt_compile/Your-first-app-with-System.CommandLine.md)

**Comment by jonsequitur** [comment]
Fixed. Thanks!

**Comment by shaggygi** [comment]
> Fixed. Thanks!

Thanks
