### ISSUE TITLE
How is one supposed to append text to --help ?

### ISSUE THREAD

**Issue by aybe** [dotnet/command-line-api#808]
I was hoping for a simple way to append text to ```--help```, but it turns out to not be as easy as it sounds.

This doesn't really help: https://github.com/dotnet/command-line-api/issues/797

I've derived from ```HelpBuilder``` but I can't really find any good place on where to append some text, ```AddAdditionalArguments``` doesn't really makes sense IMO, overridding ```SplitText``` so that in synopsis I could add multi-line text is simply silly.

Basically, I want to describe exit codes and their meaning, that's all.

Thanks for your help!

**Comment by jonsequitur** [comment]
Does this help? If not, what would make it better?

https://github.com/dotnet/command-line-api/blob/7725a38420b96a9d5b23e33a65593d332340a478/src/System.CommandLine.Tests/Help/HelpBuilderTests.cs#L1343-L1370

For some extra context, one of the early motivations behind `System.CommandLine.Rendering` was to provide a more flexible console "view" API so that help customization can be more open-ended.

**Comment by aybe** [comment]
Works perfectly.

But if I may suggest, it would be nice if in the future, one wouldn't have to type all this to get this result:

```
            var builder = new CommandLineBuilder(rootCommand);
            
            return builder
                .UseDefaults()
                .UseHelpBuilder(context => new MyHelpBuilder(new SystemConsole()))
                .Build()
                .Parse(args)
                .InvokeAsync()
                .Result;

        // HelpBuilder ommitted

```

I mean, just as there is a _synopsis_ for `RootCommand` there could be a _detailed_ section or something like that, some place where one could write multi-line text, etc.

**Comment by kasperk81** [comment]
`CustomHelpBuilderThatAddsTextAfterDefaultText` was deleted in https://github.com/dotnet/command-line-api/pull/1493. what gives?

**Comment by jonsequitur** [comment]
That was a test class that was never part of the public API and was presented here as an example. There are ways to do this kind of customization now that are part of the public API. The docs for this are here: https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help
