### ISSUE TITLE
No help shown without parameters

### ISSUE THREAD

**Issue by claunia** [dotnet/command-line-api#817]
With nuget package version 2.0.0-beta1.20104.2:
- Calling the application without any argument shows help
- Calling the application with a command without any argument shows help

With nuget package version 2.0.0-beta1.20158.1:
- Calling the application without any argument does nothing
- Calling the application with a command without any argument does nothing

If it is an intended change it is not clear how to enable the old behaviour.

Example code at:
https://github.com/aaru-dps/Aaru/blob/b666dcb0aae7725799d42bebd257c93633d12c66/Aaru/Main.cs

**Comment by jonsequitur** [comment]
This isn't intentional. A fix is in the works.

**Comment by TraGicCode** [comment]
Hey @jonsequitur ,

Is it possible to get a new nuget package published with this fix?

**Comment by TraGicCode** [comment]
Nevermind, I was able to get the latest via the following nuget feed.

https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
