### ISSUE TITLE
Please tag pre-releases

### ISSUE THREAD

**Issue by adamralph** [dotnet/command-line-api#827]
Please tag pre-releases so that we can at least tell which code is in which release.

**Comment by jonsequitur** [comment]
You can see this by going to your local package cache and either opening the package in NuGet Package Explorer or looking at the `.nuspec` file you find there.

![image](https://user-images.githubusercontent.com/547415/77253742-7d46de00-6c19-11ea-84e6-83c62ef9f92f.png)

![image](https://user-images.githubusercontent.com/547415/77253777-e169a200-6c19-11ea-92dd-3ce23c33e500.png)

**Comment by adamralph** [comment]
That is a convoluted way to find the commit. A tag would be much easier and is cheap to do.

**Comment by jonsequitur** [comment]
Could you give an example?

**Comment by adamralph** [comment]
https://github.com/adamralph/bullseye/tree/3.3.0-beta.1

**Comment by adamralph** [comment]
I see that https://www.nuget.org/packages/System.CommandLine/2.0.0-beta1.20213.1 was just released.

To satisfy this request, all that needs doing is to tag https://github.com/dotnet/command-line-api/commit/a409f2443ff747961c8885e4bbb5192b5ecba81f with `2.0.0-beta1.20213.1`, and to keep doing that in future each time a release is made.

**Comment by jonsequitur** [comment]
Done. Thanks!

**Comment by adamralph** [comment]
Fantastic. Thanks! I see that `2.0.0-beta1.20214.1` was also released and tagged. 👍

Closing this on the assumption that future releases will be tagged. Thanks!
