### ISSUE TITLE
Help - line wrap

### ISSUE THREAD

**Issue by drmcghee** [dotnet/command-line-api#833]
In my code I have a multiple line summary (comments) for my main method.

when I run my executable and ask for help myapp.exe --help the summary gets line wrapped.
I would like for each line in my summary to have a new line between.

I have tried every mechanism to make this work to no joy (also looked in the dragonfruit code a little) but couldn't find a quick fix.

     /// <summary>
     /// line 1
     /// line2
     /// </summary>

**Comment by marcusturewicz** [comment]
Unless I'm missing something, but it's not as simple as that. You might have a summary that spans multiple lines (for code readability) but you really want the newlines removed in the help description, e.g.:

```xml
/// <summary>
/// This is a really long summary because my app is really great and I want
/// to say lots of great things about it in this summary so people will use it
/// all the time and then I will get famous.
/// </Summary>
```

So how do you to tell DragonFruit that it should keep the newline? You could use a special character e.g. `-`: 

```xml
/// <summary>
/// - This is a really great app
/// - You can use it for all the things
/// </Summary>
```
But then you should support multiple levels of indentation, bullet points and so forth? Is this really worth it? For instance, `node -h` and `npm -h` don't have a description and `dotnet -h` has a super small description : `Execute a .NET SDK command`.

**Comment by drmcghee** [comment]
I don't think it needs to be complicated. just look for a newline? I don't think there is any need for detailed formatting in comments but I do see the need for  line returns

**Comment by marcusturewicz** [comment]
But the newline won't work in every case - if you have a long Summary and have used newlines for code readability, you want these removed in the help command.

**Comment by asasine** [comment]
.NET XML documentation supports the `<para/>` tag for explicitly specifying paragraphs. When it is compiled, separate paragraphs are separated by line breaks.

https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/para

**Comment by yringler** [comment]
<para> tags do not create newlines in --help from dragon fruit. That would be great if they did!

**Comment by yringler** [comment]
I ran the test, and saw that if there was only one para tag it did create the new line? But multiple it didn't, because it uses Value?
I don't have time to look into this further, but I did open a PR (only to my forks master, I don't want to clutter up the offical repo with a PR if I don't intend on following up), and anyone can feel free to take a look and base further work in this area on that.

I do think proper handling of doc string tags (list, para, etc) would help create nice help messages, which are nice to have.
yringler/command-line-api/pull/1/

**Comment by josephbateh** [comment]
Hey folks, I have a local branch that iterates on @yringler's changes and updates the test to go with it. I'm unable to push the branch to create a PR though:

```
ERROR: Permission to dotnet/command-line-api.git denied to josephbateh.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I checked the [Contributing doc](https://github.com/dotnet/command-line-api/blob/0c444f0f20c62e8083f050230433f6b72e9889bb/CONTRIBUTING.md) and I don't see a way to request access. Is there a process to request access to push branches to the repo and create pull requests?

**Comment by baronfel** [comment]
Typically you'd fork this repository, make your changes on a branch of your fork, and then send a pull request from your fork's branch to this repository.

**Comment by josephbateh** [comment]
Thanks @baronfel, followed that and created a PR: [link](https://github.com/dotnet/command-line-api/pull/1604). Hopefully I'm following the process properly, not sure if I'm supposed to link the PR to the issue.
