### ISSUE TITLE
Assigning default values

### ISSUE THREAD

**Issue by markolbert** [dotnet/command-line-api#836]
I initially constructed my options using a pattern like this:

```
var population = new Option<int>(
    new[] { "-p", "--population" },
    getDefaultValue: () => 1000,
    description : "Number of people to simulate" );
```

But I found default values weren't showing up after parsing the command line, so I switched the pattern to this:

```
var population = new Option<int>(
    new[] { "-p", "--population" },
    description : "Number of people to simulate" )
    {
        Argument = new Argument<int>(()=>1000)
    };
```

This works find. But I don't understand what's wrong with the original pattern. What am I missing?

BTW, this is a >>fantastic<< package! Good luck in continuing to hone it!

**Comment by jonsequitur** [comment]
Your first sample works for me when using 2.0.0-beta1.20158.1. Can you check the version you're using?

![image](https://user-images.githubusercontent.com/547415/78154739-770ee980-73f1-11ea-8dd9-6d445f08ab37.png)

**Comment by markolbert** [comment]
That's the same release I'm using (just wrote the code yesterday). Offhand the one difference I see between your test code and what I originally did was that I set Argument within the Option initializer, even before I included the default value Func within the Argument constructor. Could that have made a difference? Is is it necessary to set Argument or does it get created by default by the Option constructor?

**Comment by jonsequitur** [comment]
Ah! The `Option<T>` constructor delegates to the Argument property, so you might have overwritten the `getDefaultValue` from the constructor. 

The `Option.Argument` property is a bit confusing in this way and we've considered removing or hiding it.

@KathleenDollard  Any thoughts on this?

**Comment by markolbert** [comment]
I confirmed that moving the default value setter into the Option constructor and eliminating setting Argument in the initializer resolves the issue I cited.

Apropos of whether or not to hide or remove the Argument property, is there another way of setting a validator on an Option? I'm using a pattern like this:

```
var population = new Option<int>(
    new[] { "-p", "--population" },
    getDefaultValue : () => 1000,
    description : "Number of people to simulate" );

    population.Argument.AddValidator(
        x => x.GetValueOrDefault<int>() < 100 ? "Population must be >= 100" : null );
```

**Comment by jonsequitur** [comment]
There isn't currently but we would need to address that in order to hide the `Option.Argument` property. 

Another proposed change for validators is to have them operate on bound values rather than tokens, so you could just write something like this:

```csharp
population.Argument.AddValidator(
        x => x < 100 ? "Population must be >= 100" : null );
```

**Comment by markolbert** [comment]
That would be a nice enhancement, too. Again, a wonderful library!

Shall I close this thread?
