### ISSUE TITLE
Indicating that help was requested

### ISSUE THREAD

**Issue by markolbert** [dotnet/command-line-api#837]
The default behavior of the library seems to be that, if help is requested (e.g., -h, --help) the command line will be completely processed. 

This led to a problem for me in that successful parsing immediately led to further app execution when what I wanted, if help was requested, was to close the app (since the help text, by default, is automatically displayed).

Is there a setting I can check to see if help was requested?

In the absence of seeing one I came up with this workaround:

```
var parseResult = _rootCommand.Invoke( args );
var help = _rootCommand.Options.FirstOrDefault( x => x.HasAlias( "-h" ) );

if( help != null )
    {
        var result = help.Parse( string.Join( " ", args ) );

        // Help is a property of an arguments class I wrote; I check it in the app
        // before proceeding with execution
        Help = result.FindResultFor( help ) != null;
    }

return parseResult == 0;
```

But this seems more than a little kludgy.

**Comment by jonsequitur** [comment]
Could you provide a repro?

The help implementation is intended to short-circuit execution in the middleware, so your handler shouldn't be getting called. Here's an example:

https://github.com/dotnet/command-line-api/blob/dde07c52b377c8d3a556b8d90c5b331b98e63c3c/src/System.CommandLine.Tests/UseHelpTests.cs#L38-L56

**Comment by markolbert** [comment]
You can take a look at [this app I wrote](https://github.com/markolbert/ViralSpread). You'll see how I implemented the workaround I'm using. 

I created the work around because executing `someapp -h -x` (where -x is some option I'm supporting) didn't short-circuit.

However, your code snippet makes me wonder if I'm doing something fundamentally wrong which is preventing short-circuiting. What I do is add all the options I want to a root command object. Should I be adding them to a command object instead and then adding that command to the root command object? In other words, does the help short-circuit occur at the root command level?

**Comment by markolbert** [comment]
Hi Jon, you can ignore that earlier comment. I re-examined the code sample you posted and realized how the library expects to deal with the "I found a request for help and handled it" situation: you set a guard flag (`wasCalled` in the example) that only gets set to `true` if the root command handler gets called. Which won't happen if the pipeline gets short-circuited.

For whatever reason that approach wasn't clear to me from reading the docs. I was looking for some property of some object which would say "sorry, short-circuited" after the parser was called. I should've realized that wouldn't be straightforward to do given that command handlers are being used.

**Comment by jonsequitur** [comment]
> For whatever reason that approach wasn't clear to me from reading the docs. 

The reason is our docs are sorely lacking. 😅

**Comment by markolbert** [comment]
LOL! Always the case...

I'd be happy to put together some examples/docs if that would help (I really like the library, and the more I use it the more I am coming to rely on it for console apps).

One (off-topic) question, though: I'm playing around with trying to understand how parse results are bound to targets. It seems to be by matching target name to parameter (token?) alias (e.g., if the aliases for an option are -p and --population results will be found to either an object named 'p' or one named 'population'). 

I'd like to be able to override that (so I can use different names for aliases and targets). It seems like assigning a name property to an Argument would do the trick...but I ran into some problems with that. So I thought I'd clone the library and walk through the code.

Only your coding skills are, ahem, several levels above mine :) so I wasn't able to find where the binding takes place. 

If you could point me at the right class(es) or interfaces I'd be most appreciative :).

**Comment by jonsequitur** [comment]
We'd absolutely appreciate help with docs and XML doc comments.

Parsing and binding are fairly decoupled, so it's not obvious from looking at the code how they relate. The name-based binding is just a convention. Below is another approach which demonstrates binding without the name convention, though it's currently not easy to wire up because we typically create model binders behind the scenes. The idea though is to allow people to create their own binding conventions, since the name-based one isn't everyone's favorite approach.

https://github.com/dotnet/command-line-api/blob/d50118a09bef72d912b9fb85116996b687ec0928/src/System.CommandLine.Tests/Binding/ModelBinderTests.cs#L449-L487

**Comment by markolbert** [comment]
Okay, after I come up to speed a bit more I'll see what I can offer.

Thanx for the code reference. I was able to implement a custom binder but it seems like in doing so I "lose" the automatic short-circuiting for the -h help option (and presumably the --version option as well). Is that correct? If so I'll probably stick with a workaround I came up with: a dummy private class whose sole purpose is to have properties matching the argument aliases.

**Comment by jonsequitur** [comment]
I'd have to see what you're doing. Binding should typically not happen until after the middleware has the opportunity to short-circuit.

**Comment by markolbert** [comment]
I'm following the pattern laid out in lines 472-484 of `command-line-api/src/System.CommandLine.Tests/Binding/ModelBinderTests.cs`, part of the code reference you provided me earlier.

I modified it to work with an instance of RootCommand instead of command:

```
var rootCommand = new RootCommand( "Investment Simulator" );

var years = new Option<int>( new[] { "-y", "--years" }, () => 10, "years to simulate" );
years.AddValidator( ( r ) => r.GetValueOrDefault<int>() >= 1
                    ? null
                    : $"'years' must be >= 1 (default is {r.Option.GetDefaultValue()})" );
rootCommand.AddOption( years );

var investments = new Option<int>( new[] { "-i", "--investments" }, () => 5, "investments to simulate" );
investments.AddValidator( ( r ) => r.GetValueOrDefault<int>() >= 1
                    ? null
                    : $"'investments' must be >= 1 (default is {r.Option.GetDefaultValue()})" );
rootCommand.AddOption( investments );

// ...other Option creation code omitted for brevity

var binder = new ModelBinder<SimulationContext>();

binder.BindMemberFromValue(sc=>sc.Investments, investments);
binder.BindMemberFromValue(sc=>sc.MaxAnnualInvestmentReturn, maxReturn);
binder.BindMemberFromValue(sc=>sc.MaxStdDevAnnualInvestmentReturn, maxStdDev);
binder.BindMemberFromValue(sc=>sc.Simulations, simulations);
binder.BindMemberFromValue(sc=>sc.Years, years);

var bindingContext = new BindingContext( rootCommand.Parse( args ) );

var instance = (SimulationContext) binder.CreateInstance( bindingContext );
```

This works exactly as desired...except for the fact that if I pass `-h` as a command line argument to the debugger it **still** works even though it "shouldn't" (i.e., the short-circuiting isn't kicking in).

My gut tells me this may be because I'm parsing the command line and creating the instance of `SimulationContext` manually rather than going through `rootCommand.Invoke(args)`. But I'm not sure.

I can confirm, FWIW, that the `args` passed to `rootCommand.Parse()` does contain the string "-h". Also, `bindingContext.ParseResult` contains a single error, a complaint that -h is unrecognized.

**Comment by markolbert** [comment]
I've been doing some further research, walking through the library's invocation routines.

It appears that my custom binder is failing to recognize -h because it isn't executing the middleware, which, among other things, does that. I tried to duplicate what I thought was the key part of the library code in my custom binder logic:

```
var parser = new CommandLineBuilder( rootCommand )
    .UseDefaults()
    .Build();
var bindingContext = new BindingContext( parser.Parse( args ) );
var instance = (SimulationContext) binder.CreateInstance( bindingContext );
```

but that wasn't enough. Nothing in my code triggers the middleware.

I tried to create the invocation explicitly and do an `Invoke` on it before calling `CreateInstance` but that's not possible because `InvocationPipeline` is an internal class.

**Comment by markolbert** [comment]
Sorry about the flurry of comments here but I think I've found a way to integrate custom binding more "naturally" into the flow, and simplified detecting -h options to boot. Here's what I did:

I changed HelpResult to add a special non-zero result code:

```
public class HelpResult : IInvocationResult
{
    public void Apply(InvocationContext context)
    {
        context.BindingContext
            .HelpBuilder
            .Write(context.ParseResult.CommandResult.Command);

        context.ResultCode = 2;
    }
}
```

I tried doing the same thing for --version but I wasn't sure where the "version result" object was defined.

I then added some new methods to allow for retrieving the BindingContext used by the library during invocation. First change was to add the following extension method to CommandExtensions:

```
public static int Invoke(
    this Command command,
    string[] args,
    out BindingContext bindingContext,
    IConsole console = null )
{
    var retVal = GetInvocationPipeline( command, args ).Invoke( out var context, console );
    bindingContext = context;
    return retVal;
}
```

To support this I added the following Invoke method to InvocationPipeline:

```
public int Invoke( out BindingContext bindingContext, IConsole console = null )
{
    var context = new InvocationContext( parseResult, console );
    
    InvocationMiddleware invocationChain = BuildInvocationChain( context );

    Task.Run( () => invocationChain( context, invocationContext => Task.CompletedTask ) ).GetAwaiter().GetResult();

    bindingContext = context.BindingContext;

    return GetResultCode( context );
}
```

This lets me do explicit binding to properties (rather than name-based). Here's how it looks in practice for a class I define to hold the command line argument values:

```
    public class SimulationContext
    {
        public int Years { get; set; }
        public int Investments { get; set; }
        public int Simulations { get; set; }
        public double MaxAnnualInvestmentReturn { get; set; }
        public double MaxStdDevAnnualInvestmentReturn { get; set; }

        public bool Initialize( string[] args )
        {
            var rootCommand = new RootCommand( "Investment Simulator" );

            var years = new Option<int>( new[] { "-y", "--years" }, () => 10, "years to simulate" );
            years.AddValidator( ( r ) =>
                r.GetValueOrDefault<int>() >= 1
                    ? null
                    : $"'years' must be >= 1 (default is {r.Option.GetDefaultValue()})" );
            rootCommand.AddOption( years );

            // further details of option/rootcommand configuration omitted for brevity

            var invocationResult = rootCommand.Invoke( args, out var bindingContext );

            if( invocationResult != 0 )
                return false;

            var binder = new ModelBinder<SimulationContext>();

            binder.BindMemberFromValue( sc => sc.Investments, investments );
            binder.BindMemberFromValue( sc => sc.MaxAnnualInvestmentReturn, maxReturn );
            binder.BindMemberFromValue( sc => sc.MaxStdDevAnnualInvestmentReturn, maxStdDev );
            binder.BindMemberFromValue( sc => sc.Simulations, simulations );
            binder.BindMemberFromValue( sc => sc.Years, years );

            var instance = (SimulationContext) binder.CreateInstance( bindingContext );

            Years = instance.Years;
            Investments = instance.Investments;
            Simulations = instance.Simulations;
            MaxAnnualInvestmentReturn = instance.MaxAnnualInvestmentReturn;
            MaxStdDevAnnualInvestmentReturn = instance.MaxStdDevAnnualInvestmentReturn;

            return true;
        }
    }
```

I'd be interested in your thoughts on this approach (and where the --version result is defined).

**Comment by jonsequitur** [comment]
Very nice start. 

How are you defining the `RootCommand.Handler`? I'm concerned that this approach won't work as expected with some existing middleware and error handling behaviors, and it looks like you're doing binding after the handler is called. Also, because you're directly invoking the `RootCommand` it looks like it wouldn't work with subcommands, as routing to the correct subcommand's handler is done based on the parsed input.

So how to avoid these side effects? I think a more directed approach might be to provide a way to let someone specify a factory for `ModelBinder` instances as part of the configuration, to enable you to do something like this:

```csharp
var parser = new CommandLineBuilder(rootCommand)
    .UseDefaults()
    .UseModelBinder( x => // <-- not sure what x would be but probably something that provides access to the CommandLineConfiguration so you don't need to reference your symbols via a closure
    {
        var binder = new ModelBinder<SimulationContext>();
        // configure the binder
        return binder;
    })
    .Build();
```

There are two places in the code where this factory would need to be made available:

https://github.com/dotnet/command-line-api/blob/b20e71a404eaac6cde023706336723fff60f28ef/src/System.CommandLine/Binding/DelegateHandlerDescriptor.cs#L22
https://github.com/dotnet/command-line-api/blob/b20e71a404eaac6cde023706336723fff60f28ef/src/System.CommandLine/Binding/MethodInfoHandlerDescriptor.cs#L28

**Comment by markolbert** [comment]
Hmm, I'll have to study the code base more thoroughly as I'm only dimly grasping what you're getting at. For one thing, why couldn't I do something like this:

```
        public static CommandLineBuilder UseModelBinder<TModel>( 
            this CommandLineBuilder builder, Func<ModelBinder<TModel>> factory )
        {
            builder.ModelBinderFactory = factory;

            return builder;
        }
```
which would be used as follows:

```
    .UseModelBinder<SimulationContext>( ()=> {
            var binder = new ModelBinder<SimulationContext>();

            binder.BindMemberFromValue( sc => sc.Investments, investments );
            binder.BindMemberFromValue( sc => sc.MaxAnnualInvestmentReturn, maxReturn );
            binder.BindMemberFromValue( sc => sc.MaxStdDevAnnualInvestmentReturn, maxStdDev );
            binder.BindMemberFromValue( sc => sc.Simulations, simulations );
            binder.BindMemberFromValue( sc => sc.Years, years );

            return binder;
    });
```

with `investments` et al defined as Options as I'm already doing.

**Comment by jonsequitur** [comment]
The problem isn't so much with capturing the options via closure as with building an API that would make that the only way to do this, as if pushes you to define the factory delegate somewhere in your code where those option objects are also in scope. This might not be the way people prefer to organize their code.

Regarding the `UseModelBinder` signature, the `ModelBinderFactory` property in your example would be a single instance across all of the various types `TModel`. Something like this could work:

```csharp
var parser = new CommandLineBuilder()
        .UseMiddleware(context => context.BindingContext.AddService(_ => new ModelBinder<SimulationContext>()))
        .Build();
```

The two handler descriptors would then need access to the `IServiceProvider` to create model binders.

**Comment by markolbert** [comment]
I'll think about that. 

In the meantime, if you'll continue indulging me, I took a somewhat different approach. It occurred to me that, since the "ultimate" outcome of the parsing is to call an ICommandHandler, why not write a class which implements ICommandHandler but updates a user-provided instance of the target object where I want the configuration values to end up? Something like this:

```
public class ObjectBinder<TModel> : ICommandHandler
    where TModel : class
{
    private readonly TModel _target;

    public ObjectBinder( TModel target  )
    {
        _target = target ?? throw new NullReferenceException( nameof(target) );
    }

    public async Task<int> InvokeAsync( InvocationContext context )
    {
        if( context == null )
            throw new NullReferenceException( nameof(context) );

        var modelBinder = context.Parser.Configuration.ModelBinderFactory( context.Parser.Configuration.Symbols );

        modelBinder.UpdateInstance(_target, context.BindingContext);

        return 0;
    }
}
```

which would be used like this:

```
rootCommand.Handler = new ObjectBinder<SimulationContext>( this );
```

where `this` is the object holding the configuration information. 

I added `ModelBinderFactory` to `CommandLineBuilder` and `CommandLineConfiguration` per our earlier discussions like this:

```
public static CommandLineBuilder UseObjectBinding<TModel>( 
    this CommandLineBuilder builder,
    Func<ISymbolSet, ModelBinder<TModel>> modelBinderFactory )
{
    builder.ModelBinderFactory = modelBinderFactory;
    return builder;
}
```

I used `ISymbolSet` as the starting point because it seems like it's where all the IValueDescriptors that you'd want to use as binding targets are stored.

To glue this all together I had to expand the `ISymbolSet` interface to include a way to retrieve a specific `IValueDescriptor`:

```
public interface ISymbolSet : IReadOnlyCollection<ISymbol>
{
    ISymbol GetByAlias(string alias);
    IValueDescriptor GetValueDescriptor<TValue>( string alias );
}
```

but that seemed reasonable because it's only implemented in one place, the `SymbolSet` class, which I expanded like this:

```
public IValueDescriptor GetValueDescriptor<TValue>( string alias )
{
    var symbol = GetByAlias( alias ) ??
                 throw new ArgumentException( $"Could not find {nameof(ISymbol)} for '{alias}'" );

    if( symbol is IValueDescriptor retVal )
    {
        if( !typeof(TValue).IsAssignableFrom(retVal.Type) )
            throw new InvalidCastException(
                $"{nameof(ISymbol)} cannot be assigned to required Type '{typeof(TValue).Name}'" );

        return retVal;
    }

    throw new InvalidCastException( $"{nameof(ISymbol)} '{alias}' is not an {nameof(IValueDescriptor)}" );
}
```

This gets used like this:

```
var clBuilder = new CommandLineBuilder(rootCommand)
    .UseDefaults()
    .UseObjectBinding( symbols =>
     {
         var retVal = new ModelBinder<SimulationContext>();

         retVal.BindMemberFromValue( sc => sc.Investments, symbols.GetValueDescriptor<int>("-i") );
         retVal.BindMemberFromValue( sc => sc.MaxAnnualInvestmentReturn, symbols.GetValueDescriptor<double>("-r") );
         retVal.BindMemberFromValue( sc => sc.MaxStdDevAnnualInvestmentReturn, symbols.GetValueDescriptor<double>("-d") );
         retVal.BindMemberFromValue( sc => sc.Simulations, symbols.GetValueDescriptor<int>("-s") );
         retVal.BindMemberFromValue( sc => sc.Years, symbols.GetValueDescriptor<int>( "-y" ) );

         return retVal;
    } );
```

Adding this configuration information required that I modify various `Invoke` extension methods to pass in the custom `CommandLineBuilder`, because by default it appears to get created behind the scenes in `CommandExtensions`:

```
private static InvocationPipeline GetInvocationPipeline(Command command, string[] args, CommandLineBuilder builder = null)
{
    builder ??= new CommandLineBuilder( command )
        .UseDefaults();

    var parser = command.ImplicitParser ?? builder.Build();

    var parseResult = parser.Parse(args);

    return new InvocationPipeline(parseResult);
}
```

I modified the various public `Invoke` extension methods to have `CommandLineBuilder` as an optional parameter, e.g.:

```
public static int Invoke(
    this Command command,
    string[] args,
    IConsole console = null, 
    CommandLineBuilder builder = null )
    {
        return GetInvocationPipeline(command, args, builder).Invoke(console);
    }
```

In the end this all gets used like this:

```
var invocationResult = rootCommand.Invoke( args, builder: clBuilder );
```

which preserves the basic approach of configure/invoke/bind (in this case to an instance of `SimulationContext`.

However... :)

The code blows up because executing the very first line of the `UseObjectBinding` code:

```
retVal.BindMemberFromValue( sc => sc.Investments, symbols.GetValueDescriptor<int>("-i") );
```

causes `InvocationPipeline::BuildInvocationChain()` to execute the handler before it's fully defined.

I realize there are a number of changes here, although each of them is relatively minor. If you have any thoughts on what's causing the problem, or why this approach can't work, I'm all ears.

**Comment by markolbert** [comment]
Okay, I figured out what that first line is blowing up: the call to `GetByAlias()` is failing because it's only searching the symbols at the `RootCommand` level which only contains (at least in my case) a single symbol. 

It'd be easy enough to write a routine to scan for any matching child symbol...but something tells me that might be problematic in that a symbol's alias could be re-used within various subcommands.

So my incredibly lengthy post :) boils down to this question: do aliases have to be unique across subcommands? Or is something like this possible for a command arguments string:

> -y 10 [subcommand] -y 27

with the two "-y" aliases meaning different things?

**Comment by jonsequitur** [comment]
Very nice investigation, @markolbert.  I think a discussion about code in this degree of detail is better conducted in a PR, and we've gotten off the original issue topic as well. That said, I did start tinkering with an approach to this just to understand better what would be required, and I think we can do something pretty simple.

To answer your most recent question, there's no constraint for aliases to be unique across subcommands. The two `-y` aliases can reference either the same symbol or different symbols, which is the difference between these two examples:

```csharp
new RootCommand{
  new Command("a")
  {
    new Option("-y")
  },
  new Command("b")
  {
    new Option("-y")
  }
}
// versus
var optionY = new Option("-y");
new RootCommand{
  new Command("a")
  {
    optionY
  },
  new Command("b")
  {
    optionY
  }
}
```

**Comment by markolbert** [comment]
Yeah, all that code and back-and-forth is a sign that I've gotten off into the weeds.

I'm pursuing a fix for the problem I encountered (which also reduces the number of changes I have to make to the code base) so hopefully it'll pan out.

I'll close this thread after you tell me one thing: what's a PR? :)

**Comment by jonsequitur** [comment]
PR = pull request. It's much easier to have a detailed discussion of code that way.

**Comment by markolbert** [comment]
Ah! I've never done one of those. Once I'm through cleaning up my approach (which appears to be working, BTW) I'll submit one.

Closing this thread now.
