### ISSUE TITLE
Shell suggestions don't work unless executable is registered in file

### ISSUE THREAD

**Issue by samarsha** [dotnet/command-line-api#838]
My app using System.CommandLine tries to register itself, but dotnet suggest does not actually write it to the file `~/.dotnet-suggest-registration.txt` (because of #823), so it is not shown in `dotnet-suggest list`, and tab completions don't work. But if I undo the change from the PR (or manually create the registration file), tab completions work normally.

#823 says that file-based registration is not needed, but the PowerShell and Bash shims call `dotnet-suggest list` to decide when to show tab completions. Do the shims need to be updated?

**Comment by jonsequitur** [comment]
This is working for me currently even without the registration file, in PowerShell 7 on Windows 10.

What OS and shell are you seeing the issue in?

**Comment by samarsha** [comment]
I was using PowerShell 5 on Windows 10. I upgraded to PowerShell 7, but it didn't fix the problem.

Here is my shell profile:

```
> cat $PROFILE
# dotnet suggest shell start
$availableToComplete = (dotnet-suggest list) | Out-String
$availableToCompleteArray = $availableToComplete.Split([Environment]::NewLine, [System.StringSplitOptions]::RemoveEmpty
Entries)


    Register-ArgumentCompleter -Native -CommandName $availableToCompleteArray -ScriptBlock {
        param($commandName, $wordToComplete, $cursorPosition)
        $fullpath = (Get-Command $wordToComplete.CommandElements[0]).Source

        $arguments = $wordToComplete.Extent.ToString().Replace('"', '\"')
        dotnet-suggest get -e $fullpath --position $cursorPosition -- "$arguments" | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
$env:DOTNET_SUGGEST_SCRIPT_VERSION = "1.0.0"
# dotnet suggest script end
```

I see that it registers completers based on the output of `dotnet-suggest list`:

```
> dotnet-suggest list
dotnet-suggest
dotnet suggest
```

When I have the registration file, my app shows up in this list, but without the file it isn't listed.

**Comment by jonsequitur** [comment]
Which version of `dotnet-suggest` are you using?

**Comment by samarsha** [comment]
```
> dotnet-suggest --version
1.1.116801+51e70735a148ce2b06a8d4609fe39947d155ca93
```

I think this is the latest version?

**Comment by samarsha** [comment]
Here's my understanding of the bug:

* The shell shims register completers for the programs returned by `dotnet-suggest list`.
* `dotnet-suggest list` gets the list of programs by calling `FindAllRegistrations()` on this suggestion provider:

  ```
  new CombineSuggestionRegistration(
      new GlobalToolsSuggestionRegistration(),
      new FileSuggestionRegistration());
  ```
* My app is not a global tool, so `GlobalToolsSuggestionRegistration` doesn't find it. That leaves `FileSuggestionRegistration`, but #823 disabled automatic file registration.

@jonsequitur Does this seem right? I'd be happy to help debug, but I'm not sure what the expected behavior is. :) Is there some other mechanism for finding apps that aren't global tools, that isn't working on my computer? Or are non-global tools not supported for shell suggestions? Thanks!

**Comment by jonsequitur** [comment]
This looks right. 

We definitely want it to work even if your tool isn't installed as a .NET Core global tool.  But we also don't want to intercept every tab completion request in your shell, so the registration file is the subset we know is using System.CommandLine because they've registered via `CommandLineBuilder.RegisterWithDotnetSuggest `.
