### ISSUE TITLE
Can we use Option<Dictionary<TKey, TValue>>?

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/command-line-api#840]
My application need to deal with a dictionary that should be passed from the command line, but I haven't found any sample on how to pass this kind of option.

Is it possible to do it?
Thanks in advance!

**Comment by jonsequitur** [comment]
You should be able to do this but it might require a custom parse delegate. Can you give an example of what the input looks like? I presume the keys can be anything the user wants?

**Comment by SuperJMN** [comment]
@jonsequitur Thanks for your quick answer! this feels so good for devs using a library :) Faster than fast feedback!

The dictionary would be `Dictionary<string, string>`, for instance.

The case use would be something in the form of:
```
> MyApp --user-variables WimImage=D:\Sources\install.wim WimImageIndex=1 Disk=5
```

I've typed the dictionary with a syntax that makes sense for me, but I don't know if it's correct or supported by the API. 

Thanks in advance!

**Comment by jonsequitur** [comment]
You can implement your example like this. The key is the `parseArgument` parameter, which lets you convert the input into any type you need.

```csharp
var option = new Option<Dictionary<string, string>>(
    "--user-variables",
    parseArgument: argResult => argResult
                                 .Tokens
                                 .Select(t => t.Value.Split('='))
                                 .ToDictionary(p => p[0], p => p[1]));

var command = new RootCommand
{
    option
};

var result = command.Parse(@"--user-variables WimImage=D:\Sources\install.wim WimImageIndex=1 Disk=5");

result.FindResultFor(option)
      .GetValueOrDefault()
      .Should().BeEquivalentTo(new Dictionary<string, string>
      {
          ["WimImage"] = @"D:\Sources\install.wim",
          ["WimImageIndex"] = "1",
          ["Disk"] = "5"
      });
```

**Comment by SuperJMN** [comment]
I've tried your approach and it works!! Thank you a lot!

But I'm curious about how the code would change if we had a Dictionary<string, object> to be able to store other objects like strings and ints?
