### ISSUE TITLE
Required options prevent --help from working

### ISSUE THREAD

**Issue by ebeisecker** [dotnet/command-line-api#842]
Hello,

It appears that if I configure a command with an Option that is required, I have to provide that Option when attempting to retrieve help for the command --help

```
public async Task<int> Main(string[] args) {
  var parser = CreateCommand().Build();
  var result = parser.Parse(args);

  return await result.InvokeAsync();
}

private static CommandLineBuilder CreateCommand() {
  var root = new RootCommand("Sample");
  var builder = new CommandLineBuilder(root);
  
  var subCmd = new Command("sub-command", "Sample");
  var reqOption = new Option("--myOpt", "Required option")
  {
     Required = true,
     Argument = new Argument<string>()
  };
  command.AddOption(reqOption);

  command.Handler = CommandHandler.Create((IHost host) => System.Console.WriteLine("Test"));
  builder.AddCommand(subCmd);
  
  builder.UseDefaults();
  builder.UseHost();

  return builder;
}
```

If my command line is `dotnet run -- sub-command --help` I get a `Option '--myOpt' is required` I would expect to be able to use the `--help` option without having to provide the required options.

**Comment by jonsequitur** [comment]
Which version of System.CommandLine are you using?

**Comment by ebeisecker** [comment]
I'm currently using 0.3.0-alpha.20158.1

**Comment by jonsequitur** [comment]
I was unable to repro the issue with a newer version. Can you pull the latest and see if that resolves it?

**Comment by ebeisecker** [comment]
Looks like it! Thanks!
