### ISSUE TITLE
Optional Option with Optional Argument

### ISSUE THREAD

**Issue by shaggygi** [dotnet/command-line-api#845]
I'm working on a CLI app and drawing a blank on how to do this.  I have an optional `Option` with an optional `Argument` for a `double` type value.  For example, the app needs to be able to perform/display info based on the following scenarios.

1. The `Option` might not be used.  The app doesn't display anything and the `Argument` is disregarded.

```console
c:\myCli
```

2. The `Option` might be used with no value.  The app displays some info and the `Argument` is disregarded.

```console
c:\myCli --myOption
Hello, you used myOption with no value.
```

3. The `Option` might be used with a value.  The app displays some info and the `Argument` is used to perform something.

```console
c:\myCli --myOption=8.44
Hello, you used myOption with a value of 8.44.
```

Any help is appreciated.

**Comment by jonsequitur** [comment]
What is the expected difference in behavior between 1 and 2?

**Comment by shaggygi** [comment]
1. Should not perform a Console.WriteLine(...) if --myOption is not present.
2. Should perform a Console.WriteLine(...) if --myOption is present.  The option value cannot be present in this scenario.  I guess I could default to 0 as it shouldn't be used in most cases and wouldn't try performing the logic in 3.
3.  Should perform a little more logic and a Console.WriteLine(...) if --myOption and  its value are present.

Use the internal version (not the same as --version option) for example...
1. myCli
// returns nothing

2. myCli --myVersion  // This would be used to only get the internal version without perform extra logic.
internal-version = 1.5 // Currently uses 1.5 version logic.

3. myCli --myVersion= 4.2 // This would try to tell the process to use specific version logic within and will return the version it will use.
internal-version = 3.7  // In this case, it couldn't use 4.2, but could/did change to 3.7 version logic.

These scenarios are based on an external utility I'm working on and are out of my control regarding the format.  If it was, I could easily get around it.

**Comment by shaggygi** [comment]
> The next question would be, how do you expect to bind case 2 to a double? If you have a default value that you would expect to use in either case 1 or case 2, then I would say case 2 would usually be considered to be a syntax error.

I set it up like you mentioned for the Arity.  This appears to fix by skipping the logic if value is 0.

Thanks for pointing out the info.
