### ISSUE TITLE
Fixing Pull Request Issues

### ISSUE THREAD

**Issue by markolbert** [dotnet/command-line-api#846]
I submitted a pull request (my first ever, BTW :)) and noticed that the automated build and review system caught a number of errors. I'm happy to try and resolve those before the request is reviewed...but I could use some guidance on how to go about figuring out what's wrong as I'm unfamiliar with the UI and nomenclature.

Are there any resources you could direct me to?

**Comment by jonsequitur** [comment]
There's no need to open a separate issue for this. We can discuss within the PR (#844).

**Comment by jonsequitur** [comment]
You can also ask questions like this on the gitter channel: https://gitter.im/dotnet/command-line-api
