### ISSUE TITLE
ZeroOrMore and OneOrMore arities only allow 255 arguments

### ISSUE THREAD

**Issue by tannergooding** [dotnet/command-line-api#863]
As per the title, the `ZeroOrMore` and `OneOrMore` arities currently cap the maximum number of arguments at `255`: https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine/ArgumentArity.cs#L88-L90

This can be problematic for various tools that expect more than 255 inputs and it should likely be raised to be `ushort.MaxValue` or `int.MaxValue`.

**Comment by tannergooding** [comment]
Happy to submit a PR for this, would just like to know if there would be any obvious issues for just doing `int.MaxValue`

**Comment by jonsequitur** [comment]
I can't think of any issues this would cause.

**Comment by JoeRobich** [comment]
@tannergooding Thanks for this fix!
