### ISSUE TITLE
FileSuggestionRegistration public API const fields typos

### ISSUE THREAD

**Issue by amis92** [dotnet/command-line-api#864]
https://github.com/dotnet/command-line-api/blob/4e3bab11bb13b79de83ec76a172f438bbcd84b61/src/System.CommandLine.Suggest/FileSuggestionRegistration.cs#L13-L14

Const fields have typos in their names:
- `ResgistrationFileName` -> `RegistrationFileName`
- `TestDirectroyOverride` -> `TestDirectoryOverride`

**Comment by jonsequitur** [comment]
Thanks. I'm fixing these but also realizing they should not have been public. 

Were you using them?

**Comment by amis92** [comment]
Nah, I was just reading through code documentation (because of the #838); it just hit my eyes ;D
