### ISSUE TITLE
Two parser issues

### ISSUE THREAD

**Issue by raki089** [dotnet/command-line-api#868]
Hi,

here are two parser issues:

If the name of the argument (file) is different from the value (filex), parsing is ok:
`[ signtool [ sign [ -v ] [ -u <user> ] [ -p <*> ] [ -ft <1000> ] [ -rt <2000> ] [ -c <certificate> ] [ -hm <SHA1> ] [ -tshm <Authenticode> ] [ -tsu <http://timestamp.com/> ] [ -fd ] [ -as ] [ -ac <cerfile> ] [ --description <description> ] [ -durl <http://description/> ] [ file <filex> ] ] ]`

If the argument name is equal to the value, parsing fails:
`[ sigtool ![ sign [ -v ] [ -u <user> ] [ -p <*> ] [ -ft <1000> ] [ -rt <2000> ] [ -c <certificate> ] [ -hm <SHA1> ] [ -tshm <Authenticode> ] [ -tsu <http://timestamp.com/> ] [ -fd ] [ -as ] [ -ac <cerfile> ] [ --description <description> ] [ -durl <http://description/> ] ] ]   ???--> file`

Here can you see that the option "-d" with an argument does not work:
`[ signtool [ sign [ -v ] [ -u <user> ] [ --password <*> ] [ -ft <1000> ] [ -rt <2000> ] [ -c <certificate> ] [ -hm <SHA1> ] [ -tshm <SHA256> ] [ -tsu <http://timestamp.digicert.com/> ] [ -fd ] [ -as ] [ -ac <certfile> ] ![ -d !<description> <url> ] ![ file <http://description> ] ] ]   ???--> sign.exe`

If you rename the option to "-des" or "-de" parsing works:
`[ signtool [ sign [ -v ] [ -u <user> ] [ --password <*> ] [ -ft <1000> ] [ -rt <2000> ] [ -c <certificate> ] [ -hm <SHA1> ] [ -tshm <SHA256> ] [ -tsu <http://timestamp.digicert.com/> ] [ -fd ] [ -as ] [ -ac <certfile> ] [ -des <description> ] [ -durl <http://description/> ] [ file <sign.exe> ] ] ]`

Best regards
Ralph

**Comment by jonsequitur** [comment]
Can you provide the help output for the tool?
