### ISSUE TITLE
[Question] Programmatically Add Options At Runtime

### ISSUE THREAD

**Issue by shaggygi** [dotnet/command-line-api#879]
I'm working on a CLI that will have plugin components and the main CLI command will not know about possible options until after the plugin is loaded.

My scenario is the CLI might be initially called once like:

```console
c:\MyCli -a=1 -b=2
```
But then later called again with dynamic options (where `-d` is introduced by the plugin):

```
c:\MyCli -a=1 -b=2 -d=3
```

Is it possible to add extra options to be parsed using the convention for a provided type and the CommandHandler?  Using [#458 as example](https://github.com/dotnet/command-line-api/issues/458#issuecomment-495789697).

For example, and for simplicity, I have a type with three properties:

```csharp
public class MyType
{
    public string A { get; set; }
    public string B { get; set; }
    public string C { get; set; }
}

```

What if the plugin added -d as an option, what are some ideas on adding `D` property to `MyType` so when I called the line below, it would be parsed correctly?  I originally was going to use a sub-command, but the software this CLI will work with is already defined and the spec can't be altered to add new sub-commands.

```
command.Handler = CommandHandler.Create<MyType>(myType => /*   */ );
```

Any help is appreciated.

**Comment by shaggygi** [comment]
I think I might have ask this in an odd way, so let me try another approach...

I think I would be able to search the plugin that has an option by name/alias, so what code is needed to at least parse out the entire CLI command/options/values?  So using my example above (`c:\MyCli -a=1 -b=2 -d=3`), how could I parse out with the name/values so when I search/find the plugin that uses the option, I could pass the data long to it?

**Comment by jonsequitur** [comment]
It's not clear to me whether you're asking how to add options (e.g. so that they show up in help, and command line input is validated against them), add bindings for your handler (so you get type conversions, etc.), or both. Can you clarify the overall startup flow?

**Comment by shaggygi** [comment]
@jonsequitur Sorry on the confusion.

So I understand on adding to show up in the help and such (e.g. AddOption(....)).

It's more of the binding that I getting stuck for when there are new options that need to be bound for type conversions.  The binding works for the initial options (e.g. a, b, c options above).  But how would you setup for optional options (e.g. d above) with handler and type conversions.

Hope this helps.

**Comment by jonsequitur** [comment]
Is the handler being reassigned by the plugin?

**Comment by shaggygi** [comment]
Not at the moment.  It still binds to the properties within `MyType` and calls the same Execute method to perform logic sequence.  However, the plan is to perform some additional logic if the extra dynamic options were included.  So that's where I'm trying to understand how to check for those extra options/parse/bind.

**Comment by jonsequitur** [comment]
You could maybe add a middleware like this:

```csharp
commandLineBuilder.UseMiddleware(async (context, next) =>
{
    var binder = new ModelBinder<MyType>();
    binder.BindMemberFromValue( instance => instance.D, c => optionD );
    context.BindingContext.AddModelBinder(binder);
    await next(context);
});
```

This assumes you have a reference to the `Option` object for your `-d` option at the time you're setting up the parser.

**Comment by shaggygi** [comment]
Let me review and try out.  Thanks again for your help @jonsequitur.

**Comment by shaggygi** [comment]
So I don't thing this will work as I really would not have member D in my MyType class.  MyType would only have the known members.  D is a dynamic option added by plugin. The next plugin could have options E & F and a 3rd plugin could have option Z.

So instead of trying to bind to a specific type, is there a way to parse the options and their arguments to something like a Dictionary?  I could loop through it to determine when to use logic for the core options and then when to use logic for the plugin options.

**Comment by jonsequitur** [comment]
The approach will vary depending on how you're configuring the parser. Are the extension options added to the parser configuration prior to parsing, or are they being treated as unmatched tokens?

**Comment by shaggygi** [comment]
I tried an exercise using [CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils) and appears I can do what I'm trying to accomplish.  Below is a simplistic example where `GetPluginOption` is simulating a plugin is found and adds the option it requires.  I like how you can check if it has the value.

I know I'm probably overlooking something with this project's API, but is there a way to add/parse in a similar manner?

```csharp
public class Program
{
    public static int Main(string[] args)
    {
        var app = new CommandLineApplication();

        var optionA = app.Option<int>("-a|--optionA", "Option A", CommandOptionType.SingleValue);
        var optionB = app.Option<int>("-b|--optionB", "Option B", CommandOptionType.SingleValue);
        var pluginOption = GetPluginOption(app);
        app.HelpOption();

        app.OnExecute(() =>
        {
            var opA = optionA.HasValue() ? optionA.Value() : "nothing";
            Console.WriteLine($"Option A: {opA}");
            var opB = optionB.HasValue() ? optionB.Value() : "nothing";
            Console.WriteLine($"Option B: {opB}");
            var opPlugin = pluginOption.HasValue() ? pluginOption.Value() : "nothing";
            Console.WriteLine($"Plugin Option: {opPlugin}");
            return 0;
        });

        return app.Execute(args);
    }

    // Simulates the plugin is loaded did have an option that is needed.
    private static CommandOption<int> GetPluginOption(CommandLineApplication app)
    {            
        // Load plugin code...
        return app.Option<int>("-d|--optionD", "Option D", CommandOptionType.SingleValue);
    }
}
```

**Comment by jonsequitur** [comment]
Below is a pretty direct translation of the code you wrote into the `System.CommandLine` API. The main difference that I noticed while translating is in this version, a separate object (`System.CommandLine.Parsing.ParseResult`) holds the parsed values. This is because we don't mutate the `Option` objects after building the parser, meaning the parser is reusable and concurrency-safe. (Sometimes you want to parse "command lines" in places other than an application entry point.)

Is this helpful?

```csharp
public class Program
{
    public static int Main(string[] args)
    {
        var optionA = new Option<int>(new[] { "-a", "--optionA" }, "Option A");
        var optionB = new Option<int>(new[] { "-b", "--optionB" }, "Option B");
        
        var app = new RootCommand
        {
            optionA,
            optionB
        };

        var pluginOption = GetPluginOption(app);

        app.Handler = CommandHandler.Create((ParseResult result) =>
        {
            var opA = result.FindResultFor(optionA)?.GetValueOrDefault() ?? "nothing";
            Console.WriteLine($"Option A: {opA}");
            var opB = result.FindResultFor(optionB)?.GetValueOrDefault() ?? "nothing";
            Console.WriteLine($"Option B: {opB}");
            var opPlugin = result.FindResultFor(pluginOption)?.GetValueOrDefault() ?? "nothing";
            Console.WriteLine($"Plugin Option: {opPlugin}");
            return 0;
        });

        return app.Invoke(args);
    }

    // Simulates the plugin is loaded did have an option that is needed.
    private static Option<int> GetPluginOption(RootCommand app)
    {
        // Load plugin code...
        var option = new Option<int>(new[] { "-d", "--optionD" }, "Option D");
        app.Add(option);
        return option;
    }
}
```

**Comment by shaggygi** [comment]
> Is this helpful?

@jonsequitur This is exactly what I needed 🎉.  I'm sorry on not explaining the details well and I really appreciate your help/time.  Closing issue now. 👍
