### ISSUE TITLE
[Question] how to do a logging verbose option with Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by BobSilent** [dotnet/command-line-api#880]
Hi,

i am trying to create a command line app, which uses dependency injection via `Microsoft.Extensions.Hosting` and uses `System.CommandLine.Hosting`.

Now I wanted to add a new option `--verbose` for setting verbose filters for the ConsoleLogger.

But how would i do it in an elegant way?
currently i have an extension method of the `CommandLineBuilder` to add the option (all only quick and dirty)
```csharp
public static CommandLineBuilder ConfigureVerboseOption(
    this CommandLineBuilder builder,
    Action createConsole)
{
    //TODO: Can I only check for the string, not for the Option Object?
    if (builder.Command.Children.GetByAlias("--verbose") != null)
    {
        return builder;
    }

    var verboseOption = new Option<bool>(new[] { "--verbose", "-v" }, "verbose logging");
    builder.AddGlobalOption(verboseOption);

    //builder.UseMiddleware(async (context, next) =>
    //{
    //    if (context.ParseResult.HasOption(verboseOption))
    //    {
    //        ???
    //    }

    //    await next(context);
    //});

    return builder;
}
``` 
First i thought i can use somehow the middleware...

and
```csharp
host.ConfigureLogging((ctx, logging) =>
		  {
			  if (host.Properties.TryGetValue(
				  typeof(InvocationContext), out var ctx2))
			  {
				  var invocationContext = ctx2 as InvocationContext;
				  if (invocationContext.ParseResult.HasOption("--verbose"))
				  {
					  logging.AddFilter("Microsoft.Hosting.Lifetime", LogLevel.Warning)
						.AddConsole(options => options.Format = ConsoleLoggerFormat.Systemd );

				  }
			  }
			  //logging.ConfigureCommandLineVerboseConsole();
		  });
```
Is this the way I would do it, i know it works, but it does not "feel" good.
Thanks

**Comment by jonsequitur** [comment]
> //TODO: Can I only check for the string, not for the Option Object?
>    if (builder.Command.Children.GetByAlias("--verbose") != null)

`Children` contains the actual list of objects so you can use an equality check here, e.g. `Children.Any(c => c == verboseOption)`. Or you can derive from `Option<T>` which is what we do for help: 

https://github.com/dotnet/command-line-api/blob/7146ca4b45df26bbf85ebb38dc1e44a3c40ca7d0/src/System.CommandLine/Parsing/ParseResultVisitor.cs#L240-L242

For the binding part, what's the code you would like to be able to write?

**Comment by BobSilent** [comment]
I looked at the code and played a little bit more around with it.

>For the binding part, what's the code you would like to be able to write?
Maybe the verbose option is something special, or should be something special, and it should be a common Option comparable to
- `UseHelp()`
- `UseVersionOption()`
something like
- `UseVerboseOption(isHidden: false)`

as in most of my command line tools I use this.

Therefore i would like to write something like this 
`logging.AddConfiguration<VerboseOption>((iLoggingBuilder, optionValue) => iLoggingBuilder.Add...)`
or
`logging.AddConditionalConfiguration`

instead of 

```csharp
host.ConfigureLogging((ctx, logging) =>
    {
        if (ctx.Properties.TryGetValue(typeof(InvocationContext), out var ctx2))
        {
            var invocationContext = ctx2 as InvocationContext;

            if (invocationContext.ParseResult.HasOption("--verbose"))
            {
                logging.Add...
            }
```

regarding the Idea you suggested with `Children.Any(c => c == verboseOption)`
I created
```csharp
internal class VerboseOption : Option<bool>
{
    public VerboseOption() : base(new[]
    {
        "-v",
        "/v",
        "--verbose",
    }, "Show help and usage information")
    {
    }

    protected bool Equals(VerboseOption other)
    {
        return other != null;
    }

    public override bool Equals(object obj)
    {
        return obj is VerboseOption;
    }

    public override int GetHashCode()
    {
        return typeof(VerboseOption).GetHashCode();
    }
}
```
I created a static class
```csharp
internal static class Options
{
    internal static VerboseOption VerboseOption => new VerboseOption();
}
```

I created my Extension Method
```csharp
public static CommandLineBuilder UseVerboseOption(
    this CommandLineBuilder builder,
    Action createConsole)
{
    if (builder.Command.Children.Any(o => o is VerboseOption))
    {
        return builder;
    }

    builder.AddGlobalOption(Options.VerboseOption);

    return builder;
}
```
1. Wouldn't it be more readable to write this `builder.AddGlobalOption<VerboseOption>();` instead of creating the Option instance in advance? 


in my `host.ConfigureLogging((ctx, logging) =>` i wrote:
```csharp
if (invocationContext.ParseResult.HasOption(Options.VerboseOption))
```

unfortunately:
https://github.com/dotnet/command-line-api/blob/7146ca4b45df26bbf85ebb38dc1e44a3c40ca7d0/src/System.CommandLine/Parsing/ParseResultExtensions.cs#L194
uses `==` operator and this one always returns `false` for me. 
overriding of Equals brings nothing.

2. Wouldn't it be better to inherit from `IEquatable`, in other words make `ISymbol : IEquatable<ISymbol>,..` or `Symbol :  IEquatable<ISymbol>,..` with 
`virtual` or `abstract Equals` and `GetHashCode`
and maybe also override operator `==` and `!=` to call `Equals`?


Value for option only accepts string Alias
```csharp
        public T ValueForOption<T>(string alias)
```
3. I am missing this:
```csharp
        public T ValueForOption<T>(Option<T> option)
```
or for me the name would be more like that (comparable with Linq `FirstOrDefault()`): 
```csharp
        public T GetOptionValueOrDefault(Option<T> option)
```
or like that, if I already have a dedicated option class
```csharp
        public T GetOptionValueOrDefault<Option<T>>()
```

**Comment by BobSilent** [comment]
Point 2 is more or less an issue on my site
```csharp
internal static class Options
{
    internal static VerboseOption VerboseOption => new VerboseOption();
}
```

but should be 
```csharp
    internal static VerboseOption VerboseOption { get; } = new VerboseOption();
```

then `HasOption(Options.VerboseOption)` will return `true`, but i think the root question remains: Although I made a mistake, but i would see the Option as same, which means implementing Equality compare as suggested. 
Does a PR for discussion (and removing this discussion form this issue) make sense here?!

**Comment by jonsequitur** [comment]
Another API that might be useful is `ParseResult.FindResultFor`. While `ParseResult.CommandResult.Children` doesn't search recursively, `FindResultFor` does, and it takes `IOption` or `IArgument` directly:

```csharp
var value = parseResult.FindResultFor(option)?.GetValueOrDefault();
```

**Comment by BobSilent** [comment]
Closing this, and Thanks @jonsequitur  your answers are always really helpful and push me in the right direction!
