### ISSUE TITLE
Validators are only called for the last command

### ISSUE THREAD

**Issue by helloserve** [dotnet/command-line-api#881]
I've setup a series of commands that creates the following tree:

- rootCommand
  - command1
  - command2
    - new
    - update

I have three options that are applicable to all handlers (e.g. `command1`, `command2 new` and `command2 update`). They are `-f <FileInfo>`, `-s <DateTime>` and `-o <FileInfo>`.

I add these options to `rootCommand` using `.AddGlobalOption()`. So my args would look like `-f "c:\path\to\input" -s "2020-01-01" -o "c:\path\to\output" command1`.

# Expected behavior

When the input file (`-f`) doesn't exist, I expect to see the error message from `.ExistingOnly()`, or from the validator that I manually add to the argument:

```
var inputFileArgument = new Argument<FileInfo>();
inputFileArgument.AddValidator(r =>
{
	var inputFile = r.GetValueOrDefault();
	if (!File.Exists(inputFile.ToString()))
	{
		return $"The file '{inputFile}' does not exist.";
	}

	return null;
});
```

I don't see it, instead my handler generates a `FileNotFoundException`.

# Actual behavior

When I change the command line to be `-s "2020-01-01" -o "c:\path\to\output" command1 -f "c:\path\to\input"`, then I do see the expected behavior.

# Version

I first found this on version `2.0.0-beta1.20158.1`, and it is the same on version `2.0.0-beta1.20214.1`

**Comment by caderoux** [comment]
Is this similar to what I am currently seeing trying to make a global option for input file be an existing file?  I'm not getting an exception or anything.  It gets into the handler and prints the file names, neither of which exist.

```
      static int Main(string[] args)
      {

         var rootCommand = new RootCommand();

         // Which .ExistingOnly() is appropriate? - neither seem to work
         var inOption = new Option<FileInfo>("--infile", "Input File") { Argument = new Argument<FileInfo>() { Arity = ArgumentArity.ExactlyOne }.ExistingOnly() }.ExistingOnly();
         inOption.AddAlias("-i");
         inOption.Required = true;
         rootCommand.AddOption(inOption); // Also tried .AddGlobalOption

         var xmlCommand = new Command("xml");
         var xmlOption = new Option<FileInfo>("--xmlfile", "XML File") { Argument = new Argument<FileInfo>() { Arity = ArgumentArity.ExactlyOne } };
         xmlOption.AddAlias("-x");
         xmlOption.Required = true;
         xmlCommand.AddOption(xmlOption);
         xmlCommand.Description = "Export to XML File";
         xmlCommand.Handler = CommandHandler.Create((FileInfo infile, FileInfo xmlfile) =>
         {
            Console.WriteLine($"The value for --infile is: {infile?.FullName ?? "null"}");
            Console.WriteLine($"The value for --xmlfile is: {xmlfile?.FullName ?? "null"}");
         });

         rootCommand.Description = "Command Line Tools";
         rootCommand.AddCommand(xmlCommand);

         return rootCommand.InvokeAsync(args).Result;
      }
```

This is the profile I am running with in the debugger

```
    "xml filemissing": {
      "commandName": "Project",
      "commandLineArgs": "--infile filemissing.input xml --xmlfile xmlfile.xml"
    }

```

**Comment by helloserve** [comment]
Yep looks like the same issue. If you move your `--infile filemissing.input` option to be after your `xml` command, it will validate.
