### ISSUE TITLE
Handle more than 7 options in a single command

### ISSUE THREAD

**Issue by gandhis1** [dotnet/command-line-api#882]
I have a `RootCommand` with more than 7 options. It seems as though `CommandHandler.Create()` cannot handle a delegate with more than 7 parameters. Sure, you can make an argument that 7 options is on the high end, but in my application only a subset of these options would be used at once. Surely there's a way to get this to work?

**Comment by jonsequitur** [comment]
The approach we've been recommending if you have that many command line parameters is to create a class and bind each option / argument to a property: https://github.com/dotnet/command-line-api/issues/458#issuecomment-495789697
