### ISSUE TITLE
Options defined at root command are not validated for verbs

### ISSUE THREAD

**Issue by simonech** [dotnet/command-line-api#901]
If I specify that an option that I use in all my verbs is `Required` by specifying it in the `RootCommand`, I don't get a validation error if I call a sub-command without it.

Ex:

```csharp
var command = new RootCommand
{
    new Option("-f") {
        Argument = new Argument<FileInfo>().ExistingOnly(),
        Required = true
    }
};

var extractCmd = new Command("extract", "Extract an Xliff file from an HTML file.");
command.AddCommand(extractCmd);

extractCmd.Handler = CommandHandler.Create<FileInfo>(Extract);
```

If I call the app without verbs I get `Option '-f' is required.` and the help

If I call it with the verb `extract` I get into the `Extract` method defined as handler.

Shall I specify the option in all the verbs as well?

**Comment by jonsequitur** [comment]
This is intentional. Required options are only required (and, generally, options and arguments are only *validated*) if their parent verb is invoked. You can reuse commands, options, or arguments like this:

```csharp
var option = new Option<FileInfo>("-f") {
    Required = true
}.ExistingOnly();

var command = new RootCommand
{
    option
};

var extractCmd = new Command("extract", "Extract an Xliff file from an HTML file.")
{
    option
};
command.AddCommand(extractCmd);
```

Another way to accomplish the same thing is to use `AddGlobalOption`, which adds it to the specified command and all of its child commands:

```csharp
var command = new RootCommand();
var extractCmd = new Command("extract", "Extract an Xliff file from an HTML file.");
command.AddCommand(extractCmd);
command.AddGlobalOption(option);
```

**Comment by simonech** [comment]
Thank you. Yeah the `GlobalOption` makes more sense in my case, since all my verbs deal with reading a file.
