### ISSUE TITLE
Change ContainerSpan from being a IReadOnlyList

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/command-line-api#903]
In working to have PS7 leverage system.commandline.rendering, one issue is that often the content to be rendered is generated dynamically at runtime.  So having to create a ContainerSpan using just the constructor is insufficient.  Ideally, support for the addition operator or Append() would be sufficient.  However, it seems that we could simply have ContainerSpan be a ICollection.  Thoughts?

**Comment by jonsequitur** [comment]
It makes good sense to make it mutable. An `Add` method would also enable collection initializer syntax.

**Comment by SteveL-MSFT** [comment]
Adding `Add` would be sufficient and a small change.  I'll work on a PR.
