### ISSUE TITLE
Overload Add() for ContainerSpan to accept a string

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/command-line-api#907]
Current usage in PowerShell looks like:

```powershell
using namespace system.commandline.rendering

$cs = [containerspan]::new()
$cs.Add([stylespan]::BoldOn)
$cs.Add([contentspan]'hello ')
$cs.Add([stylespan]::BoldOff)
$cs.Add([contentspan]'there')
$cs.ToString([outputmode]::Ansi)
```

would be better to have:

```powershell
using namespace system.commandline.rendering

$cs = [containerspan]::new()
$cs.Add([stylespan]::BoldOn)
$cs.Add('hello ')
$cs.Add([stylespan]::BoldOff)
$cs.Add('there')
$cs.ToString([outputmode]::Ansi)
```

Where a string overload produces a `ContentSpan` object.  Thoughts?

**Comment by jonsequitur** [comment]
I think it makes sense, but it also loses the typing, so if you pass ANSI codes into that string, and then `ToString(OutputMode.NonAnsi)`, you'll get ANSI codes in the output.

**Comment by SteveL-MSFT** [comment]
Expectation is that users don't use embedded ANSI codes in the string.  I don't think we should go so far as prevent it.  If you're ok with this, I can submit a PR.
