### ISSUE TITLE
[Question] How to use CommandHandler with more than 10 options in a command?

### ISSUE THREAD

**Issue by BizarreNULL** [dotnet/command-line-api#909]
I have 13 `Option` for a `Commnad` in my CLI, how to parse all this options? With `CommandHandler` is not possible?

**Comment by jonsequitur** [comment]
You can bind options and arguments to properties on a complex type: https://github.com/dotnet/command-line-api/issues/458#issuecomment-495789697

**Comment by BizarreNULL** [comment]
Thanks @jonsequitur, I missed whis question is already answered
