### ISSUE TITLE
Help does not output available commands / help command does not ouput the the command options

### ISSUE THREAD

**Issue by Sypieni** [dotnet/command-line-api#917]
Hi

I'm writing a command line program with different subcommands.

The main looks like this :
```cs
public static void Main(string[] args)
{
  var root = new RootCommand();

  var cmdA = GetCommandA();
  var cmdB = GetCommandB();

  root.AddCommand(cmdA);
  root.AddCommand(cmdB);

  root.Description = "Program with two commands";
  root.IsHidden    = false;

  Environment.Exit(root.InvokeAsync(args).Result);
}
```

While the methods that provide me with command A and B are very similar (slightly different options) and look like 

```cs
private static Command GetCommandA()
{
  var rmaCmd = new Command("CommandA") {
    IsHidden                     = false
  , TreatUnmatchedTokensAsErrors = true
  , Description                  = "Command A description"};

  rmaCmd.AddAlias("ca");

  var inO = new Option<DirectoryInfo>(
    new[] {"--input" , "-i" }
  , "Input directory") {
    Argument = {Arity = ArgumentArity.ExactlyOne}
  , Required = true};

  rmaCmd.AddOption(inO);
  rmaCmd.Handler = CommandHandler.Create<DirectoryInfo>(ProcessCommandA);

  return rmaCmd;
}
```

Finally the handler method is probably irrelevant but looks as such 

```cs
public static void ProcessCommandA(DirectoryInfo i)
{
  /* Do something with i */
}
```
When I execute my program I get the following output:

```txt
> .\SomeProgram.exe -h
Usage:
  SomeProgram [options] [<args>...]

Arguments:
  <args>

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

The following happens when I fail to input any required command:
```txt
> .\SomeProgram.exe
Required command was not provided.

SomeProgram:
  Program with two commands

Usage:
  SomeProgram [options] [command]

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information

Commands:
  ca, CommandA      Command A description
  cb, CommandB      Command B description
```
Additonnaly, the same happens when I di specify a command with the -h flag

```txt
> .\SomeProgram.exe ca -h
Usage:
  SomeProgram [options] [<args>...]

Arguments:
  <args>

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

I do get the proper help when I fail to input a mandatory option 
```txt
> .\SomeProgram.exe ca
Option '--input' is required.

CommandA:
  Command A description"

Usage:
  SomeProgram CommandA [options]

Options:
  -i, --input <input> (REQUIRED)    Input directory
  -?, -h, --help                    Show help and usage information
```

I have read stuff in issue #586 indicating that a missing description could cause issues but that does not seem to be the case.

Am I missing something ?

Thanks a bunch

**Comment by jonsequitur** [comment]
Which version of System.CommandLine are you using?

**Comment by Sypieni** [comment]
I'm unsure. Right click -> Properties on the System.CommandLine.dll gives me version 2.0.20.25301
Is that what you're looking for ?

I'm running .net core 3.1.300

**Comment by jonsequitur** [comment]
Is the issue then that you don't see the commands described when you do this?

```console
> .\SomeProgram.exe -h
```

I'm not able to reproduce the issue using the code you provided. But I noticed that your help output shows `[<args>...]` while no arguments are added in your example code. The code you provided might not be complete enough to reproduce the issue.

**Comment by Sypieni** [comment]
That is correct. Additionally, the --input option is not shown when I do this 

```txt
> .\SomeProgram.exe ca -h
```

Regarding the code being possibly incomplete, I doubled check by doing these steps:

1. Create a new .net core console application in Visual Studio Professional 2019 v16.6.1
2. Install the nuget package via the following command
```txt
PM> Install-Package System.CommandLine.DragonFruit -Version 0.3.0-alpha.20303.1
```
3. Copy/paste the code provided in the first comment in Program.cs
4. Compile & run

I can confirm I have the following outputs

```txt
PS> .\TestDragonFruit.exe
Required command was not provided.

TestDragonFruit:
  Program with two commands

Usage:
  TestDragonFruit [options] [command]

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information

Commands:
  ca, CommandA    Command A description
  cb, CommandB    Command B description

PM> .\TestDragonFruit.exe ca
Option '--input' is required.

CommandA:
  Command A description

Usage:
  TestDragonFruit CommandA [options]

Options:
  -i, --input <input> (REQUIRED)    Input directory
  -?, -h, --help                    Show help and usage information

PM> .\TestDragonFruit.exe ca -h
Usage:
  TestDragonFruit [options] [<args>...]

Arguments:
  <args>

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information

PM> .\TestDragonFruit.exe -h
Usage:
  TestDragonFruit [options] [<args>...]

Arguments:
  <args>

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

**Comment by jonsequitur** [comment]
I think I see what's happening. 

DragonFruit doesn't support subcommands. If you're creating a parser inside of `Main`, but DragonFruit is in use, then DragonFruit is intercepting the help request and isn't aware of the parser you're defining.

In your project file, try replacing the `System.CommandLine.DragonFruit` package reference with `System.CommandLine`: https://www.nuget.org/packages/System.CommandLine/. Note that the version number will be different as well.

**Comment by pavel-agarkov** [comment]
But without System.CommandLine.DragonFruit I cannot use ConfigureFromMethod.
Is there any way to use DragonFruit without it intercepting the help request?

**Comment by pavel-agarkov** [comment]
I found the way to display nice help while still using System.CommandLine.DragonFruit

1.  Disable nuget package build targets
```xml
<PackageReference Include="System.CommandLine.DragonFruit" Version="0.3.0-alpha.20574.7">
  <ExcludeAssets>build</ExcludeAssets>
</PackageReference>
```
2.  Add help from xml docs like this
```cs
private static Command GetCommand(string methodName)
{
    var cmd = new Command(methodName.ToKebabCase());
    var commandMethod = GetMethod(methodName);
    cmd.ConfigureFromMethod(commandMethod);
    new CommandLineBuilder(cmd).ConfigureHelpFromXmlComments(commandMethod, null);
    return cmd;
}
```
