### ISSUE TITLE
Command argument is null

### ISSUE THREAD

**Issue by OGMichel** [dotnet/command-line-api#920]
**Environment**
.NET Core Version: 3.1.201
Target Framework: netcoreapp3.1
Package Version: 2.0.0-beta1.20303.1
OS: Windows10 64bits

**Issue**
I try to create a multi level Command with a different handler for each command.
For one of the command I want to add a simple Argument instead of an option.
The parsing seems to work properly  as the [parse] command returns the following result :
_**[ ConsoleApp1 [ --r [ r <test.json> ] ] ]**_
But my handler doesn't receive the value of the argument and throw the following exception:
**System.NullReferenceException : 'Object reference not set to an instance of an object.'**

Here is my code 

```cs
private static int Main(string[] args)
{
   Command FromFile = new Command("--r", "Run with settings file");
   FromFile.AddArgument(new Argument<FileInfo>());
   FromFile.Handler = CommandHandler.Create<FileInfo>(RunWithSettingFile);
   Command rootCommand = new RootCommand
   {
      FromFile
   };
   return rootCommand.InvokeAsync(args).Result;
}

private static void RunWithSettingFile(FileInfo settings)
{
   Console.WriteLine(settings.FullName);
}
```

Could you please help me understand why it doesn't work ?

**Comment by jonsequitur** [comment]
The parameter name needs to match one of the argument or option names. Try this:

```csharp
FromFile.AddArgument(new Argument<FileInfo>("settings"));
```

**Comment by OGMichel** [comment]
Thank you for your help it works fine. I should have read the "Syntax-first" paragraph of the wiki properly.
