### ISSUE TITLE
How to handle multiple instances of a subcommand ?

### ISSUE THREAD

**Issue by flonou** [dotnet/command-line-api#922]
Hi, I'm trying to use the package in order to add new command line capabilities to an already existing software (Unity3D). I'm facing some issues. The first one is that I couldn't find how to make a sub command usable multiple time in one call and the second one is that the first argument (of type string) is empty when my Handler is called (the int argument is ok however)

 ```
var commandScriptOrder = new Command("--scriptorder")
{
        new Argument<string>("behaviour name", "The name of the behaviour"),
        new Argument<int>("order", "The new excecution order value")
};
commandScriptOrder.AddAlias("-so");
commandScriptOrder.Handler = CommandHandler.Create<string, int>(ChangeScriptOrder);

var parentCommand = new RootCommand
{
        commandScriptOrder,
};
parentCommand.Name = "Unity";

// As we may have other arguments related to Unity (-batchmode, -quit, ...)
parentCommand.TreatUnmatchedTokensAsErrors = false;

// Change the executable name argument so that it marches the parent command name
string[] arguments = Environment.GetCommandLineArgs();
arguments[0] = "Unity";

// Need to use InvokeAsync otherwise the code is stuck here
parentCommand.InvokeAsync(arguments);

```

Here is the output of the `Unity.exe [parse] -quit -batchmode -so SeparateThread 222 -so UnityExecutionThread 333` command : 
`[ Unity [ -so [ behaviour name <SeparateThread> ] [ order <222> ] ] ]   ???--> -quit -batchmode -so UnityExecutionThread 333`
As you can see, the second use of -so is ignored
If I remove the `[parse]` token, `ChangeScriptOrder` will be called only once with parameters "" (empty string) and 222

**Comment by jonsequitur** [comment]
> The first one is that I couldn't find how to make a sub command usable multiple time in one call

This isn't supported. A subcommand (a.k.a. verb) can only be specified once per invocation. It looks like `-so` should be an `Option` rather than a `Command`. In order for an `Option` to accept two arguments of different types like you have, you'll need a custom parse delegate. Try something like this:

```csharp
var orderOption = new Option<ScriptOrder>(
    new[] { "-so", "---scriptorder" },
    argResult =>
    {
        if (!ScriptOrder.TryParse(
                argResult.Tokens[0].Value,
                argResult.Tokens[1].Value,
                out var so))
        {
            argResult.ErrorMessage = "oops";
            return null;
        }

        return so;
    }
);
// Specifying the arity this way means the option is only valid if exactly two arguments are passed
orderOption.Argument.Arity = new ArgumentArity(2, 2); 

// ...

public class ScriptOrder
{
    public ScriptOrder(string behaviorName, int order)
    {
        BehaviorName = behaviorName;
        Order = order;
    }

    public string BehaviorName { get; }

    public int Order { get; }

    public static bool TryParse(string value, string s, out ScriptOrder o)
    {
        if (int.TryParse(s, out var i))
        {
            o = new ScriptOrder(s, i);
            return true;
        }

        o = default;
        return false;
    }
}

```

**Comment by slide** [comment]
I am trying to use what you wrote in my application, I want to be able to do something like:

`myapp --var NAME0 VALUE0 --var NAME1 VALUE1`

so, I setup something similar to what you wrote above:

```csharp
using System;
using System.Collections.Generic;
using System.CommandLine;
using System.CommandLine.Invocation;

namespace ConsoleApp1 {
    class Variable {
        public Variable(string name, string val) {
            Name = name;
            Value = val;
        }

        public string Name { get; }

        public string Value { get; }
    }

    class Program {
        static void Main(string[] args) {
            var varOptions = new Option<Variable>("--var", description: "Variables", parseArgument: argResult => {
                return new Variable(argResult.Tokens[0].Value, argResult.Tokens[1].Value);
            });
            varOptions.Argument.Arity = new ArgumentArity(2, 2);

            var root = new RootCommand() {
                varOptions
            };
            root.Handler = CommandHandler.Create((Variable[] var) => {
                Console.WriteLine(var);
            });

            root.Invoke(args);
        }
    }
}
```

When I run with `myapp --var NAME0 VALUE0 --var NAME1 VALUE1` with this code, I get the following error:

```
Option '--var' expects a single argument but 3 were provided.
Option '--var' expects a single argument but 3 were provided.
Unrecognized command or argument 'VALUE1'

Usage:
  ConsoleApp1 [options]

Options:
  --var <var>       Variables
  --version         Show version information
  -?, -h, --help    Show help and usage information

```

Am I missing something?

**Comment by jonsequitur** [comment]
The following are equivalent:

```console
> myapp -x one -x two
> myapp -x one two
```

So the arity describes the total number of arguments applied to the option. Re-specifying the option doesn't reset the arity.

**Comment by slide** [comment]
Ok, I solved it a different way. I was thinking that arity behaved differently. I ended up just collecting all the parameters for `--var` and then making sure there was an even number of them and parsing them two at a time for the name and value. Thanks for the tips.
