### ISSUE TITLE
Ambiguous error when adding a throw in command handler

### ISSUE THREAD

**Issue by shaggygi** [dotnet/command-line-api#926]
Not sure if this is an issue with this API or more related to C# language.  When I add the throw in handler I get the compile error below.

```csharp
Handler = CommandHandler.Create<string>((projectPath) =>
{
    throw new Exception("What?");
    Console.WriteLine(File.ReadAllText(projectPath));
});
```

"The call is ambiguous between the following methods or properties: 'CommandHandler.Create<T>(Func<T, int>)' and 'CommandHandler.Create<T>(Func<T, Task<int>>)'"

**Comment by jonsequitur** [comment]
This because C# type inference can't distinguish between the overloads. Adding `return 1;` at the end, for example, will resolve the problem, even when the code is unreachable.
