### ISSUE TITLE
Handle commands with more than 7 parameters?

### ISSUE THREAD

**Issue by bounav** [dotnet/command-line-api#927]
[CommandHandler](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine/Invocation/CommandHandler.cs) only defines up to 7 strongly typed parameters.

What if you need more parameters for your command?

Is there a better way to _handle_ commands with larger numbers of parameters?

Any reason more than 7 parameters are missing from the current implementation?

**Comment by bounav** [comment]
If you need more than 7 parameters you can declare more overloads in an extension method.

Below is an example to define a 10 parameter overload.

```csharp
public static ICommandHandler Create<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
     Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> action) =>
            HandlerDescriptor.FromDelegate(action).GetCommandHandler();
```

**Comment by jonsequitur** [comment]
You can also use custom classes and options will get bound to properties or constructor parameters: https://github.com/dotnet/command-line-api/issues/458#issuecomment-495789697.

**Comment by bounav** [comment]
Perfect, that's what I was looking for. Sorry, I forgot to check the closed issues.
