### ISSUE TITLE
Optimizing command line option parse performance

### ISSUE THREAD

**Issue by nattress** [dotnet/command-line-api#929]
We have been using the command line API in [crossgen2](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/tools/crossgen2/crossgen2/CommandLineOptions.cs) for a few months. We're looking at the performance of the compiler on small workloads and noticed that for a 622ms compile of HelloWorld, 130ms is spent parsing the command line. We pass around 5-10 arguments typically. Also, everything has been AOT'd in this experiment.

Is there any advice / guidance on using the command line API when optimizing for app startup throughput? Is there anything I can do differently here so things are more statically defined.

**Comment by jonsequitur** [comment]
We haven't done much in the way of performance optimization in the parser, so there's almost certainly some significant low-hanging fruit on the System.CommandLine side.

I'd also be happy to take a look at how you're using System.CommandLine and see if anything stands out. Doing some performance analysis in the context of your code would be useful for both projects, I expect.

**Comment by jkotas** [comment]
If it helps, we have been using https://github.com/dotnet/corefxlab/tree/master/archived_projects/src/System.CommandLine. It had  order of magnitude better startup performance compared to this project.

**Comment by KathleenDollard** [comment]
Jan, 

I'd love to know more about the performance comparison. We did a rrewrite a while back, and if you're comparison was before that, we'd love to rerun to see what changed. 

The corefxlab has be deprecated and has no current support. 

Binding in particular is an area where we use reflection to greatly simplify CLI creation/usage, at a performance cost. We will be looking at whether we can push some of that into design time with source generation in the future.

**Comment by nattress** [comment]
Source generation could be promising here. For a tool like Crossgen2, we don't need dotnet suggest integration or any of the bells and whistles. We just need the args parsed as fast as possible. To contrast with the tool we're replacing, crossgen1 will compile HelloWorld in about 60ms of process wall clock time. If we want to get crossgen2 remotely close, command line parsing will need to be done in <10 ms vs the current 130ms+.

**Comment by jonsequitur** [comment]
I'd like to take a look at your code and benchmarks. The typical startup phase for a command-line app breaks into three steps, really:

1) Parsing input strings into a syntax representation,
2) Binding the syntax to the strong-typed parameters, and
3) Invoking the handler, passing in the bound values.

For case 1, there's an optimization in our tokenizer that I've been meaning to do.

There are things you can do to optimize 2 and 3 to minimize the reflection cost. 

As far as bells and whistles, we can take a look there as well, though I suspect that most of them don't impact startup speed, though one that definitely could is this: https://github.com/dotnet/command-line-api/blob/3c1af6b24204aa5eb883518a2dcf000e607fd967/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L167. You can opt out of these kinds of features easily. 

I'd be happy to take a look at your code and see what we can do. Would you like to set up some time?

**Comment by jkotas** [comment]
Here is a trivial benchmark - app with two options: https://github.com/jkotas/commandline-perf

The perf numbers that I get on WSL 2 (the binaries are compiled with `dotnet publish -c Release`):

```
jkotas@JKOTAS5:~/commandline-perf$ time ./empty/bin/Release/netcoreapp3.1/publish/empty
Hello World!

real    0m0.088s
user    0m0.076s
sys     0m0.023s
jkotas@JKOTAS5:~/commandline-perf$ time ./corefxlab/bin/Release/netcoreapp3.1/publish/corefxlab -s Hello
Bool option: False
String option: Hello

real    0m0.106s
user    0m0.097s
sys     0m0.020s
jkotas@JKOTAS5:~/commandline-perf$ time ./command-line-api/bin/Release/netcoreapp3.1/publish/command-line-api -s Hello
Bool option: False
String option: Hello

real    0m0.194s
user    0m0.185s
sys     0m0.021s
```

corefxlab System.CommandLine added 18 ms over empty app. System.CommandLine adds 6x more.

**Comment by jonsequitur** [comment]
Thanks, @jkotas. 

This looks like there's roughly a 20% overhead (relative to not using a parser) for the obsoleted CoreFxLab library and about a 120% overhead for using the new System.CommandLine.

I did a quick benchmark using the same approach (but on Windows, since I don't have a Linux setup handy) and I see a range of 30-50% overhead range for the CoreFxLab version, and, with a minor change to your code, a range of 80-100% overhead for the new System.CommandLine. I expect that we can close that gap a good deal more by reducing the use of LINQ in the tokenizer and reducing some use of reflection in the binder. This is low-hanging fruit, as we haven't done much perf work.

I'll submit a PR to your benchmark so you can compare.

**Comment by jonsequitur** [comment]
Here's the quick benchmark addition, including a small perf update I made to System.CommandLine last night: https://github.com/jkotas/commandline-perf/pull/1
