### ISSUE TITLE
Binding stops working when a string option has a default value set to null

### ISSUE THREAD

**Issue by bounav** [dotnet/command-line-api#930]
This one left me scratching my head for a whole day so I thought I'd share my findings...

If you make `getDefaultValue` for an`Option<string>` return `null`, the model binder will **not** map the parameters/options.

In the example below the Input class's constructor is not called but the handler's callback is called with `input` set to null, resulting in a `NullReferenceException` thrown in the `Execute` method.

```csharp
public class Input
{
    public Input(string a, string b)
    {
        A = a;
        B = b;
    }

    public string A { get; set; }

    public string B { get; set; }
}
```

```csharp
public class ExampleA
{
    public async Task Execute(Input input)
    {
        System.Console.WriteLine(input.A.length);
        System.Console.WriteLine(input.B.length);
    }
}
```

```csharp
var command = new Command("example")
{
    new Option<string>("--a", getDefaultValue: () => "default A",
    new Option<string>("--b", getDefaultValue: () => null
};

command.Handler = CommandHandler.Create<Input>(async (input) =>
{
    var instance = new ExampleA();

    // input is null
    await instance.Execute(input);
});
```

Changing the the default value fro option of the `--b` to an empty string instead of null fixes the issue.

```csharp
    new Option<string>("--b", getDefaultValue: () => ""
```

**Comment by jonsequitur** [comment]
This should work if the constructor parameters are made optional.

**Comment by bounav** [comment]
> This should work if the constructor parameters are made optional.

Would it look a bit strange to declare a nullable `string` parameters (`string` being nullable because it's a reference type)?

**Comment by bounav** [comment]
The [v2.0.0-beta1.21216.1 release](https://github.com/dotnet/command-line-api/releases/tag/v2.0.0-beta1.21216.1) sorted this out with the following change:

> Model binding no longer passes null for unspecified argument and option values of IEnumerable or string types. Instead, it passes an empty array or list of the appropriate type, or string.Empty, respectively.

I've updated my dependency to `System.CommandLine` and was able to remove the `getDefaultValue: () => ""` lines of code I had in my `.AddOption(...)` calls. :)

I'm going to close this issue now.
