### ISSUE TITLE
Consider overriding AnsiControlCode.ToString to return EscapeSequence

### ISSUE THREAD

**Issue by oising** [dotnet/command-line-api#932]
Looking at:
https://github.com/dotnet/command-line-api/blob/518dd1fb67ebaf436ce32ae0b9103c0e446c30aa/src/System.CommandLine.Rendering/AnsiControlCode.cs#L23

If we return `EscapeSequence` from `ToString()` instead of the empty string, it seems like we could make inline usage with interpolated strings a lot nicer to read. For example:

```C#
using Cursor = Ansi.Cursor;
var buffer = $"hello,{Cursor.Move.Right}World"
```
No need for the full `Ansi.Cursor.Move.Right.EscapeSequence` which seems overly verbose.

**Comment by jonsequitur** [comment]
These APIs are intended to be used to write output code once and have the option to output it with or without VT sequences. Here are some examples:

https://github.com/dotnet/command-line-api/blob/afd010ba8cb3cbd714c734465d1a5de1ee133e2d/src/System.CommandLine.Rendering.Tests/TextSpanTests.cs#L87-L107

**Comment by oising** [comment]
Oh, okay - gotcha @jonsequitur -- I was thinking in a very constrained way. That's very cool. Closing.
