### ISSUE TITLE
[Question] Limitation on Option Number

### ISSUE THREAD

**Issue by KodiStudios** [dotnet/command-line-api#933]
From Api:
```csharp
[return: NullableAttribute(1)]
		public static ICommandHandler Create<T1, T2, T3, T4, T5, T6, T7>([NullableAttribute(1)] Action<T1, T2, T3, T4, T5, T6, T7> action);
```

It would seem that System.CommandLine libarary supports only up to 7 options.

Am I missing something?

If indeed it supports only 7 options max, this limitation should be states somewhere on Wiki

**Comment by jarglez** [comment]
You can use a delegate to add more than seven options.

**Comment by jonsequitur** [comment]
You can also use custom classes and options will get bound to properties or constructor parameters: https://github.com/dotnet/command-line-api/issues/458#issuecomment-495789697.
