### ISSUE TITLE
ArgumentArity.ExactlyOne does not catch a missing argument

### ISSUE THREAD

**Issue by belgaard** [dotnet/command-line-api#936]
I have specified FileInfo and DirectoryInfo arguments as ArgumentArity.ExactlyOne. If I pass two of one of these on the commandline I get a nice error message. Also, if the file or directory does not exist, I get an equally kind error message. That's cool.

But if I omit one of the parameters, my handler gets a null value. That's not cool. I would expect a nice error message here as well.

Here is the code,

        private static async Task Main(string[] args)
        {
            Argument<FileInfo> trxArgument = new Argument<FileInfo>().ExistingOnly();
            trxArgument.Arity = ArgumentArity.ExactlyOne;
            var trxOption = new Option("--trx", "The .trx-file to process.")
                { Argument = trxArgument};
            trxOption.AddAlias("--tx");

            Argument<DirectoryInfo> tpdArgument = new Argument<DirectoryInfo>().ExistingOnly();
            tpdArgument.Arity = ArgumentArity.ExactlyOne;
            var tpdOption = new Option("--testplandirectory", @"The directory with test plans to process.")
                { Argument = tpdArgument};
            tpdOption.AddAlias("--tpd");

            var command = new RootCommand
            {
                trxOption,
                tpdOption
            };
            command.Description = "The Lean Test test processor.";

            command.Handler = CommandHandler.Create(async (FileSystemInfo tx, DirectoryInfo tpd, ParseResult p) =>
                {
                    // TODO: Somehow use built-in System.CommandLine functionality:!!!
                    if (tx == null || tpd == null)
                    {
                        Console.WriteLine("The .trx and test plan directory are required.");
                        return;
                    }
// ...

**Comment by jonsequitur** [comment]
Options are not required by default. To make them required, you can set `Option.Required` to `true`.

Also, setting the arity is almost never required. `ExactlyOne` is the default arity for non-collection types such as `FileInfo` and `DirectoryInfo`.

Hope that helps.

**Comment by belgaard** [comment]
Thanks, yes you are probably right - in the meantime I have changed my code to need need it anyway.
