### ISSUE TITLE
ParserConfiguration.Prefixes is ambiguous and should not modify commands

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/command-line-api#94]
The `ParserConfiguration.Prefixes` property's name doesn't quite capture its intent. 

The idea is that it should apply a set of universal prefixes to all options in order to provide a pit of success for end users who might not know which prefixes are valid, given that `-`, `--`, and `/` are variously valid in common command lines. 

It should not apply to commands, only to options, but currently the implementation affects parsing of both.

**Comment by Keboo** [comment]
The current implementation only affects the items in the passed in symbols which is is not recursive. Once we figure out how prefixes should work, we should address this as well.
