### ISSUE TITLE
Parsing issue when two Options have similar shortforms.

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/command-line-api#948]
I added the following test to ParserTests and it fails. Is that expected?

```csharp
        [Fact]
        public void Two_options_with_similar_shortforms_are_distinct()
        {
            var result = new Parser(
                    new Option("-f") { Argument = new Argument() { Arity = ArgumentArity.ZeroOrOne } },
                    new Option("-fs"))
                .Parse("-fs");

            result.HasOption("f").Should().BeFalse();
        }
```

The `-f` option gets parsed with an argument value of "s".

**Comment by jonsequitur** [comment]
It's ambiguous. The [POSIX command line](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) convention is that if you have option `-f` then `-fs` and `-f s` are considered equivalent.

**Comment by JoeRobich** [comment]
Interesting. I see now that I haven't been abiding by the "Option names are single alphanumeric characters" rule either.

I've adjusted my configuration to avoid this ambiguity. Thanks for the explanation.
