### ISSUE TITLE
Command line validation is disabled if supplying extra "--" (double dashes)

### ISSUE THREAD

**Issue by maxsjolinder** [dotnet/command-line-api#959]
First I want to thank you guys for the work on this library, it's great!

I didn't find any previous reported issue on the problem I'm having, so I thought I'd file a bug report.
I also verified that the problem exists on latest master (I'm using nuget version 2.0.0-beta1.20303.1)

In short, somehow it seems that the validation is disabled/stops working if one supply a extra "--" on the command line.

**Minimal working example to reproduce the issue**
```
class Program
{
    static int Main(string[] args)
    {
        var rootCommand = new RootCommand()
        {
            new Option<int>("--opt1"),
            new Option<int>("--opt2")
        };

        rootCommand.Handler = CommandHandler.Create<int, int>((opt1, opt2) =>
        {
            Console.WriteLine($"opt1: {opt1}");
            Console.WriteLine($"opt2: {opt2}");
        });

        return rootCommand.Invoke(args);
    }
}
```
Run program with parameters:
`program.exe --opt1 3 -- --opt2 notANumber`

**Expected behavior**
I expected some kind of validation error.
Either some parser error due to the extra "--", or at least a parsing error about "notANumber" not being a valid int.

I also expect Invoke to return a non-zero exit code. 

**Actual behavior**
The library swallows it, giving no validation error.
The console output of the program is :
```
opt1: 3
opt2: 0
```
Also, Invoke returns zero as exit code.

**Comment by omajid** [comment]
From https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

> More precisely, a double dash (--) is used in most bash built-in commands and many other commands to signify the end of command options, after which only positional parameters are accepted.
>
> Example use: lets say you want to grep a file for the string -v - normally -v will be considered the option to reverse the matching meaning (only show lines that do not match), but with -- you can grep for string -v like this:
>
>     grep -- -v file

**Comment by maxsjolinder** [comment]
Oh, I see — that explains a lot. Thank you for the clarification!
