### ISSUE TITLE
How to handle non command/option arguments?

### ISSUE THREAD

**Issue by lutz** [dotnet/command-line-api#961]
Hi 
i have an question about handling arguments there are no options or commands. As example i have a console app named "tool". The user should be drag and drop files to the exe and these arguments should be bind:

```shell
tool [File1] [File2]...[FileN]
```
Also there is an option called "--path" to use

```shell
tool --path [Path] [File1] [File2]...[FileN]
```
So the question is how i can bind the [File] arguments to the handler of RootCommand.

**Comment by jonsequitur** [comment]
This should work :

```cs
new RootCommand
{
  new Option<FileInfo>("--path"),
  new Argument<FileInfo[]>()
}
```

**Comment by lutz** [comment]
The argument works well but the option `--path` is completely ignored and `null`
