### ISSUE TITLE
Supplement default help output?

### ISSUE THREAD

**Issue by tlmii** [dotnet/command-line-api#964]
Is it possible to supplement the default `--help` output with further information after the default output? If not, is it possible to generate the default help output to use in our own custom output?

The current [HttpRepl](https://github.com/dotnet/httprepl) `--help` output shows the normal command line usage output followed by usage information for all of the internal commands available within the REPL. I'm taking a stab at using System.CommandLine for the normal command line usage to replicate the existing functionality, and so far this is the only part I haven't gotten working.

**Comment by jonsequitur** [comment]
You should be able to do what you need to do by creating a custom `HelpBuilder`. Here's an example that adds additional text to the help output:

https://github.com/dotnet/command-line-api/blob/96da131652807fb37a571aba20a4eea73e718e1c/src/System.CommandLine.Tests/Help/HelpBuilderTests.cs#L1577-L1590

**Comment by tlmii** [comment]
Thanks Jon, that looks like it'll do the trick.
