### ISSUE TITLE
Provide access to IHost.Services inside 'UseMiddleware' method.

### ISSUE THREAD

**Issue by StevenRasmussen** [dotnet/command-line-api#974]
Perhaps there's already a way to accomplish this but I was unable to figure it out.  What I would like is:

``` csharp
commandLineBuilder.UseMiddleware(context =>
{
    //  'services' here would be the 'IHost.Services'
    var someService = services.GetService<ISomeService>();
}
```

I see that in the `UseHost` extension method, the `IHost` is placed in the `BindingContext.ServiceProvider` here:
``` csharp
invocation.BindingContext.AddService(typeof(IHost), _ => host);
```
However, the `BindingContext.ServiceProvider` is "internal" and so there's no way to get the `IHost`.  Otherwise something like this would be possible:
``` csharp
commandLineBuilder.UseMiddleware(context =>
{
    var host = context.BindingContext.ServiceProvider.GetService<IHost>();
    var someService = host.Services.GetService<ISomeService>();
}
```
Directly exposing the `BindingContext.ServiceProvider` is probably not the answer... perhaps providing another extension method including the `IHost.Services` would be best (if it's possible):
``` csharp
public static CommandLineBuilder UseMiddleware(
    this CommandLineBuilder builder, 
    Action<InvocationContext> onInvoke, 
    IServiceProvider services, // IHost.Services
    MiddlewareOrder order = MiddlewareOrder.Default);
```
Or perhaps just the `IHost` itself:

``` csharp
public static CommandLineBuilder UseMiddleware(
    this CommandLineBuilder builder, 
    Action<InvocationContext> onInvoke, 
    IHost host,
    MiddlewareOrder order = MiddlewareOrder.Default);
```

I'd be happy to try and contribute a PR if some guidance is provided on direction here.

**Comment by StevenRasmussen** [comment]
Just to be clear, this is what you're suggesting?
```csharp
public static IHost GetHost(this InvocationContext invocationContext)
{
    var modelBinder = new ModelBinder<IHost>();
    return (IHost)modelBinder.CreateInstance(invocationContext.BindingContext);
}
```

Does this create a different `IHost` instance than what the rest of the application would use as part of the `UseHost` extension method?

**Comment by fredrikhr** [comment]
@StevenRasmussen correct, this is what I am suggesting. The `IHost` instance will be resolved from the internal service provider, which returns a singleton that is created inside `UseHost`. That means, your code snippet above will return the exact same instance that a command handler would get (if the handler had an `IHost` parameter).

**Comment by StevenRasmussen** [comment]
Thanks for confirming!  This would be great to have in the project here but I can certainly just create this method myself as well ;)  Thanks for pointing me in the right direction!

**Comment by reduckted** [comment]
> I am considering adding an extension method `GetHost` on the Invocation context and putting that extension into the hosting package.

Awesome! I made the exact same comment in https://github.com/dotnet/command-line-api/issues/1025#issuecomment-729271227 before I discovered this issue.
