### ISSUE TITLE
Include default values in the dragonfruit help message

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/command-line-api#981]
This main function:
```c#
static void Main(int intOption = 42, bool boolOption = false, FileInfo fileOption = null)
{
    Console.WriteLine($"The value of intOption is: {intOption}");
    Console.WriteLine($"The value of boolOption is: {boolOption}");
    Console.WriteLine($"The value of fileOption is: {fileOption?.FullName ?? "null"}");
}
```
causes this help message:
```
> ./myapp -h # or: dotnet run -- -h
Usage:
  myapp [options]

Options:
  --int-option     intOption
  --bool-option    boolOption
  --file-option    fileOption
```

but the user isn't told what the values are. Could you include that information in the help message?

**Comment by jonsequitur** [comment]
You might be using an older version. Here's what I get with version 0.3.0-alpha.20303.1:

![image](https://user-images.githubusercontent.com/547415/87812267-c1876b00-c814-11ea-92c1-17044465254d.png)

**Comment by Trolldemorted** [comment]
You are correct, it's just [the docu](https://github.com/dotnet/command-line-api/wiki/DragonFruit-overview) that's wrong 🎉
