### ISSUE TITLE
Introduce more than 7 arguments in `System.CommandLine.Invocation.CommandHandler.Create`

### ISSUE THREAD

**Issue by mristin** [dotnet/command-line-api#983]
Hi,
I noticed that the `CommandHandler.Create` is limited to at most 7 arguments of the action. This corresponds to at most 7 options, which is a bit too little in a more complex applications.

Was there a reason for this limit (instead of pushing it higher to, say, 16)? What is your suggested way to handle more than 7 options?

Thanks a lot for the answers in advance! Please let me know if I should create a pull request to introduce a higher limit if there is no particular reason for the current one.

**Comment by spmyob** [comment]
I've run into this exact same issue and would be interested in finding out if there's a workaround for this.

**Comment by jonsequitur** [comment]
The model binder also supports binding to complex types. You can see more details here: https://github.com/dotnet/command-line-api/blob/master/docs/model-binding.md#more-complex-types

**Comment by spmyob** [comment]
That looks exactly like what I needed. Not sure how I missed it in the docs. Thanks @jonsequitur.

**Comment by mristin** [comment]
@jonsequitur shouldn't that article be referenced from the home page? I also missed it, especially since the referenced article ["Argument validation and binding"](https://github.com/dotnet/command-line-api/blob/master/docs/How-To.md#Argument-validation-and-binding
) does not make a visible reference to complex type binding.

(Should I make a PR for the homepage?)

**Comment by mristin** [comment]
@jonsequitur it still wouldn't harm to add more arguments to `Create` or you'd prefer not to?

**Comment by jonsequitur** [comment]
>  it still wouldn't harm to add more arguments to Create or you'd prefer not to?

I mean, we could go to 11... Do you have a preference for more arguments versus complex model binding?

The documentation could use some help though. We've just started trying to consolidate and reorganize the docs, and we want to make a push to add XML comments as well. PRs are more than welcome.
