### ISSUE TITLE
Default ToString used in help is unhelpful for many types

### ISSUE THREAD

**Issue by mristin** [dotnet/command-line-api#984]
Hi,
(Please apologize if this is a duplicate -- I couldn't find a similar issue in the archive nor could I find anything relevant in the documentation.)

When you provide a default value as an array of strings:

```cs
var rootCommand = new RootCommand(
	"...")
{
	new Option<string[]>(
		new[]{"--prefixes"},
		()=>new[]{"^TODO|BUG|HACK"},
		"Prefix regular expressions marking the TODOs"
	)
};
```

you get a cryptic message in the help:

```
Options:
  --prefixes <prefixes>                   Prefix regular expressions marking the TODOs [**default: System.String[]**]
```

Is there a way to provide the string representation of the default value? Or at least handle the default case for `string[]` (*e.g.*, join the array with commas)?

**Comment by monoman** [comment]
I think you should not say that your option is typed as <string[]>, but as
<string> and set the Arity for it, which says that multiple values can be
provided by the user in the command line.

new Option<string>(
		"--prefixes",
		"^(TODO|BUG|HACK)",
		"Prefix regular expressions marking the TODOs"
	){ Argument = new Argument { Arity = ArgumentArity.OneOrMore } };


Rafael Teixeira
O..:.)oooo

**Comment by mristin** [comment]
@monoman thanks for the hint; that escaped my attention while reading the documentation. 

Could you maybe write down how to define the default values in the case where you set the arity?

**Comment by chhh** [comment]
@monoman That doesn't sound right. There either is no way to access values after the first one, or no way to set the defauts.
Related issue: https://github.com/dotnet/command-line-api/issues/987

**Comment by mristin** [comment]
Actually, it is not obvious how to serialize an array to a string that would be informative in help messages for all the cases (*e.g.*, should you concatenate with a comma or whitespace or ...?).

Here is what I did to temporarily fix the issue in my code.

Define somewhere the default value:

```csharp
        private static readonly string[] DefaultPrefixes =
        {
            "^TODO", "^BUG", "^HACK"
        };
```

Do not provide the default value in the option and stringify the array myself:
```csharp
                new Option<string[]?>(
                    new[]{"--prefixes"},
                    "Prefix regular expressions marking the TODOs. " +
                    $"[Default: {string.Join(" ", DefaultPrefixes)}]"
                ),
```

Use null coalescing operator to select the default value in the code:
```csharp
var resolvedPrefixes = prefixes ?? DefaultPrefixes;
```

It is not a nice workaround. What about inheriting from the `List<string>`  and overriding its `ToString()` in order to display the default value?

**Comment by jonsequitur** [comment]
@mristin I think defining your own types is a nice approach. Conventions for formatting lists are hard, and the model binder is set up to support just this kind of thing.

Any thoughts on a FAQ / recipes structure that will work well for discoverability in the docs?

**Comment by mristin** [comment]
@jonsequitur I tried looking where to put the example about how to stringify the default values, but I got indeed lost -- the structure of the documentation is really confusing for me.

Before I try to squeeze in these examples "just somewhere", let me create a separate issue where we could discuss first how to reorganize the documentation.

**Comment by chhh** [comment]
@mristin 
I've tried your subclassing approach, but I can't get it to work. It does print defaults, but the binding doesn't work when I actually run it with parameters. Here's an example - 2 options, one with defaults, one without:

```csharp
  class Program
  {
    public class PatternsArg : List<string>
    {
      public override string ToString()
      {
        return string.Join(" ", this.ToArray());
      }
    }
    
    public class Opts
    {
      public PatternsArg WithDefaults { get; set; }
      public PatternsArg NoDefaults { get; set; }
    }

    public static RootCommand CreateCmd()
    {
      var root = new RootCommand("Hello world");
      root.AddOption(new Option<PatternsArg>(
        new[] {"--with-defaults"},
        () => new PatternsArg {"haha", "hoho"},
        "List<string> option with some defaults"
      ) {Name = "WithDefaults"});
      root.AddOption(new Option<PatternsArg>(
        new[] {"--no-defaults"},
        "List<string> option with no defaults"
      ) {Name = "NoDefaults"});
      root.Handler = CommandHandler.Create((Opts opts) => Run(opts));
      return root;
    }

    public static void Run(Opts opts)
    {
      Console.WriteLine("Running");
      Console.WriteLine($"Option with defaults: {opts?.WithDefaults}");
      Console.WriteLine($"Option with no defaults: {opts?.NoDefaults}");
    }
    
    static void Main(string[] args)
    {
      string[] argVariants =
      {
        "--help",
        "--with-defaults hehe",
        "--with-defaults hehe --no-defaults koko",
        "--no-defaults koko"
      };

      foreach (var argVariant in argVariants)
      {
        var cmd = CreateCmd();
        cmd.Invoke(argVariant);
      }
    }
  }
```

**Comment by chhh** [comment]
Tried adding constructors, also didn't help:
```csharp
public PatternsArg(string s) : this(s.Split(" "))
      {
      }

      public PatternsArg(IEnumerable<string> collection) : base(collection)
      {
      }
```

**Comment by jonsequitur** [comment]
@chhh 

When you do the following, you're effectively setting the `Name` property twice, once in the constructor and then overwriting it with the property setter:

```csharp
root.AddOption(new Option<PatternsArg>(
        new[] {"--with-defaults"},
        () => new PatternsArg {"haha", "hoho"},
        "List<string> option with some defaults"
      ) {Name = "WithDefaults"});
```

Does it work if you remove `Name = "WithDefaults"`?

**Comment by chhh** [comment]
@jonsequitur No, it doesn't. I've tried both ways with and without Name.
Output:
```
ConsoleAppTestArgParse:
  Hello world

Usage:
  ConsoleAppTestArgParse [options]

Options:
  --with-defaults <with-defaults>    List<string> option with some defaults [default: haha hoho]
  --no-defaults <no-defaults>        List<string> option with no defaults
  --version                          Show version information
  -?, -h, --help                     Show help and usage information

Running =================
Option with defaults   :
Option with no defaults:
Running =================
Option with defaults   :
Option with no defaults:
Running =================
Option with defaults   :
Option with no defaults:
```

**Comment by mristin** [comment]
Thanks, @chhh for spotting the bug -- you are correct, I omitted a crucial unit test in my code and did not spot the mistake.

I can confirm, as soon as I set the member of a complex class to be a class inherited from List, the argument is set to the default value.

Here is how I define my arguments:
https://github.com/mristin/opinionated-csharp-todos/blob/f2188099c3aa559a1e1d1d39c71bfc59b3ad527f/src/OpinionatedCsharpTodos/Program.cs#L157

Here is the specification of the command:
https://github.com/mristin/opinionated-csharp-todos/blob/f2188099c3aa559a1e1d1d39c71bfc59b3ad527f/src/OpinionatedCsharpTodos/Program.cs#L255

The members `prefix`, `disallowedPrefix` and `suffix` are set to the default values though the arguments are specified:
https://github.com/mristin/opinionated-csharp-todos/blob/f2188099c3aa559a1e1d1d39c71bfc59b3ad527f/src/OpinionatedCsharpTodos.Tests/TestProgram.cs#L330

**Comment by jonsequitur** [comment]
@chhh At least from the perspective of System.CommandLine, you don't need most of those constructors.

**Comment by mristin** [comment]
@jonsequitur  Could you try to come up with a snippet that works? I am a bit lost what the proper way would be.

**Comment by jonsequitur** [comment]
Related: #987
