### ISSUE TITLE
Add a Changelog, especially for *breaking changes*

### ISSUE THREAD

**Issue by erichiller** [dotnet/command-line-api#985]
Unless I'm not seeing it, there doesn't seem to be a Changelog or list of anything from version.
It'd really be useful to have a Changelog and not have to go through each commit, especially when it comes to breaking changes.
If there already is one and I'm missing it, apologies, and could you point me to it?

**Comment by jonsequitur** [comment]
Sorry, we don't have a changelog. I've created a new release though and I'll add some notes there.

**Comment by erichiller** [comment]
Thank you! That is much appreciated.

**Comment by jonsequitur** [comment]
https://github.com/dotnet/command-line-api/releases/tag/2.0.0-beta1.20371.2
