### ISSUE TITLE
Help is not printed properly for Option<List<T>>. Error message when arity is wrong is misleading.

### ISSUE THREAD

**Issue by chhh** [dotnet/command-line-api#987]
I have an option that needs to take exactly 3 integers:
```csharp
var optFilterSize = new Option<List<int>>(
        aliases: new[] {"--filter-size"},
        getDefaultValue: () => new List<int>() {2, 2, 0},
        description: "distances from center") {
        IsRequired = false,
        Name = "FilterSize"
      };
optFilterSize.Argument.Arity = new ArgumentArity(3,3);
```
Note that I provide a default value.

It gets mapped to a property:
```csharp
public List<int> FilterSize { get; set; }
```
**There are two problems:**
1) When help is printed, defaults are not printed properly. Type is printed instead of defaults being listed, as follows:
```
--filter-size <filter-size>          distances from center [default: System.Collections.Generic.List`1[System.Int32]]
```
2) If wrong number of integers is provided as arguments by user, the error message is misleading:
```
Required argument missing for option: --filter-size
Required argument missing for option: --filter-size
```
This error message is printed twice, and then help is displayed. Instead it should say that this option requires 3 values to be specified.

**Comment by chhh** [comment]
Related: https://github.com/dotnet/command-line-api/issues/984

**Comment by jonsequitur** [comment]
Formatting lists can get complicated fairly quickly. I quite like the approach @mristin took here: https://github.com/dotnet/command-line-api/issues/984#issuecomment-663471185 

There's a second issue here though that we should clearly address, which is that the error message could be more helpful.

**Comment by chhh** [comment]
Why formatting a list can get complicated quickly?
The only difference from formatting a single value is the delimiting character (or sequence), all the other complications are the same - formatting a single value.
There are rules for parsing arguments, the rules specify the allowed delimiters. The first one of the allowed delimiters (in the current config) can be used.

What about formatting floating point values? That is also complicated. How many decimal places to display?

It looks like one solution would be to allow setting a delegate for formatting default values `string displayValue(T val)`

**Comment by mristin** [comment]
> Why formatting a list can get complicated quickly?

You need to fix the delimiter, the quote symbols as well as escaping sequences which differ across consoles (*e.g.* poweshell *versus* bash). Think regular expressions and the general solution becomes quite messy.
