### ISSUE TITLE
How is one supposed to run an app to get suggestions to work

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/command-line-api#991]
This screen shot shows a nice short name being used to run an app:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/826112/88432897-b7401080-cdc2-11ea-9f68-cda678fdc210.png">

How is one supposed to get that nice short name instead of `dotnet t-rex`

Is it just assumed that one has created an alias or little bash script to invoke the dotnet app?

Or is there a dotnet command to do that for you?

**Comment by jonsequitur** [comment]
You shouldn't have to do anything special. 

The command name you see there is specified in your project file with the `ToolCommandName` property. 

Here's the relevant code for `t-rex`: https://github.com/jonsequitur/t-rex/blob/master/t-rex/t-rex.csproj#L7

**Comment by michaelgwelch** [comment]
Ok, so you need to know to add a ToolCommandName? But how does the operating system know that's an executable? I must be missing a step. Do you need register your app with the OS or something?

**Comment by michaelgwelch** [comment]
Is the shim supposed to intercept just calls that start with `dotnet ` and also apps like t-rex that somehow registered their short name?

After modifying my path and adding the shim to my ~/.bashrc whenever I type tab after typing dotnet I typically get this result

```bash
dotnet add Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-[suggest:11] does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

Is this intended? Doesn't seem like the way most completions would work. They would just fail to suggest anything quietly.

**Comment by michaelgwelch** [comment]
Regarding t-rex, there is indeed some stuff I don't know about dotnet. https://github.com/jonsequitur/t-rex/blob/master/t-rex/build-and-install-global-tool.ps1

I was not aware of dotnet pack, install, uninstall

There's a lot to bootstrap just to get started. Sorry, I just thought I'd switch over from node.js so that I'd have quicker completions and using this library I wouldn't have to hand-code all of my completions. I've used  full framework since 2002, but that's not helping me much with dotnet.

**Comment by jonsequitur** [comment]
A .NET Core tool (like `t-rex`) is a .NET Core console app packaged up into a NuGet package for simpler distribution and installation. The PowerShell script is a pretty minimal example of the workflow. More info here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#:~:text=A%20.,machine%20in%20the%20following%20ways%3A&text=You%20can%20invoke%20the%20tool%20from%20the%20installation%20directory%20or,to%20the%20PATH%20environment%20variable.

For your tool, there's no need for anything to include the `dotnet` prefix. The `bash` shim you want is the one for `dotnet-suggest` ([here](https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine.Suggest/dotnet-suggest-shim.bash)), not the one for `dotnet`.

**Comment by michaelgwelch** [comment]
Yep, I got it now about the tool. Thanks. That was the piece I was missing. I didn't realize there were two separate bash shims. I didn't look too closely at the one you linked to and the one generated by dotnet-suggest (which is the one I was using). I just assumed it generated the same file.

**Comment by michaelgwelch** [comment]
Yeah I just did a diff between the one generated by dotnet suggest 

```bash
dotnet suggest script Bash 
``` 

and the one you linked to. They are the same. That's the one that generates the messages when I hit tab after typing dotnet and then something its not prepared to handle.

**Comment by jonsequitur** [comment]
Right. The `dotnet` version is an ancestor of the more generalized `System.CommandLine` / `dotnet-suggest` version. We hope to converge them later.
