### ISSUE TITLE
Is the middleware pipeline what you'd use to provide your own completions that aren't apparent from options

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/command-line-api#992]
So I see how much of the completions are driven by the command line options without having to write any additional code. But in my app I need my completions to be driven by my data and what else was typed on the command line. Think of branches in git for example.

The only thing I see in the docs is the middleware. I'm assuming that is what would allow you to intercept the complete calls and customize them based on context.

**Comment by jonsequitur** [comment]
You can add suggestions directly to an option or argument:

You can see a few examples here:

https://github.com/jonsequitur/command-line-api/blob/8ac2601d2d10e8ef3d8657e9849b8e6232bc1e05/src/System.CommandLine.Tests/SuggestDirectiveTests.cs#L22-L35

**Comment by michaelgwelch** [comment]
> You'll notice the second example takes a delegate,

You mean this option:

```csharp
           _vegetableOption = new Option<string>("--vegetable")
                .AddSuggestions(_ => new[] { "asparagus", "broccoli", "carrot" });
```

Ah, yes that does look like it'll do what I need. Thanks!

I think I have everything I need to make this work then. I was about to go back to node.js and start writing my completions by hand. This should make much quicker work of it. I was avoiding add any switches to my app because of all the extra code I'd have to write.

Thanks for all your replies!
