### ISSUE TITLE
Can I control what suggestions are show for my arguments in --help

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/command-line-api#994]
The number of suggestions available to a user of my app is quite large unless they've typed some letters. Showing all possible suggestions during a call to help would be overwhelming. (During an actual auto-complete at least bash will ask you "Are you sure you want to show all 200 lines?" or whatever it turns out to be.

I know I could hook into Environment.GetCommandLineArgs to see if --help or -h were part of the command line and then adjust my output.

Is there something built-in to an argument or option to control this behavior?

UPDATE: Based on some of the discussion it's apparent that I didn't state that in my case I'm talking about arguments not options. As noted in a comment by me below it would be like if you typed `git help branch` and the documentation that came back listed all of your branches.

**Comment by jonsequitur** [comment]
Let me see if I understand correctly. Are you saying the available values list (example circled in the screenshot) is too large to be helpful?

![image](https://user-images.githubusercontent.com/547415/88492710-982bb500-cf61-11ea-8b9e-749f6eff2f8a.png)

If so, this isn't controllable currently, although some sort of limit on how many we print might be useful. Another approach would be a custom `HelpBuilder`, though I'm not sure we currently expose functionality to make that very easy.

What would be your ideal output?

**Comment by michaelgwelch** [comment]
> Are you saying the available values list (example circled in the screenshot) is too large to be helpful?

That is correct. In my case one of my arguments has 2200 possible values. 

What I'm doing now is in the delegate for GetSuggestions for this argument, I'm using Environment.GetCommandLineArgs() to do a simple scan to see if -h, --help, help, -? etc. are in the list and if so just returning an empty array.

> What would be your ideal output?

So what would be acceptable (and what happens with my solution) is no arguments are shown. But in the description for the argument I list some examples. The user of the app will no what they are looking for. In this case suggestions are used to auto-complete, it's not so important that they be there to list all the possibilities.

Another idea would be to show a very small subset of possibilities rather than put the examples in the Description.

So my output might look like


```text
Arguments:
  <set> <opt1|opt2|opt3|...>             The name or id of the enumeration set you are looking for.
```

**Comment by KathleenDollard** [comment]
I'm running into this modeling the CLI as well, in that it pushes the description farther to the right than I think is pretty. I could see these options: 

* Check the length of the option name and option list. If it is more than <n> characters, use ellipses
* Consider putting options as a suffix to the description, which wraps nicely. This is the current .NET CLI parser apparent behavior (although it is hard coded). In this case don't include it if it is > <n2>. 

@michaelgwelch does hard coding samples into the description make sense for your scenario? With 2200, the chance of randomly finding great examples doesn't seem high. 

To be honest, I don't like the aesthetics of the options by the switch as much as I thought I would, so I lean to the second, at least as an option.

**Comment by michaelgwelch** [comment]
@KathleenDollard 

> @michaelgwelch does hard coding samples into the description make sense for your scenario? With 2200, the chance of randomly finding great examples doesn't seem high.

For my app a few samples are sufficient to get the point across to a user. Our main product ships with 2200 enumeration sets which are used internally for any strings that need to be translated. this cli I wrote is a tool to make it easier to lookup information about these sets (or their members) by name or id.

We currently have two versions of symbolic names for these enumeration sets (and their members). A legacy SCREAMING SNAKE CASE version and a new JSON friendly snakeCase version. So by showing a couple of examples it makes it clear to a user that they can either look for `ATTRIBUTE_ENUM_SET` or `attributeEnumSet` and both will work. 

These are arguments (not options) so I'd never have expected to see all possibilities listed. It's like if you were using `git branch` and the help system always listed all of your branches. You wouldn't expect that. The suggestions for arguments can't always be assumed to be a fixed list of choices or even if they are they aren't always going to be a short fixed list.

**Comment by jonsequitur** [comment]
> SCREAMING SNAKE CASE
🤣 

> What I'm doing now is in the delegate for GetSuggestions for this argument, I'm using Environment.GetCommandLineArgs() to do a simple scan to see if -h, --help, help, -? etc. are in the list and if so just returning an empty array.

A couple of potential improvements here: 

* Add a `ParseResult` parameter to the `SuggestDelegate` so that you can see the parse tree without having to resort to a string comparison, and
* Limit the number of help examples we take from suggestions.

Thoughts?

**Comment by michaelgwelch** [comment]
> Add a ParseResult parameter to the SuggestDelegate so that you can see the parse tree without having to resort to a string comparison, and

Yes, I think that would be helpful.

Another thing to consider is should you ever retrieve suggestions for help? For example, given my `git help branch` scenario. Is it typical that arguments would ever have suggestions in help?

If so, then this is one approach.

Some alternatives:

1. Don't ask for suggestions when generating help
2. Rather than passing in a ParseResult (or maybe as part of a ParseResult) set a property indicating this is a request for help.

The reason for the second suggestion is that there have been times (during testing) where I've confused the parser enough that it decided to generate help for me (Probably a typical response to bad input). And then all of my suggestions come back because the command line didn't have -h -? --help or help in it. So for those times where the "system" determine we should show "usage" but the command line didn't indicate this should happen, it would be nice to get an indicator of that.


However, I really like the idea of passing in a ParseResult for other reasons. The second argument of my app depends on the first. The values that are valid for the second argument can only be determined after the first has been determined. So I use a similar trick `Environment.GetCommandLineArgs()` to make that work. Having a ParseResult would be I could just as for `ValueForArgument`

**Comment by jonsequitur** [comment]
> Another thing to consider is should you ever retrieve suggestions for help? 

People explicitly asked for this feature, so I think it's best to refine it rather than remove it. I think it works pretty well for small sets of values such as the example in my screen shot above. How can we make it work better for longer lists?

> Rather than passing in a ParseResult (or maybe as part of a ParseResult) set a property indicating this is a request for help.

This has more to do with invocation than with parsing. Help is also shown, for example, on error even when not explicitly asked for in the command line input.

**Comment by michaelgwelch** [comment]
> People explicitly asked for this feature, so I think it's best to refine it rather than remove it.

Oh sure, of course. 

> This has more to do with invocation than with parsing. Help is also shown, for example, on error even when not explicitly asked for in the command line input.

This is my current problem. While I can handle the suppression of suggestions when I can detect that help was specifically asked for by one of the switches (-h, --help, -?, etc.) I cannot detect it on an error. Unless (hmm, I should go check) the ParseResult indicates there is an error. I'll go check.

**Comment by michaelgwelch** [comment]
While there is an `_errors` collection, it doesn't seem that the fact there are errors is exposed in any way at this time.

**Comment by michaelgwelch** [comment]
Yeah, I see there is a collection of Errors. I wonder if I can then use the ParseResult to check for any of the switches or one or more errors and if either condition is met then I can just return an empty list of suggestions.

**Comment by jonsequitur** [comment]
It's quite normal for there to be a parse error when suggestions are being requested, and the `HelpBuilder` doesn't get access to a parse result. You can ask for help for a `Command` without parsing any input. It occurs to me that this raises an interesting case where if a `ParseResult` is an argument to the `SuggestDelegate`, it might sometimes need to be `null` or synthesized.

**Comment by Pxtl** [comment]
> I'm running into this modeling the CLI as well, in that it pushes the description farther to the right than I think is pretty. I could see these options

I have this bug, even with an enum with only 5 choices with VerboseCamelCaseNames it pushes my verbose descriptions over to the right half of the page.  The help screen isn't pretty.

**Comment by jonsequitur** [comment]
The updated help APIs now give much finer-grained control over this. The docs are here: https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help
