### ISSUE TITLE
Check commit messages automatically

### ISSUE THREAD

**Issue by mristin** [dotnet/command-line-api#996]
I had a look at the git log and noticed that the commit messages are quite non-uniform despite the contributing guidelines (see [this page](https://github.com/dotnet/runtime/blob/master/CONTRIBUTING.md#commit-messages)).

For example:
```
Fixes a couple broken links in documentation.
Docs improvements
Update dependencies from https://github.com/dotnet/arcade build 20200630.3
```

Since I had the same problem in some of the projects I'm working on, I developed a Github action [opinionated-commit-message](https://github.com/mristin/opinionated-commit-message) so that the commit messages are automatically checked on every pull request and push. 

Would you like me to add a Github workflow that checks the commit messages automatically? It would certainly add a bit of structure in the git log. In my experience, the commit messages tend to be also more informative once the header is limited to 50 characters (thus forcing the committer to write a more elaborate body).

**Comment by jonsequitur** [comment]
I'm very reluctant to add process, especially via automation, that isn't consistent with other dotnet repos. The commit message guideline isn't a hard rule, and automation can add friction (e.g. developers have to redo commits, and may not immediately realize it needs to be done, blocking others who are waiting on a change).

When I see (or create) an uninformative commit message, my assumption is usually that it's a small commit and the diff will make it obvious what was changed.

**Comment by mristin** [comment]
Sure, these are all very valid arguments (structure vs friction). I'll close the issue.
